[msg addeffect_000]
[f 0 5 65278][f 2 1]None[n][e]

[msg addeffect_001]
[f 0 5 65278][f 2 1]+10 HP[n][e]

[msg addeffect_002]
[f 0 5 65278][f 2 1]+20 HP[n][e]

[msg addeffect_003]
[f 0 5 65278][f 2 1]+30 HP[n][e]

[msg addeffect_004]
[f 0 5 65278][f 2 1]+40 HP[n][e]

[msg addeffect_005]
[f 0 5 65278][f 2 1]+50 HP[n][e]

[msg addeffect_006]
[f 0 5 65278][f 2 1]+100 HP[n][e]

[msg addeffect_007]
[f 0 5 65278][f 2 1]+10 SP[n][e]

[msg addeffect_008]
[f 0 5 65278][f 2 1]+20 SP[n][e]

[msg addeffect_009]
[f 0 5 65278][f 2 1]+30 SP[n][e]

[msg addeffect_010]
[f 0 5 65278][f 2 1]+40 SP[n][e]

[msg addeffect_011]
[f 0 5 65278][f 2 1]+50 SP[n][e]

[msg addeffect_012]
[f 0 5 65278][f 2 1]+100 SP[n][e]

[msg addeffect_013]
[f 0 5 65278][f 2 1]Low Burn[n][e]

[msg addeffect_014]
[f 0 5 65278][f 2 1]Med Burn[n][e]

[msg addeffect_015]
[f 0 5 65278][f 2 1]High Burn[n][e]

[msg addeffect_016]
[f 0 5 65278][f 2 1]Low Freeze[n][e]

[msg addeffect_017]
[f 0 5 65278][f 2 1]Med Freeze[n][e]

[msg addeffect_018]
[f 0 5 65278][f 2 1]High Freeze[n][e]

[msg addeffect_019]
[f 0 5 65278][f 2 1]Low Shock[n][e]

[msg addeffect_020]
[f 0 5 65278][f 2 1]Med Shock[n][e]

[msg addeffect_021]
[f 0 5 65278][f 2 1]High Shock[n][e]

[msg addeffect_022]
[f 0 5 65278][f 2 1]Low Dizzy[n][e]

[msg addeffect_023]
[f 0 5 65278][f 2 1]Med Dizzy[n][e]

[msg addeffect_024]
[f 0 5 65278][f 2 1]High Dizzy[n][e]

[msg addeffect_025]
[f 0 5 65278][f 2 1]Low Confuse[n][e]

[msg addeffect_026]
[f 0 5 65278][f 2 1]Med Confuse[n][e]

[msg addeffect_027]
[f 0 5 65278][f 2 1]High Confuse[n][e]

[msg addeffect_028]
[f 0 5 65278][f 2 1]Low Fear[n][e]

[msg addeffect_029]
[f 0 5 65278][f 2 1]Med Fear[n][e]

[msg addeffect_030]
[f 0 5 65278][f 2 1]High Fear[n][e]

[msg addeffect_031]
[f 0 5 65278][f 2 1]Low Forget[n][e]

[msg addeffect_032]
[f 0 5 65278][f 2 1]Med Forget[n][e]

[msg addeffect_033]
[f 0 5 65278][f 2 1]High Forget[n][e]

[msg addeffect_034]
[f 0 5 65278][f 2 1]Low Brainwash[n][e]

[msg addeffect_035]
[f 0 5 65278][f 2 1]Med Brainwash[n][e]

[msg addeffect_036]
[f 0 5 65278][f 2 1]High Brainwash[n][e]

[msg addeffect_037]
[f 0 5 65278][f 2 1]Low Sleep[n][e]

[msg addeffect_038]
[f 0 5 65278][f 2 1]Med Sleep[n][e]

[msg addeffect_039]
[f 0 5 65278][f 2 1]High Sleep[n][e]

[msg addeffect_040]
[f 0 5 65278][f 2 1]Low Rage[n][e]

[msg addeffect_041]
[f 0 5 65278][f 2 1]Med Rage[n][e]

[msg addeffect_042]
[f 0 5 65278][f 2 1]High Rage[n][e]

[msg addeffect_043]
[f 0 5 65278][f 2 1]Low Despair[n][e]

[msg addeffect_044]
[f 0 5 65278][f 2 1]Med Despair[n][e]

[msg addeffect_045]
[f 0 5 65278][f 2 1]High Despair[n][e]

[msg addeffect_046]
[f 0 5 65278][f 2 1]+Random Ailment (low)[n][e]

[msg addeffect_047]
[f 0 5 65278][f 2 1]+Random Ailment (med)[n][e]

[msg addeffect_048]
[f 0 5 65278][f 2 1]+Random Ailment (high)[n][e]

[msg addeffect_049]
[f 0 5 65278][f 2 1]+Critical Rate up (low)[n][e]

[msg addeffect_050]
[f 0 5 65278][f 2 1]+Critical Rate up (med)[n][e]

[msg addeffect_051]
[f 0 5 65278][f 2 1]+Critical Rate up (high)[n][e]

[msg addeffect_052]
[f 0 5 65278][f 2 1]+Fire attacks[n][e]

[msg addeffect_053]
[f 0 5 65278][f 2 1]+Ice attacks[n][e]

[msg addeffect_054]
[f 0 5 65278][f 2 1]+Elec attacks[n][e]

[msg addeffect_055]
[f 0 5 65278][f 2 1]+Wind attacks[n][e]

[msg addeffect_056]
[f 0 5 65278][f 2 1]+Nuke attacks[n][e]

[msg addeffect_057]
[f 0 5 65278][f 2 1]+Psy attacks[n][e]

[msg addeffect_058]
[f 0 5 65278][f 2 1]+Bless attacks[n][e]

[msg addeffect_059]
[f 0 5 65278][f 2 1]+Curse attacks[n][e]

[msg addeffect_060]
[f 0 5 65278][f 2 1]+Repel Physical (low)[n][e]

[msg addeffect_061]
[f 0 5 65278][f 2 1]+Repel Physical (med)[n][e]

[msg addeffect_062]
[f 0 5 65278][f 2 1]+Repel Physical (high)[n][e]

[msg addeffect_063]
[f 0 5 65278][f 2 1]+Resist Burn[n][e]

[msg addeffect_064]
[f 0 5 65278][f 2 1]+Resist Freeze[n][e]

[msg addeffect_065]
[f 0 5 65278][f 2 1]+Resist Shock[n][e]

[msg addeffect_066]
[f 0 5 65278][f 2 1]+Resist Dizzy[n][e]

[msg addeffect_067]
[f 0 5 65278][f 2 1]+Resist Confuse[n][e]

[msg addeffect_068]
[f 0 5 65278][f 2 1]+Resist Fear[n][e]

[msg addeffect_069]
[f 0 5 65278][f 2 1]+Resist Forget[n][e]

[msg addeffect_070]
[f 0 5 65278][f 2 1]+Resist Hunger[n][e]

[msg addeffect_071]
[f 0 5 65278][f 2 1]+Resist Sleep[n][e]

[msg addeffect_072]
[f 0 5 65278][f 2 1]+Resist Rage[n][e]

[msg addeffect_073]
[f 0 5 65278][f 2 1]+Resist Despair[n][e]

[msg addeffect_074]
[f 0 5 65278][f 2 1]+Resist Mouse[n][e]

[msg addeffect_075]
[f 0 5 65278][f 2 1]+Resist Brainwash[n][e]

[msg addeffect_076]
[f 0 5 65278][f 2 1]+Auto-Tarukaja[n][e]

[msg addeffect_077]
[f 0 5 65278][f 2 1]+Auto-Rakukaja[n][e]

[msg addeffect_078]
[f 0 5 65278][f 2 1]+Auto-Sukukaja[n][e]

[msg addeffect_079]
[f 0 5 65278][f 2 1]+Reduce Physical dmg (low)[n][e]

[msg addeffect_080]
[f 0 5 65278][f 2 1]+Reduce Physical dmg (med)[n][e]

[msg addeffect_081]
[f 0 5 65278][f 2 1]+Reduce Physical dmg (high)[n][e]

[msg addeffect_082]
[f 0 5 65278][f 2 1]+Reduce Fire dmg (low)[n][e]

[msg addeffect_083]
[f 0 5 65278][f 2 1]+Reduce Fire dmg (med)[n][e]

[msg addeffect_084]
[f 0 5 65278][f 2 1]+Reduce Fire dmg (high)[n][e]

[msg addeffect_085]
[f 0 5 65278][f 2 1]+Reduce Ice dmg (low)[n][e]

[msg addeffect_086]
[f 0 5 65278][f 2 1]+Reduce Ice dmg (med)[n][e]

[msg addeffect_087]
[f 0 5 65278][f 2 1]+Reduce Ice dmg (high)[n][e]

[msg addeffect_088]
[f 0 5 65278][f 2 1]+Reduce Elec dmg (low)[n][e]

[msg addeffect_089]
[f 0 5 65278][f 2 1]+Reduce Elec dmg (med)[n][e]

[msg addeffect_090]
[f 0 5 65278][f 2 1]+Reduce Elec dmg (high)[n][e]

[msg addeffect_091]
[f 0 5 65278][f 2 1]+Reduce Wind dmg (low)[n][e]

[msg addeffect_092]
[f 0 5 65278][f 2 1]+Reduce Wind dmg (med)[n][e]

[msg addeffect_093]
[f 0 5 65278][f 2 1]+Reduce Wind dmg (high)[n][e]

[msg addeffect_094]
[f 0 5 65278][f 2 1]+Reduce Nuke dmg (low)[n][e]

[msg addeffect_095]
[f 0 5 65278][f 2 1]+Reduce Nuke dmg (med)[n][e]

[msg addeffect_096]
[f 0 5 65278][f 2 1]+Reduce Nuke dmg (high)[n][e]

[msg addeffect_097]
[f 0 5 65278][f 2 1]+Reduce Psy dmg (low)[n][e]

[msg addeffect_098]
[f 0 5 65278][f 2 1]+Reduce Psy dmg (med)[n][e]

[msg addeffect_099]
[f 0 5 65278][f 2 1]+Reduce Psy dmg (high)[n][e]

[msg addeffect_100]
[f 0 5 65278][f 2 1]+Reduce Bless dmg (low)[n][e]

[msg addeffect_101]
[f 0 5 65278][f 2 1]+Reduce Bless dmg (med)[n][e]

[msg addeffect_102]
[f 0 5 65278][f 2 1]+Reduce Bless dmg (high)[n][e]

[msg addeffect_103]
[f 0 5 65278][f 2 1]+Reduce Curse dmg (low)[n][e]

[msg addeffect_104]
[f 0 5 65278][f 2 1]+Reduce Curse dmg (med)[n][e]

[msg addeffect_105]
[f 0 5 65278][f 2 1]+Reduce Curse dmg (high)[n][e]

[msg addeffect_106]
[f 0 5 65278][f 2 1]+Reduce Magic dmg (low)[n][e]

[msg addeffect_107]
[f 0 5 65278][f 2 1]+Reduce Magic dmg (med)[n][e]

[msg addeffect_108]
[f 0 5 65278][f 2 1]+Reduce Magic dmg (high)[n][e]

[msg addeffect_109]
[f 0 5 65278][f 2 1]+Evade Physical (low)[n][e]

[msg addeffect_110]
[f 0 5 65278][f 2 1]+Evade Physical (med)[n][e]

[msg addeffect_111]
[f 0 5 65278][f 2 1]+Evade Physical (high)[n][e]

[msg addeffect_112]
[f 0 5 65278][f 2 1]+Evade Fire (low)[n][e]

[msg addeffect_113]
[f 0 5 65278][f 2 1]+Evade Fire (med)[n][e]

[msg addeffect_114]
[f 0 5 65278][f 2 1]+Evade Fire (high)[n][e]

[msg addeffect_115]
[f 0 5 65278][f 2 1]+Evade Ice (low)[n][e]

[msg addeffect_116]
[f 0 5 65278][f 2 1]+Evade Ice (med)[n][e]

[msg addeffect_117]
[f 0 5 65278][f 2 1]+Evade Ice (high)[n][e]

[msg addeffect_118]
[f 0 5 65278][f 2 1]+Evade Elec (low)[n][e]

[msg addeffect_119]
[f 0 5 65278][f 2 1]+Evade Elec (med)[n][e]

[msg addeffect_120]
[f 0 5 65278][f 2 1]+Evade Elec (high)[n][e]

[msg addeffect_121]
[f 0 5 65278][f 2 1]+Evade Wind (low)[n][e]

[msg addeffect_122]
[f 0 5 65278][f 2 1]+Evade Wind (med)[n][e]

[msg addeffect_123]
[f 0 5 65278][f 2 1]+Evade Wind (high)[n][e]

[msg addeffect_124]
[f 0 5 65278][f 2 1]+Evade Nuke (low)[n][e]

[msg addeffect_125]
[f 0 5 65278][f 2 1]+Evade Nuke (med)[n][e]

[msg addeffect_126]
[f 0 5 65278][f 2 1]+Evade Nuke (high)[n][e]

[msg addeffect_127]
[f 0 5 65278][f 2 1]+Evade Psy (low)[n][e]

[msg addeffect_128]
[f 0 5 65278][f 2 1]+Evade Psy (med)[n][e]

[msg addeffect_129]
[f 0 5 65278][f 2 1]+Evade Psy (high)[n][e]

[msg addeffect_130]
[f 0 5 65278][f 2 1]+Evade Bless (low)[n][e]

[msg addeffect_131]
[f 0 5 65278][f 2 1]+Evade Bless (med)[n][e]

[msg addeffect_132]
[f 0 5 65278][f 2 1]+Evade Bless (high)[n][e]

[msg addeffect_133]
[f 0 5 65278][f 2 1]+Evade Curse (low)[n][e]

[msg addeffect_134]
[f 0 5 65278][f 2 1]+Evade Curse (med)[n][e]

[msg addeffect_135]
[f 0 5 65278][f 2 1]+Evade Curse (high)[n][e]

[msg addeffect_136]
[f 0 5 65278][f 2 1]+Evade Magic (low)[n][e]

[msg addeffect_137]
[f 0 5 65278][f 2 1]+Evade Magic (med)[n][e]

[msg addeffect_138]
[f 0 5 65278][f 2 1]+Evade Magic (high)[n][e]

[msg addeffect_139]
[f 0 5 65278][f 2 1]+50% EXP[n][e]

[msg addeffect_140]
[f 0 5 65278][f 2 1]+Fire attacks[n][e]

[msg addeffect_141]
[f 0 5 65278][f 2 1]+Ice attacks[n][e]

[msg addeffect_142]
[f 0 5 65278][f 2 1]+Wind attacks[n][e]

[msg addeffect_143]
[f 0 5 65278][f 2 1]+Elec attacks[n][e]

[msg addeffect_144]
[f 0 5 65278][f 2 1]+Resist Fire[n][e]

[msg addeffect_145]
[f 0 5 65278][f 2 1]+Resist Ice[n][e]

[msg addeffect_146]
[f 0 5 65278][f 2 1]+Resist Wind[n][e]

[msg addeffect_147]
[f 0 5 65278][f 2 1]+Resist Elec[n][e]

[msg addeffect_148]
[f 0 5 65278][f 2 1]+Nuke attacks[n][e]

[msg addeffect_149]
[f 0 5 65278][f 2 1]+Psy attacks[n][e]

[msg addeffect_150]
[f 0 5 65278][f 2 1]+Bless attacks[n][e]

[msg addeffect_151]
[f 0 5 65278][f 2 1]+Curse attacks[n][e]

[msg addeffect_152]
[f 0 5 65278][f 2 1]+Resist Nuke[n][e]

[msg addeffect_153]
[f 0 5 65278][f 2 1]+Resist Psy[n][e]

[msg addeffect_154]
[f 0 5 65278][f 2 1]+Resist Bless[n][e]

[msg addeffect_155]
[f 0 5 65278][f 2 1]+Resist Curse[n][e]

[msg addeffect_156]
[f 0 5 65278][f 2 1]+Attack when enraged[n][e]

[msg addeffect_157]
[f 0 5 65278][f 2 1]Lowers enemy line of sight[n][e]

[msg addeffect_158]
[f 0 5 65278][f 2 1]Raises enemy alert time[n][e]

[msg addeffect_159]
[f 0 5 65278][f 2 1]Lowers enemy alert time[n][e]

[msg addeffect_160]
[f 0 5 65278][f 2 1]+1 Clip[n][e]

[msg addeffect_161]
[f 0 5 65278][f 2 1]+2 Clips[n][e]

[msg addeffect_162]
[f 0 5 65278][f 2 1]+3 Clips[n][e]

[msg addeffect_163]
[f 0 5 65278][f 2 1]+Null Burn[n][e]

[msg addeffect_164]
[f 0 5 65278][f 2 1]+Null Freeze[n][e]

[msg addeffect_165]
[f 0 5 65278][f 2 1]+Null Shock[n][e]

[msg addeffect_166]
[f 0 5 65278][f 2 1]+Null Dizzy[n][e]

[msg addeffect_167]
[f 0 5 65278][f 2 1]+Null Confuse[n][e]

[msg addeffect_168]
[f 0 5 65278][f 2 1]+Null Fear[n][e]

[msg addeffect_169]
[f 0 5 65278][f 2 1]+Null Forget[n][e]

[msg addeffect_170]
[f 0 5 65278][f 2 1]+Null Hunger[n][e]

[msg addeffect_171]
[f 0 5 65278][f 2 1]+Null Sleep[n][e]

[msg addeffect_172]
[f 0 5 65278][f 2 1]+Null Rage[n][e]

[msg addeffect_173]
[f 0 5 65278][f 2 1]+Null Despair[n][e]

[msg addeffect_174]
[f 0 5 65278][f 2 1]+Null Mouse[n][e]

[msg addeffect_175]
[f 0 5 65278][f 2 1]+Null Brainwash[n][e]

[msg addeffect_176]
[f 0 5 65278][f 2 1]Regenerate 1[n][e]

[msg addeffect_177]
[f 0 5 65278][f 2 1]Regenerate 2[n][e]

[msg addeffect_178]
[f 0 5 65278][f 2 1]Regenerate 3[n][e]

[msg addeffect_179]
[f 0 5 65278][f 2 1]Invigorate 1[n][e]

[msg addeffect_180]
[f 0 5 65278][f 2 1]Invigorate 2[n][e]

[msg addeffect_181]
[f 0 5 65278][f 2 1]Invigorate 3[n][e]

[msg addeffect_182]
[f 0 5 65278][f 2 1]Prevents insta-kill from Bless[n][e]

[msg addeffect_183]
[f 0 5 65278][f 2 1]Prevents Curse insta-kills[n][e]

[msg addeffect_184]
[f 0 5 65278][f 2 1]Lowers enemy Accuracy[n][e]

[msg addeffect_185]
[f 0 5 65278][f 2 1]Null all except Almighty[n][e]

[msg addeffect_186]
[f 0 5 65278][f 2 1]Halves damage, no evasion[n][e]

[msg addeffect_187]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg addeffect_188]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg addeffect_189]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg addeffect_190]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg addeffect_191]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg addeffect_192]
[f 0 5 65278][f 2 1]+EXP from battles[n][e]

[msg addeffect_193]
[f 0 5 65278][f 2 1]+Money from battles (1x)[n][e]

[msg addeffect_194]
[f 0 5 65278][f 2 1]+Reduce being targeted[n][e]

[msg addeffect_195]
[f 0 5 65278][f 2 1]+Null Bless/Curse[n][e]

[msg addeffect_196]
[f 0 5 65278][f 2 1]+3 to all stats, +20 SP[n][e]

[msg addeffect_197]
[f 0 5 65278][f 2 1]All-Out Attack power up (1x)[n][e]

[msg addeffect_198]
[f 0 5 65278][f 2 1]+1 bullet upon victory[n][e]

[msg addeffect_199]
[f 0 5 65278][f 2 1]+Crit rate/+Evade Magic[n][e]

[msg addeffect_200]
[f 0 5 65278][f 2 1]Lower skill cost 25%[n][e]

[msg addeffect_201]
[f 0 5 65278][f 2 1]+Reduce status ailment 50%[n][e]

