[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Black-framed glasses that[n]makes one look smart.[n][e]

[msg Item_002]
[s]Suspenders that go[n]with casual attire.[n][e]

[msg Item_003]
[s]A fanny pack that can[n]hold small items.[n][e]

[msg Item_004]
[s]A simple accessory[n]used to hold hair.[n][e]

[msg Item_005]
[s]A classic key ring[n]coated in silver.[n][e]

[msg Item_006]
[s]Thick, black tights.[n][e]

[msg Item_007]
[s]Polka-dotted tights made[n]overseas.[n][e]

[msg Item_008]
[s]High fidelity for[n]real audiophiles.[n][e]

[msg Item_009]
[s]A formal necktie[n]for fancy events.[n][e]

[msg Item_00A]
[s]RESERVE[n][e]

[msg Item_00B]
[s]Breathes new life[n]into any outfit.[n][e]

[msg Item_00C]
[s]Effectively energizes[n]any outfit.[n][e]

[msg Item_00D]
[s]Greatly improves[n]one's vitals.[n][e]

[msg Item_00E]
[s]RESERVE[n][e]

[msg Item_00F]
[s]RESERVE[n][e]

[msg Item_010]
[s]RESERVE[n][e]

[msg Item_011]
[s]A choker that helps[n]open up the chakras.[n][e]

[msg Item_012]
[s]A choker that[n]strengthens the mind.[n][e]

[msg Item_013]
[s]A choker that empowers[n]the soul.[n][e]

[msg Item_014]
[s]RESERVE[n][e]

[msg Item_015]
[s]RESERVE[n][e]

[msg Item_016]
[s]RESERVE[n][e]

[msg Item_017]
[s]A wristband enhancing[n]fire attacks.[n][e]

[msg Item_018]
[s]A wristband enhancing[n]ice attacks.[n][e]

[msg Item_019]
[s]A wristband enhancing[n]wind attacks.[n][e]

[msg Item_01A]
[s]A wristband enhancing[n]electric attacks.[n][e]

[msg Item_01B]
[s]A jack-o-lantern necklace[n]that enhances fire attacks.[n][e]

[msg Item_01C]
[s]RESERVE[n][e]

[msg Item_01D]
[s]RESERVE[n][e]

[msg Item_01E]
[s]RESERVE[n][e]

[msg Item_01F]
[s]A bracelet enhancing[n]nuclear attacks.[n][e]

[msg Item_020]
[s]A wristband enhancing[n]psychokinetic attacks.[n][e]

[msg Item_021]
[s]A wristband enhancing[n]bless attacks.[n][e]

[msg Item_022]
[s]A wristband enhancing[n]curse attacks.[n][e]

[msg Item_023]
[s]RESERVE[n][e]

[msg Item_024]
[s]RESERVE[n][e]

[msg Item_025]
[s]RESERVE[n][e]

[msg Item_026]
[s]RESERVE[n][e]

[msg Item_027]
[s]A wristband that fills one[n]with burning passion.[n][e]

[msg Item_028]
[s]A brilliantly colored belt.[n]You may get odd looks from[n]others when wearing it.[n][e]

[msg Item_029]
[s]RESERVE[n][e]

[msg Item_02A]
[s]A necklace with a[n]magnetic clasp.[n][e]

[msg Item_02B]
[s]An uplifting necktie.[n][e]

[msg Item_02C]
[s]Suspenders that can[n]hold up anything.[n][e]

[msg Item_02D]
[s]A belt that makes[n]you feel stronger.[n][e]

[msg Item_02E]
[s]Clappers that can put[n]out fires.[n][e]

[msg Item_02F]
[s]A rubber pouch filled[n]with hot water.[n][e]

[msg Item_030]
[s]Gloves that help prevent[n]being shocked.[n][e]

[msg Item_031]
[s]Goggles that protect[n]the eyes from harm.[n][e]

[msg Item_032]
[s]An innately soothing[n]mask.[n][e]

[msg Item_033]
[s]Wooden clogs that[n]take courage to wear.[n][e]

[msg Item_034]
[s]A notebook used to[n]write down reminders.[n][e]

[msg Item_035]
[s]A cape that somehow[n]makes one feel sated.[n][e]

[msg Item_036]
[s]Magical gem that stops[n]one from falling asleep.[n][e]

[msg Item_037]
[s]A cape that feels[n]soothing when worn.[n][e]

[msg Item_038]
[s]A cape that makes[n]one feel hopeful.[n][e]

[msg Item_039]
[s]RESERVE[n][e]

[msg Item_03A]
[s]A headband that[n]clears your mind.[n][e]

[msg Item_03B]
[s]A charm that protects[n]against burns.[n][e]

[msg Item_03C]
[s]A charm that protects[n]against freezing.[n][e]

[msg Item_03D]
[s]A charm that lets one[n]hit like an all-star.[n][e]

[msg Item_03E]
[s]A charm that protects[n]against shocks.[n][e]

[msg Item_03F]
[s]RESERVE[n][e]

[msg Item_040]
[s]A mysterious cape that[n]lets you forget your fears.[n][e]

[msg Item_041]
[s]RESERVE[n][e]

[msg Item_042]
[s]RESERVE[n][e]

[msg Item_043]
[s]RESERVE[n][e]

[msg Item_044]
[s]RESERVE[n][e]

[msg Item_045]
[s]A charm that makes[n]one unable to be sad.[n][e]

[msg Item_046]
[s]RESERVE[n][e]

[msg Item_047]
[s]RESERVE[n][e]

[msg Item_048]
[s]A mirror that exacts[n]vengeance.[n][e]

[msg Item_049]
[s]A mirror that retaliates[n]against any action.[n][e]

[msg Item_04A]
[s]A mirror that punishes[n]evil for their deeds.[n][e]

[msg Item_04B]
[s]A patch that keeps[n]one awake and alert.[n][e]

[msg Item_04C]
[s]Potpourri bearing a[n]relaxing fragrance.[n][e]

[msg Item_04D]
[s]A calendar full of[n]daily encouragements.[n][e]

[msg Item_04E]
[s]Stylish sunglasses that[n]protect the eyes as well.[n][e]

[msg Item_04F]
[s]A cape that makes one[n]see things clearly.[n][e]

[msg Item_050]
[s]A pack of flammable oil.[n][e]

[msg Item_051]
[s]A reusable ice pack.[n][e]

[msg Item_052]
[s]A rechargeable battery[n]pack.[n][e]

[msg Item_053]
[s]A mask that may[n]cause vertigo.[n][e]

[msg Item_054]
[s]A mask shrouded[n]in mystique.[n][e]

[msg Item_055]
[s]An absolutely[n]terrifying mask.[n][e]

[msg Item_056]
[s]A distracting mask that[n]wipes away thoughts.[n][e]

[msg Item_057]
[s]A hypnotic mask that[n]lulls viewers to sleep.[n][e]

[msg Item_058]
[s]A taunting mask[n]begging for a hit.[n][e]

[msg Item_059]
[s]A decadent mask with[n]an air of arrogance.[n][e]

[msg Item_05A]
[s]A cursed mask.[n][e]

[msg Item_05B]
[s]Bears the seal of a deviant.[n]Allows wearer to use a[n]unique two-in-one skill.[n][e]

[msg Item_05C]
[s]Bears the seal of a narcissist.[n]Nullifies wearer's weaknesses.[n][e]

[msg Item_05D]
[s]Bears the seal of a hoarder.[n]Innate barrier can deflect[n]all attacks except Almighty.[n][e]

[msg Item_05E]
[s]Bears the seal of a berserker.[n]Increases wearer's Agility[n]for 3 turns at start of battle.[n][e]

[msg Item_05F]
[s]Bears the seal of a miser.[n]Increases wearer's Attack[n]for 3 turns at start of battle.[n][e]

[msg Item_060]
[s]Bears the seal of a schemer.[n]Wearer's first magic attack[n]does over double damage.[n][e]

[msg Item_061]
[s]Bears the seal of an egotist.[n]Increases wearer's Defense[n]for 3 turns at start of battle.[n][e]

[msg Item_062]
[s]Bears the seal of a mourner.[n]Wearer recovers 8% HP and[n]SP after victory.[n][e]

[msg Item_063]
[s]A crystal that holds[n]the power of lust.[n][e]

[msg Item_064]
[s]A crystal that holds[n]the power of vanity.[n][e]

[msg Item_065]
[s]A crystal that holds[n]the power of gluttony.[n][e]

[msg Item_066]
[s]A crystal that holds[n]the power of wrath.[n][e]

[msg Item_067]
[s]A crystal that holds[n]the power of greed.[n][e]

[msg Item_068]
[s]A crystal that holds[n]the power of envy.[n][e]

[msg Item_069]
[s]A crystal that holds[n]the power of pride.[n][e]

[msg Item_06A]
[s]A crystal that holds[n]the power of sorrow.[n][e]

[msg Item_06B]
[s]RESERVE[n][e]

[msg Item_06C]
[s]RESERVE[n][e]

[msg Item_06D]
[s]RESERVE[n][e]

[msg Item_06E]
[s]RESERVE[n][e]

[msg Item_06F]
[s]A belt with the power[n]of a ferocious deity.[n][e]

[msg Item_070]
[s]A belt shaped like a[n]weapon of the gods.[n][e]

[msg Item_071]
[s]A belt once worn[n]by a god of war.[n][e]

[msg Item_072]
[s]A baseball cap once[n]worn by an MVP.[n][e]

[msg Item_073]
[s]A belt that provides the[n]will to withstand attacks.[n][e]

[msg Item_074]
[s]A deceptively safe-[n]looking keychain.[n][e]

[msg Item_075]
[s]A sash that imbues[n]bravery in its wearer.[n][e]

[msg Item_076]
[s]An empowered[n]friendship bracelet.[n][e]

[msg Item_077]
[s]A harp that stops[n]bewitchment.[n][e]

[msg Item_078]
[s]A royal harp that stops[n]bewitchment.[n][e]

[msg Item_079]
[s]A ring housing the[n]Reaper's power.[n][e]

[msg Item_07A]
[s]A royal ring housing even[n]more of the Reaper's power.[n][e]

[msg Item_07B]
[s]A headband filled[n]with energy.[n][e]

[msg Item_07C]
[s]A royal headband filled[n]with even more energy.[n][e]

[msg Item_07D]
[s]A headband that shows[n]one's inner desires.[n][e]

[msg Item_07E]
[s]A royal headband that[n]shows one's inner desires.[n][e]

[msg Item_07F]
[s]A ball of yarn that[n]leads to salvation.[n][e]

[msg Item_080]
[s]A royal ball of yarn that[n]leads to salvation.[n][e]

[msg Item_081]
[s]Horns like that of a[n]wild, fierce bull.[n][e]

[msg Item_082]
[s]Royal horns like that[n]of a wild, fierce bull.[n][e]

[msg Item_083]
[s]A stone with a dull[n]glisten.[n][e]

[msg Item_084]
[s]A royal stone with[n]a dull glisten.[n][e]

[msg Item_085]
[s]RESERVE[n][e]

[msg Item_086]
[s]An enchanting[n]heart-shaped harp.[n][e]

[msg Item_087]
[s]A royal, bewitching[n]heart-shaped harp.[n][e]

[msg Item_088]
[s]A set of armor that raises[n]everyone's defense.[n][e]

[msg Item_089]
[s]A royal set of armor that[n]raises everyone's defense.[n][e]

[msg Item_08A]
[s]A belt with a shine[n]that fills the soul.[n][e]

[msg Item_08B]
[s]A royal belt with a[n]shine that fills the soul.[n][e]

[msg Item_08C]
[s]The silk hat of a phantom[n]thief.[n][e]

[msg Item_08D]
[s]The crown of a legendary[n]phantom thief.[n][e]

[msg Item_08E]
[s]RESERVE[n][e]

[msg Item_08F]
[s]RESERVE[n][e]

[msg Item_090]
[s]An eyepatch worn by[n]a warrior.[n][e]

[msg Item_091]
[s]Socks that increases the[n]wearer's response time.[n][e]

[msg Item_092]
[s]RESERVE[n][e]

[msg Item_093]
[s]A choker that avoids[n]fire attacks.[n][e]

[msg Item_094]
[s]A bracelet that avoids[n]fire attacks.[n][e]

[msg Item_095]
[s]RESERVE[n][e]

[msg Item_096]
[s]A choker that avoids[n]ice attacks.[n][e]

[msg Item_097]
[s]A bracelet that avoids[n]ice attacks.[n][e]

[msg Item_098]
[s]RESERVE[n][e]

[msg Item_099]
[s]A choker that avoids[n]electric attacks.[n][e]

[msg Item_09A]
[s]A bracelet that avoids[n]electric attacks.[n][e]

[msg Item_09B]
[s]RESERVE[n][e]

[msg Item_09C]
[s]A choker that avoids[n]wind attacks.[n][e]

[msg Item_09D]
[s]A bracelet that avoids[n]wind attacks.[n][e]

[msg Item_09E]
[s]RESERVE[n][e]

[msg Item_09F]
[s]A choker that avoids[n]nuclear attacks.[n][e]

[msg Item_0A0]
[s]A bracelet that avoids[n]nuclear attacks.[n][e]

[msg Item_0A1]
[s]RESERVE[n][e]

[msg Item_0A2]
[s]A choker that avoids[n]psychokinetic attacks.[n][e]

[msg Item_0A3]
[s]A bracelet that avoids[n]psychokinetic attacks.[n][e]

[msg Item_0A4]
[s]RESERVE[n][e]

[msg Item_0A5]
[s]A choker that avoids[n]bless attacks.[n][e]

[msg Item_0A6]
[s]A bracelet that avoids[n]bless attacks.[n][e]

[msg Item_0A7]
[s]RESERVE[n][e]

[msg Item_0A8]
[s]A foul choker that[n]avoids curse attacks.[n][e]

[msg Item_0A9]
[s]A red hairpin that[n]avoids curse attacks.[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]An angel-etched badge[n]that avoids magic attacks.[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]RESERVE[n][e]

[msg Item_0AE]
[s]A ring that lets you learn[n]more quickly.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]RESERVE[n][e]

[msg Item_0B2]
[s]RESERVE[n][e]

[msg Item_0B3]
[s]RESERVE[n][e]

[msg Item_0B4]
[s]RESERVE[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]RESERVE[n][e]

[msg Item_0B7]
[s]A gem that empowers[n]its owner.[n][e]

[msg Item_0B8]
[s]A magic necklace that[n]uplifts the wearer's heart.[n][e]

[msg Item_0B9]
[s]A mystical gem that[n]raises the wearer's spirits.[n][e]

[msg Item_0BA]
[s]An alluring crown that[n]makes the wearer radiant.[n][e]

[msg Item_0BB]
[s]A magical gem that[n]brings calamity.[n][e]

[msg Item_0BC]
[s]A magical gem with the[n]power of an emperor.[n][e]

[msg Item_0BD]
[s]Famous gem said to[n]be cursed, but healing.[n][e]

[msg Item_0BE]
[s]A magical gem that[n]helps avoid magic skills.[n][e]

[msg Item_0BF]
[s]A charm shaped like[n]a cross.[n][e]

[msg Item_0C0]
[s]The belt of a man of[n]the sea.[n][e]

[msg Item_0C1]
[s]The belt of a swift-[n]footed god.[n][e]

[msg Item_0C2]
[s]The belt of a man[n]in the hall of fame.[n][e]

[msg Item_0C3]
[s]A mask bearing the[n]Phantom Thieves logo.[n][e]

[msg Item_0C4]
[s]A stone able to transform[n]into various equipment.[n][e]

[msg Item_0C5]
[s]A spooky, skull-shaped[n]charm.[n][e]

[msg Item_0C6]
[s]A stone necklace that's[n]hot to the touch.[n][e]

[msg Item_0C7]
[s]A stone necklace that's[n]cold as ice.[n][e]

[msg Item_0C8]
[s]A green stone necklace.[n][e]

[msg Item_0C9]
[s]A necklace with lightning[n]shaped stones.[n][e]

[msg Item_0CA]
[s]A necklace that looks[n]like a ring of atoms.[n][e]

[msg Item_0CB]
[s]A necklace with a psychic[n]motif.[n][e]

[msg Item_0CC]
[s]A lovely, sky-colored[n]necklace.[n][e]

[msg Item_0CD]
[s]A necklace as dark as[n]night.[n][e]

[msg Item_0CE]
[s]RESERVE[n][e]

[msg Item_0CF]
[s]Pair of dolls in the shape[n]of Hawaiian dwarves.[n][e]

[msg Item_0D0]
[s]A lei-shaped ring that's[n]engraved with initials.[n][e]

[msg Item_0D1]
[s]A badge won for beating[n]Star Forneus.[n][e]

[msg Item_0D2]
[s]A badge won for beating[n]Train of Life.[n][e]

[msg Item_0D3]
[s]A badge won for beating[n]Power Intuition.[n][e]

[msg Item_0D4]
[s]A badge won for beating[n]Punch Ouch.[n][e]

[msg Item_0D5]
[s]A badge won for beating[n]Gambla Goemon.[n][e]

[msg Item_0D6]
[s]A badge won for beating[n]Golfer Sarutahiko.[n][e]

[msg Item_0D7]
[s]A belt for men who have[n]the eye of the tiger.[n][e]

[msg Item_0D8]
[s]A compact mirror used[n]by a seasoned veteran.[n][e]

[msg Item_0D9]
[s]Contains Boss's finest[n]coffee beans.[n][e]

[msg Item_0DA]
[s]Boss's select, game[n]time underpants.[n][e]

[msg Item_0DB]
[s]A badge with the rank[n]of Lt. Commander.[n][e]

[msg Item_0DC]
[s]A badge with the rank[n]of Commander.[n][e]

[msg Item_0DD]
[s]A badge with the rank[n]of Captain.[n][e]

[msg Item_0DE]
[s]A patch that heals[n]a bit of health.[n][e]

[msg Item_0DF]
[s]A patch that heals[n]some health.[n][e]

[msg Item_0E0]
[s]A patch that heals[n]a bunch of health.[n][e]

[msg Item_0E1]
[s]An adhesive that[n]restores a bit of spirit.[n][e]

[msg Item_0E2]
[s]An adhesive that[n]restores some spirit.[n][e]

[msg Item_0E3]
[s]An adhesive that[n]restores much spirit.[n][e]

[msg Item_0E4]
[s]RESERVE[n][e]

[msg Item_0E5]
[s]RESERVE[n][e]

[msg Item_0E6]
[s]A cup that only the[n]victorious can hold.[n][e]

[msg Item_0E7]
[s]A badge that makes one[n]able to avoid any attack.[n][e]

[msg Item_0E8]
[s]An orb with almost[n]godlike power.[n][e]

[msg Item_0E9]
[s]A pillar that provides[n]heavenly protection.[n][e]

[msg Item_0EA]
[s]A veil that shields you[n]from the weak-willed.[n][e]

[msg Item_0EB]
[s]RESERVE[n][e]

[msg Item_0EC]
[s]A pearl that causes one[n]to latch onto things.[n][e]

[msg Item_0ED]
[s]A belt that uses bad[n]weather to ail people.[n][e]

[msg Item_0EE]
[s]RESERVE[n][e]

[msg Item_0EF]
[s]RESERVE[n][e]

[msg Item_0F0]
[s]RESERVE[n][e]

[msg Item_0F1]
[s]It looks like it could[n]fetch a tidy sum, but...[n][e]

[msg Item_0F2]
[s]Glasses that allow one to[n]see clearly in the fog.[n][e]

[msg Item_0F3]
[s]An armband with "S.E.E.S."[n]written on it.[n][e]

[msg Item_0F4]
[s]Seven Sisters High School[n]emblem. Beware of rumors.[n][e]

[msg Item_0F5]
[s]An emblem from St.[n]Hermelin High School.[n][e]

[msg Item_0F6]
[s]Arm computer with the[n]Demon Summoner program.[n][e]

[msg Item_0F7]
[s]A yellow bandana that[n]can dance all night.[n][e]

[msg Item_0F8]
[s]A portable Evoker.[n][e]

[msg Item_0F9]
[s]A good luck charm[n]shaped like a turtle.[n][e]

[msg Item_0FA]
[s]A keychain with a[n]wooden Tiki statue.[n][e]

[msg Item_0FB]
[s]Has extra bass to increase[n]one's rhythm.[n][e]

[msg Item_0FC]
[s]Closed-air to allow one to[n]focus.[n][e]

[msg Item_0FD]
[s]Carried by sleepless men[n]in their dreams.[n][e]

[msg Item_0FE]
[s]Has an internal PC that[n]only Samurai can use.[n][e]

[msg Item_0FF]
[s]Tubes the Kuzunoha Clan[n]use to summon demons.[n][e]

[msg Item_100]
[s]A badge won for beating[n]Featherman Seeker.[n][e]

[msg Item_101]
[s]Unused[n][e]

[msg Item_102]
[s]Unused[n][e]

[msg Item_103]
[s]Unused[n][e]

[msg Item_104]
[s]Unused[n][e]

[msg Item_105]
[s]Unused[n][e]

[msg Item_106]
[s]Unused[n][e]

[msg Item_107]
[s]Unused[n][e]

[msg Item_108]
[s]Unused[n][e]

[msg Item_109]
[s]Unused[n][e]

[msg Item_10A]
[s]RESERVE[n][e]

[msg Item_10B]
[s]Unused[n][e]

[msg Item_10C]
[s]RESERVE[n][e]

[msg Item_10D]
[s]A ring that makes one[n]move like the wind.[n][e]

[msg Item_10E]
[s]A dog tag etched with a[n]fabled sniper's name.[n][e]

[msg Item_10F]
[s]A big red ribbon.[n][e]

[msg Item_110]
[s]A ring charged[n]by fire.[n][e]

[msg Item_111]
[s]A ring powered[n]by fire.[n][e]

[msg Item_112]
[s]A ring generating[n]fiery power.[n][e]

[msg Item_113]
[s]A spiral ring charged[n]by fire.[n][e]

[msg Item_114]
[s]A spiral ring powered[n]by fire.[n][e]

[msg Item_115]
[s]A spiral ring generating[n]fiery power.[n][e]

[msg Item_116]
[s]A ring charged[n]by ice.[n][e]

[msg Item_117]
[s]A ring powered[n]by ice.[n][e]

[msg Item_118]
[s]A ring generating[n]icy power.[n][e]

[msg Item_119]
[s]A spiral ring charged[n]by ice.[n][e]

[msg Item_11A]
[s]A spiral ring powered[n]by ice.[n][e]

[msg Item_11B]
[s]A spiral ring generating[n]icy power.[n][e]

[msg Item_11C]
[s]A ring charged[n]by the wind.[n][e]

[msg Item_11D]
[s]A ring powered[n]by the wind.[n][e]

[msg Item_11E]
[s]A ring generating[n]wind power.[n][e]

[msg Item_11F]
[s]A spiral ring charged[n]by the wind.[n][e]

[msg Item_120]
[s]A spiral ring powered[n]by the wind.[n][e]

[msg Item_121]
[s]A spiral ring generating[n]wind power.[n][e]

[msg Item_122]
[s]A small ring charged[n]by electricity.[n][e]

[msg Item_123]
[s]A ring powered by[n]electricity.[n][e]

[msg Item_124]
[s]A ring generating[n]electricity.[n][e]

[msg Item_125]
[s]A spiral ring charged[n]by electricity.[n][e]

[msg Item_126]
[s]A spiral ring powered[n]by electricity.[n][e]

[msg Item_127]
[s]A spiral ring generating[n]electricity.[n][e]

[msg Item_128]
[s]A ring with the might[n]of the heavens.[n][e]

[msg Item_129]
[s]A ring powered[n]by the heavens.[n][e]

[msg Item_12A]
[s]A spiral ring with the[n]might of the heavens.[n][e]

[msg Item_12B]
[s]A spiral ring powered[n]by the heavens.[n][e]

[msg Item_12C]
[s]A ring charged[n]by the heavens.[n][e]

[msg Item_12D]
[s]A ring powered[n]by the heavens.[n][e]

[msg Item_12E]
[s]A ring generating[n]heavenly power.[n][e]

[msg Item_12F]
[s]A spiral ring charged[n]by the heavens.[n][e]

[msg Item_130]
[s]A spiral ring powered[n]by the heavens.[n][e]

[msg Item_131]
[s]A spiral ring generating[n]heavenly power.[n][e]

[msg Item_132]
[s]A ring with the might[n]of hell.[n][e]

[msg Item_133]
[s]A ring with the great[n]might of hell.[n][e]

[msg Item_134]
[s]A spiral ring with the[n]might of hell.[n][e]

[msg Item_135]
[s]A spiral ring with the[n]great might of hell.[n][e]

[msg Item_136]
[s]A ring with an[n]aura of ill will.[n][e]

[msg Item_137]
[s]A ring with a curse[n]placed on it.[n][e]

[msg Item_138]
[s]A ring with a hex[n]placed on it.[n][e]

[msg Item_139]
[s]A spiral ring with[n]an aura of ill will.[n][e]

[msg Item_13A]
[s]A spiral ring with a[n]curse placed on it.[n][e]

[msg Item_13B]
[s]A spiral ring with a[n]hex placed on it.[n][e]

[msg Item_13C]
[s]A ring charged with[n]divine ability.[n][e]

[msg Item_13D]
[s]A ring powered with[n]divine ability.[n][e]

[msg Item_13E]
[s]A ring generating the[n]most divine ability.[n][e]

[msg Item_13F]
[s]A small ring charged[n]by nuclear power.[n][e]

[msg Item_140]
[s]A ring powered by[n]nuclear energy.[n][e]

[msg Item_141]
[s]A ring generating[n]nuclear power.[n][e]

[msg Item_142]
[s]A spiral ring charged[n]by nuclear power.[n][e]

[msg Item_143]
[s]A spiral ring powered[n]by nuclear energy.[n][e]

[msg Item_144]
[s]A spiral ring generating[n]nuclear power.[n][e]

[msg Item_145]
[s]A wristband able to[n]make one dizzy.[n][e]

[msg Item_146]
[s]A spiral wristband able[n]to make many dizzy.[n][e]

[msg Item_147]
[s]A wristband that can[n]confuse others.[n][e]

[msg Item_148]
[s]A spiral wristband able[n]to confuse many.[n][e]

[msg Item_149]
[s]A wristband that can[n]frighten others.[n][e]

[msg Item_14A]
[s]A grinning mask that[n]can frighten many.[n][e]

[msg Item_14B]
[s]A wristband able to[n]make one forgetful.[n][e]

[msg Item_14C]
[s]A spiral wristband able[n]to make many forgetful.[n][e]

[msg Item_14D]
[s]A wristband able to[n]make one sleepy.[n][e]

[msg Item_14E]
[s]A spiral wristband able[n]to make many sleepy.[n][e]

[msg Item_14F]
[s]A wristband that can[n]enrage others.[n][e]

[msg Item_150]
[s]A spiral wristband that[n]can enrage many.[n][e]

[msg Item_151]
[s]A wristband able to[n]make one sad.[n][e]

[msg Item_152]
[s]A spiral wristband able[n]to make many sad.[n][e]

[msg Item_153]
[s]A wristband with[n]brainwashing power.[n][e]

[msg Item_154]
[s]A strange crown able to[n]brainwash many.[n][e]

[msg Item_155]
[s]A mask that steals[n]the enemy's health.[n][e]

[msg Item_156]
[s]A mask that steals[n]the enemy's spirit.[n][e]

[msg Item_157]
[s]A hand mirror that[n]frightens those who see it.[n][e]

[msg Item_158]
[s]A mirror that darkens[n]the mood around you.[n][e]

[msg Item_159]
[s]A camera that destroys[n]those who are afraid.[n][e]

[msg Item_15A]
[s]A ring with an ominous[n]fire design.[n][e]

[msg Item_15B]
[s]A wristband able to burn[n]everything in sight.[n][e]

[msg Item_15C]
[s]An artificial lily made[n]with small particles of ice.[n][e]

[msg Item_15D]
[s]A crown with the[n]power of ice.[n][e]

[msg Item_15E]
[s]An evil god's sculpture[n]that causes a storm.[n][e]

[msg Item_15F]
[s]A crown with the[n]power of wind.[n][e]

[msg Item_160]
[s]An electrified horn that[n]bears a goddess's face.[n][e]

[msg Item_161]
[s]A charm with the power[n]to call the thunder god.[n][e]

[msg Item_162]
[s]A cross imbued with[n]a god's judgment.[n][e]

[msg Item_163]
[s]Unused[n][e]

[msg Item_164]
[s]A white ribbon that bears[n]a young girl's curse.[n][e]

[msg Item_165]
[s]Unused[n][e]

[msg Item_166]
[s]The horn of a fire dragon,[n]imbued with heat.[n][e]

[msg Item_167]
[s]A crown that houses[n]nuclear power.[n][e]

[msg Item_168]
[s]A crown owned by[n]one in need of justice.[n][e]

[msg Item_169]
[s]A crown with the[n]power of the stars.[n][e]

[msg Item_16A]
[s]A small ring charged[n]by psychokinesis.[n][e]

[msg Item_16B]
[s]A ring powered by[n]psychokinesis.[n][e]

[msg Item_16C]
[s]A ring generating[n]psychokinesis.[n][e]

[msg Item_16D]
[s]A spiral ring charged[n]by psychokinesis.[n][e]

[msg Item_16E]
[s]A spiral ring powered[n]by psychokinesis.[n][e]

[msg Item_16F]
[s]A spiral ring generating[n]psychokinesis.[n][e]

[msg Item_170]
[s]RESERVE[n][e]

[msg Item_171]
[s]A mystical stone that has[n]the power of a dragon.[n][e]

[msg Item_172]
[s]A crown emanating[n]psychokinesis.[n][e]

[msg Item_173]
[s]A belt that lets you[n]strike hard.[n][e]

[msg Item_174]
[s]A belt that lets you[n]land a heavy blow.[n][e]

[msg Item_175]
[s]A belt that lets you[n]land a severe blow.[n][e]

[msg Item_176]
[s]A belt with the power[n]of God's Hand.[n][e]

[msg Item_177]
[s]A belt that allows a[n]strong lucky hit.[n][e]

[msg Item_178]
[s]A belt that allow a wearer[n]to land a huge lucky hit.[n][e]

[msg Item_179]
[s]A belt that allows one[n]to attack many times.[n][e]

[msg Item_17A]
[s]A belt that allows one[n]to attack several times.[n][e]

[msg Item_17B]
[s]A belt that allows one[n]to break things in half.[n][e]

[msg Item_17C]
[s]A belt that allows one[n]to slice things open.[n][e]

[msg Item_17D]
[s]A belt that allows a[n]fearsome strike.[n][e]

[msg Item_17E]
[s]A belt that allows a[n]fearsome sword dance.[n][e]

[msg Item_17F]
[s]Unused[n][e]

[msg Item_180]
[s]Unused[n][e]

[msg Item_181]
[s]A belt that gives you a[n]chance when cornered.[n][e]

[msg Item_182]
[s]A belt that allows one[n]to attack powerfully.[n][e]

[msg Item_183]
[s]A belt that allows one[n]to attack fiercely.[n][e]

[msg Item_184]
[s]A belt embossed with[n]snapping fingers.[n][e]

[msg Item_185]
[s]A belt that has 3 bullets.[n][e]

[msg Item_186]
[s]A belt equipped with[n]special bullets.[n][e]

[msg Item_187]
[s]A belt with bullets that[n]have a rebel's soul.[n][e]

[msg Item_188]
[s]A belt that has 2 bullets.[n][e]

[msg Item_189]
[s]A belt that allows one to[n]break anything.[n][e]

[msg Item_18A]
[s]A belt that allows one to[n]cut and kill anything.[n][e]

[msg Item_18B]
[s]A belt that allows one to[n]slice through anything.[n][e]

[msg Item_18C]
[s]A belt that helps its wearer[n]knock down anything.[n][e]

[msg Item_18D]
[s]A belt that allows one to[n]annihilate anything.[n][e]

[msg Item_18E]
[s]A dangerous belt[n]worn in fistfights.[n][e]

[msg Item_18F]
[s]A belt that allows you[n]to use your full potential.[n][e]

[msg Item_190]
[s]A belt that allows[n]a terrifying attack.[n][e]

[msg Item_191]
[s]A belt with the aura[n]of an ancient weapon.[n][e]

[msg Item_192]
[s]A belt with a pair of[n]fangs attached to it.[n][e]

[msg Item_193]
[s]A belt that allows[n]powerful slashes.[n][e]

[msg Item_194]
[s]A belt that allows many[n]powerful slashes.[n][e]

[msg Item_195]
[s]A belt that allows[n]a storm of slashes.[n][e]

[msg Item_196]
[s]The belt of a master[n]maulman.[n][e]

[msg Item_197]
[s]A belt that helps to[n]disorient an opponent.[n][e]

[msg Item_198]
[s]A belt with a black cat[n]design.[n][e]

[msg Item_199]
[s]A belt that allows one[n]an amnesiac strike.[n][e]

[msg Item_19A]
[s]RESERVE[n][e]

[msg Item_19B]
[s]A belt that will knock[n]one's lights out.[n][e]

[msg Item_19C]
[s]A belt designed to[n]give a mean slap.[n][e]

[msg Item_19D]
[s]A belt with a rather[n]depressing aura.[n][e]

[msg Item_19E]
[s]A strange belt with a[n]hypnotic design.[n][e]

[msg Item_19F]
[s]A popular belt with a[n]dazzling design.[n][e]

[msg Item_1A0]
[s]A belt that makes others[n]question your fashion sense.[n][e]

[msg Item_1A1]
[s]A fearsome belt to scare[n]your foes straight.[n][e]

[msg Item_1A2]
[s]A belt that can impair one's[n]memory.[n][e]

[msg Item_1A3]
[s]RESERVE[n][e]

[msg Item_1A4]
[s]You snooze, you lose.[n][e]

[msg Item_1A5]
[s]An infuriating belt made[n]for annoying others.[n][e]

[msg Item_1A6]
[s]A belt with a bleak,[n]depressing aura.[n][e]

[msg Item_1A7]
[s]A belt for persuading[n]others.[n][e]

[msg Item_1A8]
[s]A charm charged[n]with healing power.[n][e]

[msg Item_1A9]
[s]A charm powered[n]by healing power.[n][e]

[msg Item_1AA]
[s]A charm generating[n]healing power.[n][e]

[msg Item_1AB]
[s]A spiral charm charged[n]with healing power.[n][e]

[msg Item_1AC]
[s]A spiral charm powered[n]by healing power.[n][e]

[msg Item_1AD]
[s]Spiral charm generating[n]healing power.[n][e]

[msg Item_1AE]
[s]A charm that gives life[n]to the fallen.[n][e]

[msg Item_1AF]
[s]A powerful charm that[n]gives life to the fallen.[n][e]

[msg Item_1B0]
[s]A rosary that saves many[n]people through prayer.[n][e]

[msg Item_1B1]
[s]A charm of spiritual[n]water.[n][e]

[msg Item_1B2]
[s]A spiral charm of[n]spiritual water.[n][e]

[msg Item_1B3]
[s]A divine crown that can[n]save many people.[n][e]

[msg Item_1B4]
[s]A belt for when you[n]want all eyes on you.[n][e]

[msg Item_1B5]
[s]A ring with the power to[n]hide the wearer's existence.[n][e]

[msg Item_1B6]
[s]A charm that helps[n]one wake up.[n][e]

[msg Item_1B7]
[s]A spiral charm that can[n]heal mental fatigue for all.[n][e]

[msg Item_1B8]
[s]A charm that can[n]heal mental fatigue.[n][e]

[msg Item_1B9]
[s]A charm protecting from[n]elemental afflictions.[n][e]

[msg Item_1BA]
[s]A spiral charm that[n]helps many wake up.[n][e]

[msg Item_1BB]
[s]A spiral charm protecting[n]elemental afflictions for all.[n][e]

[msg Item_1BC]
[s]An anklet with an[n]evil spirit's strength.[n][e]

[msg Item_1BD]
[s]An anklet with the[n]power to increase[n]the wearer's defense.[n][e]

[msg Item_1BE]
[s]A brooch with the design[n]of a swift cat.[n][e]

[msg Item_1BF]
[s]An anklet that makes one[n]feel uplifted from within.[n][e]

[msg Item_1C0]
[s]A spiral anklet with[n]an evil spirit's strength.[n][e]

[msg Item_1C1]
[s]A spiral anklet with[n]the power to increase[n]everyone's defense.[n][e]

[msg Item_1C2]
[s]A spiral anklet that can[n]raise everyone's reflexes.[n][e]

[msg Item_1C3]
[s]A brooch that increases[n]stats when in a pinch.[n][e]

[msg Item_1C4]
[s]An anklet able to make[n]an enemy weak.[n][e]

[msg Item_1C5]
[s]An anklet that lowers[n]an enemy's defenses.[n][e]

[msg Item_1C6]
[s]An anklet that slows[n]reaction times.[n][e]

[msg Item_1C7]
[s]An anklet that causes[n]enemies to feel weak.[n][e]

[msg Item_1C8]
[s]A spiral anklet able to[n]make enemies weak.[n][e]

[msg Item_1C9]
[s]A spiral anklet that lowers[n]an enemy's defenses.[n][e]

[msg Item_1CA]
[s]A spiral anklet that[n]slows reaction times.[n][e]

[msg Item_1CB]
[s]An anklet that relieves[n]all from feeling powerless.[n][e]

[msg Item_1CC]
[s]An anklet with the power[n]to calm an enemy down.[n][e]

[msg Item_1CD]
[s]An anklet enhancing[n]one's physical attacks.[n][e]

[msg Item_1CE]
[s]An anklet enhancing[n]one's magical attacks.[n][e]

[msg Item_1CF]
[s]An anklet that sharpens[n]concentration.[n][e]

[msg Item_1D0]
[s]An anklet that sharpens[n]concentration of many.[n][e]

[msg Item_1D1]
[s]A charm with the power[n]to reflect magical attacks.[n][e]

[msg Item_1D2]
[s]A charm with the power[n]to reflect physical attacks.[n][e]

[msg Item_1D3]
[s]A charm that protects[n]one from death.[n][e]

[msg Item_1D4]
[s]A charm that can break[n]physical reflecting barriers.[n][e]

[msg Item_1D5]
[s]A charm that can break[n]magic reflecting barriers.[n][e]

[msg Item_1D6]
[s]A choker that shields[n]one from fire.[n][e]

[msg Item_1D7]
[s]A choker that shields[n]one from ice.[n][e]

[msg Item_1D8]
[s]A choker that shields[n]one from electricity.[n][e]

[msg Item_1D9]
[s]A choker that shields[n]one from the wind.[n][e]

[msg Item_1DA]
[s]A bell that breaks[n]fire barriers.[n][e]

[msg Item_1DB]
[s]A bell that breaks[n]ice barriers.[n][e]

[msg Item_1DC]
[s]A bell that breaks[n]wind barriers.[n][e]

[msg Item_1DD]
[s]A bell that breaks[n]electric barriers.[n][e]

[msg Item_1DE]
[s]A choker that shields[n]one from radiation.[n][e]

[msg Item_1DF]
[s]A choker that shields[n]one from psychokinesis.[n][e]

[msg Item_1E0]
[s]A bell that breaks[n]nuclear barriers.[n][e]

[msg Item_1E1]
[s]A bell that breaks[n]psychokinetic barriers.[n][e]

[msg Item_1E2]
[s]RESERVE[n][e]

[msg Item_1E3]
[s]A royal gem that[n]empowers its owner.[n][e]

[msg Item_1E4]
[s]A royal necklace that[n]uplifts the wearer's heart.[n][e]

[msg Item_1E5]
[s]A royal gem that[n]raises the wearer's spirits.[n][e]

[msg Item_1E6]
[s]A royal crown that[n]makes the wearer radiant.[n][e]

[msg Item_1E7]
[s]A royal magical gem that[n]brings calamity.[n][e]

[msg Item_1E8]
[s]A royal magical gem with[n]the power of an emperor.[n][e]

[msg Item_1E9]
[s]Royal gem said to be[n]cursed, but healing.[n][e]

[msg Item_1EA]
[s]A royal magical gem that[n]helps avoid magic skills.[n][e]

[msg Item_1EB]
[s]A magical metal that[n]protects the holder.[n][e]

[msg Item_1EC]
[s]A royal metal that[n]protects the holder.[n][e]

[msg Item_1ED]
[s]A lucky ring worn by[n]a famous gambler.[n][e]

[msg Item_1EE]
[s]A netsuke that is quite[n]impressive.[n][e]

[msg Item_1EF]
[s]A brooch that houses[n]nuclear power.[n][e]

[msg Item_1F0]
[s]A crimson red glove that[n]dances in starlight.[n][e]

[msg Item_1F1]
[s]A set of cool[n]headphones.[n][e]

[msg Item_1F2]
[s]The warden's favorite[n]baton.[n][e]

[msg Item_1F3]
[s]Feathery cape that makes[n]one harder to be hit.[n][e]

[msg Item_1F4]
[s]A device with a gun-[n]enhancing app.[n][e]

[msg Item_1F5]
[s]A strap made for[n]wearing a camera.[n][e]

[msg Item_1F6]
[s]Unused Item[n][e]

[msg Item_1F7]
[s]RESERVE[n][e]

[msg Item_1F8]
[s]RESERVE[n][e]

[msg Item_1F9]
[s]RESERVE[n][e]

[msg Item_1FA]
[s]RESERVE[n][e]

[msg Item_1FB]
[s]RESERVE[n][e]

[msg Item_1FC]
[s]RESERVE[n][e]

[msg Item_1FD]
[s]RESERVE[n][e]

[msg Item_1FE]
[s]RESERVE[n][e]

[msg Item_1FF]
[s]RESERVE[n][e]

