[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Unused[n][e]

[msg Item_002]
[s]Plain black tee.[n][e]

[msg Item_003]
[s]A yellow tee with a[n]flashy design on it.[n][e]

[msg Item_004]
[s]A yellow neckerchief.[n][e]

[msg Item_005]
[s]Baseball jacket. Goes[n]well with casual clothes.[n][e]

[msg Item_006]
[s]A white dress shirt.[n][e]

[msg Item_007]
[s]A slimming, long[n]sleeve turtleneck.[n][e]

[msg Item_008]
[s]A comfortable pink top.[n][e]

[msg Item_009]
[s]A simple, but fun,[n]cutsew.[n][e]

[msg Item_00A]
[s]A tailored shirt that[n]goes well with a suit.[n][e]

[msg Item_00B]
[s]Undershirt designed to[n]absorb moisture well.[n][e]

[msg Item_00C]
[s]Undershirt that absorbs[n]the blood of enemies.[n][e]

[msg Item_00D]
[s]RESERVE[n][e]

[msg Item_00E]
[s]Unisex equipment.[n]Dusty; feudal design.[n][e]

[msg Item_00F]
[s]RESERVE[n][e]

[msg Item_010]
[s]Protective pads for[n]your shoulders.[n][e]

[msg Item_011]
[s]A camisole that helps[n]combat memory loss.[n][e]

[msg Item_012]
[s]Vest worn by snipers to[n]help stay awake and alert.[n][e]

[msg Item_013]
[s]A cat collar made to[n]memorialize the owner.[n][e]

[msg Item_014]
[s]Old suit of armor once[n]worn by a feline knight.[n][e]

[msg Item_015]
[s]Suit of armor once worn[n]by a feline knight.[n][e]

[msg Item_016]
[s]A worn jacket that makes[n]you look like royalty.[n][e]

[msg Item_017]
[s]A fine jacket that makes[n]you look like royalty.[n][e]

[msg Item_018]
[s]RESERVE[n][e]

[msg Item_019]
[s]RESERVE[n][e]

[msg Item_01A]
[s]RESERVE[n][e]

[msg Item_01B]
[s]A cute sweater for[n]a cat to wear.[n][e]

[msg Item_01C]
[s]A worn, white cape. It's[n]light as an angel's wings.[n][e]

[msg Item_01D]
[s]A white cape. It's light[n]as an angel's wings.[n][e]

[msg Item_01E]
[s]Worn yet revealing set[n]of pajamas. [n][e]

[msg Item_01F]
[s]A rather revealing set[n]of pajamas. [n][e]

[msg Item_020]
[s]An ancient Roman tunic[n]worn by the very patient.[n][e]

[msg Item_021]
[s]A well-insulated apron[n]worn for many reasons.[n][e]

[msg Item_022]
[s]A shirt with a curse[n]sewn into every stitch.[n][e]

[msg Item_023]
[s]A scarf that takes a[n]weight off your heart.[n][e]

[msg Item_024]
[s]A soft, silk dress[n]that soaks up magic.[n][e]

[msg Item_025]
[s]A top quality silk dress[n]that soaks up magic.[n][e]

[msg Item_026]
[s]A lovely blue hood that[n]bolsters mental prowess.[n][e]

[msg Item_027]
[s]A regal blue hood that[n]bolsters mental prowess.[n][e]

[msg Item_028]
[s]A bulletproof vest[n]used by survivalists.[n][e]

[msg Item_029]
[s]A ladylike dress that[n]soothes the wearer.[n][e]

[msg Item_02A]
[s]Clothes that calm your[n]heart and mind.[n][e]

[msg Item_02B]
[s]A pet cone designed[n]to help wounds heal.[n][e]

[msg Item_02C]
[s]An old Japanese-style[n]outfit made out of paper.[n][e]

[msg Item_02D]
[s]A Japanese-style outfit[n]made out of paper.[n][e]

[msg Item_02E]
[s]Worn Chinese dress said[n]to be woven by a fairy.[n][e]

[msg Item_02F]
[s]A Chinese dress said to[n]be woven by a fairy.[n][e]

[msg Item_030]
[s]A faded scarf decorated[n]with mythological figures.[n][e]

[msg Item_031]
[s]Colorful scarf decorated[n]with mythological figures.[n][e]

[msg Item_032]
[s]RESERVE[n][e]

[msg Item_033]
[s]RESERVE[n][e]

[msg Item_034]
[s]Makes the wearer feel[n]at one with the cosmos.[n][e]

[msg Item_035]
[s]A blouse with bright,[n]eyecatching patterns.[n][e]

[msg Item_036]
[s]Made for night shifts to[n]help fight drowsiness.[n][e]

[msg Item_037]
[s]Protects against[n]electricity.[n][e]

[msg Item_038]
[s]A dress with colorful[n]feathers.[n][e]

[msg Item_039]
[s]A top-quality dress with[n]colorful feathers.[n][e]

[msg Item_03A]
[s]RESERVE[n][e]

[msg Item_03B]
[s]RESERVE[n][e]

[msg Item_03C]
[s]A durable men's[n]athletic shirt.[n][e]

[msg Item_03D]
[s]A camisole that helps[n]increase endurance.[n][e]

[msg Item_03E]
[s]RESERVE[n][e]

[msg Item_03F]
[s]A scarf woven with tough[n]thread to withstand impact.[n][e]

[msg Item_040]
[s]An old haori that makes [n]struggle more bearable.[n][e]

[msg Item_041]
[s]A haori that makes [n]struggle more bearable.[n][e]

[msg Item_042]
[s]Old coat of mail once[n]worn by a Nekomata.[n][e]

[msg Item_043]
[s]Coat of mail once worn[n]by a Nekomata.[n][e]

[msg Item_044]
[s]A worn apron that fills[n]you with burning passion.[n][e]

[msg Item_045]
[s]An apron that fills you[n]with burning passion.[n][e]

[msg Item_046]
[s]A red cape once owned[n]by a bullfighter.[n][e]

[msg Item_047]
[s]A blood-red cape once[n]owned by a bullfighter.[n][e]

[msg Item_048]
[s]A vest with a depiction[n]of Buddha.[n][e]

[msg Item_049]
[s]A light robe said to be[n]favored by the gods.[n][e]

[msg Item_04A]
[s]The Pope's regal robes.[n][e]

[msg Item_04B]
[s]A cat collar with real[n]impulse-control issues.[n][e]

[msg Item_04C]
[s]RESERVE[n][e]

[msg Item_04D]
[s]RESERVE[n][e]

[msg Item_04E]
[s]RESERVE[n][e]

[msg Item_04F]
[s]RESERVE[n][e]

[msg Item_050]
[s]A military-grade[n]utility vest.[n][e]

[msg Item_051]
[s]A sturdy corset made[n]with tough materials.[n][e]

[msg Item_052]
[s]RESERVE[n][e]

[msg Item_053]
[s]A radiant, bejeweled[n]cat collar.[n][e]

[msg Item_054]
[s]An old robe woven in the[n]image of ancient Pharaohs.[n][e]

[msg Item_055]
[s]A robe woven in the[n]image of ancient Pharaohs.[n][e]

[msg Item_056]
[s]A worn mystical robe[n]used in secret rituals.[n][e]

[msg Item_057]
[s]A mystical robe used[n]in secret rituals.[n][e]

[msg Item_058]
[s]An exotic but old scarf[n]made of snake skin.[n][e]

[msg Item_059]
[s]An exotic, perfect scarf[n]made of snake skin.[n][e]

[msg Item_05A]
[s]A breastplate imbued[n]with the will of a knight.[n][e]

[msg Item_05B]
[s]A breastplate imbued[n]with the will of a knight.[n][e]

[msg Item_05C]
[s]Lightweight vest that[n]makes the wearer calm.[n][e]

[msg Item_05D]
[s]An incredibly tight[n]titanium corset.[n][e]

[msg Item_05E]
[s]A shirt made to help[n]prevent despair.[n][e]

[msg Item_05F]
[s]A collar that makes it[n]hard to feel rage.[n][e]

[msg Item_060]
[s]Magic armor that evades[n]the wind.[n][e]

[msg Item_061]
[s]Top-quality armor that[n]evades the wind.[n][e]

[msg Item_062]
[s]RESERVE[n][e]

[msg Item_063]
[s]RESERVE[n][e]

[msg Item_064]
[s]A vest that can survive[n]a stomping from a giant.[n][e]

[msg Item_065]
[s]A swimsuit designed to[n]make movement easier.[n][e]

[msg Item_066]
[s]RESERVE[n][e]

[msg Item_067]
[s]A collar with the will[n]to defeat your enemies.[n][e]

[msg Item_068]
[s]A worn seductive[n]undershirt.[n][e]

[msg Item_069]
[s]A seductive undershirt.[n][e]

[msg Item_06A]
[s]An old, surprisingly[n]staticky scarf.[n][e]

[msg Item_06B]
[s]A surprisingly staticky[n]scarf.[n][e]

[msg Item_06C]
[s]Faded military fatigues[n]that aid in survival skills.[n][e]

[msg Item_06D]
[s]Military fatigues that[n]aid in survival skills.[n][e]

[msg Item_06E]
[s]RESERVE[n][e]

[msg Item_06F]
[s]RESERVE[n][e]

[msg Item_070]
[s]A haori with a pattern[n]that calms the mind.[n][e]

[msg Item_071]
[s]A dress possessing[n]powers of divination.[n][e]

[msg Item_072]
[s]A vest marked by[n]ancient runes.[n][e]

[msg Item_073]
[s]A scarf that fills you[n]with courage.[n][e]

[msg Item_074]
[s]A mystical robe that[n]imparts good luck.[n][e]

[msg Item_075]
[s]A mystical robe that[n]imparts great luck.[n][e]

[msg Item_076]
[s]RESERVE[n][e]

[msg Item_077]
[s]RESERVE[n][e]

[msg Item_078]
[s]Body armor made from[n]thin, folded iron sheets.[n][e]

[msg Item_079]
[s]A camouflage-patterned[n]dress that looks sharp.[n][e]

[msg Item_07A]
[s]RESERVE[n][e]

[msg Item_07B]
[s]A collar inspired by the[n]Feng Shui measurer.[n][e]

[msg Item_07C]
[s]A gaudy, worn, leopard[n]print vest.[n][e]

[msg Item_07D]
[s]A gaudy leopard print[n]vest.[n][e]

[msg Item_07E]
[s]An old collar fitting[n]only the pure-hearted.[n][e]

[msg Item_07F]
[s]A collar fitting only[n]the pure-hearted.[n][e]

[msg Item_080]
[s]Old black tights made[n]with tough fabric.[n][e]

[msg Item_081]
[s]Black tights made[n]with tough fabric.[n][e]

[msg Item_082]
[s]RESERVE[n][e]

[msg Item_083]
[s]RESERVE[n][e]

[msg Item_084]
[s]A festive happi worn[n]by firefighters.[n][e]

[msg Item_085]
[s]A peculiar cape that[n]clears the eyes.[n][e]

[msg Item_086]
[s]A garish shirt that guards[n]from brainwashing.[n][e]

[msg Item_087]
[s]Designed to look like[n]a water droplet splash.[n][e]

[msg Item_088]
[s]A regal cape that's[n]cold to the touch.[n][e]

[msg Item_089]
[s]The most regal of capes[n]that's cold to the touch.[n][e]

[msg Item_08A]
[s]RESERVE[n][e]

[msg Item_08B]
[s]RESERVE[n][e]

[msg Item_08C]
[s]A sturdy vest worn[n]by emperors.[n][e]

[msg Item_08D]
[s]A light and sturdy belt[n]worn by emperors.[n][e]

[msg Item_08E]
[s]RESERVE[n][e]

[msg Item_08F]
[s]A dark-colored collar that[n]inspires the fighting spirit.[n][e]

[msg Item_090]
[s]An old scarf imbued with[n]the soul of a dancing lion.[n][e]

[msg Item_091]
[s]A scarf imbued with the[n]soul of a dancing lion.[n][e]

[msg Item_092]
[s]An old but frightening[n]set of armor.[n][e]

[msg Item_093]
[s]A frightening set of[n]armor.[n][e]

[msg Item_094]
[s]An old, light, wild[n]vest with fur on it.[n][e]

[msg Item_095]
[s]A light, wild vest[n]with fur on it.[n][e]

[msg Item_096]
[s]RESERVE[n][e]

[msg Item_097]
[s]RESERVE[n][e]

[msg Item_098]
[s]A durable jacket with[n]a demonic design on it.[n][e]

[msg Item_099]
[s]A warm dress that's[n]good for the winter.[n][e]

[msg Item_09A]
[s]A shirt that taps into[n]all recorded memories.[n][e]

[msg Item_09B]
[s]A scarf made with a[n]passionate red color.[n][e]

[msg Item_09C]
[s]RESERVE[n][e]

[msg Item_09D]
[s]RESERVE[n][e]

[msg Item_09E]
[s]RESERVE[n][e]

[msg Item_09F]
[s]RESERVE[n][e]

[msg Item_0A0]
[s]Golden robes worn by[n]an immortal hero.[n][e]

[msg Item_0A1]
[s]A very light robe that[n]can pierce the heavens.[n][e]

[msg Item_0A2]
[s]RESERVE[n][e]

[msg Item_0A3]
[s]The world's most[n]desired cat collar.[n][e]

[msg Item_0A4]
[s]An old, racy bikini[n]that draws the eye.[n][e]

[msg Item_0A5]
[s]A racy bikini that[n]draws the eye.[n][e]

[msg Item_0A6]
[s]Worn men's underwear.[n]Fills one with courage.[n][e]

[msg Item_0A7]
[s]Men's printed underwear.[n]Fills one with courage.[n][e]

[msg Item_0A8]
[s]Old scarf with a whirled[n]vortex pattern.[n][e]

[msg Item_0A9]
[s]Scarf with a whirled[n]vortex pattern.[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]RESERVE[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]RESERVE[n][e]

[msg Item_0AE]
[s]A scarf that wraps the[n]wearer in compassion.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]RESERVE[n][e]

[msg Item_0B2]
[s]RESERVE[n][e]

[msg Item_0B3]
[s]RESERVE[n][e]

[msg Item_0B4]
[s]A legendary vest worn by[n]the immortal divine law.[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]Worn tights imbued[n]with terrifying magic.[n][e]

[msg Item_0B7]
[s]Tights that hide a[n]terrifying magic.[n][e]

[msg Item_0B8]
[s]An old, black outfit[n]imbued with magic.[n][e]

[msg Item_0B9]
[s]A black outfit imbued[n]with magic.[n][e]

[msg Item_0BA]
[s]An old scarf as tough[n]as dragon's scales.[n][e]

[msg Item_0BB]
[s]A scarf as tough as[n]dragon's scales.[n][e]

[msg Item_0BC]
[s]RESERVE[n][e]

[msg Item_0BD]
[s]RESERVE[n][e]

[msg Item_0BE]
[s]RESERVE[n][e]

[msg Item_0BF]
[s]RESERVE[n][e]

[msg Item_0C0]
[s]Armor guarding you from[n]worldly desires.[n][e]

[msg Item_0C1]
[s]Protects its wearer[n]from curses.[n][e]

[msg Item_0C2]
[s]Robes to help[n]evade curses.[n][e]

[msg Item_0C3]
[s]Royal armor that wards[n]away worldly desires.[n][e]

[msg Item_0C4]
[s]RESERVE[n][e]

[msg Item_0C5]
[s]Bra blessed by angels.[n]Said to stop lightning.[n][e]

[msg Item_0C6]
[s]RESERVE[n][e]

[msg Item_0C7]
[s]Extra-blessed; great at[n]stopping lightning.[n][e]

[msg Item_0C8]
[s]RESERVE[n][e]

[msg Item_0C9]
[s]Made of black feathers.[n]Guards against radiation.[n][e]

[msg Item_0CA]
[s]Made of royal feathers.[n]Guards against radiation.[n][e]

[msg Item_0CB]
[s]A pitch black jacket that[n]protects against curses.[n][e]

[msg Item_0CC]
[s]RESERVE[n][e]

[msg Item_0CD]
[s]A royal robe to[n]help evade curses.[n][e]

[msg Item_0CE]
[s]A black robe with the[n]power to transmutate.[n][e]

[msg Item_0CF]
[s]RESERVE[n][e]

[msg Item_0D0]
[s]A royal robe that emits[n]a regal, soft glow.[n][e]

[msg Item_0D1]
[s]A wrap that's awkward[n]to wear and to look at.[n][e]

[msg Item_0D2]
[s]A robe that emits[n]a soft glow.[n][e]

[msg Item_0D3]
[s]Armor with a pentagram[n]etching.[n][e]

[msg Item_0D4]
[s]Regal armor with a[n]pentagram etching.[n][e]

[msg Item_0D5]
[s]Women's equipment.[n]Dusty; feudal design.[n][e]

[msg Item_0D6]
[s]Equipment for cats.[n]Dusty; feudal design.[n][e]

[msg Item_0D7]
[s]Men's equipment.[n]Dusty; feudal design.[n][e]

[msg Item_0D8]
[s]Men's equipment.[n]Covered in paint stains.[n][e]

[msg Item_0D9]
[s]Equipment for cats.[n]Covered in paint stains.[n][e]

[msg Item_0DA]
[s]Women's equipment.[n]Covered in paint stains.[n][e]

[msg Item_0DB]
[s]Men's equipment.[n]Covered in gold smudges.[n][e]

[msg Item_0DC]
[s]Equipment for cats.[n]Covered in gold smudges.[n][e]

[msg Item_0DD]
[s]Women's equipment.[n]Covered in gold smudges.[n][e]

[msg Item_0DE]
[s]Men's equipment.[n]Full of sand.[n][e]

[msg Item_0DF]
[s]Women's equipment.[n]Full of sand.[n][e]

[msg Item_0E0]
[s]Equipment for cats.[n]Full of sand.[n][e]

[msg Item_0E1]
[s]Women's equipment.[n]Covered in space dust.[n][e]

[msg Item_0E2]
[s]Equipment for cats.[n]Covered in space dust.[n][e]

[msg Item_0E3]
[s]Men's equipment.[n]Covered in space dust.[n][e]

[msg Item_0E4]
[s]Men's equipment.[n]Sullied through gambling.[n][e]

[msg Item_0E5]
[s]Equipment for cats.[n]Sullied through gambling.[n][e]

[msg Item_0E6]
[s]Women's equipment.[n]Sullied through gambling.[n][e]

[msg Item_0E7]
[s]Equipment for cats.[n]Sullied with corruption.[n][e]

[msg Item_0E8]
[s]Men's equipment.[n]Sullied with corruption.[n][e]

[msg Item_0E9]
[s]Women's equipment.[n]Sullied with corruption.[n][e]

[msg Item_0EA]
[s]Women's equipment.[n]Tainted with greed.[n][e]

[msg Item_0EB]
[s]Men's equipment.[n]Tainted with greed.[n][e]

[msg Item_0EC]
[s]Equipment for cats.[n]Tainted with greed.[n][e]

[msg Item_0ED]
[s]Men's equipment.[n]Blindingly divine.[n][e]

[msg Item_0EE]
[s]Women's equipment.[n]Blindingly divine.[n][e]

[msg Item_0EF]
[s]Equipment for cats.[n]Blindingly divine.[n][e]

[msg Item_0F0]
[s]RESERVE[n][e]

[msg Item_0F1]
[s]RESERVE[n][e]

[msg Item_0F2]
[s]RESERVE[n][e]

[msg Item_0F3]
[s]RESERVE[n][e]

[msg Item_0F4]
[s]RESERVE[n][e]

[msg Item_0F5]
[s]RESERVE[n][e]

[msg Item_0F6]
[s]RESERVE[n][e]

[msg Item_0F7]
[s]RESERVE[n][e]

[msg Item_0F8]
[s]RESERVE[n][e]

[msg Item_0F9]
[s]RESERVE[n][e]

[msg Item_0FA]
[s]RESERVE[n][e]

[msg Item_0FB]
[s]RESERVE[n][e]

[msg Item_0FC]
[s]RESERVE[n][e]

[msg Item_0FD]
[s]RESERVE[n][e]

[msg Item_0FE]
[s]RESERVE[n][e]

[msg Item_0FF]
[s]RESERVE[n][e]

[msg Item_100]
[s]RESERVE[n][e]

[msg Item_101]
[s]RESERVE[n][e]

[msg Item_102]
[s]RESERVE[n][e]

[msg Item_103]
[s]RESERVE[n][e]

[msg Item_104]
[s]RESERVE[n][e]

[msg Item_105]
[s]RESERVE[n][e]

[msg Item_106]
[s]RESERVE[n][e]

[msg Item_107]
[s]RESERVE[n][e]

[msg Item_108]
[s]RESERVE[n][e]

[msg Item_109]
[s]RESERVE[n][e]

[msg Item_10A]
[s]RESERVE[n][e]

[msg Item_10B]
[s]RESERVE[n][e]

[msg Item_10C]
[s]RESERVE[n][e]

[msg Item_10D]
[s]A vest for those with[n]a positive outlook.[n][e]

[msg Item_10E]
[s]A robe designed using[n]taoist wisdom.[n][e]

[msg Item_10F]
[s]A scarf with an ideal[n]world drawn on it.[n][e]

[msg Item_110]
[s]A haori painted with[n]soothing colors.[n][e]

[msg Item_111]
[s]Solemn-looking armor[n]blessed by a god.[n][e]

[msg Item_112]
[s]A thin dress that fills the[n]body with a sense of unity.[n][e]

[msg Item_113]
[s]A mysterious collar[n]full of radiant light.[n][e]

[msg Item_114]
[s]RESERVE[n][e]

[msg Item_115]
[s]A strange button-down[n]shirt that seems lucky.[n][e]

[msg Item_116]
[s]A big shirt that imparts[n]an unwavering spirit.[n][e]

[msg Item_117]
[s]A mysterious vest that[n]fills you with vitality.[n][e]

[msg Item_118]
[s]Unused[n][e]

[msg Item_119]
[s]Unused[n][e]

[msg Item_11A]
[s]A breastplate worn by[n]a night guard soldier.[n][e]

[msg Item_11B]
[s]A bullet proof vest[n]painted gold.[n][e]

[msg Item_11C]
[s]A robe that seems[n]to be cursed.[n][e]

[msg Item_11D]
[s]Protective wear worn[n]by astronauts in space.[n][e]

[msg Item_11E]
[s]Layered yellow dress[n]imbued with the wind.[n][e]

[msg Item_11F]
[s]A divine vest created[n]by ancient wisdom.[n][e]

[msg Item_120]
[s]RESERVE[n][e]

[msg Item_121]
[s]RESERVE[n][e]

[msg Item_122]
[s]RESERVE[n][e]

[msg Item_123]
[s]RESERVE[n][e]

[msg Item_124]
[s]RESERVE[n][e]

[msg Item_125]
[s]RESERVE[n][e]

[msg Item_126]
[s]RESERVE[n][e]

[msg Item_127]
[s]RESERVE[n][e]

[msg Item_128]
[s]RESERVE[n][e]

[msg Item_129]
[s]RESERVE[n][e]

[msg Item_12A]
[s]RESERVE[n][e]

[msg Item_12B]
[s]RESERVE[n][e]

[msg Item_12C]
[s]RESERVE[n][e]

