[msg baton_touch_help_000]
[f 0 5 65278][f 2 1]Baton Pass Help Blank[n][e]

[msg baton_touch_help_101]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_102]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_103]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_201]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_202]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_203]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_301]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_302]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_303]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_401]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_402]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_403]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_501]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_502]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_503]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_601]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_602]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_603]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_701]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_702]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_703]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_801]
[f 0 5 65278][f 2 1]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_802]
[f 0 5 65278][f 2 1]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_803]
[f 0 5 65278][f 2 1]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_901]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_902]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_903]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_A01]
[f 0 5 65278][f 2 1]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_A02]
[f 0 5 65278][f 2 1]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_A03]
[f 0 5 65278][f 2 1]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

