[msg customParts00]
[f 0 5 65278][f 2 1]Custom part that[n]increases accuracy.[n][e]

[msg customParts01]
[f 0 5 65278][f 2 1]Custom part that decreases[n]power for greater accuracy.[n][e]

[msg customParts02]
[f 0 5 65278][f 2 1]Custom part that[n]increases attack.[n][e]

[msg customParts03]
[f 0 5 65278][f 2 1]Custom part that decreases[n]accuracy for greater power.[n][e]

[msg customParts04]
[f 0 5 65278][f 2 1]Custom part that decreases[n]accuracy for greater power.[n][e]

[msg customParts05]
[f 0 5 65278][f 2 1]Custom part with fire camo.[n]Decreases attack and bullets.[n][e]

[msg customParts06]
[f 0 5 65278][f 2 1]Custom part, lightning camo.[n]Decreases attack and bullets.[n][e]

[msg customParts07]
[f 0 5 65278][f 2 1]Custom part with ice camo.[n]Decreases attack and bullets.[n][e]

