[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]BLANK[n][e]

[msg Item_002]
[s]BLANK[n][e]

[msg Item_003]
[s]BLANK[n][e]

[msg Item_004]
[s]BLANK[n][e]

[msg Item_005]
[s]BLANK[n][e]

[msg Item_006]
[s]BLANK[n][e]

[msg Item_007]
[s]BLANK[n][e]

[msg Item_008]
[s]BLANK[n][e]

[msg Item_009]
[s]BLANK[n][e]

[msg Item_00A]
[s]BLANK[n][e]

[msg Item_00B]
[s]BLANK[n][e]

[msg Item_00C]
[s]BLANK[n][e]

[msg Item_00D]
[s]BLANK[n][e]

[msg Item_00E]
[s]BLANK[n][e]

[msg Item_00F]
[s]BLANK[n][e]

[msg Item_010]
[s]BLANK[n][e]

[msg Item_011]
[s]BLANK[n][e]

[msg Item_012]
[s]BLANK[n][e]

[msg Item_013]
[s]BLANK[n][e]

[msg Item_014]
[s]BLANK[n][e]

[msg Item_015]
[s]BLANK[n][e]

[msg Item_016]
[s]BLANK[n][e]

[msg Item_017]
[s]BLANK[n][e]

[msg Item_018]
[s]BLANK[n][e]

[msg Item_019]
[s]BLANK[n][e]

[msg Item_01A]
[s]BLANK[n][e]

[msg Item_01B]
[s]BLANK[n][e]

[msg Item_01C]
[s]Unused[n][e]

[msg Item_01D]
[s]Unused[n][e]

[msg Item_01E]
[s]The key to Café Leblanc.[n]Now you can go out at[n]night.[n][e]

[msg Item_01F]
[s]A bag from Iwai with a[n]suspicious-looking model[n]gun.[n][e]

[msg Item_020]
[s]Unused[n][e]

[msg Item_021]
[s]Unused[n][e]

[msg Item_022]
[s]Unused[n][e]

[msg Item_023]
[s]A rusty old key to a chest.[n][e]

[msg Item_024]
[s]Unused[n][e]

[msg Item_025]
[s]Unused[n][e]

[msg Item_026]
[s]Unused[n][e]

[msg Item_027]
[s]Unused[n][e]

[msg Item_028]
[s]Unused[n][e]

[msg Item_029]
[s]Unused[n][e]

[msg Item_02A]
[s]Unused[n][e]

[msg Item_02B]
[s]Unused[n][e]

[msg Item_02C]
[s]Unused[n][e]

[msg Item_02D]
[s]Unused[n][e]

[msg Item_02E]
[s]Unused[n][e]

[msg Item_02F]
[s]Unused[n][e]

[msg Item_030]
[s]Allows you to fuse[n]Black Frost.[n][e]

[msg Item_031]
[s]Allows you to fuse[n]Bugs.[n][e]

[msg Item_032]
[s]A double-layered bookmark[n]that Justine uses.[n][e]

[msg Item_033]
[s]Unused[n][e]

[msg Item_034]
[s]Proof of Kawakami's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_035]
[s]Proof of Takemi's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_036]
[s]Proof of Chihaya's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_037]
[s]Proof of Ohya's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_038]
[s]Proof of Hifumi's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_039]
[s]Proof of Makoto's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_03A]
[s]Proof of Haru's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_03B]
[s]Proof of Ann's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_03C]
[s]Proof of Futaba's love.[n]Become closer if you have[n]a same-arcana Persona.[n][e]

[msg Item_03D]
[s]BLANK[n][e]

[msg Item_03E]
[s]Calculator Makoto used.[n]Shadow Factorization[n]unlocked.[n][e]

[msg Item_03F]
[s]Dyed by Haru herself.[n]Soil Improvement[n]unlocked.[n][e]

[msg Item_040]
[s]Has Ann on the cover. Sexy[n]Technique[f 1 9 0] and Crocodile[n]Tears unlocked.[n][e]

[msg Item_041]
[s]Futaba's promises. Treasure[n]Reboot and Mementos[n]Scan unlocked.[n][e]

[msg Item_042]
[s]Unique coupon from[n]Kawakami. Special[n]Massage unlocked.[n][e]

[msg Item_043]
[s]Engraved by Takemi.[n]Allows access to all[n]items sold at the clinic.[n][e]

[msg Item_044]
[s]Divined by Chihaya.[n]Partial fortune readings[n]unlocked.[n][e]

[msg Item_045]
[s]Ohya's personal notes.[n]All Scoops unlocked.[n][e]

[msg Item_046]
[s]Hifumi's favorite piece.[n]Touryou unlocked.[n][e]

[msg Item_047]
[s]Same as Ryuji's. Ryuji's[n]Harisen Recovery and[n]Stealth Dash unlocked.[n][e]

[msg Item_048]
[s]The scarf Morgana wears.[n]Pickpocket unlocked.[n][e]

[msg Item_049]
[s]Sojiro's prized recipe.[n]Always make the best[n]coffee and curry.[n][e]

[msg Item_04A]
[s]To be written by Mishima.[n]All EXP benefits[n]unlocked.[n][e]

[msg Item_04B]
[s]Iwai's family crest.[n]All customizations[n]unlocked.[n][e]

[msg Item_04C]
[s]Given to you by Lavenza.[n]All Velvet Room warden[n]features unlocked.[n][e]

[msg Item_04D]
[s]Yusuke's painting.[n]Allows for Skill Cards[n]to be copied.[n][e]

[msg Item_04E]
[s]A gift from Yoshida.[n]All speech abilities[n]unlocked.[n][e]

[msg Item_04F]
[s]Shinya's controller.[n]All gun techniques[n]unlocked.[n][e]

[msg Item_050]
[s]Has Sae's number on it.[n]Says "lawyer" instead[n]of "prosecutor."[n][e]

[msg Item_051]
[s]Gloves used by Akechi.[n]See enemy's properties[n]unlocked.[n][e]

[msg Item_052]
[s]Baton used by Sumire.[n]Carry oneself with grace[n]unlocked.[n][e]

[msg Item_053]
[s]Notebook containing Maruki's[n]research notes. Enhance[n]oneself unlocked.[n][e]

[msg Item_054]
[s]BLANK[n][e]

[msg Item_055]
[s]BLANK[n][e]

[msg Item_056]
[s]BLANK[n][e]

[msg Item_057]
[s]BLANK[n][e]

[msg Item_058]
[s]BLANK[n][e]

[msg Item_059]
[s]BLANK[n][e]

[msg Item_05A]
[s]BLANK[n][e]

[msg Item_05B]
[s]BLANK[n][e]

[msg Item_05C]
[s]BLANK[n][e]

[msg Item_05D]
[s]BLANK[n][e]

[msg Item_05E]
[s]BLANK[n][e]

[msg Item_05F]
[s]BLANK[n][e]

[msg Item_060]
[s]BLANK[n][e]

[msg Item_061]
[s]BLANK[n][e]

[msg Item_062]
[s]BLANK[n][e]

[msg Item_063]
[s]BLANK[n][e]

[msg Item_064]
[s]BLANK[n][e]

[msg Item_065]
[s]BLANK[n][e]

[msg Item_066]
[s]An old map, showing the[n]layout of the Old Castle.[n][e]

[msg Item_067]
[s]An old map, showing the[n]layout of the tower.[n][e]

[msg Item_068]
[s]BLANK[n][e]

[msg Item_069]
[s]A gold medal won in an[n]international competition.[n][e]

[msg Item_06A]
[s]BLANK[n][e]

[msg Item_06B]
[s]BLANK[n][e]

[msg Item_06C]
[s]BLANK[n][e]

[msg Item_06D]
[s]BLANK[n][e]

[msg Item_06E]
[s]BLANK[n][e]

[msg Item_06F]
[s]A book on the king.[n]It's pretty hefty.[n][e]

[msg Item_070]
[s]A book on the queen.[n]It's pretty hefty.[n][e]

[msg Item_071]
[s]A book on the slaves.[n]It's pretty hefty.[n][e]

[msg Item_072]
[s]Unused[n][e]

[msg Item_073]
[s]Unused[n][e]

[msg Item_074]
[s]The right eye thought to be[n]from Kamoshida's statue.[n][e]

[msg Item_075]
[s]The left eye thought to be[n]from Kamoshida's statue.[n][e]

[msg Item_076]
[s]A key used to open a vault[n]door at Kaneshiro's[n]Palace. 1/2[n][e]

[msg Item_077]
[s]A key used to open a vault[n]door at Kaneshiro's[n]Palace. 2/2[n][e]

[msg Item_078]
[s]The following is written:[n]R = C = 0, I = 1, H = 2[n][e]

[msg Item_079]
[s]Found in the Underground[n]Vault. P = I[n][e]

[msg Item_07A]
[s]Found in the Underground[n]Vault. E = 9, A = 3[n][e]

[msg Item_07B]
[s]Found in the Underground[n]Vault. U = A[n][e]

[msg Item_07C]
[s]Found in the Underground[n]Vault. G = P[n][e]

[msg Item_07D]
[s]Found in the Underground[n]Vault. O + H = 10[n][e]

[msg Item_07E]
[s]Found in the Underground[n]Vault. L = U + G, D = G[n][e]

[msg Item_07F]
[s]A gem with a black aura[n]found in the Pyramid.[n][e]

[msg Item_080]
[s]A gem with a crimson aura[n]found in the Pyramid.[n][e]

[msg Item_081]
[s]A gem with a white aura[n]found in the Pyramid.[n][e]

[msg Item_082]
[s]A gem with an azure aura[n]found in the Pyramid.[n][e]

[msg Item_083]
[s]Allows access to the[n]Members Floor of[n]Niijima's Palace.[n][e]

[msg Item_084]
[s]A bundle of paper you[n]stole back from bandits[n]at the desert town.[n][e]

[msg Item_085]
[s]A map of each floor of[n]Futaba's Palace.[n][e]

[msg Item_086]
[s]A partial map of[n]Niijima's Palace.[n][e]

[msg Item_087]
[s]A partial map of[n]Niijima's Palace.[n][e]

[msg Item_088]
[s]Kaneshiro's Palace's map.[n]Shows the lower floors[n]to the vaults.[n][e]

[msg Item_089]
[s]Allows access to the[n]High Limit Floor of[n]Niijima's Palace.[n][e]

[msg Item_08A]
[s]A map of Okumura's Palace.[n][e]

[msg Item_08B]
[s]The company badge for[n]Chief Clerks.[n][e]

[msg Item_08C]
[s]The company badge for[n]Section Chiefs.[n][e]

[msg Item_08D]
[s]The company badge for[n]Chief Directors.[n][e]

[msg Item_08E]
[s]The museum pamphlet.[n]Shows the entrance[n]to the central garden.[n][e]

[msg Item_08F]
[s]The museum pamphlet.[n]Shows the central[n]garden onward.[n][e]

[msg Item_090]
[s]Kaneshiro's Palace's map.[n]Shows the surface to[n]the lower floors.[n][e]

[msg Item_091]
[s]Opens the locked doors[n]in Kaneshiro's Palace.[n][e]

[msg Item_092]
[s]A partial map of[n]Niijima's Palace.[n][e]

[msg Item_093]
[s]Opens the locked doors[n]in Niijima's Palace.[n][e]

[msg Item_094]
[s]A map of the cruise ship.[n][e]

[msg Item_095]
[s]Allows entry into the[n]restaurant.[n][e]

[msg Item_096]
[s]A letter of introduction[n]from a VIP.[n][e]

[msg Item_097]
[s]One of two keys needed[n]to open the way into the[n]depths of Mementos.[n][e]

[msg Item_098]
[s]One of two keys needed[n]to open the way into the[n]depths of Mementos.[n][e]

[msg Item_099]
[s]BLANK[n][e]

[msg Item_09A]
[s]A tool used by thieves[n]to get around with[n]ease and grace.[n][e]

[msg Item_09B]
[s]A map of a large building.[n]The entrance hall's floor[n]can be seen.[n][e]

[msg Item_09C]
[s]A map of Maruki's Palace.[n]The structure of the facility[n]can be seen.[n][e]

[msg Item_09D]
[s]A card used by certain[n]members to enter[n]some of the doors.[n][e]

[msg Item_09E]
[s]A videotape without[n]a label. It seems like[n]it can still be played.[n][e]

[msg Item_09F]
[s]Unused[n][e]

[msg Item_0A0]
[s]A book detailing all sorts[n]of ways to get ripped.[n][e]

[msg Item_0A1]
[s]BLANK[n][e]

[msg Item_0A2]
[s]BLANK[n][e]

[msg Item_0A3]
[s]BLANK[n][e]

[msg Item_0A4]
[s]BLANK[n][e]

[msg Item_0A5]
[s]BLANK[n][e]

[msg Item_0A6]
[s]BLANK[n][e]

[msg Item_0A7]
[s]BLANK[n][e]

[msg Item_0A8]
[s]BLANK[n][e]

[msg Item_0A9]
[s]BLANK[n][e]

[msg Item_0AA]
[s]BLANK[n][e]

[msg Item_0AB]
[s]BLANK[n][e]

[msg Item_0AC]
[s]BLANK[n][e]

[msg Item_0AD]
[s]BLANK[n][e]

[msg Item_0AE]
[s]BLANK[n][e]

[msg Item_0AF]
[s]BLANK[n][e]

[msg Item_0B0]
[s]Unused[n][e]

[msg Item_0B1]
[s]Unused[n][e]

[msg Item_0B2]
[s]Unused[n][e]

[msg Item_0B3]
[s]Unused[n][e]

[msg Item_0B4]
[s]Unused[n][e]

[msg Item_0B5]
[s]Unused[n][e]

[msg Item_0B6]
[s]Unused[n][e]

[msg Item_0B7]
[s]Unused[n][e]

[msg Item_0B8]
[s]Unused[n][e]

[msg Item_0B9]
[s]Unused[n][e]

[msg Item_0BA]
[s]Unused[n][e]

[msg Item_0BB]
[s]Unused[n][e]

[msg Item_0BC]
[s]Unused[n][e]

[msg Item_0BD]
[s]Unused[n][e]

[msg Item_0BE]
[s]Unused[n][e]

[msg Item_0BF]
[s]Unused[n][e]

[msg Item_0C0]
[s]Unused[n][e]

[msg Item_0C1]
[s]Unused[n][e]

[msg Item_0C2]
[s]Unused[n][e]

[msg Item_0C3]
[s]Unused[n][e]

[msg Item_0C4]
[s]BLANK[n][e]

[msg Item_0C5]
[s]BLANK[n][e]

[msg Item_0C6]
[s]BLANK[n][e]

[msg Item_0C7]
[s]BLANK[n][e]

[msg Item_0C8]
[s]BLANK[n][e]

[msg Item_0C9]
[s]BLANK[n][e]

[msg Item_0CA]
[s]BLANK[n][e]

[msg Item_0CB]
[s]BLANK[n][e]

[msg Item_0CC]
[s]BLANK[n][e]

[msg Item_0CD]
[s]BLANK[n][e]

[msg Item_0CE]
[s]BLANK[n][e]

[msg Item_0CF]
[s]BLANK[n][e]

[msg Item_0D0]
[s]BLANK[n][e]

[msg Item_0D1]
[s]BLANK[n][e]

[msg Item_0D2]
[s]Unused[n][e]

[msg Item_0D3]
[s]Unused[n][e]

[msg Item_0D4]
[s]Unused[n][e]

[msg Item_0D5]
[s]Unused[n][e]

[msg Item_0D6]
[s]Unused[n][e]

[msg Item_0D7]
[s]Unused[n][e]

[msg Item_0D8]
[s]Unused[n][e]

[msg Item_0D9]
[s]A book from Jose for[n]collecting stamps.[n][e]

[msg Item_0DA]
[s]CD Single:[n]"He's a Trickster☆"[n][e]

[msg Item_0DB]
[s]A simple key without[n]any attachments.[n][e]

[msg Item_0DC]
[s]A star-shaped stone[n]that emits a mysterious[n]light from Jose.[n][e]

[msg Item_0DD]
[s]A bookmark with two[n]woven colored bands[n]used by Lavenza.[n][e]

[msg Item_0DE]
[s]A water tray created by[n]Jose used for planting[n]flowers.[n][e]

[msg Item_0DF]
[s]A document that enables[n]one to summon a Persona[n]for free.[n][e]

[msg Item_0E0]
[s]A ticket that[n]allows you to play[n]darts for free.[n][e]

[msg Item_0E1]
[s]A red stone that[n]seems to emit[n]a lustful energy.[n][e]

[msg Item_0E2]
[s]A green stone that[n]seems to emit[n]a lustful energy.[n][e]

[msg Item_0E3]
[s]A blue stone that[n]seems to emit[n]a lustful energy.[n][e]

[msg Item_0E4]
[s]Unused[n][e]

[msg Item_0E5]
[s]A red stone that[n]seems to emit[n]a dishonest energy.[n][e]

[msg Item_0E6]
[s]A green stone that[n]seems to emit[n]a dishonest energy.[n][e]

[msg Item_0E7]
[s]A blue stone that[n]seems to emit[n]a dishonest energy.[n][e]

[msg Item_0E8]
[s]Unused[n][e]

[msg Item_0E9]
[s]A red stone that[n]seems to emit[n]a voracious energy.[n][e]

[msg Item_0EA]
[s]A green stone that[n]seems to emit[n]a voracious energy.[n][e]

[msg Item_0EB]
[s]A blue stone that[n]seems to emit[n]a voracious energy.[n][e]

[msg Item_0EC]
[s]Unused[n][e]

[msg Item_0ED]
[s]A red stone that[n]seems to emit[n]an enraged energy.[n][e]

[msg Item_0EE]
[s]A green stone that[n]seems to emit[n]an enraged energy.[n][e]

[msg Item_0EF]
[s]A blue stone that[n]seems to emit[n]an enraged energy.[n][e]

[msg Item_0F0]
[s]Unused[n][e]

[msg Item_0F1]
[s]A red stone that[n]seems to emit[n]an avaricious energy.[n][e]

[msg Item_0F2]
[s]A green stone that[n]seems to emit[n]an avaricious energy.[n][e]

[msg Item_0F3]
[s]A blue stone that[n]seems to emit[n]an avaricious energy.[n][e]

[msg Item_0F4]
[s]Unused[n][e]

[msg Item_0F5]
[s]A red stone that[n]seems to emit[n]a jealous energy.[n][e]

[msg Item_0F6]
[s]A green stone that[n]seems to emit[n]a jealous energy.[n][e]

[msg Item_0F7]
[s]A blue stone that[n]seems to emit[n]a jealous energy.[n][e]

[msg Item_0F8]
[s]Unused[n][e]

[msg Item_0F9]
[s]A red stone that[n]seems to emit[n]an arrogant energy.[n][e]

[msg Item_0FA]
[s]A green stone that[n]seems to emit[n]an arrogant energy.[n][e]

[msg Item_0FB]
[s]A blue stone that[n]seems to emit[n]an arrogant energy.[n][e]

[msg Item_0FC]
[s]Unused[n][e]

[msg Item_0FD]
[s]A red stone that[n]seems to emit[n]a mournful energy.[n][e]

[msg Item_0FE]
[s]A green stone that[n]seems to emit[n]a mournful energy.[n][e]

[msg Item_0FF]
[s]A blue stone that[n]seems to emit[n]a mournful energy.[n][e]

