[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Unused[n][e]

[msg Item_002]
[s]Unused[n][e]

[msg Item_003]
[s]Unused[n][e]

[msg Item_004]
[s]Unused[n][e]

[msg Item_005]
[s]Unused[n][e]

[msg Item_006]
[s]Unused[n][e]

[msg Item_007]
[s]Unused[n][e]

[msg Item_008]
[s]Unused[n][e]

[msg Item_009]
[s]Unused[n][e]

[msg Item_00A]
[s]Unused[n][e]

[msg Item_00B]
[s]Unused[n][e]

[msg Item_00C]
[s]Unused[n][e]

[msg Item_00D]
[s]Unused[n][e]

[msg Item_00E]
[s]Unused[n][e]

[msg Item_00F]
[s]Unused[n][e]

[msg Item_010]
[s]Model gun typically[n]seen in mafia films.[n][e]

[msg Item_011]
[s]Model gun of a basic[n]high-caliber handgun.[n][e]

[msg Item_012]
[s]RESERVE[n][e]

[msg Item_013]
[s]Model gun based on one[n]popular in America.[n][e]

[msg Item_014]
[s]RESERVE[n][e]

[msg Item_015]
[s]Model gun based on[n]the Russian pistol.[n][e]

[msg Item_016]
[s]Upgraded version of the[n]model gun Nataraja.[n][e]

[msg Item_017]
[s]RESERVE[n][e]

[msg Item_018]
[s]RESERVE[n][e]

[msg Item_019]
[s]RESERVE[n][e]

[msg Item_01A]
[s]RESERVE[n][e]

[msg Item_01B]
[s]Model gun that special[n]forces use regularly.[n][e]

[msg Item_01C]
[s]RESERVE[n][e]

[msg Item_01D]
[s]RESERVE[n][e]

[msg Item_01E]
[s]Upgraded version of the[n]model gun Tyrant Pistol.[n][e]

[msg Item_01F]
[s]Model gun capable[n]of transmutation.[n][e]

[msg Item_020]
[s]Model gun based on the[n]short-barreled shotgun.[n][e]

[msg Item_021]
[s]RESERVE[n][e]

[msg Item_022]
[s]Model gun based on an[n]oversized shotgun.[n][e]

[msg Item_023]
[s]RESERVE[n][e]

[msg Item_024]
[s]RESERVE[n][e]

[msg Item_025]
[s]Model gun based on one[n]used in trench warfare.[n][e]

[msg Item_026]
[s]RESERVE[n][e]

[msg Item_027]
[s]Model gun based on a[n]fireworks launcher.[n][e]

[msg Item_028]
[s]Upgraded version of the[n]model gun Pumpkin Bomb.[n][e]

[msg Item_029]
[s]Upgraded version of the[n]model gun Megido Fire.[n][e]

[msg Item_02A]
[s]RESERVE[n][e]

[msg Item_02B]
[s]RESERVE[n][e]

[msg Item_02C]
[s]Pumpkin-shape model gun[n]capable of causing burns.[n][e]

[msg Item_02D]
[s]RESERVE[n][e]

[msg Item_02E]
[s]Model gun that can[n]also unlock things.[n][e]

[msg Item_02F]
[s]RESERVE[n][e]

[msg Item_030]
[s]RESERVE[n][e]

[msg Item_031]
[s]RESERVE[n][e]

[msg Item_032]
[s]RESERVE[n][e]

[msg Item_033]
[s]RESERVE[n][e]

[msg Item_034]
[s]RESERVE[n][e]

[msg Item_035]
[s]RESERVE[n][e]

[msg Item_036]
[s]RESERVE[n][e]

[msg Item_037]
[s]RESERVE[n][e]

[msg Item_038]
[s]RESERVE[n][e]

[msg Item_039]
[s]RESERVE[n][e]

[msg Item_03A]
[s]Model gun with[n]emphasis on handling.[n][e]

[msg Item_03B]
[s]RESERVE[n][e]

[msg Item_03C]
[s]RESERVE[n][e]

[msg Item_03D]
[s]Model gun inspired by[n]one used in Westerns.[n][e]

[msg Item_03E]
[s]Model gun that evokes[n]a sense of hellfire.[n][e]

[msg Item_03F]
[s]RESERVE[n][e]

[msg Item_040]
[s]A sturdy slingshot.[n][e]

[msg Item_041]
[s]RESERVE[n][e]

[msg Item_042]
[s]RESERVE[n][e]

[msg Item_043]
[s]RESERVE[n][e]

[msg Item_044]
[s]Slingshot with a[n]shrike aesthetic.[n][e]

[msg Item_045]
[s]RESERVE[n][e]

[msg Item_046]
[s]Upgraded version of the[n]slingshot Catnap.[n][e]

[msg Item_047]
[s]Slingshot with a[n]witch aesthetic.[n][e]

[msg Item_048]
[s]RESERVE[n][e]

[msg Item_049]
[s]Upgraded version of the[n]slingshot Sudarshana.[n][e]

[msg Item_04A]
[s]RESERVE[n][e]

[msg Item_04B]
[s]RESERVE[n][e]

[msg Item_04C]
[s]RESERVE[n][e]

[msg Item_04D]
[s]RESERVE[n][e]

[msg Item_04E]
[s]RESERVE[n][e]

[msg Item_04F]
[s]RESERVE[n][e]

[msg Item_050]
[s]RESERVE[n][e]

[msg Item_051]
[s]RESERVE[n][e]

[msg Item_052]
[s]RESERVE[n][e]

[msg Item_053]
[s]Slingshot that draws its[n]power from ley lines.[n][e]

[msg Item_054]
[s]RESERVE[n][e]

[msg Item_055]
[s]RESERVE[n][e]

[msg Item_056]
[s]RESERVE[n][e]

[msg Item_057]
[s]RESERVE[n][e]

[msg Item_058]
[s]RESERVE[n][e]

[msg Item_059]
[s]Slingshot that shoots[n]bullets as fast as a falcon.[n][e]

[msg Item_05A]
[s]A slingshot capable[n]of causing sleep.[n][e]

[msg Item_05B]
[s]RESERVE[n][e]

[msg Item_05C]
[s]RESERVE[n][e]

[msg Item_05D]
[s]A slingshot shining with[n]the light of the aurora.[n][e]

[msg Item_05E]
[s]A slingshot that flings[n]star-shaped ammunition.[n][e]

[msg Item_05F]
[s]A slingshot strong enough[n]to bring down a star.[n][e]

[msg Item_060]
[s]A machine gun manifested[n]from an awakened power.[n][e]

[msg Item_061]
[s]RESERVE[n][e]

[msg Item_062]
[s]RESERVE[n][e]

[msg Item_063]
[s]Model gun based on one[n]used by the military.[n][e]

[msg Item_064]
[s]RESERVE[n][e]

[msg Item_065]
[s]RESERVE[n][e]

[msg Item_066]
[s]Model gun based on a[n]popular machine gun.[n][e]

[msg Item_067]
[s]RESERVE[n][e]

[msg Item_068]
[s]RESERVE[n][e]

[msg Item_069]
[s]RESERVE[n][e]

[msg Item_06A]
[s]RESERVE[n][e]

[msg Item_06B]
[s]RESERVE[n][e]

[msg Item_06C]
[s]Model gun with a design[n]that looks remorseless.[n][e]

[msg Item_06D]
[s]RESERVE[n][e]

[msg Item_06E]
[s]Model gun often seen[n]in old Western films.[n][e]

[msg Item_06F]
[s]RESERVE[n][e]

[msg Item_070]
[s]RESERVE[n][e]

[msg Item_071]
[s]RESERVE[n][e]

[msg Item_072]
[s]RESERVE[n][e]

[msg Item_073]
[s]Model gun based on one[n]with a high fire rate.[n][e]

[msg Item_074]
[s]RESERVE[n][e]

[msg Item_075]
[s]RESERVE[n][e]

[msg Item_076]
[s]RESERVE[n][e]

[msg Item_077]
[s]RESERVE[n][e]

[msg Item_078]
[s]RESERVE[n][e]

[msg Item_079]
[s]Model gun that scatters[n]bullets like water.[n][e]

[msg Item_07A]
[s]Model gun based on a[n]British-made model.[n][e]

[msg Item_07B]
[s]Model gun based on one[n]that messes with minds.[n][e]

[msg Item_07C]
[s]Upgraded version of the[n]model gun Brain Shot.[n][e]

[msg Item_07D]
[s]Upgraded version of the[n]model gun Wild Hunt.[n][e]

[msg Item_07E]
[s]Model gun named after[n]the large spider.[n][e]

[msg Item_07F]
[s]RESERVE[n][e]

[msg Item_080]
[s]Assault rifle manifested[n]from an awakened power.[n][e]

[msg Item_081]
[s]Model gun based on a[n]long-barreled rifle.[n][e]

[msg Item_082]
[s]RESERVE[n][e]

[msg Item_083]
[s]Model gun based on one[n]known for its appearance.[n][e]

[msg Item_084]
[s]RESERVE[n][e]

[msg Item_085]
[s]RESERVE[n][e]

[msg Item_086]
[s]RESERVE[n][e]

[msg Item_087]
[s]RESERVE[n][e]

[msg Item_088]
[s]RESERVE[n][e]

[msg Item_089]
[s]RESERVE[n][e]

[msg Item_08A]
[s]RESERVE[n][e]

[msg Item_08B]
[s]Model gun inspired by one[n]with destructive power.[n][e]

[msg Item_08C]
[s]RESERVE[n][e]

[msg Item_08D]
[s]Model gun based on a[n]violent instrument of war.[n][e]

[msg Item_08E]
[s]RESERVE[n][e]

[msg Item_08F]
[s]Model gun inspired by an[n]Edo era matchlock gun.[n][e]

[msg Item_090]
[s]RESERVE[n][e]

[msg Item_091]
[s]Upgraded version of the[n]model gun Kuzuryu Gouhou.[n][e]

[msg Item_092]
[s]Upgraded version of the[n]model gun Heaven's Gate.[n][e]

[msg Item_093]
[s]RESERVE[n][e]

[msg Item_094]
[s]RESERVE[n][e]

[msg Item_095]
[s]RESERVE[n][e]

[msg Item_096]
[s]RESERVE[n][e]

[msg Item_097]
[s]RESERVE[n][e]

[msg Item_098]
[s]Model gun based on one[n]that howls when it fires.[n][e]

[msg Item_099]
[s]RESERVE[n][e]

[msg Item_09A]
[s]Model gun based on one[n]often used by rebels.[n][e]

[msg Item_09B]
[s]RESERVE[n][e]

[msg Item_09C]
[s]Model gun based on[n]a heavy-weight rifle.[n][e]

[msg Item_09D]
[s]RESERVE[n][e]

[msg Item_09E]
[s]Model gun that fires[n]like a dragon's roar.[n][e]

[msg Item_09F]
[s]Model gun inspired by a[n]watchman of the Heavens.[n][e]

[msg Item_0A0]
[s]A revolver manifested[n]from an awakened power.[n][e]

[msg Item_0A1]
[s]Model gun based on a[n]classic, popular revolver.[n][e]

[msg Item_0A2]
[s]RESERVE[n][e]

[msg Item_0A3]
[s]RESERVE[n][e]

[msg Item_0A4]
[s]RESERVE[n][e]

[msg Item_0A5]
[s]Model gun based on an[n]old-fashioned revolver.[n][e]

[msg Item_0A6]
[s]RESERVE[n][e]

[msg Item_0A7]
[s]RESERVE[n][e]

[msg Item_0A8]
[s]RESERVE[n][e]

[msg Item_0A9]
[s]RESERVE[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]RESERVE[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]Upgraded version of the[n]model gun Mirrirmina.[n][e]

[msg Item_0AE]
[s]Upgraded version of the[n]model gun Judge of Hell.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]RESERVE[n][e]

[msg Item_0B2]
[s]RESERVE[n][e]

[msg Item_0B3]
[s]RESERVE[n][e]

[msg Item_0B4]
[s]Model gun that has[n]some weight to it.[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]Model gun named after[n]a sacred spring.[n][e]

[msg Item_0B7]
[s]Model gun based on one[n]with a wild style.[n][e]

[msg Item_0B8]
[s]Model gun that's got[n]a kick to it.[n][e]

[msg Item_0B9]
[s]Model gun used during[n]the American Frontier.[n][e]

[msg Item_0BA]
[s]Model gun named after[n]the sun's final descent.[n][e]

[msg Item_0BB]
[s]Model gun named in[n]honor of a god of death.[n][e]

[msg Item_0BC]
[s]Model gun that can[n]reach the heavens.[n][e]

[msg Item_0BD]
[s]Model gun with a[n]destructive look.[n][e]

[msg Item_0BE]
[s]Model gun based on one[n]that howls like a demon.[n][e]

[msg Item_0BF]
[s]Model gun based on one[n]with incendiary power.[n][e]

[msg Item_0C0]
[s]Model gun made for[n]beginners.[n][e]

[msg Item_0C1]
[s]Model gun that darts[n]like a cat's paw.[n][e]

[msg Item_0C2]
[s]RESERVE[n][e]

[msg Item_0C3]
[s]Unused[n][e]

[msg Item_0C4]
[s]Unused[n][e]

[msg Item_0C5]
[s]Model gun made famous[n]by a popular idol.[n][e]

[msg Item_0C6]
[s]Upgraded version of the[n]model gun Pawzooka.[n][e]

[msg Item_0C7]
[s]RESERVE[n][e]

[msg Item_0C8]
[s]RESERVE[n][e]

[msg Item_0C9]
[s]RESERVE[n][e]

[msg Item_0CA]
[s]RESERVE[n][e]

[msg Item_0CB]
[s]Model gun based on a GL[n]that is very destructive.[n][e]

[msg Item_0CC]
[s]Model gun developed[n]for military use.[n][e]

[msg Item_0CD]
[s]Upgraded version of the[n]model gun Yagrush.[n][e]

[msg Item_0CE]
[s]RESERVE[n][e]

[msg Item_0CF]
[s]RESERVE[n][e]

[msg Item_0D0]
[s]RESERVE[n][e]

[msg Item_0D1]
[s]RESERVE[n][e]

[msg Item_0D2]
[s]Unused[n][e]

[msg Item_0D3]
[s]Unused[n][e]

[msg Item_0D4]
[s]Model gun based on one[n]capable of razing a town.[n][e]

[msg Item_0D5]
[s]RESERVE[n][e]

[msg Item_0D6]
[s]Model gun that evokes a[n]sense of demonic deeds.[n][e]

[msg Item_0D7]
[s]Model gun based on one[n]with a hellfire aesthetic.[n][e]

[msg Item_0D8]
[s]RESERVE[n][e]

[msg Item_0D9]
[s]RESERVE[n][e]

[msg Item_0DA]
[s]Model gun that lurks[n]in the dark of night.[n][e]

[msg Item_0DB]
[s]Model gun named after[n]the European folk myth.[n][e]

[msg Item_0DC]
[s]RESERVE[n][e]

[msg Item_0DD]
[s]RESERVE[n][e]

[msg Item_0DE]
[s]Unused[n][e]

[msg Item_0DF]
[s]Unused[n][e]

[msg Item_0E0]
[s]Toy ray gun that's[n]popular with children.[n][e]

[msg Item_0E1]
[s]RESERVE[n][e]

[msg Item_0E2]
[s]Toy ray gun with an[n]elegant design.[n][e]

[msg Item_0E3]
[s]Toy ray gun engraved[n]with a red "5."[n][e]

[msg Item_0E4]
[s]A slingshot built to[n]fling flaming arrows.[n][e]

[msg Item_0E5]
[s]RESERVE[n][e]

[msg Item_0E6]
[s]A slingshot strung with[n]highly elastic rubber.[n][e]

[msg Item_0E7]
[s]A slingshot with a divine,[n]supreme aura about it.[n][e]

[msg Item_0E8]
[s]RESERVE[n][e]

[msg Item_0E9]
[s]RESERVE[n][e]

[msg Item_0EA]
[s]Model gun based on one[n]built in the heavens.[n][e]

[msg Item_0EB]
[s]Toy ray gun surpassing[n]the Last Judgment.[n][e]

[msg Item_0EC]
[s]Toy ray gun that is[n]nicknamed the acting god.[n][e]

[msg Item_0ED]
[s]RESERVE[n][e]

[msg Item_0EE]
[s]RESERVE[n][e]

[msg Item_0EF]
[s]RESERVE[n][e]

[msg Item_0F0]
[s]Model gun that tempts[n]enemies to their death.[n][e]

[msg Item_0F1]
[s]Model gun based on one[n]with enhanced impact.[n][e]

[msg Item_0F2]
[s]Model gun known to[n]unleash the utmost power.[n][e]

[msg Item_0F3]
[s]Upgraded version of the[n]model gun Sahasrara.[n][e]

[msg Item_0F4]
[s]Model gun inspired by[n]the god of destruction.[n][e]

[msg Item_0F5]
[s]RESERVE[n][e]

[msg Item_0F6]
[s]Model gun based on a[n]high-caliber pistol.[n][e]

[msg Item_0F7]
[s]Model gun based on a[n]high-powered handgun.[n][e]

[msg Item_0F8]
[s]Model gun that burns[n]red at the muzzle.[n][e]

[msg Item_0F9]
[s]Toy ray gun that uses[n]special bullets.[n][e]

[msg Item_0FA]
[s]Model gun that[n]shines bright.[n][e]

[msg Item_0FB]
[s]Model gun that freezes[n]you in fear.[n][e]

[msg Item_0FC]
[s]Model gun imbued with[n]the Demon King's power.[n][e]

[msg Item_0FD]
[s]Assault rifle manifested[n]from an awakened power.[n][e]

[msg Item_0FE]
[s]Unused[n][e]

[msg Item_0FF]
[s]Model gun used regularly[n]by a famous, great man.[n][e]

