[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Restores 20 HP to one ally.[n][e]

[msg Item_002]
[s]Fast-acting formula.[n]Restores 50 HP to one ally.[n][e]

[msg Item_003]
[s]Fast-acting formula.[n]Restores 100 HP to one ally.[n][e]

[msg Item_004]
[s]A new drug developed by[n]TMC. Restores 200 HP to[n]one ally.[n][e]

[msg Item_005]
[s]Restores 30% HP to one ally.[n][e]

[msg Item_006]
[s]Fully restores HP[n]of one ally.[n][e]

[msg Item_007]
[s]A new drug developed by[n]TMC. Restores 50 HP to[n]all allies.[n][e]

[msg Item_008]
[s]A new drug developed by[n]TMC. Restores 100 HP to[n]all allies.[n][e]

[msg Item_009]
[s]A new drug developed by[n]TMC. Restores 200 HP to[n]all allies.[n][e]

[msg Item_00A]
[s]Fully restores HP[n]of all allies.[n][e]

[msg Item_00B]
[s]Restores 10 SP to one ally.[n][e]

[msg Item_00C]
[s]Restores 50 SP[n]to one ally.[n][e]

[msg Item_00D]
[s]Restores 100 SP[n]to one ally.[n][e]

[msg Item_00E]
[s]Fully restores SP[n]of one ally.[n][e]

[msg Item_00F]
[s]Revives one fallen[n]ally to 50% HP.[n][e]

[msg Item_010]
[s]Revives one fallen[n]ally to full HP.[n][e]

[msg Item_011]
[s]Unused[n][e]

[msg Item_012]
[s]Medical ointment.[n]Cures Burn/Freeze/[n]Shock for one ally.[n][e]

[msg Item_013]
[s]Topical balm. Cures Rage/[n]Despair/Brainwash/Fear/[n]Confuse for one ally.[n][e]

[msg Item_014]
[s]Over-the-counter capsule.[n]Cures Dizzy/Forget/Sleep/[n]Hunger for one ally.[n][e]

[msg Item_015]
[s]Unused[n][e]

[msg Item_016]
[s]Unused[n][e]

[msg Item_017]
[s]Guarantees escape[n]from battle. Not all[n]battles apply.[n][e]

[msg Item_018]
[s]Fully restores HP[n]and SP of all allies.[n][e]

[msg Item_019]
[s]Cures all non-special[n]ailments for all allies.[n][e]

[msg Item_01A]
[s]Cures all non-special[n]ailments for one ally.[n][e]

[msg Item_01B]
[s]Restores 30% HP to[n]one ally. Raises Attack[n]and lowers Defense.[n][e]

[msg Item_01C]
[s]Restores 30% HP to one[n]ally. Raises Attack and[n]lowers Accuracy/Evasion.[n][e]

[msg Item_01D]
[s]Restores 30% HP to one ally.[n]Raises Accuracy/Evasion and[n]lowers Attack.[n][e]

[msg Item_01E]
[s]Unused[n][e]

[msg Item_01F]
[s]Barrier that reflects magical[n]attacks except Almighty[n]for one ally one time.[n][e]

[msg Item_020]
[s]Barrier that reflects[n]physical attacks for[n]one ally one time.[n][e]

[msg Item_021]
[s]Raises Attack for all[n]allies for three turns.[n][e]

[msg Item_022]
[s]Raises Accuracy/[n]Evasion for all allies[n]for three turns.[n][e]

[msg Item_023]
[s]Raises Defense for all[n]allies for three turns.[n][e]

[msg Item_024]
[s]A new antiseptic made[n]by TMC. Removes stat[n]buffs for all foes.[n][e]

[msg Item_025]
[s]A new antiseptic made[n]by TMC. Removes stat[n]debuffs for all allies.[n][e]

[msg Item_026]
[s]Deals 50 Fire dmg to[n]one foe. High chance[n]of inflicting Burn.[n][e]

[msg Item_027]
[s]Deals 50 Fire dmg to[n]all foes.[n][e]

[msg Item_028]
[s]Deals 50 Ice dmg to[n]one foe. High chance[n]of inflicting Freeze.[n][e]

[msg Item_029]
[s]Deals 50 Ice dmg to[n]all foes.[n][e]

[msg Item_02A]
[s]Deals 50 Wind dmg to[n]one foe.[n][e]

[msg Item_02B]
[s]Deals 50 Wind dmg to[n]all foes.[n][e]

[msg Item_02C]
[s]Deals 50 Elec dmg to[n]one foe. High chance[n]of inflicting Shock.[n][e]

[msg Item_02D]
[s]Deals 50 Elec dmg to[n]all foes.[n][e]

[msg Item_02E]
[s]Deals 100 Almighty[n]dmg to all foes.[n][e]

[msg Item_02F]
[s]Medium chance of[n]Bless insta-kill[n]to one foe.[n][e]

[msg Item_030]
[s]Medium chance of[n]Curse insta-kill[n]to one foe.[n][e]

[msg Item_031]
[s]Deals 150 Fire dmg to[n]one foe.[n][e]

[msg Item_032]
[s]Deals 150 Wind dmg to[n]one foe.[n][e]

[msg Item_033]
[s]Deals 150 Ice dmg to[n]one foe.[n][e]

[msg Item_034]
[s]Deals 150 Elec dmg to[n]one foe.[n][e]

[msg Item_035]
[s]Deals 50 Psy dmg to[n]one foe.[n][e]

[msg Item_036]
[s]Deals 50 Psy dmg to[n]all foes.[n][e]

[msg Item_037]
[s]Deals 50 Nuke dmg to[n]one foe.[n][e]

[msg Item_038]
[s]Deals 50 Nuke dmg to[n]all foes.[n][e]

[msg Item_039]
[s]Deals 50 Bless dmg to[n]one foe.[n][e]

[msg Item_03A]
[s]Deals 50 Bless dmg to[n]all foes.[n][e]

[msg Item_03B]
[s]Deals 50 Curse dmg to[n]one foe.[n][e]

[msg Item_03C]
[s]Deals 50 Curse dmg to[n]all foes.[n][e]

[msg Item_03D]
[s]Revives one fallen[n]ally to 50% HP.[n][e]

[msg Item_03E]
[s]Restores 50 HP[n]to one ally.[n][e]

[msg Item_03F]
[s]New drug by TMC.[n]Revives one fallen[n]ally to full HP.[n][e]

[msg Item_040]
[s]Protects from insta-[n]kill attacks one time.[n][e]

[msg Item_041]
[s]Unused[n][e]

[msg Item_042]
[s]New drug developed by[n]TMC. Revives all fallen[n]allies to 50% HP.[n][e]

[msg Item_043]
[s]New drug developed by[n]TMC. Revives all fallen[n]allies to full HP.[n][e]

[msg Item_044]
[s]A spring-exclusive body[n]oil. Cures all non-special[n]ailments for one ally.[n][e]

[msg Item_045]
[s]Unused[n][e]

[msg Item_046]
[s]A pre-owned DVD player.[n]Very old, but still functional.[n]Missing the remote.[n][e]

[msg Item_047]
[s]A cheap plant nutrient.[n]For those who want basic[n]care for their plants.[n][e]

[msg Item_048]
[s]A pricey plant nutrient.[n]For those who want good[n]care for their plants.[n][e]

[msg Item_049]
[s]A premium plant nutrient.[n]For those who want serious[n]care for their plants.[n][e]

[msg Item_04A]
[s]Deals 150 Psy dmg to[n]one foe.[n][e]

[msg Item_04B]
[s]Deals 150 Nuke dmg to[n]one foe.[n][e]

[msg Item_04C]
[s]Deals 150 Bless dmg to[n]one foe.[n][e]

[msg Item_04D]
[s]Deals 150 Curse dmg to[n]one foe.[n][e]

[msg Item_04E]
[s]Unused[n][e]

[msg Item_04F]
[s]Unused[n][e]

[msg Item_050]
[s]A tool set for[n]fixing computers.[n][e]

[msg Item_051]
[s]Unused[n][e]

[msg Item_052]
[s]A palm-sized, colorful vase[n]made of glass. For the flower[n]lover in your life.[n][e]

[msg Item_053]
[s]A star-shaped hand mirror[n]that's supposed to be lucky.[n]For a spiritual someone.[n][e]

[msg Item_054]
[s]A box of stick-like snacks that[n]come in a variety of flavors.[n]For the young at heart.[n][e]

[msg Item_055]
[s]A guide that lets you feel[n]the atmosphere of the[n]antique book town.[n][e]

[msg Item_056]
[s]A book that teaches the[n]tricks of buying household[n]electronics for cheap.[n][e]

[msg Item_057]
[s]A ring inset with a heart-[n]shaped jewel. Made to[n]captivate a woman's heart.[n][e]

[msg Item_058]
[s]A necklace adorned with a[n]heart-shaped jewel. Made to[n]captivate a woman's heart.[n][e]

[msg Item_059]
[s]A famous brand of perfume[n]with a gentle scent. For a[n]sensual person in your life.[n][e]

[msg Item_05A]
[s]A deluxe aromatherapy[n]set to relax the mind and[n]body after intense focus.[n][e]

[msg Item_05B]
[s]A small cactus that looks[n]nice in an office setting.[n]For the desk jockey.[n][e]

[msg Item_05C]
[s]A basket full of flowers from[n]every season. For the flower[n]lover in your life.[n][e]

[msg Item_05D]
[s]A rose-scented fragrance for[n]a luxurious bathtime. For the[n]special lady in your life.[n][e]

[msg Item_05E]
[s]A chic, black mug. For the[n]one who's married to their[n]desk.[n][e]

[msg Item_05F]
[s]A small fan with a bright[n]sakura pattern. For a[n]traditional lady.[n][e]

[msg Item_060]
[s]An elegant fountain pen,[n]rereleased due to demand.[n]For the discerning eye.[n][e]

[msg Item_061]
[s]The latest robot vacuum that[n]cleans automatically. For the[n]busy businessperson.[n][e]

[msg Item_062]
[s]A 1/12 scale figurine made[n]with attention to detail. For[n]the bike lover in your life.[n][e]

[msg Item_063]
[s]A set of plushies of a popular[n]character. For the one who[n]likes rare finds.[n][e]

[msg Item_064]
[s]Raises chances of being[n]targeted by foes for[n]one ally.[n][e]

[msg Item_065]
[s]A tool that allows you to[n]return to the Metaverse[n]entrance.[n][e]

[msg Item_066]
[s]Unused[n][e]

[msg Item_067]
[s]Elude enemy pursuit by[n]becoming temporarily[n]undetectable.[n][e]

[msg Item_068]
[s]Unused[n][e]

[msg Item_069]
[s]A mist that puts nearby[n]enemies to sleep.[n][e]

[msg Item_06A]
[s]A tonic that calms an[n]enemy's nerves, lowering[n]a Palace's Security Level.[n][e]

[msg Item_06B]
[s]Unused[n][e]

[msg Item_06C]
[s]Unused[n][e]

[msg Item_06D]
[s]A bundle of silk yarn.[n]Perfect for crafting.[n][e]

[msg Item_06E]
[s]Animal skin used for[n]transcription. Also used[n]for crafting tools.[n][e]

[msg Item_06F]
[s]A fastener made from tin.[n]Has value as a handmade[n]component.[n][e]

[msg Item_070]
[s]Natural oil harvested from[n]plants. Can be used as fuel[n]for machine tools.[n][e]

[msg Item_071]
[s]Elastic bark. Can be used[n]as a component when[n]making tools.[n][e]

[msg Item_072]
[s]Iron sand containing traces[n]of magnetic properties. Can[n]be used to make steel.[n][e]

[msg Item_073]
[s]A lens that gathers light.[n]Perfect for tools that[n]utilize light.[n][e]

[msg Item_074]
[s]A thin sheet of aluminum.[n]Easy to use.[n][e]

[msg Item_075]
[s]A highly elastic animal hide.[n]A must-have for crafting.[n][e]

[msg Item_076]
[s]A pyrophoric, toxic powder[n]used for ignition.[n][e]

[msg Item_077]
[s]Shimmering silver liquid[n]metal used to make tools.[n]Handle with care.[n][e]

[msg Item_078]
[s]Unused[n][e]

[msg Item_079]
[s]A book of quotes by great[n]philosophers. Read to[n]enrich your knowledge.[n][e]

[msg Item_07A]
[s]Hair-raising ghost stories.[n]Reading this will surely[n]steel your guts.[n][e]

[msg Item_07B]
[s]A best-seller on cleaning.[n]The author's proficiency[n]is worth studying.[n][e]

[msg Item_07C]
[s]A heartwarming tale of[n]a dog and his master. It[n]is filled with kindness.[n][e]

[msg Item_07D]
[s]Unused[n][e]

[msg Item_07E]
[s]Unused[n][e]

[msg Item_07F]
[s]A retro boxing game.[n]Playing could give you the[n]charm of a challenger.[n][e]

[msg Item_080]
[s]The world's first spicy[n]coffee. Restores 10 HP[n]to one ally.[n][e]

[msg Item_081]
[s]Triple-filtered Shibuya[n]river water. Restores[n]10 HP to one ally.[n][e]

[msg Item_082]
[s]An old model television.[n]It's missing the remote.[n][e]

[msg Item_083]
[s]Unused[n][e]

[msg Item_084]
[s]Unused[n][e]

[msg Item_085]
[s]A book chronicling a great[n]swordsman's life. Find the[n]guts to face death.[n][e]

[msg Item_086]
[s]The essential compendium[n]for anyone in the flower[n]industry.[n][e]

[msg Item_087]
[s]Unused[n][e]

[msg Item_088]
[s]Unused[n][e]

[msg Item_089]
[s]Unused[n][e]

[msg Item_08A]
[s]The epic of a tireless seeker[n]of wisdom. May impart[n]knowledge upon the reader.[n][e]

[msg Item_08B]
[s]Biography of a beloved[n]leader. His warm character[n]shows much kindness.[n][e]

[msg Item_08C]
[s]The passion involved in being[n]an automata technician. May[n]improve one's proficiency.[n][e]

[msg Item_08D]
[s]A book about the romantic[n]life of a ladies man.[n]Learn from his charm.[n][e]

[msg Item_08E]
[s]Unused[n][e]

[msg Item_08F]
[s]Just plain junk. No point[n]in having it.[n][e]

[msg Item_090]
[s]Unused[n][e]

[msg Item_091]
[s]Unused[n][e]

[msg Item_092]
[s]Unused[n][e]

[msg Item_093]
[s]A popular Japanese[n]snack. Restores 20 HP[n]to one ally.[n][e]

[msg Item_094]
[s]A Holy Stone shattered[n]to pieces. Restores[n]5 SP to one ally.[n][e]

[msg Item_095]
[s]A ticket necessary[n]to watch a movie[n]at the theater.[n][e]

[msg Item_096]
[s]Movie 02 Ticket[n][e]

[msg Item_097]
[s]Movie 03 Ticket[n][e]

[msg Item_098]
[s]Movie 04 Ticket[n][e]

[msg Item_099]
[s]Unused[n][e]

[msg Item_09A]
[s]Unused[n][e]

[msg Item_09B]
[s]Ten consecutive numbers[n]for the Summer Mammoth[n]lottery.[n][e]

[msg Item_09C]
[s]Bun with chestnuts and[n]carrots in it. Restores[n]200 HP to one ally.[n][e]

[msg Item_09D]
[s]Unused[n][e]

[msg Item_09E]
[s]Unused[n][e]

[msg Item_09F]
[s]A book on the old district[n]reborn thanks to the new[n]Tokyo Skytree.[n][e]

[msg Item_0A0]
[s]A retro space shooting[n]game. Playing could[n]make you gutsier.[n][e]

[msg Item_0A1]
[s]A book that introduces[n]great parks for spending[n]a quiet weekend.[n][e]

[msg Item_0A2]
[s]A retro board game.[n]Playing could make[n]you kinder.[n][e]

[msg Item_0A3]
[s]A retro fighting game.[n]Playing could make[n]you gutsier.[n][e]

[msg Item_0A4]
[s]Two episodes. A corpse holds[n]hints to the truth. Sharp[n]deductions save all.[n][e]

[msg Item_0A5]
[s]Three episodes. Cutting-edge[n]forensic technology holds[n]the key to a mystery.[n][e]

[msg Item_0A6]
[s]The story of a homely[n]girl who captivates people[n]with her inner charm.[n][e]

[msg Item_0A7]
[s]A realistic teen drama.[n]Watching their romances[n]makes you charming.[n][e]

[msg Item_0A8]
[s]A heartrending drama[n]about working in the ER.[n]Teaches you kindness.[n][e]

[msg Item_0A9]
[s]Unused[n][e]

[msg Item_0AA]
[s]Rainy day special. Large[n]candied natto. Restores[n]80 HP to all allies.[n][e]

[msg Item_0AB]
[s]A pack full of select[n]squid snacks. Restores[n]20 HP to all allies.[n][e]

[msg Item_0AC]
[s]A set of badges featuring[n]a rising pop idol. For a[n]trendy friend.[n][e]

[msg Item_0AD]
[s]Unused[n][e]

[msg Item_0AE]
[s]Unused[n][e]

[msg Item_0AF]
[s]Unused[n][e]

[msg Item_0B0]
[s]A photo guidebook of the[n]shrines hidden in the big[n]city.[n][e]

[msg Item_0B1]
[s]A guidebook for beginners[n]on the popular fishing[n]ponds.[n][e]

[msg Item_0B2]
[s]A magazine compiling[n]information about[n]Yongen-Jaya.[n][e]

[msg Item_0B3]
[s]A star-gazing guidebook[n]that has a special on[n]planetariums.[n][e]

[msg Item_0B4]
[s]A doll of the winter frost[n]fairy whose kind smile[n]will capture your heart.[n][e]

[msg Item_0B5]
[s]A Big Bang Burger mascot[n]doll. Makes you feel like[n]a Big Bang.[n][e]

[msg Item_0B6]
[s]A security company's[n]mascot doll. People like[n]his shady looks.[n][e]

[msg Item_0B7]
[s]A peculiarly-designed doll[n]that is popular due to its[n]scary looks.[n][e]

[msg Item_0B8]
[s]Pudding made from uji[n]matcha green tea. For the[n]sweet tooth.[n][e]

[msg Item_0B9]
[s]Chocolate truffles made[n]with meticulous detail.[n]For the sweet tooth.[n][e]

[msg Item_0BA]
[s]Unused[n][e]

[msg Item_0BB]
[s]Greatly raises chances[n]of being targeted by[n]foes for one ally.[n][e]

[msg Item_0BC]
[s]Unused[n][e]

[msg Item_0BD]
[s]Unused[n][e]

[msg Item_0BE]
[s]Water used for rituals.[n]Removes all stat buffs for[n]all foes.[n][e]

[msg Item_0BF]
[s]Purified holy water.[n]Removes all stat debuffs[n]for all allies.[n][e]

[msg Item_0C0]
[s]Non-alcoholic wine used[n]during ceremonies. Fully[n]restores HP of all allies.[n][e]

[msg Item_0C1]
[s]Used during ceremonies.[n]Cures all non-special[n]ailments for all allies.[n][e]

[msg Item_0C2]
[s]Rainy day special with[n]terrific texture. Restores[n]200 HP to one ally.[n][e]

[msg Item_0C3]
[s]A silk crêpe book cover with[n]a Japanese-style print on it.[n]For the traditional lady.[n][e]

[msg Item_0C4]
[s]Sponge cake topped with[n]coarse sugar. For someone[n]with a sweet tooth.[n][e]

[msg Item_0C5]
[s]An intensely red lipstick[n]worn by a popular model.[n]For the fashion-conscious.[n][e]

[msg Item_0C6]
[s]Unused[n][e]

[msg Item_0C7]
[s]Unused[n][e]

[msg Item_0C8]
[s]A hammer that negates[n]physical reflecting[n]barriers of one foe.[n][e]

[msg Item_0C9]
[s]A hammer that negates[n]magic reflecting[n]barriers of one foe.[n][e]

[msg Item_0CA]
[s]Unused[n][e]

[msg Item_0CB]
[s]Unused[n][e]

[msg Item_0CC]
[s]Unused[n][e]

[msg Item_0CD]
[s]Unused[n][e]

[msg Item_0CE]
[s]Unused[n][e]

[msg Item_0CF]
[s]Unused[n][e]

[msg Item_0D0]
[s]Unused[n][e]

[msg Item_0D1]
[s]Unused[n][e]

[msg Item_0D2]
[s]A simple yet sturdy rod.[n]Makes catching fish[n]a little easier.[n][e]

[msg Item_0D3]
[s]A strong and tough rod.[n]Makes catching fish[n]even easier.[n][e]

[msg Item_0D4]
[s]A resilient next-gen rod.[n]Makes catching fish[n]extremely easy.[n][e]

[msg Item_0D5]
[s]Contains arginine.[n]Restores 5 SP to one[n]ally.[n][e]

[msg Item_0D6]
[s]Now with more pepper.[n]Restores 20 HP to one[n]ally.[n][e]

[msg Item_0D7]
[s]Unsettlingly nutritious.[n]Restores 10 HP to[n]one ally.[n][e]

[msg Item_0D8]
[s]Food to go. Restores 30% HP[n]to one ally, lowers Attack,[n]raises Accuracy/Evasion.[n][e]

[msg Item_0D9]
[s]Food to go. Restores 30% HP[n]to one ally, lowers Accuracy/[n]Evasion and raises Attack.[n][e]

[msg Item_0DA]
[s]Food to go. Both tasty and[n]satiating. Restores 50 HP and[n]cures Hunger for one ally.[n][e]

[msg Item_0DB]
[s]Restores 30% HP to one[n]ally, lowers Defense and[n]raises Attack.[n][e]

[msg Item_0DC]
[s]Rich with omega-3 fatty[n]acids to increase your[n]knowledge.[n][e]

[msg Item_0DD]
[s]Blended with collagen,[n]making you radiant[n]with charm.[n][e]

[msg Item_0DE]
[s]Made from seaweed minerals[n]to revitalize you, making[n]you more proficient.[n][e]

[msg Item_0DF]
[s]Made with bitter melon.[n]It takes guts to drink[n]this terrifying mixture.[n][e]

[msg Item_0E0]
[s]Made using hot spring[n]water. You can feel the[n]kindness within you.[n][e]

[msg Item_0E1]
[s]Unused[n][e]

[msg Item_0E2]
[s]Just one bite satisfies[n]your stomach. Cures[n]Hunger for one ally.[n][e]

[msg Item_0E3]
[s]Ten random numbers for the[n]Summer Mammoth lottery.[n][e]

[msg Item_0E4]
[s]A refreshing lollipop.[n]Cures Despair for[n]one ally.[n][e]

[msg Item_0E5]
[s]A mysterious stone.[n]Cures Freeze for[n]one ally.[n][e]

[msg Item_0E6]
[s]A curious orb. Cures[n]Burn for one ally.[n][e]

[msg Item_0E7]
[s]A mysterious crystal.[n]Cures Shock for one[n]ally.[n][e]

[msg Item_0E8]
[s]Refreshing Mandarin[n]orange flavor. Restores[n]10 HP to one ally.[n][e]

[msg Item_0E9]
[s]Unused[n][e]

[msg Item_0EA]
[s]Yon-Germain's staple[n]sandwich. Restores[n]10 HP to one ally.[n][e]

[msg Item_0EB]
[s]A fruity, seasonal[n]pastry. Restores[n]30 HP to one ally.[n][e]

[msg Item_0EC]
[s]Unused[n][e]

[msg Item_0ED]
[s]Fast-selling bread.[n]Restores 50 HP and cures[n]Hunger for one ally.[n][e]

[msg Item_0EE]
[s]A drink that blows away[n]sleepiness. Cures Sleep[n]for one ally.[n][e]

[msg Item_0EF]
[s]A blend of Eastern and[n]Western teas. Restores[n]10 HP to one ally.[n][e]

[msg Item_0F0]
[s]Practically liquid[n]caffeine. Restores[n]10 HP to one ally.[n][e]

[msg Item_0F1]
[s]Popular tea often[n]sold online. Restores[n]10 HP to one ally.[n][e]

[msg Item_0F2]
[s]Makes you want to dance[n]all night. Restores 10 HP[n]to one ally.[n][e]

[msg Item_0F3]
[s]Unexpectedly great[n]taste. Restores 10 HP[n]to one ally.[n][e]

[msg Item_0F4]
[s]Coveted by old-school[n]gamers. Restores 10 HP[n]to one ally.[n][e]

[msg Item_0F5]
[s]A retro gambling game.[n]Playing could make you[n]more charming.[n][e]

[msg Item_0F6]
[s]A retro golf game.[n]Playing could make you[n]more proficient.[n][e]

[msg Item_0F7]
[s]A postcard that looks like a[n]calling card. Mail it to[n]someone close to you.[n][e]

[msg Item_0F8]
[s]Autumn-only. Cures all[n]non-special ailments for[n]one ally.[n][e]

[msg Item_0F9]
[s]Increases training[n]efficiency. Restores[n]30% HP to one ally.[n][e]

[msg Item_0FA]
[s]Rainy day-only. Helps[n]training. Restores[n]30% HP to one ally.[n][e]

[msg Item_0FB]
[s]Bread with a nostalgic[n]taste. Restores 10 HP[n]to one ally.[n][e]

[msg Item_0FC]
[s]Unused[n][e]

[msg Item_0FD]
[s]Unused[n][e]

[msg Item_0FE]
[s]Unused[n][e]

[msg Item_0FF]
[s]Unused[n][e]

[msg Item_100]
[s]Unused[n][e]

[msg Item_101]
[s]Unused[n][e]

[msg Item_102]
[s]Unused[n][e]

[msg Item_103]
[s]Unused[n][e]

[msg Item_104]
[s]Unused[n][e]

[msg Item_105]
[s]Unused[n][e]

[msg Item_106]
[s]Unused[n][e]

[msg Item_107]
[s]Unused[n][e]

[msg Item_108]
[s]Unused[n][e]

[msg Item_109]
[s]Unused[n][e]

[msg Item_10A]
[s]For those who reach for the[n]stars. Ball speed: 87 mph.[n][e]

[msg Item_10B]
[s]The final challenge from the[n]batting cage proprietor.[n]Ball speed: 103 mph.[n][e]

[msg Item_10C]
[s]For beginners. Ball speed:[n]43 mph.[n][e]

[msg Item_10D]
[s]For batters with intermediate[n]experience. Ball speed: 55[n]mph.[n][e]

[msg Item_10E]
[s]For those with confidence[n]in their swing. Ball speed:[n]68 mph.[n][e]

[msg Item_10F]
[s]A special dish made with[n]crayfish paste. For those[n]with the guts to indulge.[n][e]

[msg Item_110]
[s]Salisbury steak, just[n]like Grandma made it.[n]You feel kindness.[n][e]

[msg Item_111]
[s]Tea made with a plethora[n]of fruit. Softens your skin[n]to make you charming.[n][e]

[msg Item_112]
[s]Just finishing this tower of[n]ice cream without it[n]falling makes you proficient.[n][e]

[msg Item_113]
[s]Coffee brewed with love.[n]Even a clumsy maid can[n]make this super-easily.[n][e]

[msg Item_114]
[s]Tea steeped with care.[n]Even a clumsy maid can[n]make this easily.[n][e]

[msg Item_115]
[s]Topped with whipped cream[n]at the table. Might be hard[n]for a clumsy maid.[n][e]

[msg Item_116]
[s]Comes with free ketchup[n]art. May be too much for[n]a clumsy maid.[n][e]

[msg Item_117]
[s]Unused[n][e]

[msg Item_118]
[s]Unused[n][e]

[msg Item_119]
[s]Unused[n][e]

[msg Item_11A]
[s]Unused[n][e]

[msg Item_11B]
[s]Unused[n][e]

[msg Item_11C]
[s]Unused[n][e]

[msg Item_11D]
[s]Unused[n][e]

[msg Item_11E]
[s]Unused[n][e]

[msg Item_11F]
[s]Unused[n][e]

[msg Item_120]
[s]Unused[n][e]

[msg Item_121]
[s]Unused[n][e]

[msg Item_122]
[s]Unused[n][e]

[msg Item_123]
[s]Unused[n][e]

[msg Item_124]
[s]Unused[n][e]

[msg Item_125]
[s]Unused[n][e]

[msg Item_126]
[s]Unused[n][e]

[msg Item_127]
[s]Unused[n][e]

[msg Item_128]
[s]Unused[n][e]

[msg Item_129]
[s]Unused[n][e]

[msg Item_12A]
[s]Unused[n][e]

[msg Item_12B]
[s]Unused[n][e]

[msg Item_12C]
[s]Unused[n][e]

[msg Item_12D]
[s]Unused[n][e]

[msg Item_12E]
[s]Unused[n][e]

[msg Item_12F]
[s]Unused[n][e]

[msg Item_130]
[s]Unused[n][e]

[msg Item_131]
[s]Unused[n][e]

[msg Item_132]
[s]Unused[n][e]

[msg Item_133]
[s]A bait for small fish.[n]Can only catch small fish.[n][e]

[msg Item_134]
[s]A bait for average fish.[n]Can catch medium-sized[n]fish.[n][e]

[msg Item_135]
[s]A bait for big fish.[n]Can catch larger fish.[n][e]

[msg Item_136]
[s]Flavorful bait that can catch[n]normal fish of any size.[n][e]

[msg Item_137]
[s]A bait specifically for[n]the Guardian. No other[n]fish will bite.[n][e]

[msg Item_138]
[s]The taste is Big Bang[n]level! Restores 20 HP[n]to all allies.[n][e]

[msg Item_139]
[s]Fried potatoes with onion[n]rings like Saturn. Restores[n]20 HP to one ally.[n][e]

[msg Item_13A]
[s]Spring-only. Filled with[n]Earth veggies. Restores[n]40 HP to all allies.[n][e]

[msg Item_13B]
[s]Unused[n][e]

[msg Item_13C]
[s]Autumn-only. The egg looks[n]like the moon. Restores[n]120 HP to all allies.[n][e]

[msg Item_13D]
[s]A new burger by the reborn[n]Okumura Foods. Restores[n]200 HP to all allies.[n][e]

[msg Item_13E]
[s]So good it's practically[n]royalty. Restores 10 HP[n]to one ally.[n][e]

[msg Item_13F]
[s]Spring-only. Filled with[n]with fruits. Restores[n]80 HP to all allies.[n][e]

[msg Item_140]
[s]Despite the name, it's[n]a kebab. Restores[n]20 HP to one ally.[n][e]

[msg Item_141]
[s]Phantom Thieves snack.[n]Restores 50 HP and cures[n]ailments for one ally.[n][e]

[msg Item_142]
[s]Cold Chinese noodles. Only[n]available in summer. Restores[n]200 HP to one ally.[n][e]

[msg Item_143]
[s]Winter-only oden with[n]rich flavor. Restores[n]50 HP to all allies.[n][e]

[msg Item_144]
[s]Canned food to be eaten[n]as a group. Restores[n]40 HP to all allies.[n][e]

[msg Item_145]
[s]Digi-cam with latest tech.[n]Take photos in any light.[n]For the pro photographer.[n][e]

[msg Item_146]
[s]A face massager that can[n]slim your face quickly. For[n]the rising star.[n][e]

[msg Item_147]
[s]A repaired laptop.[n]It can connect to[n]Shady Commodities.[n][e]

[msg Item_148]
[s]Unused[n][e]

[msg Item_149]
[s]A mini-sized Dominion[n]figure.[n][e]

[msg Item_14A]
[s]A figure of a dying[n]Daisoujou.[n][e]

[msg Item_14B]
[s]A Decarabia figure decked[n]out with decals.[n][e]

[msg Item_14C]
[s]A Girimehkala figure[n]equipped with random[n]gear.[n][e]

[msg Item_14D]
[s]An eccentric Kin-ki[n]figure.[n][e]

[msg Item_14E]
[s]A Mothman figure[n]attempting to recreate[n]its fluffiness.[n][e]

[msg Item_14F]
[s]Movie 16 Ticket[n][e]

[msg Item_150]
[s]A tool that can open one[n]locked treasure chest.[n][e]

[msg Item_151]
[s]A tool that can open[n]any number of locked[n]treasure chests.[n][e]

[msg Item_152]
[s](cut)[n][e]

[msg Item_153]
[s]Unused[n][e]

[msg Item_154]
[s]Increases the chances of[n]encountering Treasure[n]Demons in Palaces.[n][e]

[msg Item_155]
[s]Unused[n][e]

[msg Item_156]
[s]A small red fish.[n][e]

[msg Item_157]
[s]A scaly carp.[n][e]

[msg Item_158]
[s]An elegant bitterling.[n][e]

[msg Item_159]
[s]An oily trout glimmering[n]with seven colors.[n][e]

[msg Item_15A]
[s]A carp that looks like it[n]could flutter in the wind.[n][e]

[msg Item_15B]
[s]A trout that looks like it[n]could sell at a high price.[n][e]

[msg Item_15C]
[s]A bitterling with a[n]superior taste.[n][e]

[msg Item_15D]
[s]A carp overflowing with[n]power.[n][e]

[msg Item_15E]
[s]The legendary fish serving[n]as a protector god of the[n]nation.[n][e]

[msg Item_15F]
[s]Your average adhesive[n]bandage. Restores 20 HP[n]to one ally.[n][e]

[msg Item_160]
[s]Unused[n][e]

[msg Item_161]
[s]Can only be used in safe[n]places. Restores 100% HP[n]to all allies.[n][e]

[msg Item_162]
[s]Specialty drip coffee.[n]Restores 30 SP to one[n]ally.[n][e]

[msg Item_163]
[s]Unused[n][e]

[msg Item_164]
[s]Unused[n][e]

[msg Item_165]
[s]Specialty drip coffee.[n]Restores 100 SP to one[n]ally.[n][e]

[msg Item_166]
[s]Curry that almost rivals[n]that of Leblanc's. Restores[n]20 SP to all allies.[n][e]

[msg Item_167]
[s]Recreates Boss's flavor[n]perfectly. Restores[n]50 SP to all allies.[n][e]

[msg Item_168]
[s]Curry that surpasses[n]Boss's flavor. Restores[n]100 SP to all allies.[n][e]

[msg Item_169]
[s]Unused[n][e]

[msg Item_16A]
[s]Came with Star Forneus.[n]An enthusiast would know[n]its value.[n][e]

[msg Item_16B]
[s]Can only be used in safe[n]places. Restores 50% HP[n]to all allies.[n][e]

[msg Item_16C]
[s]Came with Train of Life.[n]An enthusiast would know[n]its value.[n][e]

[msg Item_16D]
[s]Came with Power Intuition.[n]An enthusiast would know[n]its value.[n][e]

[msg Item_16E]
[s]Unused[n][e]

[msg Item_16F]
[s]Came with Punch Ouch.[n]An enthusiast would know[n]its value.[n][e]

[msg Item_170]
[s]Came with Gambla Goemon.[n]An enthusiast would know[n]its value.[n][e]

[msg Item_171]
[s]Came with Golfer[n]Sarutahiko. An enthusiast[n]would know its value.[n][e]

[msg Item_172]
[s]Broad compilation on[n]modern social thought.[n]May boost knowledge.[n][e]

[msg Item_173]
[s]Unused[n][e]

[msg Item_174]
[s]Unused[n][e]

[msg Item_175]
[s]Unused[n][e]

[msg Item_176]
[s]A thorough analysis of[n]batting. Might help with[n]your baseball skills.[n][e]

[msg Item_177]
[s]A book explaining the[n]tricks of fishing. Now[n]you can be a master![n][e]

[msg Item_178]
[s]Easy-to-learn speed-reading[n]techniques. Helps to increase[n]your reading speed.[n][e]

[msg Item_179]
[s]Comprehensive guide on[n]increasing emotional depth[n]on camera. For film buffs.[n][e]

[msg Item_17A]
[s]Unused[n][e]

[msg Item_17B]
[s]A guidebook to enjoy[n]the sweets found within[n]Chinatown.[n][e]

[msg Item_17C]
[s]A book to help men not[n]get lost while visiting[n]amusement parks.[n][e]

[msg Item_17D]
[s]A novel based on Arsène.[n]His clever tricks make[n]you knowledgeable.[n][e]

[msg Item_17E]
[s]The tale of the fearless[n]Captain Kidd. Reading this[n]would build guts.[n][e]

[msg Item_17F]
[s]The story about Zorro, the[n]gentleman bandit. Read to[n]be a kind gentleman.[n][e]

[msg Item_180]
[s]The passionate story of[n]Carmen. For those looking[n]to be charmed.[n][e]

[msg Item_181]
[s]Ishikawa Goemon's tale.[n]Experience the guts to[n]defy those in power.[n][e]

[msg Item_182]
[s]The dynamic biography of[n]Johanna. Awakens you to[n]kindness.[n][e]

[msg Item_183]
[s]A book of fictitious[n]mythos. The macabre world[n]would help build guts.[n][e]

[msg Item_184]
[s]The story of Milady. Her[n]changing faces helps to[n]make you proficient.[n][e]

[msg Item_185]
[s]The daring tales of Robin[n]Hood. Reading this could[n]help build your guts.[n][e]

[msg Item_186]
[s]A book on the hacker group[n]Medjed. Be knowledgeable[n]about internet crimes.[n][e]

[msg Item_187]
[s]Tips from a famous pickup[n]artist. Learn the charm to[n]hook up with someone.[n][e]

[msg Item_188]
[s]A compilation of tricks[n]for every video game.[n]Makes any game easy.[n][e]

[msg Item_189]
[s]Ten random numbers[n]for the year-round[n]Mammoth lottery.[n][e]

[msg Item_18A]
[s]Ten consecutive numbers[n]for the year-round[n]Mammoth lottery.[n][e]

[msg Item_18B]
[s]A scratcher ticket for the[n]Mammoth lottery. Results[n]are instantaneous.[n][e]

[msg Item_18C]
[s]Unused[n][e]

[msg Item_18D]
[s]Unused[n][e]

[msg Item_18E]
[s]Unused[n][e]

[msg Item_18F]
[s]A moving story of a woman[n]who can talk to ghosts.[n]Gives you kindness.[n][e]

[msg Item_190]
[s]A jail break drama. You[n]will learn from their[n]proficiency in sneaking.[n][e]

[msg Item_191]
[s]Adventures of a man who is[n]proficient in jury rigging[n]tools out of anything.[n][e]

[msg Item_192]
[s]A survival horror drama.[n]Viewing the onslaught of[n]zombies will build guts.[n][e]

[msg Item_193]
[s]Investigators chase after[n]supernatural cases.[n]Gives you guts.[n][e]

[msg Item_194]
[s]Unused[n][e]

[msg Item_195]
[s]Unused[n][e]

[msg Item_196]
[s]Unused[n][e]

[msg Item_197]
[s]Unused[n][e]

[msg Item_198]
[s]Unused[n][e]

[msg Item_199]
[s]Unused[n][e]

[msg Item_19A]
[s]Unused[n][e]

[msg Item_19B]
[s]Unused[n][e]

[msg Item_19C]
[s]A fashion magazine for[n]girls with unique tastes.[n][e]

[msg Item_19D]
[s]A magazine showcasing[n]date spots geared[n]toward adults.[n][e]

[msg Item_19E]
[s]Sucks the heat out[n]of your head. Cures[n]Burn for one ally.[n][e]

[msg Item_19F]
[s]A heat pack to warm[n]a chilled body. Cures[n]Freeze for one ally.[n][e]

[msg Item_1A0]
[s]A fruit salad that's fit[n]for a goddess. Restores[n]30 HP to one ally.[n][e]

[msg Item_1A1]
[s]Restores 50 HP to[n]one ally and lowers[n]Accuracy/Evasion.[n][e]

[msg Item_1A2]
[s]Restores 100 HP to[n]one ally and lowers[n]Attack.[n][e]

[msg Item_1A3]
[s]Restores 200 HP to[n]one ally and lowers[n]Defense.[n][e]

[msg Item_1A4]
[s]Eye drops that help you[n]see straight. Cures Dizzy[n]for one ally.[n][e]

[msg Item_1A5]
[s]Donuts that bring[n]relief. Cures Fear[n]for one ally.[n][e]

[msg Item_1A6]
[s]Stimulates the memory[n]from the gums. Cures[n]Forget for one ally.[n][e]

[msg Item_1A7]
[s]A tea that blasts away[n]drowsiness. Cures Sleep[n]for one ally.[n][e]

[msg Item_1A8]
[s]A present from Shinya.[n]Rabbit-shaped balloons[n]from Destinyland.[n][e]

[msg Item_1A9]
[s]Hardtack. Restores 10%[n]SP to one ally and lowers[n]Accuracy/Evasion.[n][e]

[msg Item_1AA]
[s]Canned a while ago.[n]Restores 10% SP to one[n]ally and lowers Defense.[n][e]

[msg Item_1AB]
[s]Not a chocolate bar.[n]Restores 10% SP to one[n]ally and lowers Attack.[n][e]

[msg Item_1AC]
[s]Restores 50 HP and[n]cures Hunger for[n]one ally.[n][e]

[msg Item_1AD]
[s]Unused[n][e]

[msg Item_1AE]
[s]Unused[n][e]

[msg Item_1AF]
[s]Made from the king of[n]fruits. Restores 10 HP[n]to one ally.[n][e]

[msg Item_1B0]
[s]So good it makes you say,[n]"Whoa!" Restores 20 HP to[n]one ally.[n][e]

[msg Item_1B1]
[s]You can never drink all[n]the kernels. Restores[n]20 HP to one ally.[n][e]

[msg Item_1B2]
[s]Makes you think you're[n]drunk. Restores 20 HP[n]to one ally.[n][e]

[msg Item_1B3]
[s]Triple-filtered carbonated[n]Shibuya water. Restores[n]30 HP to one ally.[n][e]

[msg Item_1B4]
[s]Blended with placenta.[n]Restores 5 SP to one[n]ally.[n][e]

[msg Item_1B5]
[s]Unused[n][e]

[msg Item_1B6]
[s]Unused[n][e]

[msg Item_1B7]
[s]Unused[n][e]

[msg Item_1B8]
[s]Unused[n][e]

[msg Item_1B9]
[s]Restores 100 HP to one[n]ally. Lowers Defense/[n]Accuracy/Evasion.[n][e]

[msg Item_1BA]
[s]Restores 100 HP to one[n]ally. Lowers Attack/[n]Accuracy/Evasion.[n][e]

[msg Item_1BB]
[s]Restores 100 HP to one[n]ally. Lowers Attack[n]and Defense.[n][e]

[msg Item_1BC]
[s]No ingredients listed.[n]Restores 30% SP to one[n]ally. Lowers all stats.[n][e]

[msg Item_1BD]
[s]A very bitter coffee.[n]Restores 30 SP to one[n]ally.[n][e]

[msg Item_1BE]
[s]An extremely bitter coffee.[n]Restores 30 SP to one[n]ally.[n][e]

[msg Item_1BF]
[s]Almost like Leblanc's, but[n]incredibly spicy. Restores[n]20 SP to all allies.[n][e]

[msg Item_1C0]
[s]Just like Boss's, but[n]incredibly spicy. Restores[n]50 SP to all allies.[n][e]

[msg Item_1C1]
[s]Surpasses Boss's, but is[n]extremely spicy. Restores[n]50 SP to all allies.[n][e]

[msg Item_1C2]
[s]A present from Ryuji. A[n]fake food sample from a[n]ramen shop in Ogikubo.[n][e]

[msg Item_1C3]
[s]A present from Kawakami.[n]The night view from[n]Seaside Park.[n][e]

[msg Item_1C4]
[s]A present from Yusuke.[n]A replica of a sculpture[n]at a museum.[n][e]

[msg Item_1C5]
[s]A present from Iwai.[n]A miniature figure[n]of a swan boat.[n][e]

[msg Item_1C6]
[s]A present from Chihaya.[n]A 1/4000 scale Skytree-[n]shaped lamp.[n][e]

[msg Item_1C7]
[s]A present from Haru. A[n]spatula from a monja shop[n]that takes skill to use.[n][e]

[msg Item_1C8]
[s]A present from Ann.[n]A poster of a top-[n]running idol.[n][e]

[msg Item_1C9]
[s]A present from Yusuke. Glow-[n]in-the-dark constellations,[n]complete with a guide.[n][e]

[msg Item_1CA]
[s]A present from Hifumi.[n]A giant wooden ornament[n]of a king piece in shogi.[n][e]

[msg Item_1CB]
[s]A present from Futaba. A[n]figure of a hero anybody[n]would look up to.[n][e]

[msg Item_1CC]
[s]A present from Yusuke.[n]An arrow from Meiji[n]Shrine that destroys evil.[n][e]

[msg Item_1CD]
[s]A present from Futaba. A[n]souvenir T-shirt printed[n]in English.[n][e]

[msg Item_1CE]
[s]Gum that eases your[n]body and soul. Cures[n]Shock for one ally.[n][e]

[msg Item_1CF]
[s]Unused[n][e]

[msg Item_1D0]
[s]Unused[n][e]

[msg Item_1D1]
[s]Unused[n][e]

[msg Item_1D2]
[s]Handmade chocolate from[n]Kawakami. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D3]
[s]Premium chocolate from[n]Takemi. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D4]
[s]Premium chocolate from[n]Chihaya. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D5]
[s]Premium chocolate from[n]Ohya. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D6]
[s]Handmade chocolate from[n]Hifumi. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D7]
[s]Premium chocolate from[n]Makoto. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D8]
[s]Handmade chocolate from[n]Haru. Fully restores[n]SP of one ally.[n][e]

[msg Item_1D9]
[s]Premium chocolate from[n]Ann. Fully restores[n]SP of one ally.[n][e]

[msg Item_1DA]
[s]Handmade chocolate from[n]Futaba. Fully restores[n]SP of one ally.[n][e]

[msg Item_1DB]
[s]Cheap chocolate from[n]Ryuji. Restores 10 SP[n]to one ally.[n][e]

[msg Item_1DC]
[s]Cheap chocolate from[n]Sojiro. Restores 10 SP[n]to one ally.[n][e]

[msg Item_1DD]
[s]A present from Haru. A[n]good luck charm sold at[n]Tori no Ichi festival.[n][e]

[msg Item_1DE]
[s]A present from Makoto. A[n]cushion based off of a[n]Chinatown favorite.[n][e]

[msg Item_1DF]
[s]A present from Makoto.[n]A baseball team mascot[n]found at Dome Town.[n][e]

[msg Item_1E0]
[s]A present from Ohya. A[n]teacup printed with fish[n]names, used at sushi bars.[n][e]

[msg Item_1E1]
[s]A present from Ann.[n]A millionth customer[n]prize fountain.[n][e]

[msg Item_1E2]
[s]Unused[n][e]

[msg Item_1E3]
[s]Unused[n][e]

[msg Item_1E4]
[s]Unused[n][e]

[msg Item_1E5]
[s]This system is needed to[n]play FD games.[n][e]

[msg Item_1E6]
[s]Unused[n][e]

[msg Item_1E7]
[s]A doll of a worried-[n]looking sheep man.[n][e]

[msg Item_1E8]
[s]Bread with strawberry[n]jam filling. Restores[n]20 HP to one ally.[n][e]

[msg Item_1E9]
[s]A limited product that[n]rejuvenates. Revives one[n]fallen ally to full HP.[n][e]

[msg Item_1EA]
[s]Christmas-only pastry.[n]Revives one fallen ally[n]to full HP.[n][e]

[msg Item_1EB]
[s]Autumn-only Japanese[n]sweet. Restores 200 HP[n]to one ally.[n][e]

[msg Item_1EC]
[s]A can full of a variety of[n]nuts. Restores 40 HP to all[n]allies.[n][e]

[msg Item_1ED]
[s]A sticky sweet potato[n]low in fiber. Restores[n]10 SP to one ally.[n][e]

[msg Item_1EE]
[s]A winter-only roasted[n]sweet potato. Restores[n]50 SP to one ally.[n][e]

[msg Item_1EF]
[s]Unused[n][e]

[msg Item_1F0]
[s]Unused[n][e]

[msg Item_1F1]
[s]Unused[n][e]

[msg Item_1F2]
[s]Unused[n][e]

[msg Item_1F3]
[s]A hard-to-grow carrot.[n]Fully restores SP of[n]one ally.[n][e]

[msg Item_1F4]
[s]A hard-to-grow tomato.[n]Restores 100 SP to all[n]allies.[n][e]

[msg Item_1F5]
[s]A hard-to-grow bean.[n]Doubles the damage of[n]physical attacks one time.[n][e]

[msg Item_1F6]
[s]A hard-to-grow onion.[n]Doubles the damage of[n]magical attacks one time.[n][e]

[msg Item_1F7]
[s]Unused[n][e]

[msg Item_1F8]
[s]Ann's takoyaki-style[n]cream puffs. Restores[n]100 SP to one ally.[n][e]

[msg Item_1F9]
[s]Donuts that were made[n]by Makoto. Restores[n]100 SP to one ally.[n][e]

[msg Item_1FA]
[s]Candy shaped like a[n]cherry blossom. Restores[n]100 SP to one ally.[n][e]

[msg Item_1FB]
[s]Kawakami's specially[n]made taiyaki. Restores[n]100 SP to one ally.[n][e]

[msg Item_1FC]
[s]A gyoza hot dog Ryuji[n]made. Restores 100 SP[n]to one ally.[n][e]

[msg Item_1FD]
[s]Unused[n][e]

[msg Item_1FE]
[s]Unused[n][e]

[msg Item_1FF]
[s]A broken laptop. It looks[n]salvageable.[n][e]

[msg Item_200]
[s]Increases training[n]efficiency. Restores[n]30% HP to one ally.[n][e]

[msg Item_201]
[s]Unused[n][e]

[msg Item_202]
[s]Unused[n][e]

[msg Item_203]
[s]Unused[n][e]

[msg Item_204]
[s]A guidebook that lists[n]attractions in aquariums[n]all over Tokyo.[n][e]

[msg Item_205]
[s]A guidebook that covers[n]popular and obscure spots[n]alike.[n][e]

[msg Item_206]
[s]Incense that imparts[n]physical strength. Increases[n]Persona's St by 1.[n][e]

[msg Item_207]
[s]Incense that strengthens the[n]heart. Increases Persona's[n]Ma by 1.[n][e]

[msg Item_208]
[s]Incense that imparts[n]patience. Increases[n]Persona's En by 1.[n][e]

[msg Item_209]
[s]Incense that lightens your[n]body. Increases Persona's[n]Ag by 1.[n][e]

[msg Item_20A]
[s]Incense that imparts good[n]fortune. Increases Persona's[n]Lu by 1.[n][e]

[msg Item_20B]
[s]Quality incense that imparts[n]physical strength. Increases[n]Persona's St by 2.[n][e]

[msg Item_20C]
[s]Quality incense that[n]strengthens the heart.[n]Increases Persona's Ma by 2.[n][e]

[msg Item_20D]
[s]Quality incense that imparts[n]patience. Increases Persona's[n]En by 2.[n][e]

[msg Item_20E]
[s]Quality incense that[n]lightens your body.[n]Increases Persona's Ag by 2.[n][e]

[msg Item_20F]
[s]Quality incense that imparts[n]good fortune. Increases[n]Persona's Lu by 2.[n][e]

[msg Item_210]
[s]Mystical incense that[n]imparts physical strength.[n]Increases Persona's St by 3.[n][e]

[msg Item_211]
[s]Mystical incense that[n]strengthens the heart.[n]Increases Persona's Ma by 3.[n][e]

[msg Item_212]
[s]Mystical incense that[n]imparts patience.[n]Increases Persona's En by 3.[n][e]

[msg Item_213]
[s]Mystical incense that[n]lightens your body.[n]Increases Persona's Ag by 3.[n][e]

[msg Item_214]
[s]Mystical incense that[n]imparts good fortune.[n]Increases Persona's Lu by 3.[n][e]

[msg Item_215]
[s]Ground beef cutlet that[n]people line up to buy.[n]Restores 30 SP to one ally.[n][e]

[msg Item_216]
[s]Muscle-building supplement.[n]Raises Attack for one ally for[n]three turns.[n][e]

[msg Item_217]
[s]Muscle-making supplement.[n]Raises Defense for one ally[n]for three turns.[n][e]

[msg Item_218]
[s]Supplement for fast muscles.[n]Raises Accuracy/Evasion for[n]one ally for three turns.[n][e]

[msg Item_219]
[s]Unused[n][e]

[msg Item_21A]
[s]Ultimate sakura-mochi made[n]by a famous confectioner.[n]Restores 10 SP to one ally.[n][e]

[msg Item_21B]
[s]Unused[n][e]

[msg Item_21C]
[s]A colorful postcard[n]with an elegant air to it.[n]For the art enthusiast.[n][e]

[msg Item_21D]
[s]A sophisticated pen case[n]made with quality leather.[n]For the gentleman.[n][e]

[msg Item_21E]
[s]A variety of ramen from[n]locales throughout Japan.[n]For the noodle lover.[n][e]

[msg Item_21F]
[s]Vitamins that cover all[n]the bases of health. For[n]the busybody.[n][e]

[msg Item_220]
[s]A slim bangle with a simple[n]and chic design. Can be[n]worn by men.[n][e]

[msg Item_221]
[s]Body-building tools for[n]arms and legs. For the[n]exercise enthusiast.[n][e]

[msg Item_222]
[s]Sporty sunglasses that[n]decrease UV rays by 10%.[n]For the avid runner.[n][e]

[msg Item_223]
[s]A set of 28 kitchen utensils[n]that help you cook anything.[n]For the master chef.[n][e]

[msg Item_224]
[s]An extremely difficult 3D[n]puzzle. For the desk worker[n]who needs a break.[n][e]

[msg Item_225]
[s]Unused[n][e]

[msg Item_226]
[s]Unused[n][e]

[msg Item_227]
[s]Unused[n][e]

[msg Item_228]
[s]Unused[n][e]

[msg Item_229]
[s]Unused[n][e]

[msg Item_22A]
[s]Unused[n][e]

[msg Item_22B]
[s]Unused[n][e]

[msg Item_22C]
[s]Unused[n][e]

[msg Item_22D]
[s]Unused[n][e]

[msg Item_22E]
[s]Small vial of liquid. High[n]chance of inflicting Dizzy[n]to one foe.[n][e]

[msg Item_22F]
[s]Large vial of liquid. Medium[n]chance of inflicting Dizzy[n]to all foes.[n][e]

[msg Item_230]
[s]Small vial of liquid. High[n]chance of inflicting Confuse[n]to one foe.[n][e]

[msg Item_231]
[s]Large vial of liquid. Medium[n]chance of inflicting Confuse[n]to all foes.[n][e]

[msg Item_232]
[s]Small vial of liquid. High[n]chance of inflicting Fear[n]to one foe.[n][e]

[msg Item_233]
[s]Large vial of liquid. Medium[n]chance of inflicting Fear[n]to all foes.[n][e]

[msg Item_234]
[s]Small vial of liquid. High[n]chance of inflicting Forget[n]to one foe.[n][e]

[msg Item_235]
[s]Large vial of liquid. Medium[n]chance of inflicting Forget[n]to all foes.[n][e]

[msg Item_236]
[s]Small vial of liquid. High[n]chance of inflicting Sleep[n]to one foe.[n][e]

[msg Item_237]
[s]Large vial of liquid. Medium[n]chance of inflicting Sleep[n]to all foes.[n][e]

[msg Item_238]
[s]Small vial of liquid. High[n]chance of inflicting Rage[n]to one foe.[n][e]

[msg Item_239]
[s]Large vial of liquid. Medium[n]chance of inflicting Rage[n]to all foes.[n][e]

[msg Item_23A]
[s]Small vial of liquid. High[n]chance of inflicting[n]Despair to one foe.[n][e]

[msg Item_23B]
[s]Large vial of liquid. Medium[n]chance of inflicting Despair[n]to all foes.[n][e]

[msg Item_23C]
[s]Small vial of liquid. High[n]chance of inflicting[n]Brainwash to one foe.[n][e]

[msg Item_23D]
[s]Large vial of liquid. Medium[n]chance of inflicting[n]Brainwash to all foes.[n][e]

[msg Item_23E]
[s]Quality incense that raises[n]Persona's St and Ma by 1.[n][e]

[msg Item_23F]
[s]Quality incense that raises[n]Persona's St and En by 1.[n][e]

[msg Item_240]
[s]Quality incense that raises[n]Persona's St and Ag by 1.[n][e]

[msg Item_241]
[s]Quality incense that raises[n]Persona's St and Lu by 1.[n][e]

[msg Item_242]
[s]Quality incense that raises[n]Persona's Ma and En by 1.[n][e]

[msg Item_243]
[s]Quality incense that raises[n]Persona's Ma and Ag by 1.[n][e]

[msg Item_244]
[s]Quality incense that raises[n]Persona's Ma and Lu by 1.[n][e]

[msg Item_245]
[s]Quality incense that raises[n]Persona's En and Ag by 1.[n][e]

[msg Item_246]
[s]Quality incense that raises[n]Persona's En and Lu by 1.[n][e]

[msg Item_247]
[s]High-quality incense that[n]raises Persona's St, Ma, and[n]Ag by 1.[n][e]

[msg Item_248]
[s]Featherman game with[n]a cult following. May make[n]you more knowledgeable.[n][e]

[msg Item_249]
[s]Came with Featherman[n]Seeker. An enthusiast[n]would know its value.[n][e]

[msg Item_24A]
[s]Coupon for free daytime[n]use at the batting cages.[n][e]

[msg Item_24B]
[s]Muscle builder that increases[n]ATK/DEF/Accuracy/Evasion[n]for one ally.[n][e]

[msg Item_24C]
[s]Lord of the Guardians.[n]Very rarely seen.[n][e]

[msg Item_24D]
[s]Black Frost figurine. Puts[n]you in the mood to do evil.[n][e]

[msg Item_24E]
[s]Buchimaru figurine.[n]A perennial favorite.[n][e]

[msg Item_24F]
[s]The mascot of Jagariko,[n]a popular snack brand.[n][e]

[msg Item_250]
[s]Bait of unknown origin.[n]Only used to catch a[n]particular type of fish.[n][e]

[msg Item_251]
[s]Fishing rod made using[n]space technology. The[n]quality is out of this world.[n][e]

[msg Item_252]
[s]A sea slug doll with[n]beady eyes. A gift from[n][f 4 31 10 1].[n][e]

[msg Item_253]
[s]Phoenix Ranger figurines[n]that even connoisseurs can[n]enjoy. A gift from Ryuji.[n][e]

[msg Item_254]
[s]Handmade chocolate from[n]Sumire. Fully restores SP of[n]one ally.[n][e]

[msg Item_255]
[s]Courtesy chocolate from[n]Ann. Restores 100 SP to[n]one ally.[n][e]

[msg Item_256]
[s]Courtesy chocolate from[n]Makoto. Restores 100 SP[n]to one ally.[n][e]

[msg Item_257]
[s]Courtesy chocolate from[n]Haru. Restores 100 SP to[n]one ally.[n][e]

[msg Item_258]
[s]Courtesy chocolate from[n]Futaba. Restores 100 SP[n]to one ally.[n][e]

[msg Item_259]
[s]Courtesy chocolate from[n]Takemi. Restores 100 SP[n]to one ally.[n][e]

[msg Item_25A]
[s]Courtesy chocolate from[n]Chihaya. Restores 100 SP[n]to one ally.[n][e]

[msg Item_25B]
[s]Courtesy chocolate from[n]Kawakami. Restores 100[n]SP to one ally.[n][e]

[msg Item_25C]
[s]Courtesy chocolate from[n]Ohya. Restores 100 SP to[n]one ally.[n][e]

[msg Item_25D]
[s]Courtesy chocolate from[n]Hifumi. Restores 100 SP[n]to one ally.[n][e]

[msg Item_25E]
[s]Courtesy chocolate from[n]Sumire. Restores 100 SP[n]to one ally.[n][e]

[msg Item_25F]
[s]Courtesy chocolate from[n]Sae. Restores 100 SP to[n]one ally.[n][e]

[msg Item_260]
[s]Candy chosen with Makoto.[n]Fully restores SP of one ally.[n][e]

[msg Item_261]
[s]Candy chosen with Haru.[n]Fully restores SP of one ally.[n][e]

[msg Item_262]
[s]Candy chosen with Ann.[n]Fully restores SP of one ally.[n][e]

[msg Item_263]
[s]Candy chosen with Futaba.[n]Fully restores SP of one ally.[n][e]

[msg Item_264]
[s]Candy chosen with Chihaya.[n]Fully restores SP of one ally.[n][e]

[msg Item_265]
[s]Candy chosen with Takemi.[n]Fully restores SP of one ally.[n][e]

[msg Item_266]
[s]Candy chosen with[n]Kawakami. Fully restores[n]SP of one ally.[n][e]

[msg Item_267]
[s]Candy chosen with Ohya.[n]Fully restores SP of one ally.[n][e]

[msg Item_268]
[s]Candy chosen with Hifumi.[n]Fully restores SP of one ally.[n][e]

[msg Item_269]
[s]Candy chosen with [f 4 31 10 1].[n]Fully restores SP of one ally.[n][e]

[msg Item_26A]
[s]This flower's meaning is[n]"I love you." Who might[n]like to receive this?[n][e]

[msg Item_26B]
[s]The meaning of the flower is[n]"Ultimate Love." Who might[n]like to receive this?[n][e]

[msg Item_26C]
[s]The meaning of the flower is[n]"Unchanging Love." Who[n]might like to receive this?[n][e]

[msg Item_26D]
[s]Tool that can only be used[n]in safe places. Restores 20%[n]SP to all allies.[n][e]

[msg Item_26E]
[s]Tool that can only be used[n]in safe places. Restores 40%[n]SP to all allies.[n][e]

[msg Item_26F]
[s]Darts made with superior[n]feel and balance. Sought[n]out by pros.[n][e]

[msg Item_270]
[s]Special cue made for jump[n]shots. For those who want[n]to master billiards.[n][e]

[msg Item_271]
[s]Worthy of resurrecting[n]a Hierophant. Revives all[n]fallen allies to full HP.[n][e]

[msg Item_272]
[s]Classic strawberry daifuku.[n]Fully restores HP and cures[n]all ailments of all allies.[n][e]

[msg Item_273]
[s]Techniques written by a[n]professional darts player.[n][e]

[msg Item_274]
[s]Techniques written by a[n]professional billiards player.[n][e]

[msg Item_275]
[s]Women's stories of love and[n]passion. Learn about leading[n]a charmed life.[n][e]

[msg Item_276]
[s]A maverick rodent's medical[n]heroics. Learn about true[n]kindness.[n][e]

[msg Item_277]
[s]A writer and editor battle[n]looming deadlines. Praised[n]for its gutsy tension.[n][e]

[msg Item_278]
[s]A teacher and a near defunct[n]high school golf team. Be[n]proficient in persuasion.[n][e]

[msg Item_279]
[s]Membership card for a[n]Maid Café. Earn a stamp[n]with every visit.[n][e]

[msg Item_27A]
[s]A signed photo of Clara.[n]The autograph covers[n]most of the face.[n][e]

[msg Item_27B]
[s]Cheese with little flavor.[n]Restores 20 HP to one ally.[n][e]

[msg Item_27C]
[s]Cheese with good flavor.[n]Restores 50 HP to one ally.[n][e]

[msg Item_27D]
[s]Cheese with rich flavor.[n]Restores 100 HP to one ally.[n][e]

[msg Item_27E]
[s]A packet of thick pumpkin[n]soup. Restores 100 HP to[n]one ally.[n][e]

[msg Item_27F]
[s]RESERVE[n][e]

[msg Item_280]
[s]A pair of impossibly puzzling[n]rings. For those who like a[n]challenge.[n][e]

[msg Item_281]
[s]A cushion made of material[n]that is squishy to the touch.[n]For the busy businessperson.[n][e]

[msg Item_282]
[s]370,000 rotations per[n]second obliterates plaque.[n]For the busy businessperson.[n][e]

[msg Item_283]
[s]Ultra-loud alarm clock to[n]wake up any sleepyhead.[n]For the busy businessperson.[n][e]

[msg Item_284]
[s]A palm-sized machine that[n]dispenses fragrance and[n]moisture. For desk workers.[n][e]

[msg Item_285]
[s]A katana keychain with[n]a dragon design. For[n]the young man at heart.[n][e]

[msg Item_286]
[s]Well-thumbed reference[n]book. Increases the[n]effectiveness of studying.[n][e]

[msg Item_287]
[s]Aim-enhancing supplement.[n]Increases chance of Critical[n]for one ally.[n][e]

[msg Item_288]
[s]European-style jelly to eat[n]on the go. Restores 100 HP[n]to one ally.[n][e]

[msg Item_289]
[s]Disinfectant that weakens[n]bacteria. Lowers Attack of[n]all foes for 3 turns.[n][e]

[msg Item_28A]
[s]Powerful disinfectant.[n]Decreases Defense of[n]all foes for 3 turns.[n][e]

[msg Item_28B]
[s]Fast-acting disinfectant.[n]Lowers Accuracy/Evasion[n]for all foes for 3 turns.[n][e]

[msg Item_28C]
[s]Disinfectant that weakens[n]any bacteria. Lowers all[n]stats of one foe for 3 turns.[n][e]

[msg Item_28D]
[s]Cleansing air freshener.[n]Cures all non-special[n]ailments for one ally.[n][e]

[msg Item_28E]
[s]Invigorating air freshener.[n]Cures all non-special[n]ailments for all allies.[n][e]

[msg Item_28F]
[s]Unused[n][e]

[msg Item_290]
[s]Unused[n][e]

[msg Item_291]
[s]RESERVE[n][e]

[msg Item_292]
[s]A girl facing unfortunate[n]circumstances. Learn about[n]leading a charmed life.[n][e]

[msg Item_293]
[s]RESERVE[n][e]

[msg Item_294]
[s]A shiny, delicious apple.[n]Fully restores HP of all allies.[n][e]

[msg Item_295]
[s]Emergency medicine.[n]Revives one fallen ally[n]to 50% HP.[n][e]

[msg Item_296]
[s]Shroud possibly worn by a[n]saint. Medium chance of[n]Bless insta-kill to all foes.[n][e]

[msg Item_297]
[s]Fortune telling board with[n]a past. Medium chance of[n]Curse insta-kill to all foes.[n][e]

[msg Item_298]
[s]Increases ATK/DEF/[n]Accuracy/Evasion for[n]one ally for 3 turns.[n][e]

[msg Item_299]
[s]Decreases ATK/DEF[n]Accuracy/Evasion for[n]one foe for 3 turns.[n][e]

[msg Item_29A]
[s]Deals 50 Fire dmg to[n]one foe. High chance[n]of inflicting Burn.[n][e]

[msg Item_29B]
[s]Deals 50 Wind dmg to[n]one foe.[n][e]

[msg Item_29C]
[s]Deals 50 Elec dmg to[n]one foe. High chance[n]of inflicting Shock.[n][e]

[msg Item_29D]
[s]Deals 50 Ice dmg to[n]one foe. High chance[n]of inflicting Freeze.[n][e]

[msg Item_29E]
[s]Deals 50 Nuke dmg to[n]one foe.[n][e]

[msg Item_29F]
[s]Deals 50 Psy dmg to[n]one foe.[n][e]

[msg Item_2A0]
[s]Deals 50 Bless dmg to[n]one foe.[n][e]

[msg Item_2A1]
[s]Deals 50 Curse dmg to[n]one foe.[n][e]

[msg Item_2A2]
[s]Forms a barrier that[n]nullifies an insta-kill for[n]all allies one time.[n][e]

[msg Item_2A3]
[s]Charm increasing strength.[n]Doubles the damage of[n]physical attacks one time.[n][e]

[msg Item_2A4]
[s]Charm improving focus.[n]Doubles the damage of[n]magical attacks one time.[n][e]

[msg Item_2A5]
[s]For the expert-level[n]craftsman. Improves skills[n]for making infiltration tools.[n][e]

[msg Item_2A6]
[s]Basics for the aspiring[n]craftsman. Improves skills[n]for making infiltration tools.[n][e]

[msg Item_2A7]
[s]Filled with juicy meat.[n]Restores 30 HP to one ally.[n][e]

[msg Item_2A8]
[s]Meat bun with a reddish tint.[n]Tastes better than it looks.[n]Restores 50 HP to one ally.[n][e]

[msg Item_2A9]
[s]Spicy meat bun that warms[n]you to your core. Restores[n]100 HP to one ally.[n][e]

[msg Item_2AA]
[s]Assorted cans of corned[n]beef. Restores 40 HP to[n]all allies.[n][e]

[msg Item_2AB]
[s]Multi-pack of assorted[n]cereal. Restores 80 HP[n]to all allies.[n][e]

[msg Item_2AC]
[s]Large container of caramel[n]popcorn. Restores 100 HP[n]to all allies.[n][e]

[msg Item_2AD]
[s]Contains four sets of used[n]clothes. What you get is a[n]surprise.[n][e]

[msg Item_2AE]
[s]Fills you up like a New Year's[n]Day meal. Restores 30% SP[n]to one ally. Lowers all stats.[n][e]

[msg Item_2AF]
[s]A sweet treat for the[n]stomach. Restores 50 HP and[n]cures Hunger for one ally.[n][e]

[msg Item_2B0]
[s]Exotic food. Restores 30%[n]HP to one ally, lowers Attack,[n]raises Accuracy/Evasion.[n][e]

[msg Item_2B1]
[s]A joy-inducing deluxe[n]Chinese sticky rice dumpling.[n]Restores 100 SP to one ally.[n][e]

[msg Item_2B2]
[s]Osechi made of chocolate.[n]Even sweeter with friends.[n]Fully restores HP of all allies.[n][e]

[msg Item_2B3]
[s]Old book about the fragility[n]of the human heart. Expands[n]Technical conditions.[n][e]

[msg Item_2B4]
[s]Breaks all known limits.[n]Ball speed: ??? mph.[n][e]

[msg Item_2B5]
[s]The ingredients are super[n]secret. Fully restores HP[n]and SP of all allies.[n][e]

[msg Item_2B6]
[s]Miraculous techniques[n]by a billiards master.[n]Learn about massé.[n][e]

[msg Item_2B7]
[s]Quality incense that raises[n]Persona's Ag and Lu by 1.[n][e]

