[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Unused[n][e]

[msg Item_002]
[s]Unused[n][e]

[msg Item_003]
[s]Unused[n][e]

[msg Item_004]
[s]Unused[n][e]

[msg Item_005]
[s]Unused[n][e]

[msg Item_006]
[s]Unused[n][e]

[msg Item_007]
[s]Unused[n][e]

[msg Item_008]
[s]Unused[n][e]

[msg Item_009]
[s]Unused[n][e]

[msg Item_00A]
[s]Unused[n][e]

[msg Item_00B]
[s]Unused[n][e]

[msg Item_00C]
[s]Unused[n][e]

[msg Item_00D]
[s]Unused[n][e]

[msg Item_00E]
[s]Unused[n][e]

[msg Item_00F]
[s]Unused[n][e]

[msg Item_010]
[s]Unused[n][e]

[msg Item_011]
[s]Unused[n][e]

[msg Item_012]
[s]A glowing staff.[n]Sells for a lot.[n][e]

[msg Item_013]
[s]Played when celebrating.[n]Sells for a lot.[n][e]

[msg Item_014]
[s]Given to the winners.[n]Sells for a lot.[n][e]

[msg Item_015]
[s]A nice porcelain teacup.[n]Sells for a good amount.[n][e]

[msg Item_016]
[s]Made of stainless steel.[n]Sells for a good amount.[n][e]

[msg Item_017]
[s]Has a mysterious flame.[n]Sells for a good amount.[n][e]

[msg Item_018]
[s]Dripping with wax.[n]Sells for a good amount.[n][e]

[msg Item_019]
[s]Has a ball and chain.[n]Sells for some.[n][e]

[msg Item_01A]
[s]A collar with a lock.[n]Sells for some.[n][e]

[msg Item_01B]
[s]The blade is chipped.[n]Sells for some.[n][e]

[msg Item_01C]
[s]It has a big hole in it.[n]Sells for a little.[n][e]

[msg Item_01D]
[s]It is bent in many ways.[n]Sells for a little.[n][e]

[msg Item_01E]
[s]Looks used.[n]Sells for a little.[n][e]

[msg Item_01F]
[s]A damaged wine glass.[n]Sells for a little.[n][e]

[msg Item_020]
[s]A work of a beautiful[n]woman. Sells for a lot.[n][e]

[msg Item_021]
[s]Depicts beautiful scenery.[n]Sells for a lot.[n][e]

[msg Item_022]
[s]Filled with flowers and[n]birds. Sells for a lot.[n][e]

[msg Item_023]
[s]Has plenty of satire.[n]Sells for a good amount.[n][e]

[msg Item_024]
[s]Used in Noh performances.[n]Sells for a good amount.[n][e]

[msg Item_025]
[s]Made from animal hair.[n]Sells for a good amount.[n][e]

[msg Item_026]
[s]Feels good to write on it.[n]Sells for some.[n][e]

[msg Item_027]
[s]The embroidery is loose.[n]Sells for some.[n][e]

[msg Item_028]
[s]A small damaged vase.[n]Sells for some.[n][e]

[msg Item_029]
[s]An iron pot.[n]Sells for some.[n][e]

[msg Item_02A]
[s]Feels handmade.[n]Sells for a little.[n][e]

[msg Item_02B]
[s]Made of light plastic.[n]Sells for a little.[n][e]

[msg Item_02C]
[s]An amateur portrait.[n]Sells for a little.[n][e]

[msg Item_02D]
[s]A crooked sculpture.[n]Sells for a little.[n][e]

[msg Item_02E]
[s]A commemorative coin.[n]Sells for a lot.[n][e]

[msg Item_02F]
[s]For a big food company.[n]Sells for a lot.[n][e]

[msg Item_030]
[s]A stamp made of amber.[n]Sells for a lot.[n][e]

[msg Item_031]
[s]An old bill worth a lot.[n]Sells for a good amount.[n][e]

[msg Item_032]
[s]An old, rare coin.[n]Sells for a good amount.[n][e]

[msg Item_033]
[s]Used at old festivals.[n]Sells for a good amount.[n][e]

[msg Item_034]
[s]A leather stamp case.[n]Sells for some.[n][e]

[msg Item_035]
[s]Removed from a safe door.[n]Sells for some.[n][e]

[msg Item_036]
[s]Used to count bills.[n]Sells for some.[n][e]

[msg Item_037]
[s]Used by bankers.[n]Sells for some.[n][e]

[msg Item_038]
[s]It's out of ink.[n]Sells for a little.[n][e]

[msg Item_039]
[s]It won't unlock.[n]Sells for a little.[n][e]

[msg Item_03A]
[s]Has been used quite a lot.[n]Sells for a little.[n][e]

[msg Item_03B]
[s]An old used wallet.[n]Sells for a little.[n][e]

[msg Item_03C]
[s]Decorated in gems.[n]Sells for a lot.[n][e]

[msg Item_03D]
[s]A snake crest.[n]Sells for a lot.[n][e]

[msg Item_03E]
[s]Filled with organs.[n]Sells for a lot.[n][e]

[msg Item_03F]
[s]Fits in the palm of your hand.[n]Sells for a good amount.[n][e]

[msg Item_040]
[s]A beetle-shaped stone.[n]Sells for a good amount.[n][e]

[msg Item_041]
[s]Worn by mummies.[n]Sells for a good amount.[n][e]

[msg Item_042]
[s]A beat-up sword.[n]Sells for some.[n][e]

[msg Item_043]
[s]A rusted Egyptian cross.[n]Sells for some.[n][e]

[msg Item_044]
[s]Too torn to decipher.[n]Sells for some.[n][e]

[msg Item_045]
[s]A piece of a mural.[n]Sells for some.[n][e]

[msg Item_046]
[s]A shard of a mural.[n]Sells for some.[n][e]

[msg Item_047]
[s]A piece of a coffin.[n]Sells for a little.[n][e]

[msg Item_048]
[s]A hieroglyphic staff.[n]Sells for a little.[n][e]

[msg Item_049]
[s]From the altar pillar.[n]Sells for a little.[n][e]

[msg Item_04A]
[s]Rock that could be from the[n]moon. Sells for a lot.[n][e]

[msg Item_04B]
[s]Metal that doesn't seem[n]to belong on Earth.[n]Sells for a lot.[n][e]

[msg Item_04C]
[s]Used since ancient times.[n]Sells for a lot.[n][e]

[msg Item_04D]
[s]Disc-shaped toy spacecraft.[n]Sells for a good amount.[n][e]

[msg Item_04E]
[s]A portable flashlight.[n]Sells for a good amount.[n][e]

[msg Item_04F]
[s]Emits lights of all colors.[n]Sells for a good amount.[n][e]

[msg Item_050]
[s]Used to steer spaceships.[n]Sells for some.[n][e]

[msg Item_051]
[s]From an android.[n]Sells for some.[n][e]

[msg Item_052]
[s]Used to catch signals.[n]Sells for some.[n][e]

[msg Item_053]
[s]A mini pocket version.[n]Sells for some.[n][e]

[msg Item_054]
[s]Frozen food used in space.[n]Sells for a little.[n][e]

[msg Item_055]
[s]A broken circuit board.[n]Sells for a little.[n][e]

[msg Item_056]
[s]Popular in space as well.[n]Sells for a little.[n][e]

[msg Item_057]
[s]A spacecraft part.[n]Sells for a little.[n][e]

[msg Item_058]
[s]Made by a famous craftsman.[n]Sells for a lot.[n][e]

[msg Item_059]
[s]Small but pricey earrings.[n]Sells for a lot.[n][e]

[msg Item_05A]
[s]Embedded with gems.[n]Sells for a lot.[n][e]

[msg Item_05B]
[s]The frame is silver.[n]Sells for a good amount.[n][e]

[msg Item_05C]
[s]Made from ivory.[n]Sells for a good amount.[n][e]

[msg Item_05D]
[s]Loved by a skilled dealer.[n]Sells for a good amount.[n][e]

[msg Item_05E]
[s]The type magicians like.[n]Sells for some.[n][e]

[msg Item_05F]
[s]Has a very stable center.[n]Sells for some.[n][e]

[msg Item_060]
[s]Makes shuffling easy.[n]Sells for some.[n][e]

[msg Item_061]
[s]Rolls on touch.[n]Sells for some.[n][e]

[msg Item_062]
[s]Used to close cuffs.[n]Sells for a little.[n][e]

[msg Item_063]
[s]It has lost its color.[n]Sells for a little.[n][e]

[msg Item_064]
[s]Expensive but used.[n]Sells for a little.[n][e]

[msg Item_065]
[s]Not a full deck of cards.[n]Sells for a little.[n][e]

[msg Item_066]
[s]Jewelry using coral.[n]Sells for a lot.[n][e]

[msg Item_067]
[s]Full of black pearls.[n]Sells for a lot.[n][e]

[msg Item_068]
[s]A fancy cosmetic case.[n]Sells for a lot.[n][e]

[msg Item_069]
[s]Made of marble.[n]Sells for a good amount.[n][e]

[msg Item_06A]
[s]Made from tortoiseshell.[n]Sells for a good amount.[n][e]

[msg Item_06B]
[s]A shell is engraved in it.[n]Sells for a good amount.[n][e]

[msg Item_06C]
[s]Fixed with a shiny shell.[n]Sells for a good amount.[n][e]

[msg Item_06D]
[s]Modeled after a peacock.[n]Sells for some.[n][e]

[msg Item_06E]
[s]Crafted with skill.[n]Sells for some.[n][e]

[msg Item_06F]
[s]Comes with a cover.[n]Sells for some.[n][e]

[msg Item_070]
[s]A wind-up type.[n]Sells for a little.[n][e]

[msg Item_071]
[s]Gives a nostalgic feeling.[n]Sells for a little.[n][e]

[msg Item_072]
[s]Lights up the dance floor.[n]Sells for a little.[n][e]

[msg Item_073]
[s]Used to hide your identity.[n]Sells for a little.[n][e]

[msg Item_074]
[s]BLANK[n][e]

[msg Item_075]
[s]BLANK[n][e]

[msg Item_076]
[s]BLANK[n][e]

[msg Item_077]
[s]BLANK[n][e]

[msg Item_078]
[s]BLANK[n][e]

[msg Item_079]
[s]BLANK[n][e]

[msg Item_07A]
[s]BLANK[n][e]

[msg Item_07B]
[s]BLANK[n][e]

[msg Item_07C]
[s]BLANK[n][e]

[msg Item_07D]
[s]BLANK[n][e]

[msg Item_07E]
[s]BLANK[n][e]

[msg Item_07F]
[s]BLANK[n][e]

[msg Item_080]
[s]BLANK[n][e]

[msg Item_081]
[s]BLANK[n][e]

[msg Item_082]
[s]An extra large lump of gold.[n]Sells for a good amount.[n][e]

[msg Item_083]
[s]Large lump of gold.[n]Sells for a good amount.[n][e]

[msg Item_084]
[s]Small lump of gold.[n]Sells for a good amount.[n][e]

[msg Item_085]
[s]Jagged-edged silver coin.[n]Sells for some.[n][e]

[msg Item_086]
[s]Silver coin with a hole.[n]Sells for some.[n][e]

[msg Item_087]
[s]A thin silver coin.[n]Sells for some.[n][e]

[msg Item_088]
[s]Jagged-edged copper coin.[n]Sells for a little.[n][e]

[msg Item_089]
[s]Copper coin with a hole.[n]Sells for a little.[n][e]

[msg Item_08A]
[s]A thin copper coin.[n]Sells for a little.[n][e]

[msg Item_08B]
[s]A beautiful black gem.[n]Sells for a ton.[n][e]

[msg Item_08C]
[s]A white round gem.[n]Sells for a ton.[n][e]

[msg Item_08D]
[s]A light purple gem.[n]Sells for a ton.[n][e]

[msg Item_08E]
[s]A vivid blue gem.[n]Sells for a ton.[n][e]

[msg Item_08F]
[s]A multicolored gem.[n]Sells for a ton.[n][e]

[msg Item_090]
[s]A bright yellow gem.[n]Sells for a ton.[n][e]

[msg Item_091]
[s]A crimson red gem.[n]Sells for a ton.[n][e]

[msg Item_092]
[s]An aqua blue gem.[n]Sells for a ton.[n][e]

[msg Item_093]
[s]A beautiful red gem.[n]Sells for a ton.[n][e]

[msg Item_094]
[s]A green gem of knowledge.[n]Sells for a ton.[n][e]

[msg Item_095]
[s]A dark blue gem.[n]Sells for a ton.[n][e]

[msg Item_096]
[s]A glamorously shining gem.[n]Sells for a ton.[n][e]

[msg Item_097]
[s]A beautiful dark green gem.[n]Sells for a ton.[n][e]

[msg Item_098]
[s]BLANK[n][e]

[msg Item_099]
[s]BLANK[n][e]

[msg Item_09A]
[s]BLANK[n][e]

[msg Item_09B]
[s]BLANK[n][e]

[msg Item_09C]
[s]BLANK[n][e]

[msg Item_09D]
[s]BLANK[n][e]

[msg Item_09E]
[s]BLANK[n][e]

[msg Item_09F]
[s]BLANK[n][e]

[msg Item_0A0]
[s]BLANK[n][e]

[msg Item_0A1]
[s]A lump of precious[n]metal that shines silver.[n]Sells for a ton.[n][e]

[msg Item_0A2]
[s]Lighting equipment[n]that won't turn on.[n]Sells for a little.[n][e]

[msg Item_0A3]
[s]Cassette tape with[n]film spilling out.[n]Sells for a little.[n][e]

[msg Item_0A4]
[s]Inextricable cords.[n]Sells for a little.[n][e]

[msg Item_0A5]
[s]Misprinted poster.[n]Sells for a little.[n][e]

[msg Item_0A6]
[s]Unused sound recorder.[n]Sells for some.[n][e]

[msg Item_0A7]
[s]Discarded pointer device.[n]Sells for some.[n][e]

[msg Item_0A8]
[s]Old voltage converter.[n]Sells for some.[n][e]

[msg Item_0A9]
[s]Meter of some sort.[n]Sells for some.[n][e]

[msg Item_0AA]
[s]Distorted industrial lens.[n]Sells for some.[n][e]

[msg Item_0AB]
[s]Worn-out projector.[n]Sells for a ton.[n][e]

[msg Item_0AC]
[s]Sensor that reacts to sound.[n]Sells for a ton.[n][e]

[msg Item_0AD]
[s]Device with a broken[n]temperature control.[n]Sells for a ton.[n][e]

[msg Item_0AE]
[s]Maruki Super Expensive S[n][e]

[msg Item_0AF]
[s]Maruki Super Expensive S[n][e]

[msg Item_0B0]
[s]BLANK[n][e]

[msg Item_0B1]
[s]Prison Jewel[n][e]

[msg Item_0B2]
[s]Horn that makes no sound.[n]Sells for a little.[n][e]

[msg Item_0B3]
[s]Uniform cap with a big hole.[n]Sells for a little.[n][e]

[msg Item_0B4]
[s]Broken, useless baton.[n]Sells for a little.[n][e]

[msg Item_0B5]
[s]Handcuffs that won't lock.[n]Sells for a little.[n][e]

[msg Item_0B6]
[s]Iron ball with a black lust.[n]Sells for some.[n][e]

[msg Item_0B7]
[s]Tidy prison uniform.[n]Sells for some.[n][e]

[msg Item_0B8]
[s]Shining pin badge.[n]Sells for some.[n][e]

[msg Item_0B9]
[s]Megaphone that can[n]be heard from anywhere.[n]Sells for some.[n][e]

[msg Item_0BA]
[s]Extremely sharp barbed wire.[n]Sells for some.[n][e]

[msg Item_0BB]
[s]Emblem that shines gold.[n]Sells for a ton.[n][e]

[msg Item_0BC]
[s]Golden cap badge.[n]Sells for a ton.[n][e]

[msg Item_0BD]
[s]Arm band that shines silver.[n]Sells for a ton.[n][e]

[msg Item_0BE]
[s]Prison Super Expensive S[n][e]

[msg Item_0BF]
[s]Prison Super Expensive S[n][e]

[msg Item_0C0]
[s]BLANK[n][e]

[msg Item_0C1]
[s]Lump of shining copper.[n]Sells for some.[n][e]

[msg Item_0C2]
[s]Shining copper made[n]into a luxurious chain.[n]Sells for a little.[n][e]

[msg Item_0C3]
[s]Copper object[n]shaped like a hand.[n]Sells for a little.[n][e]

[msg Item_0C4]
[s]Copper object[n]shaped like a heart.[n]Sells for a crazy amount.[n][e]

[msg Item_0C5]
[s]Shining copper object[n]shaped like a star.[n]Sells for a crazy amount.[n][e]

[msg Item_0C6]
[s]Copper object shaped[n]like a moon. Sells for[n]an exorbitant amount.[n][e]

[msg Item_0C7]
[s]Copper mist object.[n]Sells for an[n]exorbitant amount.[n][e]

[msg Item_0C8]
[s]A large lump of[n]glimmering silver.[n]Sells for a little.[n][e]

[msg Item_0C9]
[s]Glimmering silver made[n]into a luxurious chain.[n]Sells for a crazy amount.[n][e]

[msg Item_0CA]
[s]Silver object[n]shaped like a hand.[n]Sells for a crazy amount.[n][e]

[msg Item_0CB]
[s]Silver object[n]shaped like a heart.[n]Sells for a crazy amount.[n][e]

[msg Item_0CC]
[s]Glimmering silver[n]object shaped like a star.[n]Sells for a crazy amount.[n][e]

[msg Item_0CD]
[s]Silver object shaped[n]like a moon. Sells for[n]an exorbitant amount.[n][e]

[msg Item_0CE]
[s]Silver mist object.[n]Sells for an exorbitant[n]amount.[n][e]

[msg Item_0CF]
[s]Large golden lump.[n]Sells for a crazy amount.[n][e]

[msg Item_0D0]
[s]Golden object made[n]into a luxurious chain.[n]Sells for a crazy amount.[n][e]

[msg Item_0D1]
[s]Golden object[n]shaped like a hand.[n]Sells for a crazy amount.[n][e]

[msg Item_0D2]
[s]Golden object[n]shaped like a heart.[n]Sells for a crazy amount.[n][e]

[msg Item_0D3]
[s]Golden object[n]shaped like a star.[n]Sells for a crazy amount.[n][e]

[msg Item_0D4]
[s]Golden object[n]shaped like a moon.[n]Sells for a shocking amount.[n][e]

[msg Item_0D5]
[s]Golden mist object.[n]Sells for a shocking amount.[n][e]

[msg Item_0D6]
[s]Lump of platinum.[n]Sells for a crazy amount.[n][e]

[msg Item_0D7]
[s]Lump of diamond.[n]Sells for an exorbitant[n]amount.[n][e]

[msg Item_0D8]
[s]BLANK[n][e]

[msg Item_0D9]
[s]BLANK[n][e]

[msg Item_0DA]
[s]BLANK[n][e]

[msg Item_0DB]
[s]BLANK[n][e]

[msg Item_0DC]
[s]BLANK[n][e]

[msg Item_0DD]
[s]BLANK[n][e]

[msg Item_0DE]
[s]BLANK[n][e]

[msg Item_0DF]
[s]BLANK[n][e]

[msg Item_0E0]
[s]BLANK[n][e]

[msg Item_0E1]
[s]BLANK[n][e]

[msg Item_0E2]
[s]BLANK[n][e]

[msg Item_0E3]
[s]BLANK[n][e]

[msg Item_0E4]
[s]BLANK[n][e]

[msg Item_0E5]
[s]BLANK[n][e]

[msg Item_0E6]
[s]BLANK[n][e]

[msg Item_0E7]
[s]BLANK[n][e]

[msg Item_0E8]
[s]BLANK[n][e]

[msg Item_0E9]
[s]BLANK[n][e]

[msg Item_0EA]
[s]BLANK[n][e]

[msg Item_0EB]
[s]BLANK[n][e]

[msg Item_0EC]
[s]BLANK[n][e]

[msg Item_0ED]
[s]BLANK[n][e]

[msg Item_0EE]
[s]BLANK[n][e]

[msg Item_0EF]
[s]BLANK[n][e]

[msg Item_0F0]
[s]BLANK[n][e]

[msg Item_0F1]
[s]BLANK[n][e]

[msg Item_0F2]
[s]BLANK[n][e]

[msg Item_0F3]
[s]BLANK[n][e]

[msg Item_0F4]
[s]BLANK[n][e]

[msg Item_0F5]
[s]BLANK[n][e]

[msg Item_0F6]
[s]BLANK[n][e]

[msg Item_0F7]
[s]BLANK[n][e]

[msg Item_0F8]
[s]BLANK[n][e]

[msg Item_0F9]
[s]BLANK[n][e]

[msg Item_0FA]
[s]BLANK[n][e]

[msg Item_0FB]
[s]BLANK[n][e]

[msg Item_0FC]
[s]BLANK[n][e]

[msg Item_0FD]
[s]BLANK[n][e]

[msg Item_0FE]
[s]BLANK[n][e]

[msg Item_0FF]
[s]BLANK[n][e]

