[msg myth_000]
[s]RESERVE[n]Mythology[n][e]

[msg myth_001]
[s]The greatest angel[n]in Judeo-Christian[n]legend. He is known[n]as the Voice of God[n]or the Angel of[n]Contracts. Despite[n]his duty to maintain[n]the world's order,[n]he shows no mercy[n]towards humanity.[n][e]

[msg myth_002]
[s]Demonic Lord of the[n]Flies whose insect[n]minions carry souls[n]for him to control.[n]He is mentioned in the[n]Bible as a leader of[n]evil spirits and is seen[n]as a powerful demon.[n][e]

[msg myth_003]
[s]A hero in Celtic[n]folklore. He was[n]called Setanta until[n]he earned the name,[n]"Culann's Hound."[n]There are many tales[n]of his adventures.[n]He received his spear,[n]Gae Bolg, from his[n]mentor, Scathach.[n][e]

[msg myth_004]
[s]A drunkard who[n]tricked the Devil[n]out of taking him to[n]Hell. When refused[n]entry to Heaven, he[n]was forced to wander[n]the earth with only[n]an ember as a light.[n][e]

[msg myth_005]
[s]A winter fairy of[n]European descent.[n]He leaves ice[n]patterns on windows[n]and nips people's[n]noses. Though[n]normally an innocent[n]creature, he will[n]freeze his victims to[n]death if provoked.[n][e]

[msg myth_006]
[s]Friendly fairies of[n]the forest that[n]tend to hide from[n]humans. They like[n]to play tricks on[n]the Laz people. It[n]is said they are[n]the souls of dead,[n]unbaptized children.[n][e]

[msg myth_007]
[s]The guardian hound[n]who prevents[n]anyone from[n]entering or exiting[n]the underworld in[n]Greek lore. It was[n]born from Typhon[n]and Echidna, and is[n]the older brother of[n]Orthrus.[n][e]

[msg myth_008]
[s]A demon who tempts[n]sleeping men and[n]attacks infants.[n]She is the daughter[n]of the demoness,[n]Lilith. Like her[n]mother, she drains[n]men of their essence.[n][e]

[msg myth_009]
[s]One of the 72[n]demons of the[n]Goetia. He looks[n]like a knight and[n]has the power to[n]see things to come.[n]He also knows[n]much about war.[n][e]

[msg myth_010]
[s]The father of all[n]gods in Norse[n]legend. He willingly[n]sacrificed one eye[n]to gain wisdom. In[n]preparation for[n]Ragnarok, he gathers[n]the souls of fallen[n]warriors to his hall,[n]Valhalla.[n][e]

[msg myth_011]
[s]A spirit of Chinese[n]folklore who dwells[n]in trees once used[n]for hangings. She is[n]smaller than a human[n]and cannot speak,[n]but her voice is said[n]to be as clear and[n]as beautiful as[n]a bird's song.[n][e]

[msg myth_012]
[s]One of the 72[n]demons of the[n]Goetia, this demon[n]appears as a[n]pentacle. Keeper[n]of jewels and herbal[n]lore, Decarabia is[n]said to have the[n]ability to shape-[n]shift at will.[n][e]

[msg myth_013]
[s]A Buddhist demon[n]that represents the[n]fear of death. Also[n]known as "The Evil[n]One," he sent his[n]daughters to tempt[n]Buddha during his[n]meditations.[n][e]

[msg myth_014]
[s]One of the 72[n]demons of the[n]Goetia, he is known[n]as the President of[n]Hell. He can shape-[n]shift from leopard to[n]human and reveal[n]the truth behind[n]divine mysteries.[n][e]

[msg myth_015]
[s]The Norse thunder[n]god and son of Odin,[n]Thor owns the power[n]enhancing belt,[n]Megingjard, and[n]wields Mjolnir, a[n]hammer that causes[n]lightning to strike[n]and returns to its[n]owner if thrown.[n][e]

[msg myth_016]
[s]A legendary white[n]horse with a single[n]spiral horn. It can[n]only be tamed by a[n]pure maiden, and its[n]horn supposedly has[n]miraculous healing[n]capabilities.[n][e]

[msg myth_017]
[s]One of the four[n]major archangels.[n]His name means[n]"Flame of God,"[n]and he knows all[n]the celestial[n]phenomena. He is[n]the first angel[n]Satan met on earth.[n][e]

[msg myth_018]
[s]The Hindu goddess[n]of rivers, and[n]patron of speech,[n]writing, learning,[n]the arts, and[n]sciences. Brahma[n]is her husband.[n][e]

[msg myth_019]
[s]"Choosers of the[n]slain" in Norse[n]lore. Armed with[n]shining armor and[n]swords, they look[n]for brave warriors[n]to take to Valhalla,[n]so that they may[n]fight in Ragnarok.[n][e]

[msg myth_020]
[s]A female demon in[n]Hindu lore. Though[n]originally a Dravidian[n]fertility goddess, the[n]spread of Hinduism[n]changed perception[n]of her to a demonic[n]figure. Usually[n]depicted as a nude,[n]voluptuous, female.[n][e]

[msg myth_021]
[s]The Hindu elephant-[n]headed god. He was[n]originally created by[n]Parvati in order to[n]prevent anyone from[n]watching her bathe.[n]Shiva batted off his[n]original head and[n]replaced it with an[n]elephant's head.[n][e]

[msg myth_022]
[s]The jackal-headed[n]god of the dead and[n]embalming from[n]Egyptian myth. He[n]weighs the hearts[n]of the dead to[n]determine their[n]final destination.[n][e]

[msg myth_023]
[s]The Canaanite god[n]of death. Every[n]year he attempts[n]to kill Baal, the[n]god of fertility,[n]only to see him[n]raised from the[n]dead with the help[n]of Baal's sister,[n]Anat.[n][e]

[msg myth_024]
[s]One of the four[n]major archangels,[n]his name means[n]"healer." He recites[n]the history of the[n]fallen angels and[n]the creation of[n]Adam and Eve.[n][e]

[msg myth_025]
[s]A warrior woman[n]of the Land of[n]Shadows in Celtic[n]lore. She taught the[n]hero, Cu Chulainn,[n]the art of war and[n]gave him the spear,[n]Gae Bolg.[n][e]

[msg myth_026]
[s]The leader of a[n]swarm of pixies.[n]Any pixie in a[n]leadership role[n]or with remarkable[n]power is called by[n]this name.[n][e]

[msg myth_027]
[s]A mystical creature[n]in Balinese lore,[n]it represents good[n]and is Rangda's[n]eternal rival.[n]Even if defeated,[n]it will be reborn.[n]The result is a[n]never-ending[n]struggle...[n][e]

[msg myth_028]
[s]A giant elephant[n]monster of Sri[n]Lankan myth, it is[n]typically portrayed[n]as being ridden by[n]the Evil One, Mara.[n]Whoever looks into[n]its evil eye is said[n]to be met with[n]misfortune.[n][e]

[msg myth_029]
[s]The king of snow[n]who rules over an[n]infinite number of[n]Jack Frosts. He has[n]the power to freeze[n]the entire world,[n]but is unaware of[n]it due to his naïve[n]personality.[n][e]

[msg myth_030]
[s]A young man of[n]Greek myth. He[n]rejected the nymph[n]Echo, who faded to[n]a whisper out of[n]despair. Cursed by[n]Nemesis, he fell[n]in love with his[n]own reflection and[n]wasted away.[n][e]

[msg myth_031]
[s]Osiris's wife as[n]well as his younger[n]sister. Upon the[n]death of her husband,[n]she revived him with[n]her incredible magic[n]power. Isis is seen[n]at many gravesites[n]as the guardian[n]goddess of the dead.[n][e]

[msg myth_032]
[s]A serpentine[n]woman of Greek[n]myth, she was once[n]the queen of Libya.[n]Zeus's jealous wife,[n]Hera, killed her[n]children, causing[n]her to go mad and[n]transform into[n]a monster.[n][e]

[msg myth_033]
[s]The spirit who[n]said, "For we are[n]many," in ancient[n]scriptures. The[n]name comes from[n]the Roman military[n]term for an army[n]unit of 3,000 to[n]6,000 men.[n][e]

[msg myth_034]
[s]A Hindu demon. He[n]is an enemy of the[n]gods and attacks[n]humans to feed off[n]of them. His hideous[n]appearance strikes[n]fear into those who[n]see him. Rakshasa[n]shape-shifts to[n]deceive his enemies.[n][e]

[msg myth_035]
[s]Evil spirits of[n]Murngin lore[n]believed to be[n]reborn shadows.[n]They kidnap and[n]eat children, and[n]strike down any[n]sorcerer who uses[n]black magic.[n][e]

[msg myth_036]
[s]One of the 72[n]demons of the[n]Goetia, he appears[n]as a great sea[n]monster. Known as[n]the great Marquis of[n]Hell, he is skilled[n]linguistically, and is[n]a master of rhetoric.[n][e]

[msg myth_037]
[s]A brave young man[n]in Celtic myth.[n]After defeating a[n]fierce guard dog, he[n]volunteered to take[n]its place, earning[n]him the nickname[n]"Hound of Culann."[n][e]

[msg myth_038]
[s]The queen of the[n]fairies and Oberon's[n]wife. She is derived[n]from the Roman[n]goddess Diana.[n]She was later[n]immortalized in[n]Shakespeare's play[n]"A Midsummer Night's[n]Dream."[n][e]

[msg myth_039]
[s]A male demon of[n]European lore in[n]medieval times.[n]They visit sleeping[n]women and have[n]sexual intercourse[n]with them. The[n]resulting children[n]become witches[n]or wizards.[n][e]

[msg myth_040]
[s]An evil monster[n]from Japanese lore[n]known for its[n]hideous appearance[n]and brute strength.[n]They loot and plunder[n]villages, massacring[n]the townspeople with[n]their iron clubs.[n][e]

[msg myth_041]
[s]Said to have been[n]Adam's first wife,[n]she desired to be[n]his equal and[n]refused to obey him.[n]She was cast out of[n]Eden and became a[n]demon of the night.[n]She is the mother of[n]the demoness, Lilim.[n][e]

[msg myth_042]
[s]A wicked witch of[n]Balinese lore, she[n]represents evil[n]and is Barong's[n]eternal rival.[n]Even if defeated,[n]she will come back[n]to life, and their[n]battle will have[n]no end.[n][e]

[msg myth_043]
[s]A divine wolf god[n]in Japanese folklore,[n]also written as[n]"Oguchi-no-Magami."[n]It is often drawn on[n]prayer boards to[n]prevent fires and[n]thefts, but it is[n]also feared as a[n]human-eater.[n][e]

[msg myth_044]
[s]A beautiful Hindu[n]goddess of love and[n]one of Shiva's wives.[n]Always by his side,[n]she played a role in[n]opening his third[n]eye. She can turn[n]into Durga or Kali[n]when angered.[n][e]

[msg myth_045]
[s]One of the four[n]major archangels.[n]She is also the only[n]female angel at this[n]rank. Her name comes[n]from the Sumerian[n]word for "governor."[n]She is the angel who[n]told Mary of her[n]pregnancy.[n][e]

[msg myth_046]
[s]Repeller of evil[n]found at Kinpusen[n]by En-no-Ozunu.[n]Believed to be a[n]fusion of Buddha,[n]Guanyin, and[n]Maitreya, he is a god[n]who originated from[n]Japan rather than[n]the Buddhavacana.[n][e]

[msg myth_047]
[s]A mysterious blonde[n]girl. She is quite[n]powerful, despite[n]her looks. Some say[n]she is the ghost of[n]a girl who died a[n]sad death. Others[n]say she is a spirit[n]born from someone's[n]imagination.[n][e]

[msg myth_048]
[s]A goddess of death[n]and destruction. She[n]is said to be another[n]face of Parvati. She[n]is violent, wears a[n]string of skulls,[n]and carries bloody[n]weapons, but she[n]also blesses her[n]followers.[n][e]

[msg myth_049]
[s]A type of tengu said[n]to have lived on Mt.[n]Kurama in Kyoto. The[n]most powerful and[n]well-known of the[n]tengu, they have the[n]power to fend off[n]disease and bring[n]good fortune.[n][e]

[msg myth_050]
[s]The king of the[n]fairies and Titania's[n]husband. He is quite[n]old, but due to a[n]curse, his looks are[n]that of a young boy.[n]He often flirts with[n]human women, ending[n]in a scolding from[n]his wife.[n][e]

[msg myth_051]
[s]An exceptionally[n]powerful shikigami.[n]Only the most elite[n]onmyoji are able to[n]summon and bind it[n]to paper. It can ward[n]off disaster or cure[n]illness, but its[n]ordinary temperament[n]is quite vicious.[n][e]

[msg myth_052]
[s]A giant snake with[n]eight heads that[n]Susano-o defeated to[n]save Kushinada-Hime.[n]The legendary sword[n]Ame-no-Murakumo-no-[n]Tsurugi, also known[n]as the "Sword of[n]Kusanagi," emerged[n]from its belly.[n][e]

[msg myth_053]
[s]One of the 72 demons[n]of the Goetia. Known[n]as the Prince of Hell,[n]he appears as a horse[n]and answers questions[n]of the past, present,[n]and future. He is faithful[n]to his conjurer.[n][e]

[msg myth_054]
[s]A monkey god of[n]Hindu descent. His[n]father is Vayu, the[n]wind god. Extremely[n]nimble, he performed[n]many heroic deeds in[n]the Ramayana. He is[n]powerful, can fly, and[n]can change his shape[n]into many forms.[n][e]

[msg myth_055]
[s]Eighth of the nine[n]orders of angels.[n]Their duty is to[n]minister to humans[n]and deliver messages.[n]They are warriors of[n]Heaven and lead[n]Heaven's forces[n]during battle with[n]the armies of evil.[n][e]

[msg myth_056]
[s]A "piggyback[n]monster" of Japan[n]that jumps on the[n]backs of those who[n]pass grassy paths.[n]It is heavy and not[n]easily removed, but[n]will turn into gold[n]coins if you can[n]carry it back home.[n][e]

[msg myth_057]
[s]The fairy queen in[n]Celtic myth. Often[n]identified with[n]Titania. She would[n]offer mead mixed[n]with her blood to[n]her many consorts.[n][e]

[msg myth_058]
[s]Metatron's twin[n]brother in Judeo-[n]Christian lore, he[n]is the master of[n]heavenly songs.[n]It is said that a[n]human would take[n]500 years to walk[n]the length of his[n]body.[n][e]

[msg myth_059]
[s]The "Destroyer"[n]and "Angel of the[n]Bottomless Pit,"[n]as described in[n]ancient scriptures.[n]He controls locusts[n]and uses them to[n]cause massive[n]destruction to[n]villages.[n][e]

[msg myth_060]
[s]A holy beast said[n]to protect houses[n]from evil and bring[n]good fortune. They[n]look similar to Shinto[n]guardian dogs, but[n]are actually modeled[n]after a lion. There[n]are many stories about[n]it in Ryukyu lore.[n][e]

[msg myth_061]
[s]A fairy in German[n]folklore who carries[n]a bag of magical[n]sand, which puts[n]humans to sleep[n]when thrown into[n]their eyes. If the[n]victim resists, the[n]Sandman will sit[n]on their eyelids.[n][e]

[msg myth_062]
[s]One of the 72[n]demons of the[n]Goetia. He led[n]Sodom and[n]Gomorrah to ruin[n]and persecuted[n]Jesus. He grants[n]high social status[n]to those who[n]summon him.[n][e]

[msg myth_063]
[s]A beautiful fairy[n]of Irish lore that[n]yearns for the love[n]of a human man. She[n]drains the life of[n]her lovers in return[n]for granting them[n]artistic inspiration.[n][e]

[msg myth_064]
[s]The Phrygian mother[n]goddess of the earth,[n]she is often depicted[n]with wild animals, and[n]lions in particular.[n]She had her priest,[n]Attis, as a lover, but[n]drove him insane when[n]he was forced to[n]marry another.[n][e]

[msg myth_065]
[s]A cursed god of[n]death, evil, and the[n]night in Slavic lore.[n]His name means[n]"Black God," and he[n]is the counterpart[n]of the "White God,"[n]Belobog. Despite[n]being feared, he was[n]also worshipped.[n][e]

[msg myth_066]
[s]One of the 72 demons[n]of the Goetia. He[n]appears as a leopard[n]and can see the past[n]and future. He can[n]control fire and burn[n]all his adversaries[n]to death.[n][e]

[msg myth_067]
[s]A one-eyed, one-[n]legged monster[n]said to live deep in[n]the mountains of[n]Kumano, Japan. It's[n]believed to be the[n]degraded blacksmith[n]god, Ame no Me-[n]Hitotsu no Kami.[n][e]

[msg myth_068]
[s]The two-headed pet[n]dog belonging to[n]the giant, Geryon,[n]in Greek myth. He[n]guarded a herd of[n]red oxen, but was[n]killed by Hercules[n]during one of his[n]twelve labors.[n][e]

[msg myth_069]
[s]A female demon of[n]European lore in[n]medieval times.[n]They visit sleeping[n]men and have sexual[n]intercourse with[n]them. The victims[n]don't wake up but[n]may dream of the[n]encounter.[n][e]

[msg myth_070]
[s]A cryptid sighted[n]during the 60s-80s[n]in West Virginia. It[n]has shining red eyes[n]and is named for the[n]fin-like appendages[n]on its sides. It uses its[n]keen sense for blood[n]to track down the[n]source and feed on it.[n][e]

[msg myth_071]
[s]Taira no Masakado,[n]hero of the Heian[n]period. He claimed[n]the title "Shinno"[n](New Emperor) and[n]rebelled against[n]the government. He[n]was killed, but it[n]is said he became[n]a demigod.[n][e]

[msg myth_072]
[s]The fourth of the[n]nine orders of[n]angels. Their duty[n]is to oversee the[n]other angels. Their[n]actions are the[n]manifestation of[n]God's will.[n][e]

[msg myth_073]
[s]Long-lived cats[n]are said to become[n]these malevolent[n]cat demons. Their[n]powers vary[n]according to how[n]long they have[n]lived, ranging from[n]shape-shifting to[n]controlling the dead.[n][e]

[msg myth_074]
[s]A Jack Frost that[n]yearned for evil.[n]This powerful demon[n]is born when a[n]cute Jack Frost[n]remembers its[n]nature as a demon.[n][e]

[msg myth_075]
[s]A mysterious god of[n]ancient Japan. Most[n]famously worshipped[n]by Nagasunehiko, who[n]was defeated in battle[n]against Emperor Jinmu,[n]Arahabaki came to be[n]treated as a symbol of[n]rebellion and defiance.[n][e]

[msg myth_076]
[s]Ninth of the nine[n]orders of angels.[n]They are closest in[n]nature to humans.[n]They watch over[n]individuals and warn[n]those who stray[n]from the path.[n][e]

[msg myth_077]
[s]A Norse giantess[n]called the "snow-[n]shoe goddess" and[n]the embodiment of[n]winter. According to[n]legend, all the gods[n]will return to her at[n]the end of Ragnarok.[n][e]

[msg myth_078]
[s]The goddess of life[n]in Shinto myth. She[n]once mediated[n]between Izanagi[n]and Izanami during[n]their confrontation[n]in Yomi, the land[n]of the dead.[n][e]

[msg myth_079]
[s]A Chinese god of[n]war, he is said to[n]have invented many[n]weapons. He and[n]his followers[n]rebelled against[n]the Yellow Emperor,[n]Huang Di, but were[n]ultimately defeated.[n][e]

[msg myth_080]
[s]The sixth of the[n]nine orders of[n]angels. It is said[n]that they were the[n]first order to be[n]created. Their[n]duty is to protect[n]human souls from[n]demons.[n][e]

[msg myth_081]
[s]A dog spirit said to[n]possess people in[n]Japanese lore.[n]Those possessed[n]are in a state of[n]"inu-tsuki" and[n]lose consciousness.[n]Onmyoji use Inugami[n]as familiars.[n][e]

[msg myth_082]
[s]The general of Hell.[n]He keeps watch over[n]other demons. One[n]of Hell's greatest[n]necromancers, he[n]can control souls[n]and corpses.[n][e]

[msg myth_083]
[s]Among the eight[n]Yashaou and one[n]of Bishamonten's[n]attendants.[n]Originally a child-[n]eating demon, he[n]was converted by theBuddha and becamea protector figure.[n][e]

[msg myth_084]
[s]A primitive monster[n]with a viscous body.[n]There are various[n]theories as to its[n]origin, but it is[n]still under debate.[n]Said to compulsively[n]collect shiny objects.[n][e]

[msg myth_085]
[s]An evil deity of[n]Mesopotamian[n]folklore with[n]an eagle's body[n]and lion's head.[n]While the god Enlil[n]purified himself,[n]Anzu stole the[n]Tablets of Destiny[n]from him.[n][e]

[msg myth_086]
[s]A divine creature in[n]Japanese lore. They[n]are three-legged[n]birds sent by[n]Amaterasu to help[n]humans. They are[n]said to have helped[n]Emperor Jinmu claim[n]victory.[n][e]

[msg myth_087]
[s]A Japanese general[n]of the Genpei War[n]near the end of the[n]Heian era and start of[n]the Kamakura era. His[n]bold ingenuity and[n]ruthless skill with a[n]blade are still praised[n]in Japan today.[n][e]

[msg myth_088]
[s]A Japanese god of[n]war, hunting, and[n]fertility. He fought[n]Take-Mikazuchi for[n]control of Japan and[n]lost. He escaped[n]to Suwa, but was[n]prohibited to leave[n]since.[n][e]

[msg myth_089]
[s]Japanese goddess[n]of entertainment,[n]she governs many[n]sacred dances. She[n]is most famous for[n]luring out Amaterasu,[n]who had barricaded[n]herself inside a cave.[n][e]

[msg myth_090]
[s]A Japanese goddess.[n]She governs fields[n]and fertility. All[n]of her sisters were[n]sacrificed to[n]Yamata-no-Orochi,[n]but she was saved[n]by Susano-o and[n]became his wife.[n][e]

[msg myth_091]
[s]A Buddhist demon[n]said to drain human[n]life energy. He has[n]dark skin, stands 3[n]meters tall, and[n]sometimes changes[n]his shape to a gourd.[n]Known to have once[n]served Rudra, the[n]god of storms.[n][e]

[msg myth_092]
[s]One of the four[n]oni controlled by[n]Fujiwara no Chikata.[n]By eliminating its[n]aura and preventing[n]others from sensing[n]its presence, it is[n]able to surprise its[n]enemies.[n][e]

[msg myth_093]
[s]One of the four oni[n]controlled by[n]Fujiwara no Chikata,[n]its body is so hard[n]that no weapons[n]can penetrate it.[n]It and its comrades[n]fell into hell through[n]holes that can still be[n]found in modern Iga.[n][e]

[msg myth_094]
[s]One of the four[n]oni controlled by[n]Fujiwara no Chikata,[n]it can cause floods[n]with the swing of its[n]arms. In the Taiheiki,[n]Ki no Tomoo expelled[n]the oni by reading a[n]Japanese poem.[n][e]

[msg myth_095]
[s]One of the four oni[n]controlled by[n]Fujiwara no Chikata,[n]it sends hurricanes[n]to blow away its[n]enemies. Some say[n]that Fuu-ki is the[n]original ninja.[n][e]

[msg myth_096]
[s]The Hindu king[n]of birds. In the[n]Ramayana, he[n]fought bravely[n]against Ravana[n]in an attempt to[n]save Sita, Rama's[n]wife and the 7th[n]avatar of Vishnu,[n]but lost.[n][e]

[msg myth_097]
[s]A god in Assyrian[n]legend, his name[n]is interchangeable[n]with Sakkut,[n]another incarnation[n]of the star-god,[n]Saturn.[n][e]

[msg myth_098]
[s]A horse-like fairy[n]of Celtic folklore[n]that lives by the[n]water. It drowns[n]those who ride on[n]it, but is a valuable[n]mount if you can[n]tame it.[n][e]

[msg myth_099]
[s]Egyptian moon god[n]that takes the[n]form of a baboon,[n]he is the one who[n]measures time. He[n]gave Isis the power[n]to resurrect Osiris[n]after he was killed[n]by the evil god Seth.[n][e]

[msg myth_100]
[s]The Greek god of[n]wine and theater. He[n]was originally a god[n]of life protecting[n]the mountains of[n]Thrace. He taught[n]humans how to make[n]wine.[n][e]

[msg myth_101]
[s]Hindu water spirits,[n]they are beautiful[n]young women who[n]dance for the gods.[n]They also guide[n]heroes fallen in[n]battle to paradise.[n][e]

[msg myth_102]
[s]One of the 72[n]demons of the[n]Goetia. The great[n]Marquis of Hell, he[n]appears where there[n]is battle to stoke the[n]hatred within soldiers.[n]He helps defeat the[n]enemies of those[n]who summon him.[n][e]

[msg myth_103]
[s]BLANK[n][e]

[msg myth_104]
[s]Small human-like[n]creatures, that[n]have kind, calm[n]personalities. Once[n]coexisting with the[n]Ainu people of Japan,[n]there was a falling[n]out at some point,[n]and they disappeared.[n][e]

[msg myth_105]
[s]A type of tengu.[n]Their spiritual[n]power is weaker than[n]other tengu, so they[n]are much smaller.[n]They are said to be[n]the reincarnations[n]of long-lived wolves.[n][e]

[msg myth_106]
[s]A bluish-tinged[n]diamond that[n]Napoléon Bonaparte[n]had mounted to the[n]pommel of his sword.[n]It was named after[n]the French Regent[n]Philippe II, Duke of[n]Orléans, who had[n]purchased it in 1717.[n][e]

[msg myth_107]
[s]The diamond[n]necklace that[n]Jeanne de la Motte[n]swindled from[n]jewelers in 1785 by[n]claiming it was on[n]behalf of the Queen[n]of France, Marie[n]Antoinette.[n][e]

[msg myth_108]
[s]Also known as the[n]Stone of Destiny,[n]it is a stone used[n]in the coronations[n]of Scotland's[n]monarchs. Legends[n]say the stone is[n]linked to angels.[n][e]

[msg myth_109]
[s]Once called the[n]world's largest[n]diamond, it was cut[n]when it came to[n]the British royal[n]family. It is said to[n]bring bad luck to any[n]man who wears it,[n]so only the females[n]have ever adorned it.[n][e]

[msg myth_110]
[s]A diamond stolen[n]from a Hindu[n]temple that is[n]said to drive its[n]owner to their[n]death. It was cut[n]into smaller pieces[n]in an attempt to[n]break the curse.[n][e]

[msg myth_111]
[s]Also known as[n]Charlemagne's[n]talisman, it is said[n]to make its owner an[n]emperor. In between[n]the two gems is a[n]piece of Jesus'[n]cross and a hair of[n]the Virgin Mary.[n][e]

[msg myth_112]
[s]Unlike its name[n]suggests, the Hope[n]Diamond is a cursed[n]jewel that brings[n]ruin from one owner[n]to the next. A few[n]supposed victims[n]include King Louis[n]XVI and his wife,[n]Marie Antoinette.[n][e]

[msg myth_113]
[s]An ancient Out-Of-[n]Place-Artifact found[n]in Central and[n]South America. It is[n]said that if you[n]collect 13 of them in[n]one spot, the truth[n]of the universe[n]will be revealed.[n][e]

[msg myth_114]
[s]A metal mentioned[n]in ancient Greek[n]literature. Some[n]accounts say it was[n]merely brass, but[n]other stories suggest[n]it was, in fact, a[n]legendary material.[n][e]

[msg myth_115]
[s]BLANK[n][e]

[msg myth_116]
[s]BLANK[n][e]

[msg myth_117]
[s]BLANK[n][e]

[msg myth_118]
[s]BLANK[n][e]

[msg myth_119]
[s]BLANK[n][e]

[msg myth_120]
[s]BLANK[n][e]

[msg myth_121]
[s]A magical plant[n]whose roots look[n]like a human. They[n]are valued for their[n]healing properties[n]in potions, but the[n]screams they let out[n]when pulled from the[n]ground will kill[n]anyone who hears them.[n][e]

[msg myth_122]
[s]The chief Semitic[n]god who governs[n]over fertility. He is[n]the god of Canaan[n]and brother and[n]consort to the[n]goddess Anat, who[n]saved him from Mot.[n][e]

[msg myth_123]
[s]Hindu deities[n]of passion and[n]relations. They are[n]Kali's attendants.[n]They eat human[n]flesh and gather[n]at graveyards and[n]crematories each[n]night. Their name[n]means "sky dancer."[n][e]

[msg myth_124]
[s]A fairy of England[n]and Scotland.[n]She carries out[n]household chores[n]while everyone[n]sleeps and is a[n]welcome spirit. It[n]is said you can hear[n]her silk skirt rustle[n]as she works.[n][e]

[msg myth_125]
[s]A Welsh creature[n]commonly known as[n]"Bugbear" or the[n]"Boogeyman." Its[n]existence is often[n]used by mothers to[n]scare children into[n]behaving.[n][e]

[msg myth_126]
[s]A mass of malevolent[n]intent and emotion[n]that failed to become[n]a true demon. All it[n]does is eat prey[n]and grow.[n][e]

[msg myth_127]
[s]An evil creature[n]with two curving[n]horns. It represents[n]impurity, unlike[n]the Unicorn. Said[n]to be derived from[n]Re'em in the Bible.[n]Another legend says[n]that it feeds off of[n]disloyal husbands.[n][e]

[msg myth_128]
[s]A sun deity who was[n]worshipped in the[n]Roman Empire from[n]the 1st to the 4th[n]century AD. He was[n]said to be reborn[n]after death, and a[n]festival was held on[n]the winter solstice[n]for him.[n][e]

[msg myth_129]
[s]A spirit of rivers[n]and mountains in[n]Japanese lore, they[n]dwell in ancient[n]trees and ageless[n]rocks. They are not[n]evil, and will often[n]appear as humans or[n]supernatural wonders[n]to warn people.[n][e]

[msg myth_130]
[s]Japanese plant[n]spirits born from[n]trees that have[n]lived for a 100[n]years. Cutting down[n]one of these trees[n]is said to cause[n]misfortune.[n][e]

[msg myth_131]
[s]A general term for[n]familiars used by[n]Judeo-Christian[n]magicians, they are[n]usually sealed away[n]in bottles, rings,[n]or talismans. They[n]torment the target[n]selected by the[n]conjuror.[n][e]

[msg myth_132]
[s]A monstrous, fire[n]spitting, Japanese[n]bird with a man's[n]face. It is actually[n]a corpse that was[n]not given a proper[n]memorial service.[n]They appear before[n]monks who neglect[n]their duties.[n][e]

[msg myth_133]
[s]A creature of[n]Japanese lore with[n]a monkey's head,[n]tiger's legs, and[n]snake's tail. The[n]Tale of Heike says[n]it hid behind a dark[n]cloud each night to[n]attack the Emperor.[n][e]

[msg myth_134]
[s]A type of preta, or[n]"hungry ghost," in[n]Hindu lore that eats[n]human corpses. It[n]enters a human[n]through the mouth[n]and causes harm.[n]Those who see one[n]are said to die[n]within nine months.[n][e]

[msg myth_135]
[s]An angel of[n]Gnosticism,[n]governing over[n]peace and[n]righteousness.[n]Though said to be[n]the savior of the[n]angels, he used[n]to be a human,[n]the king of Salem.[n][e]

[msg myth_136]
[s]A goat-headed[n]demon that is[n]worshipped in Black[n]Sabbaths. His name[n]can be used as[n]a catch-all term for[n]demons in general.[n]He would become an[n]object of worship[n]for witches.[n][e]

[msg myth_137]
[s]The king of the[n]Naga, a half-man,[n]half-snake tribe[n]in Hindu lore. The[n]dragon kings Nanda[n]and Takshaka of[n]Buddhist myth fall[n]into this royal[n]category.[n][e]

[msg myth_138]
[s]Half-snake, half-[n]human divine beings[n]in Hindu lore,[n]worshipped as[n]bringers of rain.[n]They live in the[n]bottoms of lakes and[n]seas, singing and[n]dancing when they[n]are not fighting.[n][e]

[msg myth_139]
[s]A divine bird-man[n]in Hindu lore, he[n]once fought the[n]gods and received[n]immortality in[n]exchange for[n]becoming Vishnu's[n]carrier.[n][e]

[msg myth_140]
[s]A Canaanite god[n]of fire. A bronze[n]statue of a man[n]with a bull's head[n]stands at an altar.[n]Sacrificial children[n]were thrown into[n]the statue after[n]it was heated.[n][e]

[msg myth_141]
[s]Goddesses of fate[n]in Norse lore. They[n]live below the roots[n]of Yggdrasil and[n]weave the threads of[n]fate, which even the[n]gods are bound by.[n][e]

[msg myth_142]
[s]Demonic governor[n]of the deadly sin[n]of sloth. He also[n]excels at invention[n]and discovery. May[n]derive from Ba'al[n]Pe'or, Syrian god[n]of abundant crops.[n][e]

[msg myth_143]
[s]One of the 72[n]demons of the[n]Goetia. Known[n]as the Duke of[n]Hell, he rides[n]a gigantic horse[n]and burns those[n]without manners.[n][e]

[msg myth_144]
[s]A demon summoned[n]by a sorcerer[n]named Crowley at[n]the beginning of[n]the 20th century.[n]He obstructs those[n]attempting to[n]reach enlightenment.[n][e]

[msg myth_145]
[s]BLANK[n][e]

[msg myth_146]
[s]BLANK[n][e]

[msg myth_147]
[s]BLANK[n][e]

[msg myth_148]
[s]BLANK[n][e]

[msg myth_149]
[s]BLANK[n][e]

[msg myth_150]
[s]BLANK[n][e]

[msg myth_151]
[s]One of the four[n]aspects of Shinto[n]thought, it works[n]gently to help[n]maintain a calm mind.[n]It is said to aid in[n]one's relations and[n]sociability, and can[n]lead one in a[n]positive direction.[n][e]

[msg myth_152]
[s]One of the four[n]aspects of Shinto[n]thought, it uses its[n]power to bring good[n]omens. It is said to[n]aid in one's wisdom,[n]observation, and[n]skill, and can mend[n]fractured paths.[n][e]

[msg myth_153]
[s]One of the four[n]aspects of Shinto[n]thought, it has the[n]power to grant[n]ferocity. It is said[n]to aid in one's[n]bravery, growth, and[n]endeavors, though it[n]can lead in a[n]negative direction.[n][e]

[msg myth_154]
[s]One of the four[n]aspects of Shinto[n]thought, it brings[n]great bounty from[n]the hunt. It is said[n]to aid in love,[n]profit, and growth,[n]and can create new[n]paths.[n][e]

[msg myth_155]
[s]The Arabian mother[n]goddess also known[n]as Allat. She was[n]thought to reside in[n]the Black Stone at[n]the Kaaba. She and[n]her son, Dusura,[n]were worshipped[n]there by desert[n]nomads.[n][e]

[msg myth_156]
[s]One of the major[n]Hindu gods, he is[n]known as the[n]Destroyer but is[n]also related to[n]regeneration. His[n]wife is Parvati.[n][e]

[msg myth_157]
[s]One of the four[n]major archangels,[n]he is at the top of[n]the angelic hierarchy.[n]He carries a long[n]spear that can cut[n]through anything,[n]and his name means[n]"One Who Is Like God."[n][e]

[msg myth_158]
[s]The Hindu king of[n]Asuras is named[n]Maha Vairocana, or[n]"One Who Shines On[n]All." In Buddhism, he[n]is known as Dainichi[n]Nyorai.[n][e]

[msg myth_159]
[s]A giant Hindu[n]monster. Its mouth[n]is so enormous it[n]can swallow the Earth[n]and the heavens in[n]one bite. Its name[n]means "He who[n]intoxicates."[n][e]

[msg myth_160]
[s]The fiend known as[n]the "Whore of[n]Babylon," riding a[n]beast with seven[n]heads and ten[n]horns, she carries[n]a golden cup of[n]abominations and[n]the filth of her acts.[n][e]

[msg myth_161]
[s]The youngest of[n]the three Moirae[n]Sisters of Greek[n]legend. She spins[n]the threads of[n]life with her[n]spindle.[n][e]

[msg myth_162]
[s]The middle sister[n]of the three Moirae[n]Sisters of Greek[n]legend. She is[n]the apportioner,[n]measuring the[n]thread which[n]determines each[n]person's lifespan.[n][e]

[msg myth_163]
[s]The eldest of[n]the three Moirae[n]Sisters of Greek[n]mythology. She[n]cuts the threads[n]of life for those[n]whose time has[n]come.[n][e]

[msg myth_164]
[s]A god of dual gender[n]whose appearance is[n]half that of the[n]destroyer, Shiva,[n]and half his wife,[n]Parvati. Ardha is[n]the ideal figure of[n]Shaktism, the[n]perfect god.[n][e]

[msg myth_165]
[s]BLANK[n][e]

[msg myth_166]
[s]One of the major[n]Hindu gods, he is[n]the preserver and[n]protector of the[n]universe. Legends[n]claim that he will[n]make ten appearances[n]across time and space[n]to strike down evil[n]and uphold justice. [n][e]

[msg myth_167]
[s]Also known as[n]Kishimojin, she[n]once ate children,[n]but stopped after[n]Buddha changed her[n]ways. She now eats[n]pomegranates and[n]is a goddess of[n]parenting.[n][e]

[msg myth_168]
[s]A snake with a[n]rainbow body from[n]Murngin lore. He is[n]a fertility deity[n]who controls the[n]weather and resides[n]in a holy pond filled[n]with rainbow-colored[n]water.[n][e]

[msg myth_169]
[s]Giants born from[n]Uranus and Gaia.[n]The name means[n]"those with a[n]hundred arms."[n]During the war of[n]the Titans, Zeus[n]freed them from the[n]Underworld to help[n]him obtain victory.[n][e]

[msg myth_170]
[s]An archangel who is[n]said to be the form[n]of Satan before he[n]fell from Heaven.[n]The second son of[n]God, he rebelled[n]against Him for[n]freedom and bestowed[n]free will and chaos[n]upon humanity.[n][e]

[msg myth_171]
[s]BLANK[n][e]

[msg myth_172]
[s]BLANK[n][e]

[msg myth_173]
[s]BLANK[n][e]

[msg myth_174]
[s]BLANK[n][e]

[msg myth_175]
[s]BLANK[n][e]

[msg myth_176]
[s]BLANK[n][e]

[msg myth_177]
[s]BLANK[n][e]

[msg myth_178]
[s]BLANK[n][e]

[msg myth_179]
[s]BLANK[n][e]

[msg myth_180]
[s]RESERVE[n]Mythology[n][e]

[msg myth_181]
[s]A Persona of another[n]story. A poet skilled[n]with the lyre. He[n]tried to retrieve[n]his wife from Hades,[n]but she vanished[n]when he looked back[n]before reaching[n]the surface.[n][e]

[msg myth_182]
[s]A Persona of another[n]story. The Greek god[n]of death, he is the[n]son of Nyx and the[n]twin brother of[n]Hypnos. He is known[n]to provide mortals[n]with a peaceful[n]death.[n][e]

[msg myth_183]
[s]A Persona of another[n]story. One of the[n]ancient gods who[n]existed before Japan[n]was formed. He created[n]the Oyashima from[n]chaos, then gave birth[n]to countless children[n]and laid the foundation[n]of soil and nature.[n][e]

[msg myth_184]
[s]A Persona of another[n]story. He is Izanagi's[n]rival and looks just[n]like him. Magatsu[n]means "calamity."[n]Unlike Izanagi, who[n]founded the land and[n]brought order, he[n]leads all back into[n]chaos.[n][e]

[msg myth_185]
[s]A Persona of another[n]story. A divine being[n]born from a glowing[n]bamboo shoot. Though[n]many proposed to her,[n]none could complete[n]her strict tasks. She[n]eventually returned[n]to her home, the moon.[n][e]

[msg myth_186]
[s]A Persona of another[n]story. She is the[n]daughter of Minos,[n]the king of Crete.[n]She helped Theseus[n]defeat the Minotaur[n]and gave him a ball[n]of yarn so he could[n]escape the labyrinth.[n][e]

[msg myth_187]
[s]A Persona of another[n]story. Due to a[n]curse on his mother,[n]Pasiphae, he was born[n]a bull-headed monster.[n]Locked away in the[n]labyrinth as the[n]Minotaur, he wielded[n]a double-sided axe.[n][e]

[msg myth_188]
[s]A Persona of another[n]story. An important[n]god born from the[n]Japanese god Izanagi,[n]he governs over the[n]moon and the night.[n]There are many[n]theories behind this[n]mysterious god.[n][e]

[msg myth_189]
[s]A Persona of another[n]story. He appears[n]before Judgment Day[n]to save the virtuous.[n]He is a universal[n]figure, appearing in[n]myths around the[n]world. Many stories[n]involve his death[n]and rebirth.[n][e]

[msg myth_190]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]He appears before[n]Judgment Day to[n]save the virtuous.[n]He is a universal[n]figure, appearing[n]in myths around[n]the world.[n][e]

[msg myth_191]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]A Greek poet who[n]tried to retrieve[n]his wife from Hades,[n]but she vanished[n]when he looked back[n]before reaching[n]the surface.[n][e]

[msg myth_192]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]The Greek god of[n]death, he is the son[n]of Nyx and the twin[n]brother of Hypnos.[n]He is known to[n]provide mortals with[n]a peaceful death.[n][e]

[msg myth_193]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]One of the ancient[n]gods who existed[n]before Japan was[n]formed. He created the[n]Oyashima from chaos,[n]then gave birth to[n]countless children.[n][e]

[msg myth_194]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]He is Izanagi's rival.[n]Magatsu means[n]"calamity," so, unlike[n]Izanagi who founded[n]the land and brought[n]order, he leads all[n]back into chaos.[n][e]

[msg myth_195]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]She appeared from[n]a glowing bamboo[n]shoot. She received[n]many proposals, but[n]rejected them and[n]returned to the moon.[n][e]

[msg myth_196]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]She is the daughter[n]of Minos. She helped[n]Theseus defeat the[n]Minotaur and gave[n]him a ball of yarn[n]so he could escape[n]the labyrinth.[n][e]

[msg myth_197]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]Son of Pasiphae, he[n]was born a bull-[n]headed monster.[n]Locked away in the[n]labyrinth as the[n]Minotaur, he wielded[n]a double-sided axe.[n][e]

[msg myth_198]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]An important god born[n]from the Japanese god[n]Izanagi, he governs[n]over the moon and the[n]night. There are many[n]theories behind this[n]mysterious god.[n][e]

[msg myth_199]
[s]RESERVE[n]Mythology[n][e]

[msg myth_200]
[s]A being based off of[n]the main character[n]of Maurice Leblanc's[n]novels, Arsène[n]Lupin. He appears[n]everywhere and is a[n]master of disguise.[n]He is known to help[n]law-abiding citizens.[n][e]

[msg myth_201]
[s]A being based off of[n]the main character[n]of Maurice Leblanc's[n]novels, Arsène[n]Lupin. He appears[n]everywhere and is a[n]master of disguise.[n]He is known to help[n]law-abiding citizens.[n][e]

[msg myth_202]
[s]A 17th century[n]privateer who[n]eventually became a[n]world-renowned[n]pirate. At his[n]execution, he[n]declared he had[n]hidden treasure,[n]leaving behind many[n]legends.[n][e]

[msg myth_203]
[s]A masked swordsman[n]of justice who[n]fought in California[n]against corrupt[n]officials during the[n]era of Spanish rule.[n]He always left his[n]"Z" mark with his[n]rapier wherever he[n]appeared.[n][e]

[msg myth_204]
[s]A gypsy thief from[n]the novel by Merimee,[n]which became famous[n]through the opera by[n]Bizet. She is a femme[n]fatale who is beautiful[n]but also very capricious.[n][e]

[msg myth_205]
[s]Ishikawa Goemon was[n]a thief who stole[n]from the rich and[n]gave to the poor in[n]Japan during the[n]Azuchi-Momoyama[n]period. The kabuki[n]scene of him sitting[n]on the gate of[n]Nanzen-ji is famous.[n][e]

[msg myth_206]
[s]The mysterious female[n]pope of the Middle[n]Ages. She posed as a[n]man and eventually[n]made it all the way[n]up to pope due to her[n]unrivaled intellect.[n]Her existence shook[n]the history of the[n]Catholic church.[n][e]

[msg myth_207]
[s]The beautiful woman[n]that appears in[n]Dumas's "Three[n]Musketeers." Branded[n]with a fleur-de-lis[n]symbol, she used[n]many aliases to[n]control nobility[n]and get her[n]vengeance.[n][e]

[msg myth_208]
[s]The grimoire which[n]contains vital[n]information of the[n]Cthulhu mythos by[n]Lovecraft. Its[n]original name is Al[n]Azif. It is said the[n]book itself is alive.[n][e]

[msg myth_209]
[s]A noble thief that[n]made waves in[n]England during the[n]Middle Ages. He is[n]an expert archer and[n]leader of the Merry[n]Men, outlaws of[n]justice who made[n]Sherwood Forest their[n]home.[n][e]

[msg myth_210]
[s]RESERVE[n]Mythology[n][e]

[msg myth_211]
[s]An archangel who is[n]said to be the form[n]of Satan before he[n]fell from Heaven.[n]The second son of[n]God, he rebelled[n]against Him for[n]freedom and bestowed[n]free will and chaos[n]upon humanity.[n][e]

[msg myth_212]
[s]A title Sun Wukong[n]had given himself.[n]Born from a rock, he[n]wreaked havoc and was[n]punished by Buddha[n]who imprisoned him[n]under a mountain.[n]Eventually, he was[n]saved by a monk[n]named Xuanzang.[n][e]

[msg myth_213]
[s]The Roman god of[n]travelers and thieves.[n]A diverse god, he is[n]seen as a symbol of[n]the human unconscious[n]and the mental world.[n]He is equated with the[n]Philosopher's Stone,[n]the ultimate mystery[n]in the field of alchemy.[n][e]

[msg myth_214]
[s]A Greek goddess of[n]crossroads, ghosts,[n]and witchcraft, she[n]is commonly attended[n]to by dogs. She is[n]also known to be the[n]chief of the witches[n]that appear in the[n]play "Macbeth."[n][e]

[msg myth_215]
[s]A Japanese god found[n]in the Izumo Fudoki.[n]He was one of the[n]three gods born from[n]Izanagi. He was a[n]violent ruffian, but[n]also had a sensitive[n]side, showing love[n]for his mother and[n]reading poems.[n][e]

[msg myth_216]
[s]The daughter of[n]Ugaritic's highest[n]god El. She is the[n]goddess of fertility,[n]as well as hunting[n]and war. Her[n]characteristics are[n]the characteristics[n]of the seasons in[n]Canaan.[n][e]

[msg myth_217]
[s]A Middle Eastern[n]goddess of fertility.[n]Many scriptures note[n]her folklore, and[n]there is even a[n]mention of her as[n]the "Queen of Heaven"[n]in the Bible.[n][e]

[msg myth_218]
[s]The Greek Titan who[n]created mankind from[n]clay. He later stole[n]fire from Olympus and,[n]in turn, gave it to[n]mankind against Zeus's[n]will. His name is[n]often synonymous[n]with fire and[n]"divine knowledge."[n][e]

[msg myth_219]
[s]RESERVE[n]Mythology[n][e]

[msg myth_220]
[s]RESERVE[n]Mythology[n][e]

[msg myth_221]
[s]RESERVE[n]Mythology[n][e]

[msg myth_222]
[s]RESERVE[n]Mythology[n][e]

[msg myth_223]
[s]RESERVE[n]Mythology[n][e]

[msg myth_224]
[s]RESERVE[n]Mythology[n][e]

[msg myth_225]
[s]RESERVE[n]Mythology[n][e]

[msg myth_226]
[s]RESERVE[n]Mythology[n][e]

[msg myth_227]
[s]RESERVE[n]Mythology[n][e]

[msg myth_228]
[s]RESERVE[n]Mythology[n][e]

[msg myth_229]
[s]RESERVE[n]Mythology[n][e]

[msg myth_230]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_231]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_232]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_233]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_234]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_235]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_236]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_237]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_238]
[s]RESERVE231[n]Mythology[n][e]

[msg myth_239]
[s]A malignant god of[n]Norse mythology.[n]Not always driven by[n]malice, but impulsive[n]and devious. He had[n]an uneasy peace with[n]Odin and the gods,[n]but his part in Baldr's[n]death drove them to[n]finally punish him.[n][e]

[msg myth_240]
[s]The French name of[n]the titular heroine of[n]Cinderella, an oft-[n]retold tale of great[n]renown in which a[n]mistreated waif gains[n]luxury, beauty, and[n]a single night's dance[n]with a prince through[n]the power of magic.[n][e]

[msg myth_241]
[s]The true name of[n]Freyja, of the Norse[n]Vanir deities. Younger[n]twin sister of Freyr.[n]Her name means "dís[n]of the Vanir"—dís[n]being a goddess.[n]Known to be a great[n]beauty and a witchlike[n]master of magic.[n][e]

[msg myth_242]
[s]The other name of[n]Captain Kidd, world-[n]renowned pirate.[n]For years after his[n]death, songs and[n]legends of his life[n]inspired many to[n]chase rumors of his[n]buried treasure[n]across the seas.[n][e]

[msg myth_243]
[s]The true name of[n]California's masked[n]swordsman of justice,[n]who fought corrupt[n]officials during the[n]era of Spanish rule.[n]Despite being marked[n]as a thief, he fought[n]for the weak as a[n]true gentleman.[n][e]

[msg myth_244]
[s]A beautiful actress[n]who performed as[n]Carmen in the opera[n]named for the role.[n]So tempestuous and[n]outspoken was she[n]that it's said the main[n]role was rewritten to[n]better suit her.[n][e]

[msg myth_245]
[s]Childhood nickname[n]of Goemon Ishikawa.[n]During his youth,[n]he was raised among[n]the Iga-ryu ninjas[n]before he set off on[n]his own to become[n]a rogue ninja.[n][e]

[msg myth_246]
[s]Another name of[n]Johanna, the female[n]pope of the Middle[n]Ages. Posing as a[n]man, her wits and[n]ability helped her[n]climb the ranks. Her[n]story shook the[n]Catholic church to[n]its core.[n][e]

[msg myth_247]
[s]The Countess of[n]Carlisle, and the[n]historical basis for[n]Alexandre Dumas's[n]femme fatale, Milady[n]de Winter. Known[n]for her beauty and[n]cunning, she was a[n]courtier much[n]favored by the Queen.[n][e]

[msg myth_248]
[s]The original name of[n]the Necronomicon,[n]a tome full of the[n]Cthulhu Mythos's[n]mysteries. Said to[n]have been authored[n]by Abdul Alhazred,[n]a poet and devotee[n]of Cthulhu known as[n]the "mad Arab."[n][e]

[msg myth_249]
[s]The legendary Saxon[n]who opposed the[n]Normans during the[n]conquest of England[n]in the 11th century.[n]Said to have been[n]the basis for tales of[n]Robin Hood. Called[n]"Hereward the Wake"[n]for his watchfulness.[n][e]

[msg myth_250]
[s]The true name of[n]Cinderella's heroine.[n]"Cinder Ella" was a[n]derisive nickname,[n]born from her hard[n]work always leaving[n]her dusty and sooty.[n]After marrying her[n]prince, she became[n]"Princess Ella."[n][e]

[msg myth_251]
[s]A fallen angel in[n]Judeo-Christian[n]lore whose name[n]signifies "Morning[n]Star." Primarily[n]known for defying[n]God but also[n]worshipped as a[n]bringer of light[n]to mankind.[n][e]

[msg myth_252]
[s]The Judeo-Christian[n]prince of darkness,[n]he is known for his[n]role as the snake[n]that tempted Adam[n]and Eve in Eden. It[n]is also said that he[n]was sent by God to[n]test man's piety.[n][e]

[msg myth_253]
[s]A fallen Judeo-[n]Christian angel, he[n]led a rebellion with[n]an army of angels[n]against God and[n]lost. He waits in[n]Hell for his chance[n]to challenge God[n]once more and[n]strike Him down.[n][e]

[msg myth_254]
[s]Known as the Gold[n]Dragon, it reigns[n]over the Ssu-Ling,[n]celestial creatures[n]of Chinese lore. It[n]is located at the[n]center of the four[n]beasts.[n][e]

[msg myth_255]
[s]A Kunitsu deity of[n]Japanese mythology[n]that governs[n]agriculture and[n]medicine. He is said[n]to have built the[n]country of Izumo[n]with Susano-o's[n]daughter, Suseri-Hime.[n][e]

[msg myth_256]
[s]Goddesses of fate[n]in Norse myth. They[n]live below the[n]roots of Yggdrasil[n]and weave the[n]threads of fate,[n]by which even the[n]gods are bound.[n][e]

[msg myth_257]
[s]A Hindu god of war,[n]known as Skanda or[n]Murugan. He rides[n]atop a peacock[n]called Paravani,[n]with bow and arrow[n]drawn. He commands[n]the army of the[n]gods and defeated[n]the forces of Asura.[n][e]

[msg myth_258]
[s]Seven days after its[n]birth, a wolf killed[n]its mother. Yoshizane[n]Satomi later promised[n]his daughter's hand[n]if it could defeat[n]the enemy, but after[n]Yatsufusa's success,[n]Yoshizane's retainer[n]shot it dead.[n][e]

[msg myth_259]
[s]The Nihonshoki[n]sword deity who[n]pacified Ashihara-[n]no-Nakatsukuni. His[n]name comes from[n]"futsu," the fashion[n]in which things are[n]cut, and "nushi,"[n]his nature as a god.[n][e]

[msg myth_260]
[s]RESERVE[n]Mythology[n][e]

[msg myth_261]
[s]The Egyptian god of[n]the desert, chaos,[n]and evil. He murdered[n]his brother, Osiris,[n]and tried to become[n]chief god, but he[n]was castrated by[n]Osiris's son, Horus.[n][e]

[msg myth_262]
[s]The revered goddess[n]of war and love in[n]ancient Mesopotamia.[n]She seduced many[n]men to their doom.[n]When Gilgamesh, the[n]hero, spurned her,[n]she murdered his[n]best friend, Enkidu.[n][e]

[msg myth_263]
[s]RESERVE[n]Mythology[n][e]

[msg myth_264]
[s]A fire giant in[n]Norse lore. He rules[n]the fire realm,[n]Muspelheim, and[n]brandishes a burning[n]sword. At Ragnarok,[n]he will set the world[n]ablaze.[n][e]

[msg myth_265]
[s]The German name[n]of the hero in the[n]epic poem, "The[n]Nibelungenlied."[n]The dragon Fafnir's[n]blood made him[n]invincible, but a[n]single leaf on his[n]back resulted in a[n]weak spot.[n][e]

[msg myth_266]
[s]The Hindu goddess[n]of beauty and good[n]fortune, Vishnu's[n]wife, and Kama's[n]mother. She is the[n]goddess of love,[n]believed to have[n]been born from an[n]ocean of milk.[n][e]

[msg myth_267]
[s]A god who migrated[n]from Silla to Kyushu[n]to give oracles to[n]the people. Later[n]deified as a[n]guardian of samurai[n]across Japan. Also[n]called Yahata, or[n]"a figure for gods[n]to possess."[n][e]

[msg myth_268]
[s]RESERVE[n]Mythology[n][e]

[msg myth_269]
[s]Demonic governor of[n]the deadly sin of[n]sloth, who also[n]excels at invention[n]and discovery. May[n]derive from Ba'al[n]Pe'or, Syrian god[n]of abundant crops.[n][e]

[msg myth_270]
[s]A cursed Norse[n]spirit in the form[n]of a beautiful[n]woman, known to[n]bloom from the[n]blood of hanged men.[n]She was believed[n]to tell secrets if[n]properly tended to.[n][e]

[msg myth_271]
[s]A divine bird-man[n]in Hindu lore. He[n]once fought the[n]gods and received[n]immortality in[n]exchange for[n]becoming Vishnu's[n]carrier.[n][e]

[msg myth_272]
[s]The Roman goddess[n]of luck, she spins[n]the Wheel of[n]Fortune. She is[n]believed to have[n]originally been a[n]fertility goddess.[n]Her Greek counterpart[n]is Tyche.[n][e]

[msg myth_273]
[s]One of the Ssu-Ling,[n]celestial creatures[n]of Chinese myth. It is[n]a giant bird that is[n]said to chirp in five[n]beautiful voices. It[n]represents the[n]direction south, the[n]season of summer,[n]and the element of fire.[n][e]

[msg myth_274]
[s]The noblest of the[n]Ssu-Ling creatures[n]of Chinese myth.[n]It represents the[n]direction east, the[n]season of spring,[n]and the element of[n]wood. It dwells in a[n]palace at the bottom[n]of the ocean.[n][e]

[msg myth_275]
[s]One of the Ssu-Ling,[n]celestial creatures[n]of Chinese myth. It[n]represents the[n]direction north, the[n]season of winter, and[n]the element of water.[n]Known to be a great[n]warrior, it supports the[n]Earth from below.[n][e]

[msg myth_276]
[s]One of the Ssu-Ling,[n]celestial creatures[n]of Chinese myth. It[n]represents the[n]direction west, the[n]season of autumn, and[n]the element of metal.[n]He is believed to be[n]the king of all beasts.[n][e]

[msg myth_277]
[s]Also known as[n]Tamonten and[n]Vaishravana in[n]Buddhist lore, he[n]is the strongest[n]of the Heavenly[n]Kings. He protects[n]the North and is[n]the god of war.[n][e]

[msg myth_278]
[s]Also known as[n]Virupaksha, he is[n]the protector of[n]the West, and is[n]one of the Four[n]Heavenly Kings of[n]Buddhist origin. He[n]keeps a close watch[n]on the world with[n]his sharp gaze.[n][e]

[msg myth_279]
[s]Also known as[n]Dhritarashtra, he[n]is the protector[n]of the East, and[n]is one of the Four[n]Heavenly Kings of[n]Buddhist origin.[n]He helps maintain[n]the security of[n]the nation.[n][e]

[msg myth_280]
[s]Also known as[n]Virudhaka, he is[n]the protector of[n]the South, and is one[n]of the Four Heavenly[n]Kings of Buddhist[n]origin. He is the god[n]of the five grains,[n]and was once the[n]chief of the gods.[n][e]

[msg myth_281]
[s]A motorcyclist[n]whose violent[n]nature turned him[n]into a demon. His[n]anger with himself[n]and the world[n]causes him to lash[n]out, that everyone[n]else would suffer[n]as well.[n][e]

[msg myth_282]
[s]A monk who died[n]while fasting, his[n]spiritual power[n]allows his body to[n]continue to exist[n]without rotting.[n]It is said that he[n]will appear before[n]people on the day[n]of salvation.[n][e]

[msg myth_283]
[s]Angels that sound[n]the trumpets at[n]the time of the[n]Apocalypse. As each[n]trumpet sounds, the[n]more plagues and[n]disasters will occur,[n]turning the earth[n]into a land of death[n]and suffering.[n][e]

[msg myth_284]
[s]One of the Four[n]Horsemen of the[n]Apocalypse, he[n]rides a white[n]horse with a bow[n]in hand. A crown[n]was granted to him,[n]and he promises[n]victory.[n][e]

[msg myth_285]
[s]A master sportsman[n]who entertains the[n]audience in exchange[n]for his own life: one[n]mistake can mean[n]death. Some believe[n]that matadors who[n]die while performing[n]remain in this world.[n][e]

[msg myth_286]
[s]One of the Four[n]Horsemen of the[n]Apocalypse, he[n]rides a pale horse[n]and represents[n]death. He has the[n]power to destroy[n]life.[n][e]

[msg myth_287]
[s]An ancient god of[n]Egypt whose eyes[n]are the sun and[n]moon. Revered by[n]some as the chief[n]god, he is often[n]depicted as a hawk[n]or a falcon.[n][e]

[msg myth_288]
[s]RESERVE[n]Mythology[n][e]

[msg myth_289]
[s]A Phrygian god who[n]symbolizes life,[n]death, and revival.[n]He rejected Cybele's[n]love and was driven[n]mad, dying after he[n]castrated himself.[n]Cybele then[n]resurrected him.[n][e]

[msg myth_290]
[s]RESERVE[n]Mythology[n][e]

[msg myth_291]
[s]The god of war in[n]Greek myth. Other[n]gods despised[n]him for his cruel[n]and violent nature.[n]He opposed Athena,[n]who resented war.[n][e]

[msg myth_292]
[s]In Zoroastrian lore,[n]Sraosha's duty is[n]to listen to the[n]cry of humans for[n]Ahura Mazda. He[n]is also known to[n]descend after sunset[n]to vanquish evil. His[n]name literally means[n]"observance."[n][e]

[msg myth_293]
[s]One of the 72[n]demons of the[n]Goetia. Known[n]as the Duke of[n]Hell, he rides[n]a gigantic horse[n]and burns those[n]without manners.[n][e]

[msg myth_294]
[s]Japanese god of[n]words, thought to[n]be the deification[n]of echoes. Said to[n]proclaim good and[n]bad in a single[n]word, and all[n]words uttered by[n]him come true.[n][e]

[msg myth_295]
[s]An ancient Persian[n]god of contracts,[n]who was also[n]revered as a sun[n]god who brought[n]harvests when he[n]was introduced to[n]the Zoroastrian[n]religion.[n][e]

[msg myth_296]
[s]The legendary bird[n]of Chinese myth,[n]said to appear only[n]in times of peace.[n]It is the ruler of[n]all birds. When it[n]dies, birds across[n]the land chirp with[n]sadness.[n][e]

[msg myth_297]
[s]The seventh of the[n]nine orders of[n]angels. They guard[n]cities and nations,[n]and protect various[n]religious figures.[n][e]

[msg myth_298]
[s]A prophetic Taoist[n]god, originally[n]known as Mao[n]Shogun. Due to a[n]linguistic error[n]involving the[n]Chinese word for[n]"cat," his name[n]was changed to[n]Neko Shogun.[n][e]

[msg myth_299]
[s]A giant serpent of[n]Hindu legend. It is[n]said the gods and[n]demons used him to[n]churn the sea of[n]milk. The strain[n]caused him to[n]exhale incredibly[n]potent venom, but[n]Shiva swallowed it.[n][e]

[msg myth_300]
[s]The 1,000-headed[n]serpent of Hindu[n]legend, Ananta is[n]Sanskrit for[n]"infinite." After[n]resting on him,[n]Vishnu woke up and[n]created the universe.[n][e]

[msg myth_301]
[s]The third of the[n]nine orders of[n]angels. They are[n]the angels of dignity[n]and justice who[n]carry God's throne[n]and govern thought.[n]They are angels[n]of knowledge.[n][e]

[msg myth_302]
[s]RESERVE[n]Mythology[n][e]

[msg myth_303]
[s]An Aztec deity[n]known as the[n]Feathered Serpent.[n]He created humans[n]with his own blood[n]and taught them[n]how to sustain[n]themselves.[n][e]

[msg myth_304]
[s]One of the Four[n]Horsemen of the[n]Apocalypse, he[n]rides a red horse[n]and carries a great[n]sword. He has the[n]power to destroy[n]peace and make men[n]slay one another.[n][e]

[msg myth_305]
[s]One of the Four[n]Horsemen of the[n]Apocalypse, he[n]rides a black horse[n]and carries scales.[n]He brings famine[n]and has the right[n]to end lives through[n]suffering.[n][e]

[msg myth_306]
[s]Shiva's first[n]consort in Hindu[n]myth, she threw[n]herself into a[n]sacrificial fire[n]in protest of her[n]father's treatment[n]of Shiva. Reborn as[n]Parvati, she was[n]reunited with Shiva.[n][e]

[msg myth_307]
[s]A Canaanite god[n]of fire. A bronze[n]statue of a man[n]with a bull's head[n]stands at an altar.[n]Sacrificial children[n]were thrown into[n]the statue after[n]it was heated.[n][e]

[msg myth_308]
[s]The Babylonian lord[n]of wind and scorching[n]sands. He has the[n]body of a man, a lion's[n]head, the claws and[n]wings of an eagle,[n]and has a deadly[n]poison. The diseases[n]he spreads can only[n]be cured with magic.[n][e]

[msg myth_309]
[s]RESERVE[n]Mythology[n][e]

[msg myth_310]
[s]RESERVE[n]Mythology[n][e]

[msg myth_311]
[s]RESERVE[n]Mythology[n][e]

[msg myth_312]
[s]RESERVE[n]Mythology[n][e]

[msg myth_313]
[s]RESERVE[n]Mythology[n][e]

[msg myth_314]
[s]RESERVE[n]Mythology[n][e]

[msg myth_315]
[s]RESERVE[n]Mythology[n][e]

[msg myth_316]
[s]RESERVE[n]Mythology[n][e]

[msg myth_317]
[s]RESERVE[n]Mythology[n][e]

[msg myth_318]
[s]RESERVE[n]Mythology[n][e]

[msg myth_319]
[s]RESERVE[n]Mythology[n][e]

[msg myth_320]
[s]RESERVE[n]Mythology[n][e]

[msg myth_321]
[s]RESERVE[n]Mythology[n][e]

[msg myth_322]
[s]RESERVE[n]Mythology[n][e]

[msg myth_323]
[s]RESERVE[n]Mythology[n][e]

[msg myth_324]
[s]RESERVE[n]Mythology[n][e]

[msg myth_325]
[s]RESERVE[n]Mythology[n][e]

[msg myth_326]
[s]RESERVE[n]Mythology[n][e]

[msg myth_327]
[s]RESERVE[n]Mythology[n][e]

[msg myth_328]
[s]RESERVE[n]Mythology[n][e]

[msg myth_329]
[s]RESERVE[n]Mythology[n][e]

[msg myth_330]
[s]The maternal figure[n]of Christianity.[n]Gabriel informed her[n]that she was to be[n]the mother of Jesus.[n]Some sects revere[n]her as the Virgin[n]Mary, but other[n]denominations do[n]not focus on her.[n][e]

[msg myth_331]
[s]The second of[n]Zoroastrianism's[n]"divine sparks,"[n]Amesha Spenta, its[n]name means "good[n]thought." This holy[n]entity is said to have[n]given Zoroaster[n]revelations from[n]God.[n][e]

[msg myth_332]
[s]A fae beast from the[n]Scottish highlands.[n]Their kingdoms are[n]in tree hollows or[n]abandoned houses.[n]Dog-sized, with vivid[n]green eyes. Some live[n]with humans, as[n]they understand[n]our speech.[n][e]

[msg myth_333]
[s]An indigenous god[n]of the Shinano region[n]from before the[n]forces of Yamato[n]occupied the land.[n]Said to be born from[n]the belief that divine[n]spirits dwelled in[n]rocks and stones.[n][e]

[msg myth_334]
[s]RESERVE[n]Mythology[n][e]

[msg myth_335]
[s]RESERVE[n]Mythology[n][e]

[msg myth_336]
[s]RESERVE[n]Mythology[n][e]

[msg myth_337]
[s]RESERVE[n]Mythology[n][e]

[msg myth_338]
[s]RESERVE[n]Mythology[n][e]

[msg myth_339]
[s]RESERVE[n]Mythology[n][e]

[msg myth_340]
[s]RESERVE[n]Mythology[n][e]

[msg myth_341]
[s]RESERVE[n]Mythology[n][e]

[msg myth_342]
[s]RESERVE[n]Mythology[n][e]

[msg myth_343]
[s]RESERVE[n]Mythology[n][e]

[msg myth_344]
[s]RESERVE[n]Mythology[n][e]

[msg myth_345]
[s]RESERVE[n]Mythology[n][e]

[msg myth_346]
[s]RESERVE[n]Mythology[n][e]

[msg myth_347]
[s]RESERVE[n]Mythology[n][e]

[msg myth_348]
[s]RESERVE[n]Mythology[n][e]

[msg myth_349]
[s]RESERVE[n]Mythology[n][e]

[msg myth_350]
[s]RESERVE[n]Mythology[n][e]

[msg myth_351]
[s]RESERVE[n]Mythology[n][e]

[msg myth_352]
[s]RESERVE[n]Mythology[n][e]

[msg myth_353]
[s]RESERVE[n]Mythology[n][e]

[msg myth_354]
[s]RESERVE[n]Mythology[n][e]

[msg myth_355]
[s]RESERVE[n]Mythology[n][e]

[msg myth_356]
[s]RESERVE[n]Mythology[n][e]

[msg myth_357]
[s]RESERVE[n]Mythology[n][e]

[msg myth_358]
[s]RESERVE[n]Mythology[n][e]

[msg myth_359]
[s]RESERVE[n]Mythology[n][e]

[msg myth_360]
[s]A Persona of another[n]story. A Japanese god[n]of creation, he begat[n]the sky, ocean, and[n]night, and 8 million[n]other gods. Opposes[n]his once-wife, the[n]goddess Izanami,[n]after an encounter[n]in Yomotsu Hirasaka.[n][e]

[msg myth_361]
[s]RESERVE[n]Mythology[n][e]

[msg myth_362]
[s]A Persona of another[n]story. Daughter of[n]Zeus, and a goddess[n]of great martial[n]ability. She fights to[n]protect her land or[n]her family, but never[n]for sheer bloodlust.[n]Her symbol is the[n]olive tree.[n][e]

[msg myth_363]
[s]Another alias of[n]Maurice Leblanc's[n]hero, Arsène Lupin.[n]Infamous as a[n]phantom thief, he[n]was also known to[n]be a man of many[n]friends, lovers, and[n]treasured allies.[n][e]

[msg myth_364]
[s]RESERVE[n]Mythology[n][e]

[msg myth_365]
[s]A Persona of another[n]story. A poet skilled[n]with the lyre. He[n]tried to retrieve[n]his wife from Hades,[n]but she vanished[n]when he looked back[n]before reaching[n]the surface.[n][e]

[msg myth_366]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]A Japanese god of[n]creation, he begat[n]the sky, ocean, and[n]night, and 8 million[n]other gods. Opposes[n]his once-wife, the[n]goddess Izanami.[n][e]

[msg myth_367]
[s]RESERVE[n]Mythology[n][e]

[msg myth_368]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]Daughter of Zeus,[n]and a goddess of[n]great martial ability.[n]She fights for her[n]land or her family,[n]but never out of[n]sheer bloodlust.[n][e]

[msg myth_369]
[s]RESERVE[n]Mythology[n][e]

[msg myth_370]
[s]RESERVE[n]Mythology[n][e]

[msg myth_371]
[s]A Persona turned[n]picaro after becoming[n]the Trickster's mask.[n]A Greek poet who[n]tried to retrieve[n]his wife from Hades,[n]but she vanished[n]when he looked back[n]before reaching[n]the surface.[n][e]

[msg myth_372]
[s]RESERVE[n]Mythology[n][e]

[msg myth_373]
[s]RESERVE[n]Mythology[n][e]

[msg myth_374]
[s]RESERVE[n]Mythology[n][e]

[msg myth_375]
[s]RESERVE[n]Mythology[n][e]

[msg myth_376]
[s]RESERVE[n]Mythology[n][e]

[msg myth_377]
[s]RESERVE[n]Mythology[n][e]

[msg myth_378]
[s]RESERVE[n]Mythology[n][e]

[msg myth_379]
[s]RESERVE[n]Mythology[n][e]

[msg myth_380]
[s]RESERVE[n]Mythology[n][e]

[msg myth_381]
[s]RESERVE[n]Mythology[n][e]

[msg myth_382]
[s]RESERVE[n]Mythology[n][e]

[msg myth_383]
[s]RESERVE[n]Mythology[n][e]

[msg myth_384]
[s]RESERVE[n]Mythology[n][e]

[msg myth_385]
[s]RESERVE[n]Mythology[n][e]

[msg myth_386]
[s]RESERVE[n]Mythology[n][e]

[msg myth_387]
[s]RESERVE[n]Mythology[n][e]

[msg myth_388]
[s]RESERVE[n]Mythology[n][e]

[msg myth_389]
[s]RESERVE[n]Mythology[n][e]

[msg myth_390]
[s]RESERVE[n]Mythology[n][e]

[msg myth_391]
[s]RESERVE[n]Mythology[n][e]

[msg myth_392]
[s]RESERVE[n]Mythology[n][e]

[msg myth_393]
[s]RESERVE[n]Mythology[n][e]

[msg myth_394]
[s]RESERVE[n]Mythology[n][e]

[msg myth_395]
[s]RESERVE[n]Mythology[n][e]

[msg myth_396]
[s]RESERVE[n]Mythology[n][e]

[msg myth_397]
[s]RESERVE[n]Mythology[n][e]

[msg myth_398]
[s]RESERVE[n]Mythology[n][e]

[msg myth_399]
[s]RESERVE[n]Mythology[n][e]

[msg myth_400]
[s]RESERVE[n]Mythology[n][e]

[msg myth_401]
[s]RESERVE[n]Mythology[n][e]

[msg myth_402]
[s]RESERVE[n]Mythology[n][e]

[msg myth_403]
[s]RESERVE[n]Mythology[n][e]

[msg myth_404]
[s]RESERVE[n]Mythology[n][e]

[msg myth_405]
[s]RESERVE[n]Mythology[n][e]

[msg myth_406]
[s]RESERVE[n]Mythology[n][e]

[msg myth_407]
[s]RESERVE[n]Mythology[n][e]

[msg myth_408]
[s]RESERVE[n]Mythology[n][e]

[msg myth_409]
[s]RESERVE[n]Mythology[n][e]

[msg myth_410]
[s]RESERVE[n]Mythology[n][e]

[msg myth_411]
[s]RESERVE[n]Mythology[n][e]

[msg myth_412]
[s]RESERVE[n]Mythology[n][e]

[msg myth_413]
[s]RESERVE[n]Mythology[n][e]

[msg myth_414]
[s]RESERVE[n]Mythology[n][e]

[msg myth_415]
[s]RESERVE[n]Mythology[n][e]

[msg myth_416]
[s]RESERVE[n]Mythology[n][e]

[msg myth_417]
[s]RESERVE[n]Mythology[n][e]

[msg myth_418]
[s]RESERVE[n]Mythology[n][e]

[msg myth_419]
[s]RESERVE[n]Mythology[n][e]

[msg myth_420]
[s]RESERVE[n]Mythology[n][e]

[msg myth_421]
[s]RESERVE[n]Mythology[n][e]

[msg myth_422]
[s]RESERVE[n]Mythology[n][e]

[msg myth_423]
[s]RESERVE[n]Mythology[n][e]

[msg myth_424]
[s]An evil spirit with the[n]same name as the[n]Death appearing in[n]medieval oratorios.[n]It is depicted as a[n]skeleton with a black[n]cloak and a sickle[n]to reap humans.[n]It dances the feared[n]"Dance of Death."[n][e]

[msg myth_425]
[s]The Arabian mother[n]goddess also known[n]as Allat. She was[n]thought to reside in[n]the Black Stone at[n]the Kaaba. She and[n]her son, Dusura,[n]were worshipped[n]there by desert[n]nomads.[n][e]

[msg myth_426]
[s]A revered bird of[n]Native American[n]mythology said to live[n]atop cloud-shrouded[n]peaks. Resembles an[n]eagle. Its wingbeats[n]create thunderclaps,[n]and some legends say[n]its eyes can unleash[n]lightning.[n][e]

[msg myth_427]
[s]An evil dragon of[n]Norse lore, it was[n]vanquished by the[n]hero, Siegfried.[n]According to the[n]Völsunga saga, it was[n]venomous, had legs[n]like snakes, and[n]shook the ground[n]with every step.[n][e]

[msg myth_428]
[s]A malformed, winged[n]servant of the Cthulhu[n]Mythos's cosmic god[n]Hastur. They can fly[n]even in the vacuum[n]of space, and it's said[n]that if you can[n]summon one, it will[n]carry you wherever[n]you wish.[n][e]

[msg myth_429]
[s]An evil god of the[n]Cthulhu Mythos and[n]one of the eldritch[n]deities known as[n]Great Old Ones. It[n]wields great power[n]over wind. Also called[n]"The Unspeakable"[n]and "The King in[n]Yellow."[n][e]

[msg myth_430]
[s]A fae knight of the[n]Seelie Court, said to[n]protect the forest of[n]Carterhaugh. After[n]being kidnapped by[n]the faeries at the[n]tender age of 9,[n]he lived much of[n]his life among them.[n][e]

[msg myth_431]
[s]The third of the[n]nine orders of[n]angels. They are[n]the angels of dignity[n]and justice who[n]carry God's throne[n]and govern thought.[n]They are angels[n]of knowledge.[n][e]

[msg myth_432]
[s]A fire giant in[n]Norse lore. He rules[n]the fire realm,[n]Muspelheim, and[n]brandishes a burning[n]sword. At Ragnarok,[n]he will set the world[n]ablaze.[n][e]

[msg myth_433]
[s]A general name for[n]gods and spirits of[n]Vodum. The gods[n]that actually affect[n]human lives are[n]called by this name.[n]Those with negative[n]power are said to be[n]able to kill with a[n]fatal curse.[n][e]

[msg myth_434]
[s]Part lion, part goat[n]and part snake, this[n]creature originally[n]represented the[n]seasons. In Greek[n]mythology, it was[n]viewed as a violent[n]monster. Born of[n]Typhon and Echidna.[n][e]

[msg myth_435]
[s]One of the eight[n]Yashaou. His domain[n]is war and protection.[n]Once a child-eating[n]demon, he became[n]one of the greatest[n]of the Wisdom Kings[n]after Buddha[n]converted him to[n]good.[n][e]

[msg myth_436]
[s]A fae beast from the[n]Scottish highlands.[n]Their kingdoms are[n]in tree hollows or[n]abandoned houses.[n]Dog-sized, with vivid[n]green eyes. Some live[n]with humans, as[n]they understand[n]our speech.[n][e]

[msg myth_437]
[s]The German name[n]of the hero in the[n]epic poem, "The[n]Nibelungenlied."[n]The dragon Fafnir's[n]blood made him[n]invincible, but a[n]single leaf on his[n]back resulted in a[n]weak spot.[n][e]

[msg myth_438]
[s]RESERVE[n]Mythology[n][e]

[msg myth_439]
[s]RESERVE[n]Mythology[n][e]

[msg myth_440]
[s]RESERVE[n]Mythology[n][e]

[msg myth_441]
[s]RESERVE[n]Mythology[n][e]

[msg myth_442]
[s]RESERVE[n]Mythology[n][e]

[msg myth_443]
[s]RESERVE[n]Mythology[n][e]

[msg myth_444]
[s]RESERVE[n]Mythology[n][e]

[msg myth_445]
[s]RESERVE[n]Mythology[n][e]

[msg myth_446]
[s]RESERVE[n]Mythology[n][e]

[msg myth_447]
[s]RESERVE[n]Mythology[n][e]

[msg myth_448]
[s]RESERVE[n]Mythology[n][e]

[msg myth_449]
[s]RESERVE[n]Mythology[n][e]

[msg myth_450]
[s]RESERVE[n]Mythology[n][e]

[msg myth_451]
[s]RESERVE[n]Mythology[n][e]

[msg myth_452]
[s]RESERVE[n]Mythology[n][e]

[msg myth_453]
[s]RESERVE[n]Mythology[n][e]

[msg myth_454]
[s]RESERVE[n]Mythology[n][e]

[msg myth_455]
[s]RESERVE[n]Mythology[n][e]

[msg myth_456]
[s]RESERVE[n]Mythology[n][e]

[msg myth_457]
[s]RESERVE[n]Mythology[n][e]

[msg myth_458]
[s]RESERVE[n]Mythology[n][e]

[msg myth_459]
[s]RESERVE[n]Mythology[n][e]

[msg myth_460]
[s]RESERVE[n]Mythology[n][e]

[msg myth_461]
[s]RESERVE[n]Mythology[n][e]

[msg myth_462]
[s]RESERVE[n]Mythology[n][e]

[msg myth_463]
[s]RESERVE[n]Mythology[n][e]

