[msg quest00]
[f 0 5 65278][f 2 1]This mission hasn't occurred.[n][f 1 1][e]

[msg quest_notice_00]
[f 0 5 65278][f 2 1]Change the heart of the target in Mementos![n][f 1 1][e]

[msg quest_clear_01]
[f 0 5 65278][f 2 1]It looks like we successfully changed the target's[n]heart. Let's go check and see.[n][f 1 1][e]

[msg quest_clear_02]
[f 0 5 65278][f 2 1]It seems we successfully changed the target's heart.[n][f 1 1][e]

[msg quest_faild]
[f 0 5 65278][f 2 1]It looks like the target disappeared into the depths of[n]Mementos...[n][f 1 1][e]

[msg questTEST_0]
[f 0 5 65278][f 2 1]クエストのテストメッセージ。[n]これは概要です。[n][f 1 1][e]

[msg questTEST_1]
[f 0 5 65278][f 2 1]クエストのテストメッセージ。[n]これは調査中です。[n][f 1 1][e]

[msg questTEST_2]
[f 0 5 65278][f 2 1]クエストのテストメッセージ。[n]これは受注可能です。[n][f 1 1][e]

[msg quest01_0]
[f 0 5 65278][f 2 1]Ann told me about a twisted host who leeches off[n]women, then dumps them once he has no use for[n]them.[n][f 1 1][e]

[msg quest01_2]
[f 0 5 65278][f 2 1]I got some interesting info from Ann. We have[n]a name now, so let's meet up at the hideout![n][f 1 1][e]

[msg quest02_0]
[f 0 5 65278][f 2 1]A housewife who covets and takes other people's things[n]is troubling those around her...[n][f 1 1][e]

[msg quest02_1]
[f 0 5 65278][f 2 1]This housewife who covets and takes other people's[n]things can be found on Central Street.[n][f 1 1][e]

[msg quest02_2]
[f 0 5 65278][f 2 1]Mishima told me about a housewife who takes[n]people's things. We have a name—let's meet at[n]the hideout![n][f 1 1][e]

[msg quest03_0]
[f 0 5 65278][f 2 1]A student in front of the Shujin Academy gate cruelly[n]bullies this student, pretending it's a joke...[n][f 1 1][e]

[msg quest03_1]
[f 0 5 65278][f 2 1]I learned about some bullying near the school gate.[n]Let's go check it out when we have time.[n][f 1 1][e]

[msg quest03_2]
[f 0 5 65278][f 2 1]I found the bullying Shujin student. We have a name[n]now, so let's meet up at the hideout![n][f 1 1][e]

[msg quest04_0]
[f 0 5 65278][f 2 1]Ryuji told me about a cheap and selfish mother who[n]refuses to pay for school lunches.[n][f 1 1][e]

[msg quest04_2]
[f 0 5 65278][f 2 1]Ryuji told me about a cheap and selfish mother.[n]We have a name, so let's meet up at the hideout![n][f 1 1][e]

[msg quest05_0]
[f 0 5 65278][f 2 1]I hear there's a housewife whose sense of entitlement[n]makes her an unbearable complainer...[n][f 1 1][e]

[msg quest05_1]
[f 0 5 65278][f 2 1]I heard from Mishima that the forum posted about a[n]complaining housewife.[n][f 1 1][e]

[msg quest05_2]
[f 0 5 65278][f 2 1]I got info from Mishima about the complaining[n]housewife. We have a name—let's meet at the[n]hideout![n][f 1 1][e]

[msg quest07_0]
[f 0 5 65278][f 2 1]A female student is possessed by dangerous feelings[n]of jealousy over the boy she likes...[n][f 1 1][e]

[msg quest07_1]
[f 0 5 65278][f 2 1]Mishima told me the rumor about a cyberstalker[n]student. Let's search the Shujin campus for her.[n][f 1 1][e]

[msg quest07_2]
[f 0 5 65278][f 2 1]I heard about the cyberstalker from Mishima.[n]We have a name, so let's meet up at the hideout![n][f 1 1][e]

[msg quest08_0]
[f 0 5 65278][f 2 1]クエ08概要(不要)[n][f 1 1][e]

[msg quest08_1]
[f 0 5 65278][f 2 1]クエ08調査中(不要)[n][f 1 1][e]

[msg quest08_2]
[f 0 5 65278][f 2 1]The target seems to be somewhere inside Mementos.[n]Let's find our target![n][f 1 1][e]

[msg quest09_0]
[f 0 5 65278][f 2 1]A guy who works at a bank misuses his authority to[n]embezzle money from his place of employment...[n][f 1 1][e]

[msg quest09_1]
[f 0 5 65278][f 2 1]I hear there's a criminal who embezzles money[n]from a bank...[n][f 1 1][e]

[msg quest09_2]
[f 0 5 65278][f 2 1]Mishima told me about an embezzler. We have a[n]name, so let's meet up at the hideout![n][f 1 1][e]

[msg quest10_0]
[f 0 5 65278][f 2 1]A troubling customer is hassling an employee at[n]the convenience store where I work part-time...[n][f 1 1][e]

[msg quest10_1]
[f 0 5 65278][f 2 1]I heard from my convenience store co-worker[n]about the target who's been hassling employees...[n][f 1 1][e]

[msg quest10_2]
[f 0 5 65278][f 2 1]I learned about the target at the convenience store.[n]We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest11_0]
[f 0 5 65278][f 2 1]Inspired by the Phantom Thieves, a burglary ring[n]has been stealing from restaurants in Shibuya...[n][f 1 1][e]

[msg quest11_1]
[f 0 5 65278][f 2 1]I learned about a burglary ring that secretly operates[n]in Shibuya. Let's find some leads on them.[n][f 1 1][e]

[msg quest11_2]
[f 0 5 65278][f 2 1]I got a lead on Shibuya's burglary ring. We have[n]a name now, so let's meet up at the hideout![n][f 1 1][e]

[msg quest12_0]
[f 0 5 65278][f 2 1]There's a student who has bullies under his control,[n]causing crimes like some kind of gang leader...[n][f 1 1][e]

[msg quest12_1]
[f 0 5 65278][f 2 1]This is the bully behind the bully whose heart we[n]changed. We can find him near the school gate.[n][f 1 1][e]

[msg quest12_2]
[f 0 5 65278][f 2 1]I've found the leader who towers above the other[n]bullies. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest13_0]
[f 0 5 65278][f 2 1]The mother of a florist employee is gambling away[n]her income with no consideration for her family.[n][f 1 1][e]

[msg quest13_1]
[f 0 5 65278][f 2 1]I heard from my florist co-worker about her[n]mother who can't quit her gambling addiction.[n][f 1 1][e]

[msg quest13_2]
[f 0 5 65278][f 2 1]I learned about a gambling addict at my part-time[n]job. I have a name now, so let's meet at the hideout![n][f 1 1][e]

[msg quest15_0]
[f 0 5 65278][f 2 1]A self-important old man clings to past glories,[n]harshly criticizing anyone who happens to be younger.[n][f 1 1][e]

[msg quest15_1]
[f 0 5 65278][f 2 1]Mishima told me a rumor about an arrogant and[n]cantankerous old man mentioned on the forum.[n][f 1 1][e]

[msg quest15_2]
[f 0 5 65278][f 2 1]I learned about an ornery old man from Mishima.[n]We have a name, so let's meet up at the hideout![n][f 1 1][e]

[msg quest19_0]
[f 0 5 65278][f 2 1]An unethical land developer is threatening an[n]old man to sell his movie theater in Yongen-Jaya.[n][f 1 1][e]

[msg quest19_1]
[f 0 5 65278][f 2 1]I heard from Mishima that the forum posted about[n]an unethical land developer.[n][f 1 1][e]

[msg quest19_2]
[f 0 5 65278][f 2 1]Mishima told me about the land developer in[n]Yongen-Jaya. We have a name—let's meet at[n]the hideout![n][f 1 1][e]

[msg quest21_0]
[f 0 5 65278][f 2 1]A female student who fancies herself a queen[n]treats her underclassmen like slaves...[n][f 1 1][e]

[msg quest21_1]
[f 0 5 65278][f 2 1]I heard from Mishima that the forum posted about a[n]tyrannical student at school.[n][f 1 1][e]

[msg quest21_2]
[f 0 5 65278][f 2 1]Mishima told me about a tyrannical female student[n]at Kosei. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest22_0]
[f 0 5 65278][f 2 1]A desperate employee who can't stand up to his boss[n]is scheming to cause major trouble...[n][f 1 1][e]

[msg quest22_2]
[f 0 5 65278][f 2 1]Yusuke told me about an employee driven by[n]despair. We have a name, so let's meet up at[n]the hideout![n][f 1 1][e]

[msg quest23_0]
[f 0 5 65278][f 2 1]An older student is blackmailing his underclassman[n]to act as his personal gofer.[n][f 1 1][e]

[msg quest23_1]
[f 0 5 65278][f 2 1]I heard a rumor at the convenience store[n]about a Shujin student who pushes around[n]an underclassman.[n][f 1 1][e]

[msg quest23_2]
[f 0 5 65278][f 2 1]A Shujin student forced his schoolmate to be his[n]gofer. I got a name—let's meet at the hideout![n][f 1 1][e]

[msg quest24_0]
[f 0 5 65278][f 2 1]A youth copycatting Kaneshiro is swindling money[n]with his group on Central Street.[n][f 1 1][e]

[msg quest24_1]
[f 0 5 65278][f 2 1]I heard from Mishima that the forum posted about[n]a young Kaneshiro copycat.[n][f 1 1][e]

[msg quest24_2]
[f 0 5 65278][f 2 1]I learned about the Kaneshiro copycat from Mishima.[n]We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest25_0]
[f 0 5 65278][f 2 1]Futaba told me about a negligent police officer who[n]is ignoring the stalker incident reports...[n][f 1 1][e]

[msg quest25_2]
[f 0 5 65278][f 2 1]I learned about a negligent police officer from Futaba.[n]We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest26_0]
[f 0 5 65278][f 2 1]I hear a middle-aged manager is misusing his[n]authority to abuse his subordinates...[n][f 1 1][e]

[msg quest26_1]
[f 0 5 65278][f 2 1]I heard at the bar I work at about a middle-aged[n]manager abusing his subordinates...[n][f 1 1][e]

[msg quest26_2]
[f 0 5 65278][f 2 1]I learned about an abusive middle-aged manager.[n]We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest27_0]
[f 0 5 65278][f 2 1]Some player is using cheats to win in online battles in[n]Gun About, the hit video game...[n][f 1 1][e]

[msg quest27_1]
[f 0 5 65278][f 2 1]There's a rumor in the gaming world about a player[n]cheating in online Gun About matches...[n][f 1 1][e]

[msg quest27_2]
[f 0 5 65278][f 2 1]An irritable gamer told me about an infamous[n]cheater. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest28_0]
[f 0 5 65278][f 2 1]Morgana told me about a student using her mother's[n]position as PTA president to harass her teacher.[n][f 1 1][e]

[msg quest28_2]
[f 0 5 65278][f 2 1]Morgana told me some student is harassing her[n]teacher. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest29_0]
[f 0 5 65278][f 2 1]There's supposedly a murderer out in Shibuya who[n]will eventually kill again unless he's stopped...[n][f 1 1][e]

[msg quest29_1]
[f 0 5 65278][f 2 1]Mishima told me the forum posted about a killer who[n]roams Shibuya.[n][f 1 1][e]

[msg quest29_2]
[f 0 5 65278][f 2 1]I've finally got the homeless contract killer's name.[n]Let's meet up at the hideout![n][f 1 1][e]

[msg quest30_0]
[f 0 5 65278][f 2 1]There's a daughter being forced to live her life to[n]fulfill her mother's own dreams...[n][f 1 1][e]

[msg quest30_1]
[f 0 5 65278][f 2 1]At the convenience store, I heard about a daughter[n]forced to live her life for her mother's dreams.[n][f 1 1][e]

[msg quest30_2]
[f 0 5 65278][f 2 1]I've got the name of the mother living vicariously[n]through her own child. Let's meet at the hideout![n][f 1 1][e]

[msg quest31_0]
[f 0 5 65278][f 2 1]A boy in Akihabara has been illegally downloading[n]video games and is even bragging about it...[n][f 1 1][e]

[msg quest31_1]
[f 0 5 65278][f 2 1]Mishima told me about a boy pirating video games[n]who's been mentioned on the forum.[n][f 1 1][e]

[msg quest31_2]
[f 0 5 65278][f 2 1]I learned about a boy guilty of video game piracy.[n]We have a name, so let's meet up at the hideout![n][f 1 1][e]

[msg quest32_0]
[f 0 5 65278][f 2 1]Haru told me about a rich and handsome playboy[n]who charms women into giving him money...[n][f 1 1][e]

[msg quest32_2]
[f 0 5 65278][f 2 1]I learned about a charmer fooling women out of their[n]money. We have a name—let's meet at the hideout.[n][f 1 1][e]

[msg quest33_0]
[f 0 5 65278][f 2 1]An immoral producer working in entertainment[n]is taking advantage of young women dreaming of[n]fame.[n][f 1 1][e]

[msg quest33_1]
[f 0 5 65278][f 2 1]Mishima told me a rumor about an entertainment[n]producer who forces clients to sleep with him.[n][f 1 1][e]

[msg quest33_2]
[f 0 5 65278][f 2 1]I've got the name of that immoral producer. Let's[n]meet up at the hideout![n][f 1 1][e]

[msg quest34_0]
[f 0 5 65278][f 2 1]I heard from Mishima about a store manager who[n]steals cash from the register and harasses part-timers.[n][f 1 1][e]

[msg quest34_2]
[f 0 5 65278][f 2 1]I learned about a corrupt store manager from[n]Mishima. We have a name—let's meet at the[n]hideout![n][f 1 1][e]

[msg quest35_0]
[f 0 5 65278][f 2 1]An indie idol is riding the Phantom Thieves'[n]popularity and using lies to attain greater[n]fame...[n][f 1 1][e]

[msg quest35_1]
[f 0 5 65278][f 2 1]Mishima told me a rumor about an indie idol at[n]Central Street who's been acting pretty strangely.[n][f 1 1][e]

[msg quest35_2]
[f 0 5 65278][f 2 1]I've got the name of that indie idol, so let's meet up[n]at the hideout![n][f 1 1][e]

[msg quest36_0]
[f 0 5 65278][f 2 1]Some manager at a company does no work, but[n]takes all the credit for his subordinates' efforts.[n][f 1 1][e]

[msg quest36_1]
[f 0 5 65278][f 2 1]I learned about some imperious manager from[n]Mishima. Let's go to that Shinjuku bar to investigate.[n][f 1 1][e]

[msg quest36_2]
[f 0 5 65278][f 2 1]At the bar, I learned about an imperious manager.[n]We've got a name—let's meet at the hideout![n][f 1 1][e]

[msg quest39_0]
[f 0 5 65278][f 2 1]An older teacher at Shujin is picking on new hires,[n]forcing them to do her grunt work...[n][f 1 1][e]

[msg quest39_1]
[f 0 5 65278][f 2 1]Mishima told me a rumor about an older teacher[n]at Shujin who picks on the newly hired teachers.[n][f 1 1][e]

[msg quest39_2]
[f 0 5 65278][f 2 1]We learned an older Shujin teacher is picking on new[n]hires. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest40_0]
[f 0 5 65278][f 2 1]I hear someone is indiscriminately assaulting[n]homeless people and office workers around[n]Shibuya...[n][f 1 1][e]

[msg quest40_1]
[f 0 5 65278][f 2 1]Mishima told me someone's been attacking people.[n]Let's go to the underground mall to investigate.[n][f 1 1][e]

[msg quest40_2]
[f 0 5 65278][f 2 1]I learned at the florist about someone attacking[n]people. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest42_0]
[f 0 5 65278][f 2 1]Someone erased critical data and isn't showing up to[n]work due to an unjust grudge against his company.[n][f 1 1][e]

[msg quest42_1]
[f 0 5 65278][f 2 1]I heard at the bar I work at about a guy who erased[n]critical company data because of a petty grudge.[n][f 1 1][e]

[msg quest42_2]
[f 0 5 65278][f 2 1]I learned about a vindictive employee at the bar. We have a[n]name—let's meet at the hideout![n][f 1 1][e]

[msg quest48_0]
[f 0 5 65278][f 2 1]Some college student is abusing cats just to blow off[n]steam...[n][f 1 1][e]

[msg quest48_1]
[f 0 5 65278][f 2 1]Let's gather info about the cat abuse by working[n]part-time at the Central Street convenience store.[n][f 1 1][e]

[msg quest48_2]
[f 0 5 65278][f 2 1]I learned about the cat abuser at the convenience[n]store. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest49_0]
[f 0 5 65278][f 2 1]A greedy man who keeps borrowing money[n]is trying to escape his debt by going overseas.[n][f 1 1][e]

[msg quest49_1]
[f 0 5 65278][f 2 1]Mishima told me about a debtor running from[n]his debts who's been mentioned on the forum.[n][f 1 1][e]

[msg quest49_2]
[f 0 5 65278][f 2 1]Mishima told me about a debtor running from his[n]debts. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest50_0]
[f 0 5 65278][f 2 1]A group is going around, committing fraud[n]to exploit the elderly and take their money...[n][f 1 1][e]

[msg quest50_1]
[f 0 5 65278][f 2 1]Mishima told me about a young man exploiting[n]the elderly who's been mentioned on the forum.[n][f 1 1][e]

[msg quest50_2]
[f 0 5 65278][f 2 1]I learned about a youth who's exploiting the elderly.[n]We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest51_0]
[f 0 5 65278][f 2 1]Shinya's mother, Hanae Oda, has an aggressive[n]behavior problem, and it's affecting her son badly.[n][f 1 1][e]

[msg quest51_1]
[f 0 5 65278][f 2 1]Let's help Shinya with his problem by changing his[n]mother's heart in Mementos.[n][f 1 1][e]

[msg quest51_2]
[f 0 5 65278][f 2 1]I want to help Shinya and change his mother's heart.[n]We have her name—let's meet at the hideout![n][f 1 1][e]

[msg quest51_3]
[f 0 5 65278][f 2 1]I successfully changed Shinya's mother's heart for[n]him.[n][f 1 1][e]

[msg quest52_0]
[f 0 5 65278][f 2 1]A woman is consulting the Shinjuku fortune teller[n]for help because of her boyfriend's physical abuse...[n][f 1 1][e]

[msg quest52_1]
[f 0 5 65278][f 2 1]Let's prove that fate can change to the fortune[n]teller by changing the abusive boyfriend's heart.[n][f 1 1][e]

[msg quest52_2]
[f 0 5 65278][f 2 1]I've got the name of the guy who beats his girlfriend,[n]so let's discuss this at the hideout.[n][f 1 1][e]

[msg quest52_3]
[f 0 5 65278][f 2 1]I successfully changed the heart of the abusive[n]boyfriend that the fortune teller told me about.[n][f 1 1][e]

[msg quest53_0]
[f 0 5 65278][f 2 1]Yuichi Fukurai, the ADP chairman, controls Chihaya...[n][f 1 1][e]

[msg quest53_1]
[f 0 5 65278][f 2 1]Let's help Chihaya by changing the ADP chairman's[n]heart in Mementos.[n][f 1 1][e]

[msg quest53_2]
[f 0 5 65278][f 2 1]Let's expose the ADP chairman's true nature for[n]Chihaya. I got his name—let's meet at the hideout![n][f 1 1][e]

[msg quest53_3]
[f 0 5 65278][f 2 1]I successfully changed the ADP chairman's heart for[n]Chihaya.[n][f 1 1][e]

[msg quest54_0]
[f 0 5 65278][f 2 1]Iwai has a deal related to his[n]model guns with his former ally[n]Tsuda, but he's in trouble...[n][f 1 1][e]

[msg quest54_1]
[f 0 5 65278][f 2 1]Let's change Tsuda's heart in Mementos and solve[n]Iwai's problem.[n][f 1 1][e]

[msg quest54_2]
[f 0 5 65278][f 2 1]Iwai's former ally is threatening him to modify guns.[n]We have his name—let's meet at the hideout![n][f 1 1][e]

[msg quest54_3]
[f 0 5 65278][f 2 1]I successfully changed Tsuda's heart for Iwai.[n][f 1 1][e]

[msg quest55_0]
[f 0 5 65278][f 2 1]In her university hospital days, Takemi was blamed[n]for Medical Director Oyamada's mistake.[n][f 1 1][e]

[msg quest55_1]
[f 0 5 65278][f 2 1]Let's change Medical Chief of Staff Oyamada's heart[n]in Mementos.[n][f 1 1][e]

[msg quest55_2]
[f 0 5 65278][f 2 1]Takemi's former boss is trying to crush her practice.[n]We have his name—let's meet at the hideout![n][f 1 1][e]

[msg quest55_3]
[f 0 5 65278][f 2 1]I successfully changed the medical chief of staff's[n]heart for Takemi.[n][f 1 1][e]

[msg quest56_0]
[f 0 5 65278][f 2 1]Kawakami is being extorted by her former student's[n]guardians who blame her for his death.[n][f 1 1][e]

[msg quest56_1]
[f 0 5 65278][f 2 1]Let's change the hearts of her former student's[n]guardians in Mementos to help Kawakami.[n][f 1 1][e]

[msg quest56_2]
[f 0 5 65278][f 2 1]I want to punish that couple for threatening[n]Kawakami. I have their names—let's meet at[n]the hideout![n][f 1 1][e]

[msg quest56_3]
[f 0 5 65278][f 2 1]I successfully changed Takase's guardians' hearts for[n]Kawakami.[n][f 1 1][e]

[msg quest57_0]
[f 0 5 65278][f 2 1]Ohya wants to investigate the case of her missing[n]partner, but her boss is stopping her.[n][f 1 1][e]

[msg quest57_1]
[f 0 5 65278][f 2 1]Let's change Ohya's boss's heart so Ohya can[n]investigate why her partner is missing.[n][f 1 1][e]

[msg quest57_2]
[f 0 5 65278][f 2 1]I want to stop Ohya's boss from interfering with[n]Ohya. We have a name—let's meet at the hideout![n][f 1 1][e]

[msg quest57_3]
[f 0 5 65278][f 2 1]I successfully changed Ohya's boss's heart for Ohya.[n][f 1 1][e]

[msg quest58_0]
[f 0 5 65278][f 2 1]Mitsuyo Togo is a stage mother who controls her[n]daughter Hifumi...[n][f 1 1][e]

[msg quest58_1]
[f 0 5 65278][f 2 1]Let's change Hifumi's mother's heart in Mementos[n]and solve Hifumi's problem.[n][f 1 1][e]

[msg quest58_2]
[f 0 5 65278][f 2 1]Hifumi is in anguish after her mother urged her to[n]throw a match. Let's meet at the hideout![n][f 1 1][e]

[msg quest58_3]
[f 0 5 65278][f 2 1]I successfully changed Hifumi's mother's heart for[n]Hifumi.[n][f 1 1][e]

[msg quest59_0]
[f 0 5 65278][f 2 1]Futaba's best friend Kana is being exploited by her[n]parents...[n][f 1 1][e]

[msg quest59_1]
[f 0 5 65278][f 2 1]Let's change Kana's parents' hearts in Mementos so[n]we can solve Futaba's problem.[n][f 1 1][e]

[msg quest59_2]
[f 0 5 65278][f 2 1]I want to save Futaba's best friend. We have their[n]names, so let's meet up at the hideout.[n][f 1 1][e]

[msg quest59_3]
[f 0 5 65278][f 2 1]I successfully changed Kana's parents' hearts for[n]Futaba.[n][f 1 1][e]

[msg quest60_0]
[f 0 5 65278][f 2 1]Futaba's uncle is trying to take parental custody of[n]Futaba from Boss...[n][f 1 1][e]

[msg quest60_1]
[f 0 5 65278][f 2 1]Let's change Futaba's uncle's heart in Mementos and[n]solve Sojiro's problem.[n][f 1 1][e]

[msg quest60_2]
[f 0 5 65278][f 2 1]I have to stop Futaba's uncle from threatening[n]Leblanc. Let's talk to Futaba and figure something[n]out.[n][f 1 1][e]

[msg quest60_3]
[f 0 5 65278][f 2 1]I successfully changed Futaba's uncle's heart for[n]Sojiro's sake.[n][f 1 1][e]

[msg quest70_0]
[f 0 5 65278][f 2 1]秘宝NPC解禁クエ の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest70_1]
[f 0 5 65278][f 2 1]秘宝NPC解禁クエ を調査中[n]ターゲットは誰だ?[n][f 1 1][e]

[msg quest70_2]
[f 0 5 65278][f 2 1]I obtained information on the target.[n]We have a name now, so let's meet up[n]at the hideout![n][f 1 1][e]

[msg quest70_3]
[f 0 5 65278][f 2 1]Let's steal the target's heart in Mementos![n][f 1 1][e]

[msg quest70_4]
[f 0 5 65278][f 2 1]I successfully changed the target's heart. Let's[n]return to the real world and see what happens.[n][f 1 1][e]

[msg quest70_5]
[f 0 5 65278][f 2 1]It looks like I was able to change the target's heart.[n][f 1 1][e]

[msg quest71_0]
[f 0 5 65278][f 2 1]せめて、心だけでも の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest71_1]
[f 0 5 65278][f 2 1]せめて、心だけでも を調査中[n]ターゲットは誰だ?[n][f 1 1][e]

[msg quest71_2]
[f 0 5 65278][f 2 1]Ryuji told me about an unreasonable complainer.[n]We have a name, so let's meet up at the hideout![n]The Meta-Nav says "Skill Card: Charge."[n][f 1 1][e]

[msg quest71_3]
[f 0 5 65278][f 2 1]Let's change the unreasonable complainer's heart in[n]Mementos and save the accessory store in Shibuya.[n]The Meta-Nav says "Skill Card: Charge."[n][f 1 1][e]

[msg quest71_4]
[f 0 5 65278][f 2 1]I successfully changed the unreasonable complainer's[n]heart. Let's return to the real world and see what[n]happens.[n][f 1 1][e]

[msg quest71_5]
[f 0 5 65278][f 2 1]I successfully changed the unreasonable[n]complainer's heart. It seems that peace has[n]returned to the accessory store in Shibuya.[n][f 1 1][e]

[msg quest72_0]
[f 0 5 65278][f 2 1]町から猫が消えたなら の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest72_1]
[f 0 5 65278][f 2 1]Morgana told me about some cat abductions that[n]are happening. Ask around Yongen for information![n][f 1 1][e]

[msg quest72_2]
[f 0 5 65278][f 2 1]I've gathered information on the cat abductions.[n]Let's meet at the hideout and go to Mementos![n][f 1 1][e]

[msg quest72_3]
[f 0 5 65278][f 2 1]I've gathered information on the cat abductions.[n]Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest72_4]
[f 0 5 65278][f 2 1]I successfully changed the cat abductor's heart.[n]Let's return to the real world and see what happens.[n][f 1 1][e]

[msg quest72_5]
[f 0 5 65278][f 2 1]I successfully changed the cat abductor's heart.[n]Hopefully we'll see cats in Yongen again.[n][f 1 1][e]

[msg quest73_0]
[f 0 5 65278][f 2 1]くすんだ栄光 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest73_1]
[f 0 5 65278][f 2 1]Ann told me about someone who hates Shiho.[n]Ask around the school courtyard for information.[n][f 1 1][e]

[msg quest73_2]
[f 0 5 65278][f 2 1]I've gathered information on the person who[n]hates Shiho. We have a name, so let's meet up[n]at the hideout![n][f 1 1][e]

[msg quest73_3]
[f 0 5 65278][f 2 1]I've gathered information on the person who hates[n]Shiho. Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest73_4]
[f 0 5 65278][f 2 1]I successfully changed the target's heart. Let's[n]return to the real world and see what happens.[n][f 1 1][e]

[msg quest73_5]
[f 0 5 65278][f 2 1]I successfully changed the target's heart.[n]Ann will be relieved.[n][f 1 1][e]

[msg quest74_0]
[f 0 5 65278][f 2 1]虚構の通貨 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest74_1]
[f 0 5 65278][f 2 1]Makoto told me about a woman committing[n]investment frauds. Ask around for info in Shibuya[n]and Shinjuku![n][f 1 1][e]

[msg quest74_2]
[f 0 5 65278][f 2 1]I've gathered information on the woman committing[n]investment frauds. Let's meet up at the hideout and[n]go to Mementos![n][f 1 1][e]

[msg quest74_3]
[f 0 5 65278][f 2 1]I've gathered information on the woman committing[n]investment frauds. Let's change the target's heart in[n]Mementos![n][f 1 1][e]

[msg quest74_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the woman who[n]was committing investment frauds. Let's return to[n]the real world and see what happens.[n][f 1 1][e]

[msg quest74_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the woman who[n]was committing investment frauds. The fraud victims[n]have seen justice.[n][f 1 1][e]

[msg quest75_0]
[f 0 5 65278][f 2 1]冴えないオタクのアンビバレンス の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest75_1]
[f 0 5 65278][f 2 1]Futaba told me about "Tackle," who has been[n]causing problems in Akihabara. Ask around for[n]info in Akihabara and Shinjuku![n][f 1 1][e]

[msg quest75_2]
[f 0 5 65278][f 2 1]I've gathered information on "Tackle," the man who's[n]been causing problems in Akihabara. Let's meet up at[n]the hideout and go to Mementos![n][f 1 1][e]

[msg quest75_3]
[f 0 5 65278][f 2 1]I've gathered information on "Tackle," the man[n]who's been causing problems in Akihabara. Let's[n]change the target's heart in Mementos![n][f 1 1][e]

[msg quest75_4]
[f 0 5 65278][f 2 1]I've successfully changed "Tackle's" heart. Let's[n]return to the real world and see what happens.[n][f 1 1][e]

[msg quest75_5]
[f 0 5 65278][f 2 1]I've successfully changed "Tackle's" heart.[n]Peace has returned to Akihabara.[n][f 1 1][e]

[msg quest76_0]
[f 0 5 65278][f 2 1]日本画と同人誌 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest76_1]
[f 0 5 65278][f 2 1]Yusuke told me about a popular doujin artist[n]who's been suspected of plagiarism. Ask around[n]in Akihabara and gather information![n][f 1 1][e]

[msg quest76_2]
[f 0 5 65278][f 2 1]I've gathered information on the popular doujin[n]artist who's suspected of plagiarism. Let's meet up[n]at the hideout and go to Mementos![n][f 1 1][e]

[msg quest76_3]
[f 0 5 65278][f 2 1]I've gathered information on the popular doujin[n]artist who's suspected of plagiarism. Let's change[n]the target's heart in Mementos![n][f 1 1][e]

[msg quest76_4]
[f 0 5 65278][f 2 1]I've gathered information on the popular doujin[n]artist who's suspected of plagiarism. Let's return[n]to the real world and see what happens.[n][f 1 1][e]

[msg quest76_5]
[f 0 5 65278][f 2 1]I've gathered information on the popular doujin[n]artist who's suspected of plagiarism. She's repented[n]and will work harder to write manga from now on.[n][f 1 1][e]

[msg quest77_0]
[f 0 5 65278][f 2 1]奇跡のドリンク の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest77_1]
[f 0 5 65278][f 2 1]Haru told me about a dishonest businessperson[n]dealing in health foods. Ask around for info in[n]Yongen-Jaya![n][f 1 1][e]

[msg quest77_2]
[f 0 5 65278][f 2 1]I've gathered information on the shady health[n]food business. Let's meet at the hideout and go[n]to Mementos![n][f 1 1][e]

[msg quest77_3]
[f 0 5 65278][f 2 1]I've gathered information on the shady health food[n]business. Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest77_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the dishonest[n]health food seller. Let's return to the real world[n]and see what happens.[n][f 1 1][e]

[msg quest77_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the dishonest[n]health foods seller. Now more people will be able[n]to seek proper treatment.[n][f 1 1][e]

[msg quest78_0]
[f 0 5 65278][f 2 1]偶像とÜ角獣 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest78_1]
[f 0 5 65278][f 2 1]I heard about a man who's overly obsessed[n]with idols. Ask around in Akihabara and gather[n]information![n][f 1 1][e]

[msg quest78_2]
[f 0 5 65278][f 2 1]I gathered information on the man who's overly[n]obsessed with idols in Akihabara. Let's meet up[n]at the hideout and go to Mementos![n][f 1 1][e]

[msg quest78_3]
[f 0 5 65278][f 2 1]I gathered information on the man who's overly[n]obsessed with idols in Akihabara. Let's change the[n]target's heart in Mementos![n][f 1 1][e]

[msg quest78_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the man who[n]was overly obsessed with idols. Let's return to the[n]real world and see what happens.[n][f 1 1][e]

[msg quest78_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the man who[n]was overly obsessed with idols. Now his family[n]will have peace again.[n][f 1 1][e]

[msg quest79_0]
[f 0 5 65278][f 2 1]代議士と声なき¼頼人 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest79_1]
[f 0 5 65278][f 2 1]I heard about a false accusation incident that[n]happened on Central Street. I should cooperate[n]with Akechi and gather more information![n][f 1 1][e]

[msg quest79_2]
[f 0 5 65278][f 2 1]I gathered information on the false accusation[n]incident. Let's meet up at the hideout and go to[n]Mementos![n][f 1 1][e]

[msg quest79_3]
[f 0 5 65278][f 2 1]I gathered information on the false accusation[n]incident. Let's change the target's heart in[n]Mementos![n][f 1 1][e]

[msg quest79_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of congressman[n]who pressed false charges against his son. Let's[n]return to the real world and see what happens.[n][f 1 1][e]

[msg quest79_5]
[f 0 5 65278][f 2 1]I successfully changed the congressman who[n]pressed false charges against his son. The son[n]was also arrested for extortion.[n][f 1 1][e]

[msg quest80_0]
[f 0 5 65278][f 2 1]フェイクマン・ショー の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest80_1]
[f 0 5 65278][f 2 1]I heard about AIMaask OUZI. I should ask students[n]around Kichijoji during the afternoon![n][f 1 1][e]

[msg quest80_2]
[f 0 5 65278][f 2 1]I gathered information on AIMaask OUZI. Let's[n]meet up at the hideout and go to Mementos![n][f 1 1][e]

[msg quest80_3]
[f 0 5 65278][f 2 1]I gathered information on AIMaask OUZI. Let's[n]change the target's heart in Mementos![n][f 1 1][e]

[msg quest80_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of AIMaask OUZI.[n]Let's return to the real world and see what happens.[n][f 1 1][e]

[msg quest80_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of AIMaask OUZI.[n]His family will finally have peace.[n][f 1 1][e]

[msg quest81_0]
[f 0 5 65278][f 2 1]色男のバラッド の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest81_1]
[f 0 5 65278][f 2 1]色男のバラッド を調査中[n]ターゲットは誰だ?[n][f 1 1][e]

[msg quest81_2]
[f 0 5 65278][f 2 1]I heard about a cruel womanizer from Ann. Let's[n]meet up at the hideout and go to Mementos![n][f 1 1][e]

[msg quest81_3]
[f 0 5 65278][f 2 1]I heard about a cruel womanizer from Ann.[n]Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest81_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the cruel[n]womanizer. Let's return to the real world and[n]see what happens.[n][f 1 1][e]

[msg quest81_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the cruel[n]womanizer. The women can be at ease now.[n][f 1 1][e]

[msg quest82_0]
[f 0 5 65278][f 2 1]老人狂騒曲 の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest82_1]
[f 0 5 65278][f 2 1]Mishima told you about an old man causing trouble.[n]Ask around for info in Kichijoji at night![n][f 1 1][e]

[msg quest82_2]
[f 0 5 65278][f 2 1]I gathered information on the trouble making[n]old man. Let's meet up at the hideout and go to[n]Mementos![n][f 1 1][e]

[msg quest82_3]
[f 0 5 65278][f 2 1]I gathered information on the trouble making old[n]man. Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest82_4]
[f 0 5 65278][f 2 1]I changed the heart of the old man causing trouble[n]in Kichijoji at night. Let's return to the real world[n]and see what happens.[n][f 1 1][e]

[msg quest82_5]
[f 0 5 65278][f 2 1]I changed the heart of the old man causing trouble[n]in Kichijoji at night. Now peace will return to Kichijoji.[n][f 1 1][e]

[msg quest83_0]
[f 0 5 65278][f 2 1]理想と現実の狭間で の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest83_1]
[f 0 5 65278][f 2 1]Sumire told you about a table tennis player who's[n]been accused of playing fixed matches. Ask around[n]for info in Shibuya![n][f 1 1][e]

[msg quest83_2]
[f 0 5 65278][f 2 1]I've gathered information on the table tennis player[n]who's been accused of playing fixed matches. Let's[n]meet up at the hideout and go to Mementos![n][f 1 1][e]

[msg quest83_3]
[f 0 5 65278][f 2 1]I've gathered information on the table tennis player[n]who's been accused of playing fixed matches. Let's[n]change the target's heart in Mementos![n][f 1 1][e]

[msg quest83_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the table tennis[n]player who's been accused of playing fixed matches.[n]Let's return to the real world and see what happens.[n][f 1 1][e]

[msg quest83_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the table tennis[n]player who's been accused of playing fixed matches.[n]Let's hope that she can shine once more.[n][f 1 1][e]

[msg quest84_0]
[f 0 5 65278][f 2 1]僕が僕であるために の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest84_1]
[f 0 5 65278][f 2 1]仮[n][f 1 1][e]

[msg quest84_2]
[f 0 5 65278][f 2 1]Mishima told me about a boy who wishes for his[n]own death. Let's meet up at the hideout and go to[n]Mementos![n][f 1 1][e]

[msg quest84_3]
[f 0 5 65278][f 2 1]I obtained information on the boy who wishes[n]for his own death. Let's change the target's heart[n]in Mementos![n][f 1 1][e]

[msg quest84_4]
[f 0 5 65278][f 2 1]I successfully changed the boy's heart. Let's return[n]to the real world and see what happens.[n][f 1 1][e]

[msg quest84_5]
[f 0 5 65278][f 2 1]I successfully changed the boy's heart. Now the[n]siblings can have peace again.[n][f 1 1][e]

[msg quest85_0]
[f 0 5 65278][f 2 1]メメントス最奥部クエストボス の概要[n]何が起きてる?[n][f 1 1][e]

[msg quest85_1]
[f 0 5 65278][f 2 1]メメントス最奥部クエストボス を調査中[n]ターゲットは誰だ?[n][f 1 1][e]

[msg quest85_2]
[f 0 5 65278][f 2 1]Futaba told me about a mother who neglects her[n]daughter. Let's meet up at the hideout and go to[n]Mementos![n][f 1 1][e]

[msg quest85_3]
[f 0 5 65278][f 2 1]I heard about a mother who neglects her daughter.[n]Let's change the target's heart in Mementos![n][f 1 1][e]

[msg quest85_4]
[f 0 5 65278][f 2 1]I successfully changed the heart of the negligent[n]mother. Let's go back to the real world and see[n]what happens.[n][f 1 1][e]

[msg quest85_5]
[f 0 5 65278][f 2 1]I successfully changed the heart of the negligent[n]mother. Peace will return to the family.[n][f 1 1][e]

