[msg skill_000]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_001]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_002]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_003]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_004]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_005]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_006]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_007]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_008]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_009]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_00A]
[f 0 5 65278][f 2 1]Light Fire dmg to[n]one foe. Chance of[n]inflicting Burn.[n][e]

[msg skill_00B]
[f 0 5 65278][f 2 1]Medium Fire dmg to[n]one foe. Chance of[n]inflicting Burn.[n][e]

[msg skill_00C]
[f 0 5 65278][f 2 1]Heavy Fire dmg to[n]one foe. Chance of[n]inflicting Burn.[n][e]

[msg skill_00D]
[f 0 5 65278][f 2 1]Light Fire dmg to[n]all foes. Chance of[n]inflicting Burn.[n][e]

[msg skill_00E]
[f 0 5 65278][f 2 1]Medium Fire dmg to[n]all foes. Chance of[n]inflicting Burn.[n][e]

[msg skill_00F]
[f 0 5 65278][f 2 1]Heavy Fire dmg to[n]all foes. Chance of[n]inflicting Burn.[n][e]

[msg skill_010]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_011]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_012]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_013]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_014]
[f 0 5 65278][f 2 1]Light Ice dmg to[n]one foe. Chance of[n]inflicting Freeze.[n][e]

[msg skill_015]
[f 0 5 65278][f 2 1]Medium Ice dmg to[n]one foe. Chance of[n]inflicting Freeze.[n][e]

[msg skill_016]
[f 0 5 65278][f 2 1]Heavy Ice dmg to[n]one foe. Chance of[n]inflicting Freeze.[n][e]

[msg skill_017]
[f 0 5 65278][f 2 1]Light Ice dmg to[n]all foes. Chance of[n]inflicting Freeze.[n][e]

[msg skill_018]
[f 0 5 65278][f 2 1]Medium Ice dmg to[n]all foes. Chance of[n]inflicting Freeze.[n][e]

[msg skill_019]
[f 0 5 65278][f 2 1]Heavy Ice dmg to[n]all foes. Chance of[n]inflicting Freeze.[n][e]

[msg skill_01A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_01B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_01C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_01D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_01E]
[f 0 5 65278][f 2 1]Light Wind dmg[n]to one foe.[n][e]

[msg skill_01F]
[f 0 5 65278][f 2 1]Medium Wind dmg[n]to one foe.[n][e]

[msg skill_020]
[f 0 5 65278][f 2 1]Heavy Wind dmg[n]to one foe.[n][e]

[msg skill_021]
[f 0 5 65278][f 2 1]Light Wind dmg[n]to all foes.[n][e]

[msg skill_022]
[f 0 5 65278][f 2 1]Medium Wind dmg[n]to all foes.[n][e]

[msg skill_023]
[f 0 5 65278][f 2 1]Heavy Wind dmg[n]to all foes.[n][e]

[msg skill_024]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_025]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_026]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_027]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_028]
[f 0 5 65278][f 2 1]Light Elec dmg to[n]one foe. Chance of[n]inflicting Shock.[n][e]

[msg skill_029]
[f 0 5 65278][f 2 1]Medium Elec dmg[n]to one foe. Chance of[n]inflicting Shock.[n][e]

[msg skill_02A]
[f 0 5 65278][f 2 1]Heavy Elec dmg to[n]one foe. Chance of[n]inflicting Shock.[n][e]

[msg skill_02B]
[f 0 5 65278][f 2 1]Light Elec dmg to[n]all foes. Chance of[n]inflicting Shock.[n][e]

[msg skill_02C]
[f 0 5 65278][f 2 1]Medium Elec dmg[n]to all foes. Chance[n]of inflicting Shock.[n][e]

[msg skill_02D]
[f 0 5 65278][f 2 1]Heavy Elec dmg to[n]all foes. Chance of[n]inflicting Shock.[n][e]

[msg skill_02E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_02F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_030]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_031]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_032]
[f 0 5 65278][f 2 1]Low chance of Bless[n]insta-kill to one[n]foe.[n][e]

[msg skill_033]
[f 0 5 65278][f 2 1]Medium chance of[n]Bless insta-kill[n]to one foe.[n][e]

[msg skill_034]
[f 0 5 65278][f 2 1]Low chance of Bless[n]insta-kill to all[n]foes.[n][e]

[msg skill_035]
[f 0 5 65278][f 2 1]Medium chance of[n]Bless insta-kill[n]to all foes.[n][e]

[msg skill_036]
[f 0 5 65278][f 2 1]Light Bless dmg[n]to one foe.[n][e]

[msg skill_037]
[f 0 5 65278][f 2 1]Medium Bless dmg[n]to one foe.[n][e]

[msg skill_038]
[f 0 5 65278][f 2 1]Heavy Bless dmg[n]to one foe.[n][e]

[msg skill_039]
[f 0 5 65278][f 2 1]Light Bless dmg[n]to all foes.[n][e]

[msg skill_03A]
[f 0 5 65278][f 2 1]Medium Bless dmg[n]to all foes.[n][e]

[msg skill_03B]
[f 0 5 65278][f 2 1]Heavy Bless dmg[n]to all foes.[n][e]

[msg skill_03C]
[f 0 5 65278][f 2 1]Low chance of Curse[n]insta-kill to one[n]foe.[n][e]

[msg skill_03D]
[f 0 5 65278][f 2 1]Medium chance of[n]Curse insta-kill[n]to one foe.[n][e]

[msg skill_03E]
[f 0 5 65278][f 2 1]Low chance of Curse[n]insta-kill to all[n]foes.[n][e]

[msg skill_03F]
[f 0 5 65278][f 2 1]Medium chance of[n]Curse insta-kill[n]to all foes.[n][e]

[msg skill_040]
[f 0 5 65278][f 2 1]Light Curse dmg[n]to one foe.[n][e]

[msg skill_041]
[f 0 5 65278][f 2 1]Medium Curse dmg[n]to one foe.[n][e]

[msg skill_042]
[f 0 5 65278][f 2 1]Heavy Curse dmg[n]to one foe.[n][e]

[msg skill_043]
[f 0 5 65278][f 2 1]Light Curse dmg[n]to all foes.[n][e]

[msg skill_044]
[f 0 5 65278][f 2 1]Medium Curse dmg[n]to all foes.[n][e]

[msg skill_045]
[f 0 5 65278][f 2 1]Heavy Curse dmg[n]to all foes.[n][e]

[msg skill_046]
[f 0 5 65278][f 2 1]Medium Almighty dmg[n]to all foes.[n][e]

[msg skill_047]
[f 0 5 65278][f 2 1]Heavy Almighty dmg[n]to all foes.[n][e]

[msg skill_048]
[f 0 5 65278][f 2 1]Severe Almighty dmg[n]to all foes.[n][e]

[msg skill_049]
[f 0 5 65278][f 2 1]Light Nuke dmg[n]to one foe.[n][e]

[msg skill_04A]
[f 0 5 65278][f 2 1]Medium Nuke dmg[n]to one foe.[n][e]

[msg skill_04B]
[f 0 5 65278][f 2 1]Heavy Nuke dmg[n]to one foe.[n][e]

[msg skill_04C]
[f 0 5 65278][f 2 1]Light Nuke dmg[n]to all foes.[n][e]

[msg skill_04D]
[f 0 5 65278][f 2 1]Medium Nuke dmg[n]to all foes.[n][e]

[msg skill_04E]
[f 0 5 65278][f 2 1]Heavy Nuke dmg[n]to all foes.[n][e]

[msg skill_04F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_050]
[f 0 5 65278][f 2 1]High chance of[n]Dizzy to one foe.[n][e]

[msg skill_051]
[f 0 5 65278][f 2 1]Medium chance of[n]Dizzy to all foes.[n][e]

[msg skill_052]
[f 0 5 65278][f 2 1]High chance of[n]Confuse to one foe.[n][e]

[msg skill_053]
[f 0 5 65278][f 2 1]Medium chance of[n]Confuse to all foes.[n][e]

[msg skill_054]
[f 0 5 65278][f 2 1]High chance of[n]Fear to one foe.[n][e]

[msg skill_055]
[f 0 5 65278][f 2 1]Medium chance of[n]Fear to all foes.[n][e]

[msg skill_056]
[f 0 5 65278][f 2 1]High chance of[n]Forget to one foe.[n][e]

[msg skill_057]
[f 0 5 65278][f 2 1]Medium chance of[n]Forget to all foes.[n][e]

[msg skill_058]
[f 0 5 65278][f 2 1]High chance of[n]Hunger to one foe.[n][e]

[msg skill_059]
[f 0 5 65278][f 2 1]Medium chance of[n]Hunger to all foes.[n][e]

[msg skill_05A]
[f 0 5 65278][f 2 1]High chance of[n]Sleep to one foe.[n][e]

[msg skill_05B]
[f 0 5 65278][f 2 1]Medium chance of[n]Sleep to all foes.[n][e]

[msg skill_05C]
[f 0 5 65278][f 2 1]High chance of[n]Rage to one foe.[n][e]

[msg skill_05D]
[f 0 5 65278][f 2 1]Medium chance of[n]Rage to all foes.[n][e]

[msg skill_05E]
[f 0 5 65278][f 2 1]High chance of[n]Despair to one foe.[n][e]

[msg skill_05F]
[f 0 5 65278][f 2 1]Medium chance of[n]Despair to all foes.[n][e]

[msg skill_060]
[f 0 5 65278][f 2 1]High chance of[n]Brainwash to one foe.[n][e]

[msg skill_061]
[f 0 5 65278][f 2 1]Medium chance of[n]Brainwash to all foes.[n][e]

[msg skill_062]
[f 0 5 65278][f 2 1]High chance of[n]Mouse to one foe.[n][e]

[msg skill_063]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_064]
[f 0 5 65278][f 2 1]Medium Almighty[n]dmg to all.[n][e]

[msg skill_065]
[f 0 5 65278][f 2 1]Medium Almighty[n]dmg to all.[n][e]

[msg skill_066]
[f 0 5 65278][f 2 1]Heavy Almighty[n]dmg to all.[n][e]

[msg skill_067]
[f 0 5 65278][f 2 1]Drains HP from[n]one foe.[n][e]

[msg skill_068]
[f 0 5 65278][f 2 1]Drains SP from[n]one foe.[n][e]

[msg skill_069]
[f 0 5 65278][f 2 1]Drains high amount[n]of HP from one foe.[n][e]

[msg skill_06A]
[f 0 5 65278][f 2 1]Drains high amount[n]of SP from one foe.[n][e]

[msg skill_06B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_06C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_06D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_06E]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting ailments[n]to one foe.[n][e]

[msg skill_06F]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting ailments[n]to all.[n][e]

[msg skill_070]
[f 0 5 65278][f 2 1]High chance of[n]Rage to one foe.[n][e]

[msg skill_071]
[f 0 5 65278][f 2 1]Insta-kills foes[n]inflicted with Fear.[n][e]

[msg skill_072]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_073]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_074]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_075]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_076]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_077]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_078]
[f 0 5 65278][f 2 1]Severe Fire dmg to[n]one foe. Chance of[n]inflicting Burn.[n][e]

[msg skill_079]
[f 0 5 65278][f 2 1]Severe Fire dmg to[n]all foes. Chance of[n]inflicting Burn.[n][e]

[msg skill_07A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_07B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_07C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_07D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_07E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_07F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_080]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_081]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_082]
[f 0 5 65278][f 2 1]Severe Ice dmg to[n]one foe. Chance of[n]inflicting Freeze.[n][e]

[msg skill_083]
[f 0 5 65278][f 2 1]Severe Ice dmg to[n]all foes. Chance of[n]inflicting Freeze.[n][e]

[msg skill_084]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_085]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_086]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_087]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_088]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_089]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_08A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_08B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_08C]
[f 0 5 65278][f 2 1]Severe Wind dmg[n]to one foe.[n][e]

[msg skill_08D]
[f 0 5 65278][f 2 1]Severe Wind dmg[n]to all foes.[n][e]

[msg skill_08E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_08F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_090]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_091]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_092]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_093]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_094]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_095]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_096]
[f 0 5 65278][f 2 1]Severe Elec dmg[n]to one foe. Chance[n]of inflicting Shock.[n][e]

[msg skill_097]
[f 0 5 65278][f 2 1]Severe Elec dmg to[n]all foes. Chance of[n]inflicting Shock.[n][e]

[msg skill_098]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_099]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_09F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A0]
[f 0 5 65278][f 2 1]Bless attack that[n]reduces HP of one[n]foe by 50%.[n][e]

[msg skill_0A1]
[f 0 5 65278][f 2 1]High chance of Bless[n]insta-kill to all[n]foes.[n][e]

[msg skill_0A2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0A9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0AA]
[f 0 5 65278][f 2 1]Curse attack that[n]reduces HP of one[n]foe by 50%.[n][e]

[msg skill_0AB]
[f 0 5 65278][f 2 1]High chance of Curse[n]insta-kill to all[n]foes.[n][e]

[msg skill_0AC]
[f 0 5 65278][f 2 1]Activates Masukunda,[n]Marakunda, and[n]Matarunda.[n][e]

[msg skill_0AD]
[f 0 5 65278][f 2 1]Activates Masukunda[n]and Marakunda.[n][e]

[msg skill_0AE]
[f 0 5 65278][f 2 1]Activates Masukunda.[n][e]

[msg skill_0AF]
[f 0 5 65278][f 2 1]Increases activation[n]of Moral Support.[n][e]

[msg skill_0B0]
[f 0 5 65278][f 2 1]Severe Nuke dmg[n]to one foe.[n][e]

[msg skill_0B1]
[f 0 5 65278][f 2 1]Severe Nuke dmg[n]to all foes.[n][e]

[msg skill_0B2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0B3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0B4]
[f 0 5 65278][f 2 1]Severe Almighty dmg[n]to one foe.[n][e]

[msg skill_0B5]
[f 0 5 65278][f 2 1]Severe Almighty dmg[n]to all foes.[n][e]

[msg skill_0B6]
[f 0 5 65278][f 2 1]Severe Almighty dmg[n]to all foes.[n][e]

[msg skill_0B7]
[f 0 5 65278][f 2 1]Restores med amount of HP[n]and increases Attack for[n]one ally for 3 turns.[n][e]

[msg skill_0B8]
[f 0 5 65278][f 2 1]Forms a barrier that can[n]absorb one attack (except[n]Almighty).[n][e]

[msg skill_0B9]
[f 0 5 65278][f 2 1]Increases Defense for[n]all allies for 3 turns.[n][e]

[msg skill_0BA]
[f 0 5 65278][f 2 1]Cures all non-special[n]ailments for all allies.[n][e]

[msg skill_0BB]
[f 0 5 65278][f 2 1]Next magical attack[n]deals over double the[n]damage for one ally.[n][e]

[msg skill_0BC]
[f 0 5 65278][f 2 1]Increases Agility for[n]all allies for 3 turns.[n][e]

[msg skill_0BD]
[f 0 5 65278][f 2 1]Next physical attack [n]deals over double the [n]damage for one ally.[n][e]

[msg skill_0BE]
[f 0 5 65278][f 2 1]Light Psy dmg[n]to one foe.[n][e]

[msg skill_0BF]
[f 0 5 65278][f 2 1]Medium Psy dmg[n]to one foe.[n][e]

[msg skill_0C0]
[f 0 5 65278][f 2 1]Heavy Psy dmg[n]to one foe.[n][e]

[msg skill_0C1]
[f 0 5 65278][f 2 1]Light Psy dmg[n]to all foes.[n][e]

[msg skill_0C2]
[f 0 5 65278][f 2 1]Medium Psy dmg[n]to all foes.[n][e]

[msg skill_0C3]
[f 0 5 65278][f 2 1]Heavy Psy dmg[n]to all foes.[n][e]

[msg skill_0C4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0C5]
[f 0 5 65278][f 2 1]Severe Psy dmg[n]to one foe.[n][e]

[msg skill_0C6]
[f 0 5 65278][f 2 1]Severe Psy dmg[n]to all foes.[n][e]

[msg skill_0C7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0C8]
[f 0 5 65278][f 2 1]Light Phys dmg[n]to one foe.[n][e]

[msg skill_0C9]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to one foe.[n][e]

[msg skill_0CA]
[f 0 5 65278][f 2 1]Severe Phys dmg[n]to one foe.[n][e]

[msg skill_0CB]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe.[n][e]

[msg skill_0CC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0CD]
[f 0 5 65278][f 2 1]Miniscule Phys dmg[n]to one foe with high[n]chance of Critical.[n][e]

[msg skill_0CE]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe with high[n]chance of Critical.[n][e]

[msg skill_0CF]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]one foe 1-3 times.[n][e]

[msg skill_0D0]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]one foe 3-4 times.[n][e]

[msg skill_0D1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0D2]
[f 0 5 65278][f 2 1]Light Phys dmg[n]to one foe.[n][e]

[msg skill_0D3]
[f 0 5 65278][f 2 1]Medium Phys dmg to[n]one foe. Powers up[n]after a Baton Pass.[n][e]

[msg skill_0D4]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe.[n][e]

[msg skill_0D5]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe with high[n]chance of Critical.[n][e]

[msg skill_0D6]
[f 0 5 65278][f 2 1]Revives all fallen[n]allies to full HP.[n][e]

[msg skill_0D7]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]all foes 8 times.[n][e]

[msg skill_0D8]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe 3 times[n]with high Accuracy.[n][e]

[msg skill_0D9]
[f 0 5 65278][f 2 1]Severe Phys dmg[n]to one foe. Medium[n]chance of Fear.[n][e]

[msg skill_0DA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0DB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0DC]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Powers[n]up when surrounded.[n][e]

[msg skill_0DD]
[f 0 5 65278][f 2 1]Heavy Phys dmg to[n]one foe. Powers up[n]after a Baton Pass.[n][e]

[msg skill_0DE]
[f 0 5 65278][f 2 1]Severe Phys dmg to[n]one foe. Powers up[n]after a Baton Pass.[n][e]

[msg skill_0DF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0E0]
[f 0 5 65278][f 2 1]Medium Gun dmg[n]to one foe.[n][e]

[msg skill_0E1]
[f 0 5 65278][f 2 1]Light Gun dmg to[n]all foes 3 times.[n][e]

[msg skill_0E2]
[f 0 5 65278][f 2 1]Severe Gun dmg to[n]one foe with high[n]chance of Critical.[n][e]

[msg skill_0E3]
[f 0 5 65278][f 2 1]Severe Gun dmg[n]to all foes.[n][e]

[msg skill_0E4]
[f 0 5 65278][f 2 1]Light Gun dmg to[n]one foe 2 times.[n][e]

[msg skill_0E5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0E6]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes.[n][e]

[msg skill_0E7]
[f 0 5 65278][f 2 1]Severe Phys dmg[n]to all foes.[n][e]

[msg skill_0E8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0E9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0EA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0EB]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes.[n][e]

[msg skill_0EC]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to all foes.[n][e]

[msg skill_0ED]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to all foes.[n][e]

[msg skill_0EE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0EF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0F0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0F1]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]all foes 1-3 times.[n][e]

[msg skill_0F2]
[f 0 5 65278][f 2 1]Miniscule Phys dmg[n]to all foes 2-4 times.[n][e]

[msg skill_0F3]
[f 0 5 65278][f 2 1]Medium Phys dmg to[n]all foes 1-2 times.[n][e]

[msg skill_0F4]
[f 0 5 65278][f 2 1]Medium Phys dmg to[n]all foes 1-3 times.[n][e]

[msg skill_0F5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0F6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0F7]
[f 0 5 65278][f 2 1]Enemy-only Skill[n][e]

[msg skill_0F8]
[f 0 5 65278][f 2 1]Enemy-only Skill[n][e]

[msg skill_0F9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0FA]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]one foe 2 times.[n][e]

[msg skill_0FB]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe.[n][e]

[msg skill_0FC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_0FD]
[f 0 5 65278][f 2 1]Miniscule Phys dmg[n]to one foe 3-5 times.[n][e]

[msg skill_0FE]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe 2-3 times.[n][e]

[msg skill_0FF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_100]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_101]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_102]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_103]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_104]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Medium[n]chance of Dizzy.[n][e]

[msg skill_105]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Medium[n]chance of Confuse.[n][e]

[msg skill_106]
[f 0 5 65278][f 2 1]Light Phys dmg to[n]one foe. Medium[n]chance of Fear.[n][e]

[msg skill_107]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Medium[n]chance of Forget.[n][e]

[msg skill_108]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to one foe. Medium[n]chance of Hunger.[n][e]

[msg skill_109]
[f 0 5 65278][f 2 1]Light Gun dmg[n]to one foe. Medium[n]chance of Sleep.[n][e]

[msg skill_10A]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Medium[n]chance of Rage.[n][e]

[msg skill_10B]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to one foe. Medium[n]chance of Despair.[n][e]

[msg skill_10C]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to one foe. Medium[n]chance of Brainwash.[n][e]

[msg skill_10D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_10E]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes. Low[n]chance of Dizzy.[n][e]

[msg skill_10F]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes. Low[n]chance of Confuse.[n][e]

[msg skill_110]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to all foes. Low[n]chance of Fear.[n][e]

[msg skill_111]
[f 0 5 65278][f 2 1]Light Phys dmg[n]to all foes. Low[n]chance of Forget.[n][e]

[msg skill_112]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to all foes. Low[n]chance of Hunger.[n][e]

[msg skill_113]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes. Low[n]chance of Sleep.[n][e]

[msg skill_114]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes. Low[n]chance of Rage.[n][e]

[msg skill_115]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes. Low[n]chance of Despair.[n][e]

[msg skill_116]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to all foes. Low[n]chance of Brainwash.[n][e]

[msg skill_117]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe.[n][e]

[msg skill_118]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_119]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_11F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_120]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_121]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_122]
[f 0 5 65278][f 2 1]Next physical attack[n]deals over double the[n]damage for all allies.[n][e]

[msg skill_123]
[f 0 5 65278][f 2 1]Medium Phys dmg[n]to all foes with high[n]chance of Critical.[n][e]

[msg skill_124]
[f 0 5 65278][f 2 1]Decreases ATK/DEF/[n]Accuracy/Evasion[n]for all foes.[n][e]

[msg skill_125]
[f 0 5 65278][f 2 1]Increases ATK/DEF/[n]Accuracy/Evasion[n]for all allies.[n][e]

[msg skill_126]
[f 0 5 65278][f 2 1]Next magical attack[n]deals over double the[n]damage for all allies.[n][e]

[msg skill_127]
[f 0 5 65278][f 2 1]Ultimate support effect of[n]strengthening/healing all[n]allies may activate in battle.[n][e]

[msg skill_128]
[f 0 5 65278][f 2 1]Forms a barrier that[n]reflects all attacks[n]for all allies.[n][e]

[msg skill_129]
[f 0 5 65278][f 2 1]Colossal Almighty dmg to[n]one foe. Highly effective[n]if foe is Downed.[n][e]

[msg skill_12A]
[f 0 5 65278][f 2 1]Severe Phys dmg[n]to one foe 2 times.[n][e]

[msg skill_12B]
[f 0 5 65278][f 2 1]Knockdown attack on all[n]foes (only usable during[n]an Ambush).[n][e]

[msg skill_12C]
[f 0 5 65278][f 2 1]Restores low[n]amount of HP[n]to one ally.[n][e]

[msg skill_12D]
[f 0 5 65278][f 2 1]Restores medium[n]amount of HP[n]to one ally.[n][e]

[msg skill_12E]
[f 0 5 65278][f 2 1]Fully restores HP[n]to one ally.[n][e]

[msg skill_12F]
[f 0 5 65278][f 2 1]Increases chance of[n]Critical for all allies[n]for 3 turns.[n][e]

[msg skill_130]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_131]
[f 0 5 65278][f 2 1]Restores low[n]amount of HP[n]to all allies.[n][e]

[msg skill_132]
[f 0 5 65278][f 2 1]Restores medium[n]amount of HP[n]to all allies.[n][e]

[msg skill_133]
[f 0 5 65278][f 2 1]Fully restores HP[n]to all allies.[n][e]

[msg skill_134]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_135]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_136]
[f 0 5 65278][f 2 1]Revives one fallen ally[n]to 50% HP.[n][e]

[msg skill_137]
[f 0 5 65278][f 2 1]Revives one fallen ally[n]to full HP.[n][e]

[msg skill_138]
[f 0 5 65278][f 2 1]Fully restores HP of all[n]allies. Reduces HP of[n]caster to 1.[n][e]

[msg skill_139]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_13A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_13B]
[f 0 5 65278][f 2 1]Cures all non-special[n]ailments for one ally.[n][e]

[msg skill_13C]
[f 0 5 65278][f 2 1]Cures all non-special[n]ailments for all allies.[n][e]

[msg skill_13D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_13E]
[f 0 5 65278][f 2 1]Fully restores HP and[n]cures non-special[n]ailments for all allies.[n][e]

[msg skill_13F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_140]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_141]
[f 0 5 65278][f 2 1]Raises own chances of[n]being targeted by foes.[n][e]

[msg skill_142]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_143]
[f 0 5 65278][f 2 1]Decreases chance of[n]being targeted by foes.[n][e]

[msg skill_144]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_145]
[f 0 5 65278][f 2 1]Cures Dizzy/Forget/[n]Sleep/Hunger[n]for one ally.[n][e]

[msg skill_146]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_147]
[f 0 5 65278][f 2 1]Cures Confuse/Fear/[n]Despair/Brainwash/[n]Rage for all allies.[n][e]

[msg skill_148]
[f 0 5 65278][f 2 1]Cures Confuse/Fear/[n]Despair/Brainwash/[n]Rage for one ally.[n][e]

[msg skill_149]
[f 0 5 65278][f 2 1]Cures Burn/Freeze/Shock[n]for one ally.[n][e]

[msg skill_14A]
[f 0 5 65278][f 2 1]Cures Dizzy/Forget/[n]Sleep/Hunger[n]for all allies.[n][e]

[msg skill_14B]
[f 0 5 65278][f 2 1]Cures Burn/Freeze/Shock[n]for all allies.[n][e]

[msg skill_14C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_14D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_14E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_14F]
[f 0 5 65278][f 2 1]Increases Attack for[n]one ally for 3 turns.[n][e]

[msg skill_150]
[f 0 5 65278][f 2 1]Increases Defense for[n]one ally for 3 turns.[n][e]

[msg skill_151]
[f 0 5 65278][f 2 1]Increases Accuracy/[n]Evasion for one ally[n]for 3 turns.[n][e]

[msg skill_152]
[f 0 5 65278][f 2 1]Increases ATK/DEF/[n]Accuracy/Evasion[n]for one ally.[n][e]

[msg skill_153]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_154]
[f 0 5 65278][f 2 1]Increases Attack for[n]all allies for 3 turns.[n][e]

[msg skill_155]
[f 0 5 65278][f 2 1]Increases Defense for[n]all allies for 3 turns.[n][e]

[msg skill_156]
[f 0 5 65278][f 2 1]Increases Accuracy/[n]Evasion for all allies[n]for 3 turns.[n][e]

[msg skill_157]
[f 0 5 65278][f 2 1]Increases ATK/DEF/[n]Accuracy/Evasion for all[n]allies when surrounded.[n][e]

[msg skill_158]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_159]
[f 0 5 65278][f 2 1]Decreases Attack for[n]one foe for 3 turns.[n][e]

[msg skill_15A]
[f 0 5 65278][f 2 1]Decreases Defense for[n]one foe for 3 turns.[n][e]

[msg skill_15B]
[f 0 5 65278][f 2 1]Decreases Accuracy/[n]Evasion for one foe[n]for 3 turns.[n][e]

[msg skill_15C]
[f 0 5 65278][f 2 1]Decreases ATK/DEF/[n]Accuracy/Evasion[n]for one foe.[n][e]

[msg skill_15D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_15E]
[f 0 5 65278][f 2 1]Decreases Attack for[n]all foes for 3 turns.[n][e]

[msg skill_15F]
[f 0 5 65278][f 2 1]Decreases Defense for[n]all foes for 3 turns.[n][e]

[msg skill_160]
[f 0 5 65278][f 2 1]Decreases Accuracy/[n]Evasion for all foes[n]for 3 turns.[n][e]

[msg skill_161]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_162]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_163]
[f 0 5 65278][f 2 1]Removes all stat [n]debuffs for all allies.[n][e]

[msg skill_164]
[f 0 5 65278][f 2 1]Removes all stat[n]buffs for all foes.[n][e]

[msg skill_165]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_166]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_167]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_168]
[f 0 5 65278][f 2 1]Next physical attack [n]deals over double[n]the damage.[n][e]

[msg skill_169]
[f 0 5 65278][f 2 1]Next magical attack [n]deals over double[n]the damage.[n][e]

[msg skill_16A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_16B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_16C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_16D]
[f 0 5 65278][f 2 1]Increases chance of[n]Critical for one ally[n]for 3 turns.[n][e]

[msg skill_16E]
[f 0 5 65278][f 2 1]Increases chance of[n]Critical for all[n]for 3 turns.[n][e]

[msg skill_16F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_170]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_171]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_172]
[f 0 5 65278][f 2 1]A barrier that reflects[n]physical attacks for[n]one ally one time.[n][e]

[msg skill_173]
[f 0 5 65278][f 2 1]A barrier that reflects[n]magical attacks for[n]one ally one time.[n][e]

[msg skill_174]
[f 0 5 65278][f 2 1]A barrier that nullifies[n]an insta-kill for all[n]allies one time.[n][e]

[msg skill_175]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_176]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_177]
[f 0 5 65278][f 2 1]Negates Tetrakarn[n]on all foes.[n][e]

[msg skill_178]
[f 0 5 65278][f 2 1]Negates Makarakarn[n]on all foes.[n][e]

[msg skill_179]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_17A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_17B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_17C]
[f 0 5 65278][f 2 1]Adds Fire resistance[n]to one ally for 3 turns.[n][e]

[msg skill_17D]
[f 0 5 65278][f 2 1]Adds Ice resistance[n]to one ally for 3 turns.[n][e]

[msg skill_17E]
[f 0 5 65278][f 2 1]Adds Elec resistance[n]to one ally for 3 turns.[n][e]

[msg skill_17F]
[f 0 5 65278][f 2 1]Adds Wind resistance[n]to one ally for 3 turns.[n][e]

[msg skill_180]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_181]
[f 0 5 65278][f 2 1]Negates Fire resistance[n]of all foes. Cannot negate[n]Fire Wall.[n][e]

[msg skill_182]
[f 0 5 65278][f 2 1]Negates Ice resistance[n]of all foes. Cannot negate[n]Ice Wall.[n][e]

[msg skill_183]
[f 0 5 65278][f 2 1]Negates Wind resistance[n]of all foes. Cannot negate[n]Wind Wall.[n][e]

[msg skill_184]
[f 0 5 65278][f 2 1]Negates Elec resistance[n]of all foes. Cannot negate[n]Elec Wall.[n][e]

[msg skill_185]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_186]
[f 0 5 65278][f 2 1]Guarantees escape from[n]battle. Not all battles apply.[n][e]

[msg skill_187]
[f 0 5 65278][f 2 1]Return to the entrance[n]of the Metaverse.[n][e]

[msg skill_188]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_189]
[f 0 5 65278][f 2 1]Adds Nuke resistance[n]to one ally for 3 turns.[n][e]

[msg skill_18A]
[f 0 5 65278][f 2 1]Adds Psy resistance[n]to one ally for 3 turns.[n][e]

[msg skill_18B]
[f 0 5 65278][f 2 1]Negates Nuke resistance[n]of all foes. Cannot negate[n]Nuke Wall.[n][e]

[msg skill_18C]
[f 0 5 65278][f 2 1]Negates Psy resistance[n]of all foes. Cannot negate[n]Psy Wall.[n][e]

[msg skill_18D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_18E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_18F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_190]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_191]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_192]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_193]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_194]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_195]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_196]
[f 0 5 65278][f 2 1]Summon one unit.[n][e]

[msg skill_197]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_198]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_199]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_19F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1A9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1AA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1AB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1AC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1AD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1AE]
[f 0 5 65278][f 2 1]Gives ability to view[n]the attribute affinities[n]of one foe.[n][e]

[msg skill_1AF]
[f 0 5 65278][f 2 1]Increases Attack for[n]all allies for 3 turns.[n][e]

[msg skill_1B0]
[f 0 5 65278][f 2 1]Increases Defense for[n]all allies for 3 turns.[n][e]

[msg skill_1B1]
[f 0 5 65278][f 2 1]Increases Accuracy/[n]Evasion for all allies[n]for 3 turns.[n][e]

[msg skill_1B2]
[f 0 5 65278][f 2 1]Increases ATK/DEF/[n]Accuracy/Evasion[n]for all allies.[n][e]

[msg skill_1B3]
[f 0 5 65278][f 2 1]Next attack deals over[n]double the damage[n]for all allies.[n][e]

[msg skill_1B4]
[f 0 5 65278][f 2 1]Restores 50% HP[n]to all allies.[n][e]

[msg skill_1B5]
[f 0 5 65278][f 2 1]Restores 10% SP[n]to all allies.[n][e]

[msg skill_1B6]
[f 0 5 65278][f 2 1]Escape 100% successfully[n]from all battles except for[n]bosses.[n][e]

[msg skill_1B7]
[f 0 5 65278][f 2 1]View how effective an[n]attack will be when[n]targeting a foe.[n][e]

[msg skill_1B8]
[f 0 5 65278][f 2 1]Restores 10% HP to[n]backup members[n]after battle.[n][e]

[msg skill_1B9]
[f 0 5 65278][f 2 1]Restores 1% SP to[n]backup members[n]after battle.[n][e]

[msg skill_1BA]
[f 0 5 65278][f 2 1]Confirm affinities of[n]enemies you have[n]previously attacked.[n][e]

[msg skill_1BB]
[f 0 5 65278][f 2 1]Confirm affinities and[n]skills of enemies you have[n]previously attacked .[n][e]

[msg skill_1BC]
[f 0 5 65278][f 2 1]Confirm enemy skills and[n]all affinities, including[n]those not yet attacked.[n][e]

[msg skill_1BD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1BE]
[f 0 5 65278][f 2 1]Miniscule Wind dmg[n]to all foes.[n][e]

[msg skill_1BF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C6]
[f 0 5 65278][f 2 1]Miniscule Phys dmg[n]to one foe 2-5 times.[n][e]

[msg skill_1C7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1C9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1CF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1D9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1DF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1E9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1EA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1EB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1EC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1ED]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1EE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1EF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1F0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1F1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1F2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1F3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_1F4]
[f 0 5 65278][f 2 1]Item:[n]Recovers 20 HP[n][e]

[msg skill_1F5]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 HP[n][e]

[msg skill_1F6]
[f 0 5 65278][f 2 1]Item:[n]Recovers 200 HP[n][e]

[msg skill_1F7]
[f 0 5 65278][f 2 1]Item:[n]Recovers 400 HP[n][e]

[msg skill_1F8]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30% HP[n][e]

[msg skill_1F9]
[f 0 5 65278][f 2 1]Item:[n]Fully recovers HP[n][e]

[msg skill_1FA]
[f 0 5 65278][f 2 1]Item:[n]All recover 100 HP[n][e]

[msg skill_1FB]
[f 0 5 65278][f 2 1]Item:[n]All recover 200 HP[n][e]

[msg skill_1FC]
[f 0 5 65278][f 2 1]Item:[n]All recover 400 HP[n][e]

[msg skill_1FD]
[f 0 5 65278][f 2 1]Item:[n]Fully recovers HP[n][e]

[msg skill_1FE]
[f 0 5 65278][f 2 1]Item:[n]Recovers 10 SP[n][e]

[msg skill_1FF]
[f 0 5 65278][f 2 1]Item:[n]Recovers 50 SP[n][e]

[msg skill_200]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 SP[n][e]

[msg skill_201]
[f 0 5 65278][f 2 1]Item:[n]Fully Recovers SP[n][e]

[msg skill_202]
[f 0 5 65278][f 2 1]Item:[n]Revive[n][e]

[msg skill_203]
[f 0 5 65278][f 2 1]Item:[n]Revives with full HP[n][e]

[msg skill_204]
[f 0 5 65278][f 2 1]Item:[n]Cures Mouse[n][e]

[msg skill_205]
[f 0 5 65278][f 2 1]Unused Item[n][e]

[msg skill_206]
[f 0 5 65278][f 2 1]Item:[n]Cures Forget/Dizzy/Sleep[n][e]

[msg skill_207]
[f 0 5 65278][f 2 1]Item:[n]Cures Confuse/Fear/Rage/[n]Despair/Brainwash[n][e]

[msg skill_208]
[f 0 5 65278][f 2 1]Unused Item[n][e]

[msg skill_209]
[f 0 5 65278][f 2 1]Item:[n]Return to Metaverse entrance[n][e]

[msg skill_20A]
[f 0 5 65278][f 2 1]Item:[n]Escape from battle[n][e]

[msg skill_20B]
[f 0 5 65278][f 2 1]Item:[n]Fully recovers HP and SP[n][e]

[msg skill_20C]
[f 0 5 65278][f 2 1]Item:[n]Cures all ailments[n]except Down and KO[n][e]

[msg skill_20D]
[f 0 5 65278][f 2 1]Item:[n]Cures all ailments[n]except Down and KO[n][e]

[msg skill_20E]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30% HP for 1 ally,[n]inflicts Rakunda and Tarukaja[n][e]

[msg skill_20F]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30% HP for 1 ally,[n]inflicts Sukunda and Tarukaja[n][e]

[msg skill_210]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30% HP for 1 ally,[n]inflicts Taranda and Sukukaja[n][e]

[msg skill_211]
[f 0 5 65278][f 2 1]Item:[n]When Joker is KO'd,[n]fully recovers all allies[n][e]

[msg skill_212]
[f 0 5 65278][f 2 1]Item:[n]A barrier that reflects[n]all but Phys/Almighty[n][e]

[msg skill_213]
[f 0 5 65278][f 2 1]Item:[n]A barrier that reflects[n]Phys skills[n][e]

[msg skill_214]
[f 0 5 65278][f 2 1]Item:[n]Attack up for all allies[n][e]

[msg skill_215]
[f 0 5 65278][f 2 1]Item:[n]Evasion up for all allies[n][e]

[msg skill_216]
[f 0 5 65278][f 2 1]Item:[n]Defense up for all allies[n][e]

[msg skill_217]
[f 0 5 65278][f 2 1]Item:[n]Attack up for all allies[n][e]

[msg skill_218]
[f 0 5 65278][f 2 1]Item:[n]Negates stat debuffs[n]for all allies[n][e]

[msg skill_219]
[f 0 5 65278][f 2 1]Item:[n]50 Fire damage[n][e]

[msg skill_21A]
[f 0 5 65278][f 2 1]Item:[n]50 Fire damage[n][e]

[msg skill_21B]
[f 0 5 65278][f 2 1]Item:[n]50 Ice damage[n][e]

[msg skill_21C]
[f 0 5 65278][f 2 1]Item:[n]50 Ice damage[n][e]

[msg skill_21D]
[f 0 5 65278][f 2 1]Item:[n]50 Wind damage[n][e]

[msg skill_21E]
[f 0 5 65278][f 2 1]Item:[n]50 Wind damage[n][e]

[msg skill_21F]
[f 0 5 65278][f 2 1]Item:[n]50 Elec damage[n][e]

[msg skill_220]
[f 0 5 65278][f 2 1]Item:[n]50 Elec damage[n][e]

[msg skill_221]
[f 0 5 65278][f 2 1]Item:[n]100 Almighty damage[n][e]

[msg skill_222]
[f 0 5 65278][f 2 1]Item:[n]Bless insta-kill[n][e]

[msg skill_223]
[f 0 5 65278][f 2 1]Item:[n]Curse insta-kill[n][e]

[msg skill_224]
[f 0 5 65278][f 2 1]Item:[n]150 Fire damage[n][e]

[msg skill_225]
[f 0 5 65278][f 2 1]Item:[n]150 Wind damage[n][e]

[msg skill_226]
[f 0 5 65278][f 2 1]Item:[n]150 Ice damage[n][e]

[msg skill_227]
[f 0 5 65278][f 2 1]Item:[n]150 Elec damage[n][e]

[msg skill_228]
[f 0 5 65278][f 2 1]Item:[n]Blocks an insta-kill attack[n][e]

[msg skill_229]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_22A]
[f 0 5 65278][f 2 1]Item:[n]50 Bless damage[n][e]

[msg skill_22B]
[f 0 5 65278][f 2 1]Item:[n]50 Bless damage[n][e]

[msg skill_22C]
[f 0 5 65278][f 2 1]Item:[n]50 Curse damage[n][e]

[msg skill_22D]
[f 0 5 65278][f 2 1]Item:[n]50 Curse damage[n][e]

[msg skill_22E]
[f 0 5 65278][f 2 1]Item:[n]50 Psy damage[n][e]

[msg skill_22F]
[f 0 5 65278][f 2 1]Item:[n]50 Psy damage[n][e]

[msg skill_230]
[f 0 5 65278][f 2 1]Item:[n]50 Nuke damage[n][e]

[msg skill_231]
[f 0 5 65278][f 2 1]Item:[n]50 Nuke damage[n][e]

[msg skill_232]
[f 0 5 65278][f 2 1]Item:[n]150 Nuke damage[n][e]

[msg skill_233]
[f 0 5 65278][f 2 1]Item:[n]150 Psy damage[n][e]

[msg skill_234]
[f 0 5 65278][f 2 1]Item:[n]150 Bless damage[n][e]

[msg skill_235]
[f 0 5 65278][f 2 1]Item:[n]150 Curse damage[n][e]

[msg skill_236]
[f 0 5 65278][f 2 1]Item:[n]Cures Hunger.[n]Moderate HP recovery.[n][e]

[msg skill_237]
[f 0 5 65278][f 2 1]Item:[n]Cures Hunger.[n]Slight HP recovery.[n][e]

[msg skill_238]
[f 0 5 65278][f 2 1]Item:[n]Recovers 10 HP for 1 ally[n][e]

[msg skill_239]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30 HP for 1 ally[n][e]

[msg skill_23A]
[f 0 5 65278][f 2 1]Item:[n]Recovers 5 SP for 1 ally[n][e]

[msg skill_23B]
[f 0 5 65278][f 2 1]Item:[n]Recovers 50 HP for 1 ally.[n]Cures ailments.[n][e]

[msg skill_23C]
[f 0 5 65278][f 2 1]Item: Recovers 30 HP for[n]1 ally. Cures Rage/Despair/[n]Brainwash/Confuse.[n][e]

[msg skill_23D]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30 HP for 1 ally.[n]Cures Burn/Freeze/Shock.[n][e]

[msg skill_23E]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30 HP for 1 ally.[n]Cures Dizzy/Forget/Sleep.[n][e]

[msg skill_23F]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30 HP for 1 ally.[n]Sukunda to self.[n][e]

[msg skill_240]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 HP for 1 ally.[n]Tarunda to self.[n][e]

[msg skill_241]
[f 0 5 65278][f 2 1]Item:[n]Recovers 200 HP for 1 ally.[n]Rakunda to self.[n][e]

[msg skill_242]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 HP for 1 ally.[n]Rakunda/Sukunda to self.[n][e]

[msg skill_243]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 HP for 1 ally.[n]Sukunda/Tarunda to self.[n][e]

[msg skill_244]
[f 0 5 65278][f 2 1]Item:[n]Recovers 100 HP for 1 ally.[n]Tarunda/Rakunda to self.[n][e]

[msg skill_245]
[f 0 5 65278][f 2 1]Item:[n]Recovers 30% HP for 1 ally.[n]Debilitate to self.[n][e]

[msg skill_246]
[f 0 5 65278][f 2 1]Item:[n]Recovers 10% SP for 1 ally.[n]Rakunda to self.[n][e]

[msg skill_247]
[f 0 5 65278][f 2 1]Item:[n]Recover 10% SP for 1 ally.[n]Sukunda to self.[n][e]

[msg skill_248]
[f 0 5 65278][f 2 1]Item:[n]Recover 10% SP for 1 ally.[n]Tarunda to self.[n][e]

[msg skill_249]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_24A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_24B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_24C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_24D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_24E]
[f 0 5 65278][f 2 1]Item:[n]Recovers 10 HP[n][e]

[msg skill_24F]
[f 0 5 65278][f 2 1]Item:[n]Recovers 25 HP[n][e]

[msg skill_250]
[f 0 5 65278][f 2 1]Item:[n]Recovers 50 HP[n][e]

[msg skill_251]
[f 0 5 65278][f 2 1]Item:[n]Recovers 5 SP[n][e]

[msg skill_252]
[f 0 5 65278][f 2 1]Item:[n]Recovers 25 SP[n][e]

[msg skill_253]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_254]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_255]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_256]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_257]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_258]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_259]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_25F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_260]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_261]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_262]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_263]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_264]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_265]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_266]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_267]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_268]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_269]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_26F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_270]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_271]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_272]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_273]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_274]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_275]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_276]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_277]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_278]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_279]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_27F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_280]
[f 0 5 65278][f 2 1]Casts various[n]buffs on allies.[n][e]

[msg skill_281]
[f 0 5 65278][f 2 1]Casts even more[n]buffs on allies.[n][e]

[msg skill_282]
[f 0 5 65278][f 2 1]Recognize the most[n]effective choice in[n]Demon Negotiations.[n][e]

[msg skill_283]
[f 0 5 65278][f 2 1]Swaps fallen ally with[n]a backup member.[n][e]

[msg skill_284]
[f 0 5 65278][f 2 1]Chance of nullifying attacks[n]directed at entire party.[n][e]

[msg skill_285]
[f 0 5 65278][f 2 1]Low chance of Hold Up[n]at the start of battle[n]except when ambushed.[n][e]

[msg skill_286]
[f 0 5 65278][f 2 1]View attribute affinities[n]and skills when Analyzing.[n][e]

[msg skill_287]
[f 0 5 65278][f 2 1]Find out if a foe is carrying[n]a rare item ahead of time.[n][e]

[msg skill_288]
[f 0 5 65278][f 2 1]Restores 20% HP to[n]backup members[n]after battle.[n][e]

[msg skill_289]
[f 0 5 65278][f 2 1]Restores 3% SP to[n]backup members[n]after battle.[n][e]

[msg skill_28A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_28B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_28C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_28D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_28E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_28F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_290]
[f 0 5 65278][f 2 1]Downs one foe.[n][e]

[msg skill_291]
[f 0 5 65278][f 2 1]Medium Almighty dmg[n]to all foes.[n][e]

[msg skill_292]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_293]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_294]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_295]
[f 0 5 65278][f 2 1]Heavy dmg to one foe,[n]ignoring affinities.[n][e]

[msg skill_296]
[f 0 5 65278][f 2 1]A bullet made from the[n]Seven Deadly Sins.[n]Can pierce even a god.[n][e]

[msg skill_297]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_298]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_299]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_29F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A1]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe.[n][e]

[msg skill_2A2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2A9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2AF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2B9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2BF]
[f 0 5 65278][f 2 1]Nullifies all magical[n]attacks except[n]Almighty for one ally.[n][e]

[msg skill_2C0]
[f 0 5 65278][f 2 1]Restores 50% HP and[n]increases Accuracy/[n]Evasion for all allies.[n][e]

[msg skill_2C1]
[f 0 5 65278][f 2 1]Heavy Phys dmg[n]to one foe 2 times.[n]High Accuracy.[n][e]

[msg skill_2C2]
[f 0 5 65278][f 2 1]Heavy Almighty dmg[n]to all foes. Medium[n]chance of insta-kill.[n][e]

[msg skill_2C3]
[f 0 5 65278][f 2 1]Heavy Curse dmg to[n]all foes. Chance of[n]Confuse/Fear/Despair.[n][e]

[msg skill_2C4]
[f 0 5 65278][f 2 1]Light Bless dmg to[n]all foes 4-8 times.[n][e]

[msg skill_2C5]
[f 0 5 65278][f 2 1]Colossal Phys dmg[n]to one foe. Decreases[n]Attack.[n][e]

[msg skill_2C6]
[f 0 5 65278][f 2 1]Severe Fire dmg to[n]all foes, with high[n]chance of Fear.[n][e]

[msg skill_2C7]
[f 0 5 65278][f 2 1]Severe Curse dmg[n]to all foes.[n][e]

[msg skill_2C8]
[f 0 5 65278][f 2 1]Fully restores HP and[n]removes all stat debuffs[n]for all allies.[n][e]

[msg skill_2C9]
[f 0 5 65278][f 2 1]Heavy Almighty dmg[n]to all foes 3 times.[n][e]

[msg skill_2CA]
[f 0 5 65278][f 2 1]Restores 50% HP and[n]increases ATK/DEF/[n]ACC/EV for allies.[n][e]

[msg skill_2CB]
[f 0 5 65278][f 2 1]Severe Phys dmg to[n]all foes with high chance[n]of Critical 1-2 times.[n][e]

[msg skill_2CC]
[f 0 5 65278][f 2 1]High chance of[n]inflicting Sleep[n]to all foes.[n][e]

[msg skill_2CD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2CE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2CF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2D9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2DF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2E9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2EA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2EB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2EC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2ED]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2EE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2EF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F2]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F6]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2F9]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FA]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FC]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FD]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_2FF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_300]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_301]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_302]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_303]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_304]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_305]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_306]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_307]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_308]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_309]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30A]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30B]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30C]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30E]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_30F]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_310]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_311]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_312]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_313]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_314]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_315]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_316]
[f 0 5 65278][f 2 1]Severe Curse dmg[n]to one foe.[n][e]

[msg skill_317]
[f 0 5 65278][f 2 1]Severe Elec dmg[n]to one foe.[n][e]

[msg skill_318]
[f 0 5 65278][f 2 1]Severe Wind dmg[n]to one foe.[n]Effective vs Burn.[n][e]

[msg skill_319]
[f 0 5 65278][f 2 1]Severe Fire dmg[n]to one foe.[n][e]

[msg skill_31A]
[f 0 5 65278][f 2 1]Severe Ice dmg[n]to one foe.[n][e]

[msg skill_31B]
[f 0 5 65278][f 2 1]Severe Nuke dmg[n]to one foe.[n][e]

[msg skill_31C]
[f 0 5 65278][f 2 1]Severe Psy dmg[n]to one foe.[n][e]

[msg skill_31D]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_31E]
[f 0 5 65278][f 2 1]Severe Bless dmg[n]to one foe.[n][e]

[msg skill_31F]
[f 0 5 65278][f 2 1]Severe Almighty dmg[n]to one foe.[n][e]

[msg skill_320]
[f 0 5 65278][f 2 1]10% chance of reflecting[n]physical attacks.[n][e]

[msg skill_321]
[f 0 5 65278][f 2 1]15% chance of reflecting[n]physical attacks.[n]Does not stack.[n][e]

[msg skill_322]
[f 0 5 65278][f 2 1]20% chance of reflecting[n]physical attacks.[n]Does not stack.[n][e]

[msg skill_323]
[f 0 5 65278][f 2 1]Decreases chances of[n]being inflicted with Burn.[n][e]

[msg skill_324]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Burn.[n][e]

[msg skill_325]
[f 0 5 65278][f 2 1]Revives with 1 HP[n]when KO'd. Usable[n]once per battle.[n][e]

[msg skill_326]
[f 0 5 65278][f 2 1]Revives with full HP[n]when KO'd. Usable[n]once per battle.[n][e]

[msg skill_327]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Freeze.[n][e]

[msg skill_328]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Freeze.[n][e]

[msg skill_329]
[f 0 5 65278][f 2 1]Survive insta-kill skills[n]with 1 HP.[n][e]

[msg skill_32A]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Fire skills.[n][e]

[msg skill_32B]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Fire[n]skills. Does not stack.[n][e]

[msg skill_32C]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Ice skills.[n][e]

[msg skill_32D]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Ice[n]skills. Does not stack.[n][e]

[msg skill_32E]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Wind skills.[n][e]

[msg skill_32F]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Wind[n]skills. Does not stack.[n][e]

[msg skill_330]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Elec skills.[n][e]

[msg skill_331]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Elec[n]skills. Does not stack.[n][e]

[msg skill_332]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Phys skills.[n][e]

[msg skill_333]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Phys[n]skills. Does not stack.[n][e]

[msg skill_334]
[f 0 5 65278][f 2 1]Strengthens Fire[n]skills by 25%.[n][e]

[msg skill_335]
[f 0 5 65278][f 2 1]Strengthens Fire[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_336]
[f 0 5 65278][f 2 1]Strengthens Ice[n]skills by 25%.[n][e]

[msg skill_337]
[f 0 5 65278][f 2 1]Strengthens Ice[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_338]
[f 0 5 65278][f 2 1]Strengthens Wind[n]skills by 25%.[n][e]

[msg skill_339]
[f 0 5 65278][f 2 1]Strengthens Wind[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_33A]
[f 0 5 65278][f 2 1]Strengthens Elec[n]skills by 25%.[n][e]

[msg skill_33B]
[f 0 5 65278][f 2 1]Strengthens Elec[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_33C]
[f 0 5 65278][f 2 1]Increases Evasion from[n]all magical attacks[n]except Almighty.[n][e]

[msg skill_33D]
[f 0 5 65278][f 2 1]Increases the effect of[n]healing skills by 50%.[n][e]

[msg skill_33E]
[f 0 5 65278][f 2 1]Restores 2% of max HP[n]each turn in battle.[n][e]

[msg skill_33F]
[f 0 5 65278][f 2 1]Restores 4% of max HP[n]each turn in battle. [n][e]

[msg skill_340]
[f 0 5 65278][f 2 1]Restores 6% of max HP[n]each turn in battle.[n][e]

[msg skill_341]
[f 0 5 65278][f 2 1]Increases Evasion from[n]non-Hama Bless skills.[n][e]

[msg skill_342]
[f 0 5 65278][f 2 1]Increases Evasion from[n]non-Mudo Curse skills.[n][e]

[msg skill_343]
[f 0 5 65278][f 2 1]Restores 3 SP[n]each turn in battle.[n][e]

[msg skill_344]
[f 0 5 65278][f 2 1]Restores 5 SP[n]each turn in battle.[n][e]

[msg skill_345]
[f 0 5 65278][f 2 1]Restores 7 SP[n]each turn in battle.[n][e]

[msg skill_346]
[f 0 5 65278][f 2 1]Greatly increases Evasion[n]from non-Hama Bless[n]skills. Does not stack.[n][e]

[msg skill_347]
[f 0 5 65278][f 2 1]Greatly increases Evasion[n]from non-Mudo Curse[n]skills. Does not stack.[n][e]

[msg skill_348]
[f 0 5 65278][f 2 1]Automatic Tarukaja[n]at the start of battle.[n][e]

[msg skill_349]
[f 0 5 65278][f 2 1]Automatic Matarukaja[n]at the start of battle.[n][e]

[msg skill_34A]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Shock.[n][e]

[msg skill_34B]
[f 0 5 65278][f 2 1]Automatic Rakukaja[n]at the start of battle.[n][e]

[msg skill_34C]
[f 0 5 65278][f 2 1]Automatic Marakukaja[n]at the start of battle.[n][e]

[msg skill_34D]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Shock.[n][e]

[msg skill_34E]
[f 0 5 65278][f 2 1]Automatic Sukukaja[n]at the start of battle.[n][e]

[msg skill_34F]
[f 0 5 65278][f 2 1]Automatic Masukukaja[n]at the start of battle.[n][e]

[msg skill_350]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Hunger.[n][e]

[msg skill_351]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Hunger.[n][e]

[msg skill_352]
[f 0 5 65278][f 2 1]Decreases recovery time[n]from ailments by half.[n][e]

[msg skill_353]
[f 0 5 65278][f 2 1]Decreases recovery time[n]from ailments to 1 turn.[n][e]

[msg skill_354]
[f 0 5 65278][f 2 1]Decreases HP cost[n]of skills by half.[n][e]

[msg skill_355]
[f 0 5 65278][f 2 1]Decreases SP cost[n]of skills by half.[n][e]

[msg skill_356]
[f 0 5 65278][f 2 1]Increases Attack when[n]inflicted by Rage.[n][e]

[msg skill_357]
[f 0 5 65278][f 2 1]Decreases chance[n]of being hit by[n]a Critical.[n][e]

[msg skill_358]
[f 0 5 65278][f 2 1]Increases chance[n]of Critical.[n][e]

[msg skill_359]
[f 0 5 65278][f 2 1]Greatly decreases[n]Accuracy for one foe.[n][e]

[msg skill_35A]
[f 0 5 65278][f 2 1]Take the blow,[n]but decreases[n]damage by half.[n][e]

[msg skill_35B]
[f 0 5 65278][f 2 1]EXP gained in battle[n]increased by 1.5x.[n][e]

[msg skill_35C]
[f 0 5 65278][f 2 1]Restores 8% of max[n]HP/SP after battle.[n][e]

[msg skill_35D]
[f 0 5 65278][f 2 1]Fully restores HP/SP [n]after battle.[n][e]

[msg skill_35E]
[f 0 5 65278][f 2 1]Earn 25% EXP even when[n]not participating in battle.[n][e]

[msg skill_35F]
[f 0 5 65278][f 2 1]Earn 50% EXP even when[n]not participating in battle.[n][e]

[msg skill_360]
[f 0 5 65278][f 2 1]Earn 100% EXP even when[n]not participating in battle.[n][e]

[msg skill_361]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Confuse/Fear/Rage/[n]Despair.[n][e]

[msg skill_362]
[f 0 5 65278][f 2 1]Nullifies Hama[n]attacks.[n][e]

[msg skill_363]
[f 0 5 65278][f 2 1]Calm things down with[n]humor. Usable when[n]Sense is at "Sensitive."[n][e]

[msg skill_364]
[f 0 5 65278][f 2 1]Identify who has Treasure[n]in Mementos. Usable when[n]Instinct is at "Wild."[n][e]

[msg skill_365]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_366]
[f 0 5 65278][f 2 1]Increases resistance[n]to Fire attacks.[n]Nullifies weakness.[n][e]

[msg skill_367]
[f 0 5 65278][f 2 1]Nullifies Fire attacks.[n][e]

[msg skill_368]
[f 0 5 65278][f 2 1]Reflects Fire attacks.[n][e]

[msg skill_369]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Fire attacks.[n][e]

[msg skill_36A]
[f 0 5 65278][f 2 1]Nullifies Mudo[n]attacks.[n][e]

[msg skill_36B]
[f 0 5 65278][f 2 1]Increases resistance[n]to Ice attacks.[n]Nullifies weakness.[n][e]

[msg skill_36C]
[f 0 5 65278][f 2 1]Nullifies Ice attacks.[n][e]

[msg skill_36D]
[f 0 5 65278][f 2 1]Reflects Ice attacks.[n][e]

[msg skill_36E]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Ice attacks.[n][e]

[msg skill_36F]
[f 0 5 65278][f 2 1]EXP gained in battle[n]increased by 15%.[n][e]

[msg skill_370]
[f 0 5 65278][f 2 1]Increases resistance[n]to Wind attacks.[n]Nullifies weakness.[n][e]

[msg skill_371]
[f 0 5 65278][f 2 1]Nullifies Wind attacks.[n][e]

[msg skill_372]
[f 0 5 65278][f 2 1]Reflects Wind attacks.[n][e]

[msg skill_373]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Wind attacks.[n][e]

[msg skill_374]
[f 0 5 65278][f 2 1]Increases strength of[n]All-Out Attacks.[n][e]

[msg skill_375]
[f 0 5 65278][f 2 1]Increases resistance[n]to Elec attacks.[n]Nullifies weakness.[n][e]

[msg skill_376]
[f 0 5 65278][f 2 1]Nullifies Elec attacks.[n][e]

[msg skill_377]
[f 0 5 65278][f 2 1]Reflects Elec attacks.[n][e]

[msg skill_378]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Elec attacks.[n][e]

[msg skill_379]
[f 0 5 65278][f 2 1]Increases money gained[n]by 15%.[n][e]

[msg skill_37A]
[f 0 5 65278][f 2 1]Increases resistance[n]to Bless attacks.[n]Nullifies weakness.[n][e]

[msg skill_37B]
[f 0 5 65278][f 2 1]Nullifies Bless attacks.[n][e]

[msg skill_37C]
[f 0 5 65278][f 2 1]Reflects Bless attacks.[n][e]

[msg skill_37D]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Bless attacks.[n][e]

[msg skill_37E]
[f 0 5 65278][f 2 1]Decreases chance of[n]being targeted by foes.[n][e]

[msg skill_37F]
[f 0 5 65278][f 2 1]Increases resistance[n]to Curse attacks.[n]Nullifies weakness.[n][e]

[msg skill_380]
[f 0 5 65278][f 2 1]Nullifies Curse attacks.[n][e]

[msg skill_381]
[f 0 5 65278][f 2 1]Reflects Curse attacks.[n][e]

[msg skill_382]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Curse attacks.[n][e]

[msg skill_383]
[f 0 5 65278][f 2 1]Increases max SP[n]by 20.[n][e]

[msg skill_384]
[f 0 5 65278][f 2 1]Increases resistance[n]to Phys attacks.[n]Nullifies weakness.[n][e]

[msg skill_385]
[f 0 5 65278][f 2 1]Nullifies Phys attacks.[n][e]

[msg skill_386]
[f 0 5 65278][f 2 1]Reflects Phys attacks.[n][e]

[msg skill_387]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Phys attacks.[n][e]

[msg skill_388]
[f 0 5 65278][f 2 1]Nullifies Bless/Curse[n]skills.[n][e]

[msg skill_389]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting ailments.[n][e]

[msg skill_38A]
[f 0 5 65278][f 2 1]Increases success rate[n]of Hama skills.[n][e]

[msg skill_38B]
[f 0 5 65278][f 2 1]Increases success rate[n]of Mudo skills.[n][e]

[msg skill_38C]
[f 0 5 65278][f 2 1]Increases Accuracy of[n]Gun attacks by 5%.[n][e]

[msg skill_38D]
[f 0 5 65278][f 2 1]Increases Evasion from[n]Criticals and magical[n]attacks.[n][e]

[msg skill_38E]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Dizzy.[n][e]

[msg skill_38F]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Confuse.[n][e]

[msg skill_390]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Fear.[n][e]

[msg skill_391]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Forget.[n][e]

[msg skill_392]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Sleep.[n][e]

[msg skill_393]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Rage.[n][e]

[msg skill_394]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Despair.[n][e]

[msg skill_395]
[f 0 5 65278][f 2 1]Decreases HP and SP[n]cost of skills by 25%.[n][e]

[msg skill_396]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Brainwash.[n][e]

[msg skill_397]
[f 0 5 65278][f 2 1]Greatly increases [n]chance of Critical.[n][e]

[msg skill_398]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Dizzy.[n][e]

[msg skill_399]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Confuse.[n][e]

[msg skill_39A]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Fear.[n][e]

[msg skill_39B]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Forget.[n][e]

[msg skill_39C]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Sleep.[n][e]

[msg skill_39D]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Rage.[n][e]

[msg skill_39E]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Despair.[n][e]

[msg skill_39F]
[f 0 5 65278][f 2 1]Increases fusion[n]accident rate.[n][e]

[msg skill_3A0]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with Brainwash.[n][e]

[msg skill_3A1]
[f 0 5 65278][f 2 1]Strengthens all attacks.[n]Can stack.[n][e]

[msg skill_3A2]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Dizzy.[n][e]

[msg skill_3A3]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Confuse.[n][e]

[msg skill_3A4]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Fear.[n][e]

[msg skill_3A5]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Forget.[n][e]

[msg skill_3A6]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Sleep.[n][e]

[msg skill_3A7]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Rage.[n][e]

[msg skill_3A8]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Despair.[n][e]

[msg skill_3A9]
[f 0 5 65278][f 2 1]Restores 15% HP and 15 SP[n]each turn in battle.[n][e]

[msg skill_3AA]
[f 0 5 65278][f 2 1]Prevents infliction of[n]Brainwash.[n][e]

[msg skill_3AB]
[f 0 5 65278][f 2 1]Restores 25% HP each turn[n]in battle.[n][e]

[msg skill_3AC]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Burn.[n][e]

[msg skill_3AD]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Freeze.[n][e]

[msg skill_3AE]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting Shock.[n][e]

[msg skill_3AF]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3B0]
[f 0 5 65278][f 2 1]Increases Critical rate[n]during an Ambush.[n][e]

[msg skill_3B1]
[f 0 5 65278][f 2 1]Increases Critical rate[n]when surrounded.[n][e]

[msg skill_3B2]
[f 0 5 65278][f 2 1]Greatly decreases Accuracy[n]of all foes' attacks except[n]Almighty when surrounded.[n][e]

[msg skill_3B3]
[f 0 5 65278][f 2 1]Restores 5% max HP[n]and 10 SP each turn[n]during an Ambush.[n][e]

[msg skill_3B4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3B5]
[f 0 5 65278][f 2 1]Automatic Sukukaja[n]after a Baton Pass.[n][e]

[msg skill_3B6]
[f 0 5 65278][f 2 1]Greatly increases Evasion[n]from all affinities during[n]Rain/Snow.[n][e]

[msg skill_3B7]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting ailments[n]during Rain/Snow.[n][e]

[msg skill_3B8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3B9]
[f 0 5 65278][f 2 1]Strengthens Gun[n]skills by 25%.[n][e]

[msg skill_3BA]
[f 0 5 65278][f 2 1]Strengthens Gun[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3BB]
[f 0 5 65278][f 2 1]Increases chance of[n]Critical from Gun[n]attacks.[n][e]

[msg skill_3BC]
[f 0 5 65278][f 2 1]Increases resistance[n]to Nuke attacks.[n]Nullifies weakness.[n][e]

[msg skill_3BD]
[f 0 5 65278][f 2 1]Nullifies Nuke attacks.[n][e]

[msg skill_3BE]
[f 0 5 65278][f 2 1]Reflects Nuke attacks.[n][e]

[msg skill_3BF]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Nuke attacks.[n][e]

[msg skill_3C0]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3C1]
[f 0 5 65278][f 2 1]Increases resistance[n]to Psy attacks.[n]Nullifies weakness.[n][e]

[msg skill_3C2]
[f 0 5 65278][f 2 1]Nullifies Psy attacks.[n][e]

[msg skill_3C3]
[f 0 5 65278][f 2 1]Reflects Psy attacks.[n][e]

[msg skill_3C4]
[f 0 5 65278][f 2 1]Absorbs damage from[n]Psy attacks.[n][e]

[msg skill_3C5]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3C6]
[f 0 5 65278][f 2 1]Strengthens Nuke[n]skills by 25%.[n][e]

[msg skill_3C7]
[f 0 5 65278][f 2 1]Strengthens Nuke[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3C8]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3C9]
[f 0 5 65278][f 2 1]Strengthens Psy[n]skills by 25%.[n][e]

[msg skill_3CA]
[f 0 5 65278][f 2 1]Strengthens Psy[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3CB]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3CC]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Nuke skills.[n][e]

[msg skill_3CD]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Nuke[n]skills. Does not stack.[n][e]

[msg skill_3CE]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3CF]
[f 0 5 65278][f 2 1]Increases Evasion[n]from Psy skills.[n][e]

[msg skill_3D0]
[f 0 5 65278][f 2 1]Greatly increases[n]Evasion from Psy[n]skills. Does not stack.[n][e]

[msg skill_3D1]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3D2]
[f 0 5 65278][f 2 1]Strengthens Bless[n]skills by 25%.[n][e]

[msg skill_3D3]
[f 0 5 65278][f 2 1]Strengthens Bless[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3D4]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3D5]
[f 0 5 65278][f 2 1]Strengthens Curse[n]skills by 25%.[n][e]

[msg skill_3D6]
[f 0 5 65278][f 2 1]Strengthens Curse[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3D7]
[f 0 5 65278][f 2 1]Prevents discovery[n]by foes roaming the[n]Metaverse.[n][e]

[msg skill_3D8]
[f 0 5 65278][f 2 1]Strengthens all magic[n]skills by 25%.[n][e]

[msg skill_3D9]
[f 0 5 65278][f 2 1]Decreases chances[n]of being inflicted[n]with ailments.[n][e]

[msg skill_3DA]
[f 0 5 65278][f 2 1]Strengthens Almighty[n]skills by 25%.[n][e]

[msg skill_3DB]
[f 0 5 65278][f 2 1]Strengthens Almighty[n]skills by 50%.[n]Can stack.[n][e]

[msg skill_3DC]
[f 0 5 65278][f 2 1]Nullifies all magical[n]attacks except Almighty.[n][e]

[msg skill_3DD]
[f 0 5 65278][f 2 1]Restores 20 SP after[n]a Baton Pass.[n][e]

[msg skill_3DE]
[f 0 5 65278][f 2 1]Enable Skill Card copying.[n][e]

[msg skill_3DF]
[f 0 5 65278][f 2 1]Defeats weak foes during[n]an Ambush and provides[n]a Persona.[n][e]

[msg skill_3E0]
[f 0 5 65278][f 2 1]Restores low amount[n]of HP when using[n]Guard.[n][e]

[msg skill_3E1]
[f 0 5 65278][f 2 1]Nullifies weaknesses.[n][e]

[msg skill_3E2]
[f 0 5 65278][f 2 1]Increases max HP[n]by 40%.[n][e]

[msg skill_3E3]
[f 0 5 65278][f 2 1]Increases max SP[n]by 40%.[n][e]

[msg skill_3E4]
[f 0 5 65278][f 2 1]Restores 5 SP after[n]a Baton Pass.[n][e]

[msg skill_3E5]
[f 0 5 65278][f 2 1]Victory Cry[n][e]

[msg skill_3E6]
[f 0 5 65278][f 2 1]RESERVE[n][e]

[msg skill_3E7]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3E8]
[f 0 5 65278][f 2 1]Slightly increases dmg to[n]enemies with ailments.[n][e]

[msg skill_3E9]
[f 0 5 65278][f 2 1]Increases dmg to[n]enemies with[n]ailments.[n][e]

[msg skill_3EA]
[f 0 5 65278][f 2 1]Restores 3 SP after[n]defeating a foe with[n]Hama/Mudo attacks.[n][e]

[msg skill_3EB]
[f 0 5 65278][f 2 1]Restores 5 SP after[n]defeating a foe with[n]Hama/Mudo attacks.[n][e]

[msg skill_3EC]
[f 0 5 65278][f 2 1]Restores 7 SP after[n]defeating a foe with[n]Hama/Mudo attacks.[n][e]

[msg skill_3ED]
[f 0 5 65278][f 2 1]Slightly increases[n]Technical damage.[n][e]

[msg skill_3EE]
[f 0 5 65278][f 2 1]Increases Technical[n]damage.[n][e]

[msg skill_3EF]
[f 0 5 65278][f 2 1]Slightly increases damage[n]when low on HP.[n][e]

[msg skill_3F0]
[f 0 5 65278][f 2 1]Increases damage[n]when low on HP.[n][e]

[msg skill_3F1]
[f 0 5 65278][f 2 1]Slightly increases damage[n]from attacks that target[n]foe's weaknesses.[n][e]

[msg skill_3F2]
[f 0 5 65278][f 2 1]Increases damage from[n]attacks that target[n]foe's weaknesses.[n][e]

[msg skill_3F3]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_3F4]
[f 0 5 65278][f 2 1]Decreases HP cost[n]of skills by 10%.[n][e]

[msg skill_3F5]
[f 0 5 65278][f 2 1]Decreases HP cost[n]of skills by 25%.[n][e]

[msg skill_3F6]
[f 0 5 65278][f 2 1]Decreases SP cost[n]of skills by 10%.[n][e]

[msg skill_3F7]
[f 0 5 65278][f 2 1]Decreases SP cost[n]of skills by 25%.[n][e]

[msg skill_3F8]
[f 0 5 65278][f 2 1]Increases the effect[n]of healing skills[n]by 10%.[n][e]

[msg skill_3F9]
[f 0 5 65278][f 2 1]Increases the effect[n]of healing skills[n]by 25%.[n][e]

[msg skill_3FA]
[f 0 5 65278][f 2 1]Decreases HP cost[n]of skills to 0.[n][e]

[msg skill_3FB]
[f 0 5 65278][f 2 1]Decreases SP cost[n]of skills to 0.[n][e]

[msg skill_3FC]
[f 0 5 65278][f 2 1]Slightly increases damage[n]of single target skills.[n][e]

[msg skill_3FD]
[f 0 5 65278][f 2 1]Increases damage[n]of single target skills.[n][e]

[msg skill_3FE]
[f 0 5 65278][f 2 1]All attacks are Critical,[n]but Evasion becomes[n]impossible.[n][e]

[msg skill_3FF]
[f 0 5 65278][f 2 1]Reduce the SP cost of[n]healing skills by 25%.[n][e]

[msg skill_400]
[f 0 5 65278][f 2 1]Reduce the SP cost of[n]healing skills by 10%.[n][e]

[msg skill_401]
[f 0 5 65278][f 2 1]Decreases Accuracy by [n]half, but Attack doubles.[n][e]

[msg skill_402]
[f 0 5 65278][f 2 1]Slightly increases chance[n]of inflicting ailments.[n][e]

[msg skill_403]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_404]
[f 0 5 65278][f 2 1]Strengthens magical attacks[n]if possessing 4 or more[n]affinity skills.[n][e]

[msg skill_405]
[f 0 5 65278][f 2 1]Slightly strengthens magical[n]attacks if possessing 3 or[n]more affinity skills.[n][e]

[msg skill_406]
[f 0 5 65278][f 2 1]Increases effect period[n]of support skills.[n][e]

[msg skill_407]
[f 0 5 65278][f 2 1]Slightly increases success[n]rate of Hama/Mudo skills.[n][e]

[msg skill_408]
[f 0 5 65278][f 2 1]Increases success rate[n]of Hama/Mudo skills.[n][e]

[msg skill_409]
[f 0 5 65278][f 2 1]Increases max HP[n]by 10%.[n][e]

[msg skill_40A]
[f 0 5 65278][f 2 1]Increases max HP[n]by 20%.[n][e]

[msg skill_40B]
[f 0 5 65278][f 2 1]Increases max HP[n]by 30%.[n][e]

[msg skill_40C]
[f 0 5 65278][f 2 1]Increases max SP[n]by 10%.[n][e]

[msg skill_40D]
[f 0 5 65278][f 2 1]Increases max SP[n]by 20%.[n][e]

[msg skill_40E]
[f 0 5 65278][f 2 1]Increases max SP[n]by 30%.[n][e]

[msg skill_40F]
[f 0 5 65278][f 2 1]Slightly increases[n]Critical damage.[n][e]

[msg skill_410]
[f 0 5 65278][f 2 1]Increases Critical[n]damage.[n][e]

[msg skill_411]
[f 0 5 65278][f 2 1]Deals double  [n]the damage.[n][e]

[msg skill_412]
[f 0 5 65278][f 2 1]Slightly increases damage[n]with all enemy target skills.[n][e]

[msg skill_413]
[f 0 5 65278][f 2 1]Increases damage with[n]all enemy target skills.[n][e]

[msg skill_414]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_415]
[f 0 5 65278][f 2 1]Provide backup support[n]during battle.[n][e]

[msg skill_416]
[f 0 5 65278][f 2 1]100% chance of escape[n]when running away on[n]the 3rd turn of battle.[n][e]

[msg skill_417]
[f 0 5 65278][f 2 1]BLANK[n][e]

[msg skill_418]
[f 0 5 65278][f 2 1]Strengthens all[n]affinity skills by 50%.[n][e]

[msg skill_419]
[f 0 5 65278][f 2 1]BLANK[n][e]

