[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Allows you to learn[n]the Fire skill[n]Agi.[n][e]

[msg Item_002]
[s]Allows you to learn[n]the Fire skill[n]Agilao.[n][e]

[msg Item_003]
[s]Allows you to learn[n]the Fire skill[n]Agidyne.[n][e]

[msg Item_004]
[s]Allows you to learn[n]the Fire skill[n]Maragi.[n][e]

[msg Item_005]
[s]Allows you to learn[n]the Fire skill[n]Maragion.[n][e]

[msg Item_006]
[s]Allows you to learn[n]the Fire skill[n]Maragidyne.[n][e]

[msg Item_007]
[s]Allows you to learn[n]the Ice skill[n]Bufu.[n][e]

[msg Item_008]
[s]Allows you to learn[n]the Ice skill[n]Bufula.[n][e]

[msg Item_009]
[s]Allows you to learn[n]the Ice skill[n]Bufudyne.[n][e]

[msg Item_00A]
[s]Allows you to learn[n]the Ice skill[n]Mabufu.[n][e]

[msg Item_00B]
[s]Allows you to learn[n]the Ice skill[n]Mabufula.[n][e]

[msg Item_00C]
[s]Allows you to learn[n]the Ice skill[n]Mabufudyne.[n][e]

[msg Item_00D]
[s]Allows you to learn[n]the Wind skill[n]Garu.[n][e]

[msg Item_00E]
[s]Allows you to learn[n]the Wind skill[n]Garula.[n][e]

[msg Item_00F]
[s]Allows you to learn[n]the Wind skill[n]Garudyne.[n][e]

[msg Item_010]
[s]Allows you to learn[n]the Wind skill[n]Magaru.[n][e]

[msg Item_011]
[s]Allows you to learn[n]the Wind skill[n]Magarula.[n][e]

[msg Item_012]
[s]Allows you to learn[n]the Wind skill[n]Magarudyne.[n][e]

[msg Item_013]
[s]Allows you to learn[n]the Elec skill[n]Zio.[n][e]

[msg Item_014]
[s]Allows you to learn[n]the Elec skill[n]Zionga.[n][e]

[msg Item_015]
[s]Allows you to learn[n]the Elec skill[n]Ziodyne.[n][e]

[msg Item_016]
[s]Allows you to learn[n]the Elec skill[n]Mazio.[n][e]

[msg Item_017]
[s]Allows you to learn[n]the Elec skill[n]Mazionga.[n][e]

[msg Item_018]
[s]Allows you to learn[n]the Elec skill[n]Maziodyne.[n][e]

[msg Item_019]
[s]Allows you to learn[n]the Bless skill[n]Hama.[n][e]

[msg Item_01A]
[s]Allows you to learn[n]the Bless skill[n]Hamaon.[n][e]

[msg Item_01B]
[s]Allows you to learn[n]the Bless skill[n]Mahama.[n][e]

[msg Item_01C]
[s]Allows you to learn[n]the Bless skill[n]Mahamaon.[n][e]

[msg Item_01D]
[s]Allows you to learn[n]the Bless skill[n]Kouha.[n][e]

[msg Item_01E]
[s]Allows you to learn[n]the Bless skill[n]Kouga.[n][e]

[msg Item_01F]
[s]Allows you to learn[n]the Bless skill[n]Kougaon.[n][e]

[msg Item_020]
[s]Allows you to learn[n]the Bless skill[n]Makouha.[n][e]

[msg Item_021]
[s]Allows you to learn[n]the Bless skill[n]Makouga.[n][e]

[msg Item_022]
[s]Allows you to learn[n]the Bless skill[n]Makougaon.[n][e]

[msg Item_023]
[s]Allows you to learn[n]the Curse skill[n]Mudo.[n][e]

[msg Item_024]
[s]Allows you to learn[n]the Curse skill[n]Mudoon.[n][e]

[msg Item_025]
[s]Allows you to learn[n]the Curse skill[n]Mamudo.[n][e]

[msg Item_026]
[s]Allows you to learn[n]the Curse skill[n]Mamudoon.[n][e]

[msg Item_027]
[s]Allows you to learn[n]the Curse skill[n]Eiha.[n][e]

[msg Item_028]
[s]Allows you to learn[n]the Curse skill[n]Eiga.[n][e]

[msg Item_029]
[s]Allows you to learn[n]the Curse skill[n]Eigaon.[n][e]

[msg Item_02A]
[s]Allows you to learn[n]the Curse skill[n]Maeiha.[n][e]

[msg Item_02B]
[s]Allows you to learn[n]the Curse skill[n]Maeiga.[n][e]

[msg Item_02C]
[s]Allows you to learn[n]the Curse skill[n]Maeigaon.[n][e]

[msg Item_02D]
[s]Allows you to learn[n]the Almighty skill[n]Megido.[n][e]

[msg Item_02E]
[s]Allows you to learn[n]the Almighty skill[n]Megidola.[n][e]

[msg Item_02F]
[s]Allows you to learn[n]the Almighty skill[n]Megidolaon.[n][e]

[msg Item_030]
[s]Allows you to learn[n]the Nuke skill[n]Frei.[n][e]

[msg Item_031]
[s]Allows you to learn[n]the Nuke skill[n]Freila.[n][e]

[msg Item_032]
[s]Allows you to learn[n]the Nuke skill[n]Freidyne.[n][e]

[msg Item_033]
[s]Allows you to learn[n]the Nuke skill[n]Mafrei.[n][e]

[msg Item_034]
[s]Allows you to learn[n]the Nuke skill[n]Mafreila.[n][e]

[msg Item_035]
[s]Allows you to learn[n]the Nuke skill[n]Mafreidyne.[n][e]

[msg Item_036]
[s]Allows you to learn[n]the ailment skill[n]Dazzler.[n][e]

[msg Item_037]
[s]Allows you to learn[n]the ailment skill[n]Nocturnal Flash.[n][e]

[msg Item_038]
[s]Allows you to learn[n]the ailment skill[n]Pulinpa.[n][e]

[msg Item_039]
[s]Allows you to learn[n]the ailment skill[n]Tentarafoo.[n][e]

[msg Item_03A]
[s]Allows you to learn[n]the ailment skill[n]Evil Touch.[n][e]

[msg Item_03B]
[s]Allows you to learn[n]the ailment skill[n]Evil Smile.[n][e]

[msg Item_03C]
[s]Allows you to learn[n]the ailment skill[n]Makajama.[n][e]

[msg Item_03D]
[s]Allows you to learn[n]the ailment skill[n]Makajamaon.[n][e]

[msg Item_03E]
[s]Unused[n][e]

[msg Item_03F]
[s]Unused[n][e]

[msg Item_040]
[s]Allows you to learn[n]the ailment skill[n]Dormina.[n][e]

[msg Item_041]
[s]Allows you to learn[n]the ailment skill[n]Lullaby.[n][e]

[msg Item_042]
[s]Allows you to learn[n]the ailment skill[n]Taunt.[n][e]

[msg Item_043]
[s]Allows you to learn[n]the ailment skill[n]Wage War.[n][e]

[msg Item_044]
[s]Allows you to learn[n]the ailment skill[n]Ominous Words.[n][e]

[msg Item_045]
[s]Allows you to learn[n]the ailment skill[n]Abysmal Surge.[n][e]

[msg Item_046]
[s]Allows you to learn[n]the ailment skill[n]Marin Karin.[n][e]

[msg Item_047]
[s]Allows you to learn[n]the ailment skill[n]Brain Jack.[n][e]

[msg Item_048]
[s]Unused[n][e]

[msg Item_049]
[s]Unused[n][e]

[msg Item_04A]
[s]Unused[n][e]

[msg Item_04B]
[s]Unused[n][e]

[msg Item_04C]
[s]Allows you to learn[n]the Almighty skill[n]Life Drain.[n][e]

[msg Item_04D]
[s]Allows you to learn[n]the Almighty skill[n]Spirit Drain.[n][e]

[msg Item_04E]
[s]Unused[n][e]

[msg Item_04F]
[s]Unused[n][e]

[msg Item_050]
[s]Allows you to learn[n]the Almighty skill[n]Foul Breath.[n][e]

[msg Item_051]
[s]Allows you to learn[n]the Almighty skill[n]Stagnant Air.[n][e]

[msg Item_052]
[s]Allows you to learn[n]the Almighty skill[n]Ghastly Wail.[n][e]

[msg Item_053]
[s]Allows you to learn[n]the Fire skill[n]Inferno.[n][e]

[msg Item_054]
[s]Allows you to learn[n]the Fire skill[n]Blazing Hell.[n][e]

[msg Item_055]
[s]Allows you to learn[n]the Ice skill[n]Diamond Dust.[n][e]

[msg Item_056]
[s]Allows you to learn[n]the Ice skill[n]Ice Age.[n][e]

[msg Item_057]
[s]Allows you to learn[n]the Wind skill[n]Panta Rhei.[n][e]

[msg Item_058]
[s]Allows you to learn[n]the Wind skill[n]Vacuum Wave.[n][e]

[msg Item_059]
[s]Allows you to learn[n]the Elec skill[n]Thunder Reign.[n][e]

[msg Item_05A]
[s]Allows you to learn[n]the Elec skill[n]Wild Thunder.[n][e]

[msg Item_05B]
[s]Allows you to learn[n]the Bless skill[n]Divine Judgment.[n][e]

[msg Item_05C]
[s]Unused[n][e]

[msg Item_05D]
[s]Allows you to learn[n]the Curse skill[n]Demonic Decree.[n][e]

[msg Item_05E]
[s]Unused[n][e]

[msg Item_05F]
[s]Allows you to learn[n]the Nuke skill[n]Atomic Flare.[n][e]

[msg Item_060]
[s]Allows you to learn[n]the Nuke skill[n]Cosmic Flare.[n][e]

[msg Item_061]
[s]Unused[n][e]

[msg Item_062]
[s]Unused[n][e]

[msg Item_063]
[s]Allows you to learn[n]the Psy skill[n]Psi.[n][e]

[msg Item_064]
[s]Allows you to learn[n]the Psy skill[n]Psio.[n][e]

[msg Item_065]
[s]Allows you to learn[n]the Psy skill[n]Psiodyne.[n][e]

[msg Item_066]
[s]Allows you to learn[n]the Psy skill[n]Mapsi.[n][e]

[msg Item_067]
[s]Allows you to learn[n]the Psy skill[n]Mapsio.[n][e]

[msg Item_068]
[s]Allows you to learn[n]the Psy skill[n]Mapsiodyne.[n][e]

[msg Item_069]
[s]Allows you to learn[n]the Psy skill[n]Psycho Force.[n][e]

[msg Item_06A]
[s]Allows you to learn[n]the Psy skill[n]Psycho Blast.[n][e]

[msg Item_06B]
[s]Allows you to learn[n]the Physical skill[n]Lunge.[n][e]

[msg Item_06C]
[s]Allows you to learn[n]the Physical skill[n]Assault Dive.[n][e]

[msg Item_06D]
[s]Allows you to learn[n]the Physical skill[n]Megaton Raid.[n][e]

[msg Item_06E]
[s]Allows you to learn[n]the Physical skill[n]God's Hand.[n][e]

[msg Item_06F]
[s]Allows you to learn[n]the Physical skill[n]Lucky Punch.[n][e]

[msg Item_070]
[s]Allows you to learn[n]the Physical skill[n]Miracle Punch.[n][e]

[msg Item_071]
[s]Allows you to learn[n]the Physical skill[n]Cleave.[n][e]

[msg Item_072]
[s]Allows you to learn[n]the Physical skill[n]Giant Slice.[n][e]

[msg Item_073]
[s]Allows you to learn[n]the Physical skill[n]Brave Blade.[n][e]

[msg Item_074]
[s]Allows you to learn[n]the Physical skill[n]Sword Dance.[n][e]

[msg Item_075]
[s]Unused[n][e]

[msg Item_076]
[s]Unused[n][e]

[msg Item_077]
[s]Allows you to learn[n]the Physical skill[n]Cornered Fang.[n][e]

[msg Item_078]
[s]Allows you to learn[n]the Physical skill[n]Rising Slash.[n][e]

[msg Item_079]
[s]Allows you to learn[n]the Physical skill[n]Deadly Fury.[n][e]

[msg Item_07A]
[s]Allows you to learn[n]the Gun skill[n]Snap.[n][e]

[msg Item_07B]
[s]Allows you to learn[n]the Gun skill[n]Triple Down.[n][e]

[msg Item_07C]
[s]Allows you to learn[n]the Gun skill[n]One-shot Kill.[n][e]

[msg Item_07D]
[s]Allows you to learn[n]the Gun skill[n]Riot Gun.[n][e]

[msg Item_07E]
[s]Allows you to learn[n]the Physical skill[n]Vajra Blast.[n][e]

[msg Item_07F]
[s]Allows you to learn[n]the Physical skill[n]Vorpal Blade.[n][e]

[msg Item_080]
[s]Allows you to learn[n]the Physical skill[n]Vicious Strike.[n][e]

[msg Item_081]
[s]Allows you to learn[n]the Physical skill[n]Heat Wave.[n][e]

[msg Item_082]
[s]Allows you to learn[n]the Physical skill[n]Gigantomachia.[n][e]

[msg Item_083]
[s]Allows you to learn[n]the Physical skill[n]Rampage.[n][e]

[msg Item_084]
[s]Allows you to learn[n]the Physical skill[n]Swift Strike.[n][e]

[msg Item_085]
[s]Allows you to learn[n]the Physical skill[n]Deathbound.[n][e]

[msg Item_086]
[s]Allows you to learn[n]the Physical skill[n]Agneyastra.[n][e]

[msg Item_087]
[s]Allows you to learn[n]the Physical skill[n]Double Fangs.[n][e]

[msg Item_088]
[s]Allows you to learn[n]the Physical skill[n]Tempest Slash.[n][e]

[msg Item_089]
[s]Allows you to learn[n]the Physical skill[n]Myriad Slashes.[n][e]

[msg Item_08A]
[s]Allows you to learn[n]the Physical skill[n]Sledgehammer.[n][e]

[msg Item_08B]
[s]Allows you to learn[n]the Physical skill[n]Skull Cracker.[n][e]

[msg Item_08C]
[s]Allows you to learn[n]the Physical skill[n]Terror Claw.[n][e]

[msg Item_08D]
[s]Allows you to learn[n]the Physical skill[n]Headbutt.[n][e]

[msg Item_08E]
[s]Unused[n][e]

[msg Item_08F]
[s]Allows you to learn[n]the Gun skill[n]Dream Needle.[n][e]

[msg Item_090]
[s]Allows you to learn[n]the Physical skill[n]Hysterical Slap.[n][e]

[msg Item_091]
[s]Allows you to learn[n]the Physical skill[n]Negative Pile.[n][e]

[msg Item_092]
[s]Allows you to learn[n]the Physical skill[n]Brain Shake.[n][e]

[msg Item_093]
[s]Allows you to learn[n]the Physical skill[n]Flash Bomb.[n][e]

[msg Item_094]
[s]Allows you to learn[n]the Physical skill[n]Mind Slice.[n][e]

[msg Item_095]
[s]Allows you to learn[n]the Physical skill[n]Bloodbath.[n][e]

[msg Item_096]
[s]Allows you to learn[n]the Physical skill[n]Memory Blow.[n][e]

[msg Item_097]
[s]Unused[n][e]

[msg Item_098]
[s]Allows you to learn[n]the Physical skill[n]Dormin Rush.[n][e]

[msg Item_099]
[s]Allows you to learn[n]the Physical skill[n]Oni-Kagura.[n][e]

[msg Item_09A]
[s]Allows you to learn[n]the Physical skill[n]Bad Beat.[n][e]

[msg Item_09B]
[s]Allows you to learn[n]the Physical skill[n]Brain Buster.[n][e]

[msg Item_09C]
[s]Allows you to learn[n]the healing skill[n]Dia.[n][e]

[msg Item_09D]
[s]Allows you to learn[n]the healing skill[n]Diarama.[n][e]

[msg Item_09E]
[s]Allows you to learn[n]the healing skill[n]Diarahan.[n][e]

[msg Item_09F]
[s]Allows you to learn[n]the healing skill[n]Media.[n][e]

[msg Item_0A0]
[s]Allows you to learn[n]the healing skill[n]Mediarama.[n][e]

[msg Item_0A1]
[s]Allows you to learn[n]the healing skill[n]Mediarahan.[n][e]

[msg Item_0A2]
[s]Allows you to learn[n]the healing skill[n]Recarm.[n][e]

[msg Item_0A3]
[s]Allows you to learn[n]the healing skill[n]Samarecarm.[n][e]

[msg Item_0A4]
[s]Unused[n][e]

[msg Item_0A5]
[s]Allows you to learn[n]the healing skill[n]Amrita Drop.[n][e]

[msg Item_0A6]
[s]Allows you to learn[n]the healing skill[n]Amrita Shower.[n][e]

[msg Item_0A7]
[s]Allows you to learn[n]the healing skill[n]Mabaisudi.[n][e]

[msg Item_0A8]
[s]Allows you to learn[n]the healing skill[n]Salvation.[n][e]

[msg Item_0A9]
[s]Allows you to learn[n]the healing skill[n]Patra.[n][e]

[msg Item_0AA]
[s]Allows you to learn[n]the healing skill[n]Energy Shower.[n][e]

[msg Item_0AB]
[s]Allows you to learn[n]the healing skill[n]Energy Drop.[n][e]

[msg Item_0AC]
[s]Allows you to learn[n]the healing skill[n]Baisudi.[n][e]

[msg Item_0AD]
[s]Allows you to learn[n]the healing skill[n]Me Patra.[n][e]

[msg Item_0AE]
[s]Allows you to learn[n]the support skill[n]Tarukaja.[n][e]

[msg Item_0AF]
[s]Allows you to learn[n]the support skill[n]Rakukaja.[n][e]

[msg Item_0B0]
[s]Allows you to learn[n]the support skill[n]Sukukaja.[n][e]

[msg Item_0B1]
[s]Allows you to learn[n]the support skill[n]Heat Riser.[n][e]

[msg Item_0B2]
[s]Allows you to learn[n]the support skill[n]Matarukaja.[n][e]

[msg Item_0B3]
[s]Allows you to learn[n]the support skill[n]Marakukaja.[n][e]

[msg Item_0B4]
[s]Allows you to learn[n]the support skill[n]Masukukaja.[n][e]

[msg Item_0B5]
[s]Allows you to learn[n]the support skill[n]Thermopylae.[n][e]

[msg Item_0B6]
[s]Allows you to learn[n]the support skill[n]Tarunda.[n][e]

[msg Item_0B7]
[s]Allows you to learn[n]the support skill[n]Rakunda.[n][e]

[msg Item_0B8]
[s]Allows you to learn[n]the support skill[n]Sukunda.[n][e]

[msg Item_0B9]
[s]Allows you to learn[n]the support skill[n]Debilitate.[n][e]

[msg Item_0BA]
[s]Allows you to learn[n]the support skill[n]Matarunda.[n][e]

[msg Item_0BB]
[s]Allows you to learn[n]the support skill[n]Marakunda.[n][e]

[msg Item_0BC]
[s]Allows you to learn[n]the support skill[n]Masukunda.[n][e]

[msg Item_0BD]
[s]Allows you to learn[n]the support skill[n]Dekunda.[n][e]

[msg Item_0BE]
[s]Allows you to learn[n]the support skill[n]Dekaja.[n][e]

[msg Item_0BF]
[s]Allows you to learn[n]the support skill[n]Charge.[n][e]

[msg Item_0C0]
[s]Allows you to learn[n]the support skill[n]Concentrate.[n][e]

[msg Item_0C1]
[s]Allows you to learn[n]the support skill[n]Rebellion.[n][e]

[msg Item_0C2]
[s]Allows you to learn[n]the support skill[n]Revolution.[n][e]

[msg Item_0C3]
[s]Allows you to learn[n]the support skill[n]Tetrakarn.[n][e]

[msg Item_0C4]
[s]Allows you to learn[n]the support skill[n]Makarakarn.[n][e]

[msg Item_0C5]
[s]Allows you to learn[n]the support skill[n]Tetraja.[n][e]

[msg Item_0C6]
[s]Allows you to learn[n]the support skill[n]Tetra Break.[n][e]

[msg Item_0C7]
[s]Allows you to learn[n]the support skill[n]Makara Break.[n][e]

[msg Item_0C8]
[s]Allows you to learn[n]the support skill[n]Fire Wall.[n][e]

[msg Item_0C9]
[s]Allows you to learn[n]the support skill[n]Ice Wall.[n][e]

[msg Item_0CA]
[s]Allows you to learn[n]the support skill[n]Elec Wall.[n][e]

[msg Item_0CB]
[s]Allows you to learn[n]the support skill[n]Wind Wall.[n][e]

[msg Item_0CC]
[s]Allows you to learn[n]the support skill[n]Fire Break.[n][e]

[msg Item_0CD]
[s]Allows you to learn[n]the support skill[n]Ice Break.[n][e]

[msg Item_0CE]
[s]Allows you to learn[n]the support skill[n]Wind Break.[n][e]

[msg Item_0CF]
[s]Allows you to learn[n]the support skill[n]Elec Break.[n][e]

[msg Item_0D0]
[s]Unused[n][e]

[msg Item_0D1]
[s]Unused[n][e]

[msg Item_0D2]
[s]Allows you to learn[n]the support skill[n]Nuke Wall.[n][e]

[msg Item_0D3]
[s]Allows you to learn[n]the support skill[n]Psy Wall.[n][e]

[msg Item_0D4]
[s]Allows you to learn[n]the support skill[n]Nuke Break.[n][e]

[msg Item_0D5]
[s]Allows you to learn[n]the support skill[n]Psy Break.[n][e]

[msg Item_0D6]
[s]Allows you to learn[n]the passive skill[n]Counter.[n][e]

[msg Item_0D7]
[s]Allows you to learn[n]the passive skill[n]Counterstrike.[n][e]

[msg Item_0D8]
[s]Allows you to learn[n]the passive skill[n]High Counter.[n][e]

[msg Item_0D9]
[s]Allows you to learn[n]the passive skill[n]Endure.[n][e]

[msg Item_0DA]
[s]Allows you to learn[n]the passive skill[n]Enduring Soul.[n][e]

[msg Item_0DB]
[s]Allows you to learn[n]the passive skill[n]Dodge Bless.[n][e]

[msg Item_0DC]
[s]Allows you to learn[n]the passive skill[n]Dodge Curse.[n][e]

[msg Item_0DD]
[s]Allows you to learn[n]the passive skill[n]Survival Trick.[n][e]

[msg Item_0DE]
[s]Allows you to learn[n]the passive skill[n]Dodge Fire.[n][e]

[msg Item_0DF]
[s]Allows you to learn[n]the passive skill[n]Evade Fire.[n][e]

[msg Item_0E0]
[s]Allows you to learn[n]the passive skill[n]Dodge Ice.[n][e]

[msg Item_0E1]
[s]Allows you to learn[n]the passive skill[n]Evade Ice.[n][e]

[msg Item_0E2]
[s]Allows you to learn[n]the passive skill[n]Dodge Wind.[n][e]

[msg Item_0E3]
[s]Allows you to learn[n]the passive skill[n]Evade Wind.[n][e]

[msg Item_0E4]
[s]Allows you to learn[n]the passive skill[n]Dodge Elec.[n][e]

[msg Item_0E5]
[s]Allows you to learn[n]the passive skill[n]Evade Elec.[n][e]

[msg Item_0E6]
[s]Allows you to learn[n]the passive skill[n]Dodge Phys.[n][e]

[msg Item_0E7]
[s]Allows you to learn[n]the passive skill[n]Evade Phys.[n][e]

[msg Item_0E8]
[s]Allows you to learn[n]the passive skill[n]Fire Boost.[n][e]

[msg Item_0E9]
[s]Allows you to learn[n]the passive skill[n]Fire Amp.[n][e]

[msg Item_0EA]
[s]Allows you to learn[n]the passive skill[n]Ice Boost.[n][e]

[msg Item_0EB]
[s]Allows you to learn[n]the passive skill[n]Ice Amp.[n][e]

[msg Item_0EC]
[s]Allows you to learn[n]the passive skill[n]Wind Boost.[n][e]

[msg Item_0ED]
[s]Allows you to learn[n]the passive skill[n]Wind Amp.[n][e]

[msg Item_0EE]
[s]Allows you to learn[n]the passive skill[n]Elec Boost.[n][e]

[msg Item_0EF]
[s]Allows you to learn[n]the passive skill[n]Elec Amp.[n][e]

[msg Item_0F0]
[s]Allows you to learn[n]the passive skill[n]Angelic Grace.[n][e]

[msg Item_0F1]
[s]Allows you to learn[n]the passive skill[n]Divine Grace.[n][e]

[msg Item_0F2]
[s]Allows you to learn[n]the passive skill[n]Regenerate 1.[n][e]

[msg Item_0F3]
[s]Allows you to learn[n]the passive skill[n]Regenerate 2.[n][e]

[msg Item_0F4]
[s]Allows you to learn[n]the passive skill[n]Regenerate 3.[n][e]

[msg Item_0F5]
[s]Allows you to learn[n]the passive skill[n]Invigorate 1.[n][e]

[msg Item_0F6]
[s]Allows you to learn[n]the passive skill[n]Invigorate 2.[n][e]

[msg Item_0F7]
[s]Allows you to learn[n]the passive skill[n]Invigorate 3.[n][e]

[msg Item_0F8]
[s]Allows you to learn[n]the passive skill[n]Attack Master.[n][e]

[msg Item_0F9]
[s]Allows you to learn[n]the passive skill[n]Auto-Mataru.[n][e]

[msg Item_0FA]
[s]Allows you to learn[n]the passive skill[n]Defense Master.[n][e]

[msg Item_0FB]
[s]Allows you to learn[n]the passive skill[n]Auto-Maraku.[n][e]

[msg Item_0FC]
[s]Allows you to learn[n]the passive skill[n]Speed Master.[n][e]

[msg Item_0FD]
[s]Allows you to learn[n]the passive skill[n]Auto-Masuku.[n][e]

[msg Item_0FE]
[s]Allows you to learn[n]the passive skill[n]Fast Heal.[n][e]

[msg Item_0FF]
[s]Allows you to learn[n]the passive skill[n]Insta-Heal.[n][e]

[msg Item_100]
[s]Allows you to learn[n]the passive skill[n]Arms Master.[n][e]

[msg Item_101]
[s]Allows you to learn[n]the passive skill[n]Spell Master.[n][e]

[msg Item_102]
[s]Allows you to learn[n]the passive skill[n]Sharp Student.[n][e]

[msg Item_103]
[s]Allows you to learn[n]the passive skill[n]Apt Pupil.[n][e]

[msg Item_104]
[s]Allows you to learn[n]the passive skill[n]Ali Dance.[n][e]

[msg Item_105]
[s]Allows you to learn[n]the passive skill[n]Firm Stance.[n][e]

[msg Item_106]
[s]Allows you to learn[n]the passive skill[n]Life Aid.[n][e]

[msg Item_107]
[s]Allows you to learn[n]the passive skill[n]Victory Cry.[n][e]

[msg Item_108]
[s]Allows you to learn[n]the passive skill[n]Growth 1.[n][e]

[msg Item_109]
[s]Allows you to learn[n]the passive skill[n]Growth 2.[n][e]

[msg Item_10A]
[s]Allows you to learn[n]the passive skill[n]Growth 3.[n][e]

[msg Item_10B]
[s]Allows you to learn[n]the passive skill[n]Unshaken Will.[n][e]

[msg Item_10C]
[s]Allows you to learn[n]the passive skill[n]Evade Bless.[n][e]

[msg Item_10D]
[s]Allows you to learn[n]the passive skill[n]Evade Curse.[n][e]

[msg Item_10E]
[s]Unused[n][e]

[msg Item_10F]
[s]Allows you to learn[n]the passive skill[n]Resist Fire.[n][e]

[msg Item_110]
[s]Allows you to learn[n]the passive skill[n]Null Fire.[n][e]

[msg Item_111]
[s]Allows you to learn[n]the passive skill[n]Repel Fire.[n][e]

[msg Item_112]
[s]Allows you to learn[n]the passive skill[n]Drain Fire.[n][e]

[msg Item_113]
[s]Allows you to learn[n]the passive skill[n]Resist Ice.[n][e]

[msg Item_114]
[s]Allows you to learn[n]the passive skill[n]Null Ice.[n][e]

[msg Item_115]
[s]Allows you to learn[n]the passive skill[n]Repel Ice.[n][e]

[msg Item_116]
[s]Allows you to learn[n]the passive skill[n]Drain Ice.[n][e]

[msg Item_117]
[s]Allows you to learn[n]the passive skill[n]Resist Wind.[n][e]

[msg Item_118]
[s]Allows you to learn[n]the passive skill[n]Null Wind.[n][e]

[msg Item_119]
[s]Allows you to learn[n]the passive skill[n]Repel Wind.[n][e]

[msg Item_11A]
[s]Allows you to learn[n]the passive skill[n]Drain Wind.[n][e]

[msg Item_11B]
[s]Allows you to learn[n]the passive skill[n]Resist Elec.[n][e]

[msg Item_11C]
[s]Allows you to learn[n]the passive skill[n]Null Elec.[n][e]

[msg Item_11D]
[s]Allows you to learn[n]the passive skill[n]Repel Elec.[n][e]

[msg Item_11E]
[s]Allows you to learn[n]the passive skill[n]Drain Elec.[n][e]

[msg Item_11F]
[s]Allows you to learn[n]the passive skill[n]Resist Bless.[n][e]

[msg Item_120]
[s]Allows you to learn[n]the passive skill[n]Null Bless.[n][e]

[msg Item_121]
[s]Allows you to learn[n]the passive skill[n]Repel Bless.[n][e]

[msg Item_122]
[s]Allows you to learn[n]the passive skill[n]Drain Bless.[n][e]

[msg Item_123]
[s]Allows you to learn[n]the passive skill[n]Resist Curse.[n][e]

[msg Item_124]
[s]Allows you to learn[n]the passive skill[n]Null Curse.[n][e]

[msg Item_125]
[s]Allows you to learn[n]the passive skill[n]Repel Curse.[n][e]

[msg Item_126]
[s]Allows you to learn[n]the passive skill[n]Drain Curse.[n][e]

[msg Item_127]
[s]Allows you to learn[n]the passive skill[n]Resist Phys.[n][e]

[msg Item_128]
[s]Allows you to learn[n]the passive skill[n]Null Phys.[n][e]

[msg Item_129]
[s]Allows you to learn[n]the passive skill[n]Repel Phys.[n][e]

[msg Item_12A]
[s]Allows you to learn[n]the passive skill[n]Drain Phys.[n][e]

[msg Item_12B]
[s]Allows you to learn[n]the passive skill[n]Ailment Boost.[n][e]

[msg Item_12C]
[s]Allows you to learn[n]the passive skill[n]Hama Boost.[n][e]

[msg Item_12D]
[s]Allows you to learn[n]the passive skill[n]Mudo Boost.[n][e]

[msg Item_12E]
[s]Allows you to learn[n]the passive skill[n]Dizzy Boost.[n][e]

[msg Item_12F]
[s]Allows you to learn[n]the passive skill[n]Confuse Boost.[n][e]

[msg Item_130]
[s]Allows you to learn[n]the passive skill[n]Fear Boost.[n][e]

[msg Item_131]
[s]Allows you to learn[n]the passive skill[n]Forget Boost.[n][e]

[msg Item_132]
[s]Allows you to learn[n]the passive skill[n]Sleep Boost.[n][e]

[msg Item_133]
[s]Allows you to learn[n]the passive skill[n]Rage Boost.[n][e]

[msg Item_134]
[s]Allows you to learn[n]the passive skill[n]Despair Boost.[n][e]

[msg Item_135]
[s]Unused[n][e]

[msg Item_136]
[s]Allows you to learn[n]the passive skill[n]Brainwash Boost.[n][e]

[msg Item_137]
[s]Allows you to learn[n]the passive skill[n]Resist Dizzy.[n][e]

[msg Item_138]
[s]Allows you to learn[n]the passive skill[n]Resist Confuse.[n][e]

[msg Item_139]
[s]Allows you to learn[n]the passive skill[n]Resist Fear.[n][e]

[msg Item_13A]
[s]Allows you to learn[n]the passive skill[n]Resist Forget.[n][e]

[msg Item_13B]
[s]Allows you to learn[n]the passive skill[n]Resist Sleep.[n][e]

[msg Item_13C]
[s]Allows you to learn[n]the passive skill[n]Resist Rage.[n][e]

[msg Item_13D]
[s]Allows you to learn[n]the passive skill[n]Resist Despair.[n][e]

[msg Item_13E]
[s]Unused[n][e]

[msg Item_13F]
[s]Allows you to learn[n]the passive skill[n]Resist Brainwash.[n][e]

[msg Item_140]
[s]Allows you to learn[n]the passive skill[n]Null Dizzy.[n][e]

[msg Item_141]
[s]Allows you to learn[n]the passive skill[n]Null Confuse.[n][e]

[msg Item_142]
[s]Allows you to learn[n]the passive skill[n]Null Fear.[n][e]

[msg Item_143]
[s]Allows you to learn[n]the passive skill[n]Null Forget.[n][e]

[msg Item_144]
[s]Allows you to learn[n]the passive skill[n]Null Sleep.[n][e]

[msg Item_145]
[s]Allows you to learn[n]the passive skill[n]Null Rage.[n][e]

[msg Item_146]
[s]Allows you to learn[n]the passive skill[n]Null Despair.[n][e]

[msg Item_147]
[s]Allows you to learn[n]the passive skill[n]Null Brainwash.[n][e]

[msg Item_148]
[s]Allows you to learn[n]the passive skill[n]Burn Boost.[n][e]

[msg Item_149]
[s]Allows you to learn[n]the passive skill[n]Freeze Boost.[n][e]

[msg Item_14A]
[s]Allows you to learn[n]the passive skill[n]Shock Boost.[n][e]

[msg Item_14B]
[s]Allows you to learn[n]the passive skill[n]Fortified Moxy.[n][e]

[msg Item_14C]
[s]Allows you to learn[n]the passive skill[n]Adverse Resolve.[n][e]

[msg Item_14D]
[s]Allows you to learn[n]the passive skill[n]Last Stand.[n][e]

[msg Item_14E]
[s]Allows you to learn[n]the passive skill[n]Heat Up.[n][e]

[msg Item_14F]
[s]Unused[n][e]

[msg Item_150]
[s]Allows you to learn[n]the passive skill[n]Touch n' Go.[n][e]

[msg Item_151]
[s]Allows you to learn[n]the passive skill[n]Climate Decorum.[n][e]

[msg Item_152]
[s]Allows you to learn[n]the passive skill[n]Ambient Aid.[n][e]

[msg Item_153]
[s]Allows you to learn[n]the passive skill[n]Gun Boost.[n][e]

[msg Item_154]
[s]Allows you to learn[n]the passive skill[n]Gun Amp.[n][e]

[msg Item_155]
[s]Allows you to learn[n]the passive skill[n]Trigger Happy.[n][e]

[msg Item_156]
[s]Allows you to learn[n]the passive skill[n]Resist Nuke.[n][e]

[msg Item_157]
[s]Allows you to learn[n]the passive skill[n]Null Nuke.[n][e]

[msg Item_158]
[s]Allows you to learn[n]the passive skill[n]Repel Nuke.[n][e]

[msg Item_159]
[s]Allows you to learn[n]the passive skill[n]Drain Nuke.[n][e]

[msg Item_15A]
[s]Allows you to learn[n]the passive skill[n]Resist Psy.[n][e]

[msg Item_15B]
[s]Allows you to learn[n]the passive skill[n]Null Psy.[n][e]

[msg Item_15C]
[s]Allows you to learn[n]the passive skill[n]Repel Psy.[n][e]

[msg Item_15D]
[s]Allows you to learn[n]the passive skill[n]Drain Psy.[n][e]

[msg Item_15E]
[s]Allows you to learn[n]the passive skill[n]Nuke Boost.[n][e]

[msg Item_15F]
[s]Allows you to learn[n]the passive skill[n]Nuke Amp.[n][e]

[msg Item_160]
[s]Allows you to learn[n]the passive skill[n]Psy Boost.[n][e]

[msg Item_161]
[s]Allows you to learn[n]the passive skill[n]Psy Amp.[n][e]

[msg Item_162]
[s]Allows you to learn[n]the passive skill[n]Dodge Nuke.[n][e]

[msg Item_163]
[s]Allows you to learn[n]the passive skill[n]Evade Nuke.[n][e]

[msg Item_164]
[s]Allows you to learn[n]the passive skill[n]Dodge Psy.[n][e]

[msg Item_165]
[s]Allows you to learn[n]the passive skill[n]Evade Psy.[n][e]

[msg Item_166]
[s]Allows you to learn[n]the passive skill[n]Bless Boost.[n][e]

[msg Item_167]
[s]Allows you to learn[n]the passive skill[n]Bless Amp.[n][e]

[msg Item_168]
[s]Allows you to learn[n]the passive skill[n]Curse Boost.[n][e]

[msg Item_169]
[s]Allows you to learn[n]the passive skill[n]Curse Amp.[n][e]

[msg Item_16A]
[s]Allows you to learn[n]the passive skill[n]Magic Ability.[n][e]

[msg Item_16B]
[s]Allows you to learn[n]the passive skill[n]Fortify Spirit.[n][e]

[msg Item_16C]
[s]Allows you to learn[n]the passive skill[n]Almighty Boost.[n][e]

[msg Item_16D]
[s]Allows you to learn[n]the passive skill[n]Almighty Amp.[n][e]

[msg Item_16E]
[s]Allows you to learn[n]the passive skill[n]Zenith Defense.[n][e]

[msg Item_16F]
[s]Allows you to learn[n]the passive skill[n]Soul Chain.[n][e]

[msg Item_170]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_171]
[s]Allows you to learn[n]the Physical skill[n]Kill Rush.[n][e]

[msg Item_172]
[s]Allows you to learn[n]the Physical skill[n]Gatling Blow.[n][e]

[msg Item_173]
[s]Allows you to learn[n]the Gun skill[n]Double Shot.[n][e]

[msg Item_174]
[s]Allows you to learn[n]the Physical skill[n]Power Slash.[n][e]

[msg Item_175]
[s]Allows you to learn[n]the Physical skill[n]Death Scythe.[n][e]

[msg Item_176]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_177]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_178]
[s]Allows you to learn[n]the support skill[n]Taunting Aura.[n][e]

[msg Item_179]
[s]Allows you to learn[n]the support skill[n]Concealment.[n][e]

[msg Item_17A]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_17B]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_17C]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_17D]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_17E]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_17F]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_180]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_181]
[s]Allows you to learn[n]the passive skill[n]BLANK.[n][e]

[msg Item_182]
[s]A blank card with[n]nothing written on it.[n][e]

[msg Item_183]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_184]
[s]Allows you to learn[n]the trait skill[n]Ailment Dmg Up+.[n][e]

[msg Item_185]
[s]Allows you to learn[n]the trait skill[n]Insta-kill SP (Low).[n][e]

[msg Item_186]
[s]Allows you to learn[n]the trait skill[n]Insta-kill SP (Mid).[n][e]

[msg Item_187]
[s]Allows you to learn[n]the trait skill[n]Insta-kill SP (High).[n][e]

[msg Item_188]
[s]Allows you to learn[n]the trait skill[n]Technical Up.[n][e]

[msg Item_189]
[s]Allows you to learn[n]the trait skill[n]Technical Up+.[n][e]

[msg Item_18A]
[s]Allows you to learn[n]the trait skill[n]Low HP Atk Up.[n][e]

[msg Item_18B]
[s]Allows you to learn[n]the trait skill[n]Low HP Atk Up+.[n][e]

[msg Item_18C]
[s]Allows you to learn[n]the trait skill[n]WEAK Hit Up.[n][e]

[msg Item_18D]
[s]Allows you to learn[n]the trait skill[n]WEAK Hit Up+.[n][e]

[msg Item_18E]
[s]Allows you to learn[n]the trait skill[n]Null Insta-kill.[n][e]

[msg Item_18F]
[s]Allows you to learn[n]the trait skill[n]HP Cost -10%.[n][e]

[msg Item_190]
[s]Allows you to learn[n]the trait skill[n]HP Cost -25%.[n][e]

[msg Item_191]
[s]Allows you to learn[n]the trait skill[n]Crit Atk Up 1.[n][e]

[msg Item_192]
[s]Allows you to learn[n]the trait skill[n]Crit Atk Up 2.[n][e]

[msg Item_193]
[s]Allows you to learn[n]the trait skill[n]Crit Atk Up 3.[n][e]

[msg Item_194]
[s]Allows you to learn[n]the trait skill[n]Crit Atk Up 4.[n][e]

[msg Item_195]
[s]Allows you to learn[n]the trait skill[n]Crit Atk Up ★.[n][e]

[msg Item_196]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_197]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_198]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_199]
[s]Allows you to learn[n]the trait skill[n]SP Recovery 1.[n][e]

[msg Item_19A]
[s]Allows you to learn[n]the trait skill[n]SP Recovery 2.[n][e]

[msg Item_19B]
[s]Allows you to learn[n]the trait skill[n]SP Recovery 3.[n][e]

[msg Item_19C]
[s]Allows you to learn[n]the trait skill[n]SP Recovery 4.[n][e]

[msg Item_19D]
[s]Allows you to learn[n]the trait skill[n]SP Recovery ★.[n][e]

[msg Item_19E]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_19F]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1A0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1A1]
[s]Allows you to learn[n]the trait skill[n]Ailment Up 1.[n][e]

[msg Item_1A2]
[s]Allows you to learn[n]the trait skill[n]Ailment Up 2.[n][e]

[msg Item_1A3]
[s]Allows you to learn[n]the trait skill[n]Ailment Up 3.[n][e]

[msg Item_1A4]
[s]Allows you to learn[n]the trait skill[n]Ailment Up 4.[n][e]

[msg Item_1A5]
[s]Allows you to learn[n]the trait skill[n]Ailment Up ★.[n][e]

[msg Item_1A6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1A7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1A8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1A9]
[s]Allows you to learn[n]the trait skill[n]Magic Atk Cost 1.[n][e]

[msg Item_1AA]
[s]Allows you to learn[n]the trait skill[n]Magic Atk Cost 2.[n][e]

[msg Item_1AB]
[s]Allows you to learn[n]the trait skill[n]Magic Atk Cost 3.[n][e]

[msg Item_1AC]
[s]Allows you to learn[n]the trait skill[n]Magic Atk Cost 4.[n][e]

[msg Item_1AD]
[s]Allows you to learn[n]the trait skill[n]Magic Atk Cost ★.[n][e]

[msg Item_1AE]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1AF]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1B0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1B1]
[s]Allows you to learn[n]the trait skill[n]Phys HP Cost 1.[n][e]

[msg Item_1B2]
[s]Allows you to learn[n]the trait skill[n]Phys HP Cost 2.[n][e]

[msg Item_1B3]
[s]Allows you to learn[n]the trait skill[n]Phys HP Cost 3.[n][e]

[msg Item_1B4]
[s]Allows you to learn[n]the trait skill[n]Phys HP Cost 4.[n][e]

[msg Item_1B5]
[s]Allows you to learn[n]the trait skill[n]Phys HP Cost ★.[n][e]

[msg Item_1B6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1B7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1B8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1B9]
[s]Allows you to learn[n]the trait skill[n]Single-Target Up 1.[n][e]

[msg Item_1BA]
[s]Allows you to learn[n]the trait skill[n]Single-Target Up 2.[n][e]

[msg Item_1BB]
[s]Allows you to learn[n]the trait skill[n]Single-Target Up 3.[n][e]

[msg Item_1BC]
[s]Allows you to learn[n]the trait skill[n]Single-Target Up 4.[n][e]

[msg Item_1BD]
[s]Allows you to learn[n]the trait skill[n]Single-Target Up Up ★.[n][e]

[msg Item_1BE]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1BF]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1C0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1C1]
[s]Allows you to learn[n]the trait skill[n]Army Might 1.[n][e]

[msg Item_1C2]
[s]Allows you to learn[n]the trait skill[n]Mult-Target Up 2.[n][e]

[msg Item_1C3]
[s]Allows you to learn[n]the trait skill[n]Mult-Target Up 3.[n][e]

[msg Item_1C4]
[s]Allows you to learn[n]the trait skill[n]Mult-Target Up 4.[n][e]

[msg Item_1C5]
[s]Allows you to learn[n]the trait skill[n]Mult-Target Up ★.[n][e]

[msg Item_1C6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1C7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1C8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1C9]
[s]Allows you to learn[n]the trait skill[n]Phys Up 1.[n][e]

[msg Item_1CA]
[s]Allows you to learn[n]the trait skill[n]Phys Up 2.[n][e]

[msg Item_1CB]
[s]Allows you to learn[n]the trait skill[n]Phys Up 3.[n][e]

[msg Item_1CC]
[s]Allows you to learn[n]the trait skill[n]Phys Up 4.[n][e]

[msg Item_1CD]
[s]Allows you to learn[n]the trait skill[n]Phys Up ★.[n][e]

[msg Item_1CE]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1CF]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1D0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1D1]
[s]Allows you to learn[n]the trait skill[n]Magic Up 1.[n][e]

[msg Item_1D2]
[s]Allows you to learn[n]the trait skill[n]Magic Up 2.[n][e]

[msg Item_1D3]
[s]Allows you to learn[n]the trait skill[n]Magic Up 3.[n][e]

[msg Item_1D4]
[s]Allows you to learn[n]the trait skill[n]Magic Up 4.[n][e]

[msg Item_1D5]
[s]Allows you to learn[n]the trait skill[n]Magic Up ★.[n][e]

[msg Item_1D6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1D7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1D8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1D9]
[s]Allows you to learn[n]the trait skill[n]Baton Pass Up 1.[n][e]

[msg Item_1DA]
[s]Allows you to learn[n]the trait skill[n]Baton Pass Up 2.[n][e]

[msg Item_1DB]
[s]Allows you to learn[n]the trait skill[n]Baton Pass Up 3.[n][e]

[msg Item_1DC]
[s]Allows you to learn[n]the trait skill[n]Baton Pass Up 4.[n][e]

[msg Item_1DD]
[s]Allows you to learn[n]the trait skill[n]Baton Pass Up ★.[n][e]

[msg Item_1DE]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1DF]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1E0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1E1]
[s]Allows you to learn[n]the trait skill[n]Ambush Up 1.[n][e]

[msg Item_1E2]
[s]Allows you to learn[n]the trait skill[n]Ambush Up 2.[n][e]

[msg Item_1E3]
[s]Allows you to learn[n]the trait skill[n]Ambush Up 3.[n][e]

[msg Item_1E4]
[s]Allows you to learn[n]the trait skill[n]Ambush Up 4.[n][e]

[msg Item_1E5]
[s]Allows you to learn[n]the trait skill[n]Ambush Up ★.[n][e]

[msg Item_1E6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1E7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1E8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1E9]
[s]Allows you to learn[n]the trait skill[n]1 More Up 1.[n][e]

[msg Item_1EA]
[s]Allows you to learn[n]the trait skill[n]1 More Up 2.[n][e]

[msg Item_1EB]
[s]Allows you to learn[n]the trait skill[n]1 More Up 3.[n][e]

[msg Item_1EC]
[s]Allows you to learn[n]the trait skill[n]1 More Up 4.[n][e]

[msg Item_1ED]
[s]Allows you to learn[n]the trait skill[n]1 More Up ★.[n][e]

[msg Item_1EE]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1EF]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1F0]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1F1]
[s]Allows you to learn[n]the trait skill[n]Ailment Multiplier 1[n][e]

[msg Item_1F2]
[s]Allows you to learn[n]the trait skill[n]Ailment Multiplier 2.[n][e]

[msg Item_1F3]
[s]Allows you to learn[n]the trait skill[n]Ailment Multiplier 3.[n][e]

[msg Item_1F4]
[s]Allows you to learn[n]the trait skill[n]Ailment Multiplier 4.[n][e]

[msg Item_1F5]
[s]Allows you to learn[n]the trait skill[n]Ailment Multiplier ★.[n][e]

[msg Item_1F6]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1F7]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1F8]
[s]Allows you to learn[n]the trait skill[n]BLANK.[n][e]

[msg Item_1F9]
[s]Allows you to learn[n]the trait skill[n]Phys Up (Low).[n][e]

[msg Item_1FA]
[s]Allows you to learn[n]the trait skill[n]Phys Up (Mid).[n][e]

[msg Item_1FB]
[s]Allows you to learn[n]the trait skill[n]Phys Up (High).[n][e]

[msg Item_1FC]
[s]Allows you to learn[n]the trait skill[n]Heal Cost (Low).[n][e]

[msg Item_1FD]
[s]Allows you to learn[n]the trait skill[n]Heal Cost (Mid).[n][e]

[msg Item_1FE]
[s]Allows you to learn[n]the trait skill[n]Heal Cost (High).[n][e]

[msg Item_1FF]
[s]Allows you to learn[n]the trait skill[n]Magic Up (Low).[n][e]

[msg Item_200]
[s]Allows you to learn[n]the trait skill[n]Magic Up (Mid).[n][e]

[msg Item_201]
[s]Allows you to learn[n]the trait skill[n]Magic Up (High).[n][e]

[msg Item_202]
[s]Allows you to learn[n]the trait skill[n]Phys Cost (Low).[n][e]

[msg Item_203]
[s]Allows you to learn[n]the trait skill[n]Phys Cost (Mid).[n][e]

[msg Item_204]
[s]Allows you to learn[n]the trait skill[n]Phys Cost (High).[n][e]

[msg Item_205]
[s]Allows you to learn[n]the trait skill[n]Magic Cost (Low).[n][e]

[msg Item_206]
[s]Allows you to learn[n]the trait skill[n]Magic Cost (Mid).[n][e]

[msg Item_207]
[s]Allows you to learn[n]the trait skill[n]Magic Cost (High).[n][e]

[msg Item_208]
[s]Allows you to learn[n]the trait skill[n]Technical Up (Low).[n][e]

[msg Item_209]
[s]Allows you to learn[n]the trait skill[n]Technical Up (Mid).[n][e]

[msg Item_20A]
[s]Allows you to learn[n]the trait skill[n]Technical Up (High).[n][e]

[msg Item_20B]
[s]Allows you to learn[n]the trait skill[n]Attack Cost (Low).[n][e]

[msg Item_20C]
[s]Allows you to learn[n]the trait skill[n]Attack Cost (Mid).[n][e]

[msg Item_20D]
[s]Allows you to learn[n]the trait skill[n]Attack Cost (High).[n][e]

[msg Item_20E]
[s]Allows you to learn[n]the trait skill[n]Critical Up (Low).[n][e]

[msg Item_20F]
[s]Allows you to learn[n]the trait skill[n]Critical Up (Mid).[n][e]

[msg Item_210]
[s]Allows you to learn[n]the trait skill[n]Critical Up (High).[n][e]

[msg Item_211]
[s]Allows you to learn[n]the trait skill[n]Backup Support.[n][e]

[msg Item_212]
[s]Allows you to learn[n]the trait skill[n]Sure Escape.[n][e]

[msg Item_213]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_214]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_215]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_216]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_217]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_218]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_219]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_21F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_220]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_221]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_222]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_223]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_224]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_225]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_226]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_227]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_228]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_229]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_22F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_230]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_231]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_232]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_233]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_234]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_235]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_236]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_237]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_238]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_239]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_23F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_240]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_241]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_242]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_243]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_244]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_245]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_246]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_247]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_248]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_249]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_24F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_250]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_251]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_252]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_253]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_254]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_255]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_256]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_257]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_258]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_259]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_25F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_260]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_261]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_262]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_263]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_264]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_265]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_266]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_267]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_268]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_269]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_26F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_270]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_271]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_272]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_273]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_274]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_275]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_276]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_277]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_278]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_279]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27B]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27C]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27D]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27E]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_27F]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_280]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_281]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_282]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_283]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_284]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_285]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_286]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_287]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_288]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_289]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

[msg Item_28A]
[s]Allows you to learn[n]the trait skill[n]Critical Atk Up.[n][e]

