[msg specific_000]
[f 0 5 65278][f 2 1]ブランク(使用禁止)[n][e]

[msg specific_001]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n]0[n][e]

[msg specific_002]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n]0[n][e]

[msg specific_003]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n]0[n][e]

[msg specific_004]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n]0[n][e]

[msg specific_005]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n]0[n][e]

[msg specific_006]
[f 0 5 65278][f 2 1]Increases damage from attacks that[n]targets foe's weaknesses by 50%.[n][e]

[msg specific_007]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_008]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_009]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]healing skills by half.[n][e]

[msg specific_010]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]healing skills by 75%.[n][e]

[msg specific_011]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_012]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_013]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_014]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]support skills by half.[n][e]

[msg specific_015]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]support skills by 75%.[n][e]

[msg specific_016]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_017]
[f 0 5 65278][f 2 1]Increases chance of[n]inflicting ailments.[n][e]

[msg specific_018]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_019]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_020]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_021]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_022]
[f 0 5 65278][f 2 1]Increases chance of inflicting[n]Shock to Downed foes.[n][e]

[msg specific_023]
[f 0 5 65278][f 2 1]Increases chance of inflicting[n]ailments to Downed foes.[n][e]

[msg specific_024]
[f 0 5 65278][f 2 1]Increases chance of inflicting[n]Freeze during 1 More.[n][e]

[msg specific_025]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_026]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_027]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_028]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_029]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_030]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]magic skills by 75%.[n][e]

[msg specific_031]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_032]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_033]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_034]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_035]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_036]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_037]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_038]
[f 0 5 65278][f 2 1]Increases damage to foes[n]when low on HP.[n][e]

[msg specific_039]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_040]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_041]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_042]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_043]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_044]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_045]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_046]
[f 0 5 65278][f 2 1]Strengthens magic skills[n]targeting one foe by 20%.[n][e]

[msg specific_047]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_048]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_049]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_050]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_051]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_052]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_053]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_054]
[f 0 5 65278][f 2 1]Strengthens magic skills[n]targeting all foes by 20%.[n][e]

[msg specific_055]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_056]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_057]
[f 0 5 65278][f 2 1]Strengthens Phys skills[n]by 20%.[n][e]

[msg specific_058]
[f 0 5 65278][f 2 1]Strengthens Phys skills[n]by 30%.[n][e]

[msg specific_059]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_060]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_061]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_062]
[f 0 5 65278][f 2 1]Doubles Counter damage.[n][e]

[msg specific_063]
[f 0 5 65278][f 2 1]Triples Counter damage.[n][e]

[msg specific_064]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_065]
[f 0 5 65278][f 2 1]Strengthens magic[n]skills by 50%.[n][e]

[msg specific_066]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_067]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_068]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_069]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_070]
[f 0 5 65278][f 2 1]Decreases chance of being[n]inflicted by ailments.[n][e]

[msg specific_071]
[f 0 5 65278][f 2 1]Prevents being inflicted[n]by ailments.[n][e]

[msg specific_072]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_073]
[f 0 5 65278][f 2 1]Increases damage after[n]a Baton Pass.[n][e]

[msg specific_074]
[f 0 5 65278][f 2 1]Greatly increases damage[n]after a Baton Pass.[n][e]

[msg specific_075]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_076]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_077]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_078]
[f 0 5 65278][f 2 1]Increases chance of inflicting[n]ailments after a Baton Pass.[n][e]

[msg specific_079]
[f 0 5 65278][f 2 1]Increases chance of inflicting[n]Burn after a Baton Pass.[n][e]

[msg specific_080]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_081]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_082]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_083]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_084]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_085]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_086]
[f 0 5 65278][f 2 1]After a Baton Pass, allows use of skills[n]only available when surrounded.[n][e]

[msg specific_087]
[f 0 5 65278][f 2 1]Allows use of skills only[n]available when surrounded.[n][e]

[msg specific_088]
[f 0 5 65278][f 2 1]Rain/Snow/Pollen Warning[n]always in effect.[n][e]

[msg specific_089]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_090]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_091]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_092]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_093]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_094]
[f 0 5 65278][f 2 1]Increases Technical[n]damage by 25%.[n][e]

[msg specific_095]
[f 0 5 65278][f 2 1]Increases Technical[n]damage by 50%.[n][e]

[msg specific_096]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_097]
[f 0 5 65278][f 2 1]Increases Attack by 25%[n]per ailment inflicted on foe.[n][e]

[msg specific_098]
[f 0 5 65278][f 2 1]Increases Attack by 40%[n]per ailment inflicted on foe.[n][e]

[msg specific_099]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_100]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_101]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_102]
[f 0 5 65278][f 2 1]Increases the chance[n]of insta-kills.[n][e]

[msg specific_103]
[f 0 5 65278][f 2 1]Greatly increases the[n]chance of insta-kills.[n][e]

[msg specific_104]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_105]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_106]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_107]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_108]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_109]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_110]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_111]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_112]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_113]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_114]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_115]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_116]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_117]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_118]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_119]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_120]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_121]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_122]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_123]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_124]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_125]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_126]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_127]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_128]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_129]
[f 0 5 65278][f 2 1]All-Out Attacks may defeat all foes[n]and restore 25% HP to all allies.[n][e]

[msg specific_130]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_131]
[f 0 5 65278][f 2 1]All-Out Attacks may defeat all foes[n]and fully restore HP to all allies.[n][e]

[msg specific_132]
[f 0 5 65278][f 2 1]May increase allies' physical[n]attacks by 40%.[n][e]

[msg specific_133]
[f 0 5 65278][f 2 1]May increase allies' physical[n]attacks by 80%.[n][e]

[msg specific_134]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_135]
[f 0 5 65278][f 2 1]Increases effect of allies'[n]healing skills.[n][e]

[msg specific_136]
[f 0 5 65278][f 2 1]Increases effect of allies' healing[n]skills. May decrease SP cost.[n][e]

[msg specific_137]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_138]
[f 0 5 65278][f 2 1]May decrease SP cost of[n]allies' magic skills.[n][e]

[msg specific_139]
[f 0 5 65278][f 2 1]May decrease SP cost of[n]allies' magic skills by half.[n][e]

[msg specific_140]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_141]
[f 0 5 65278][f 2 1]May slightly increase allies'[n]chance to avoid physical attacks.[n][e]

[msg specific_142]
[f 0 5 65278][f 2 1]May increase allies' chance[n]to avoid physical attacks.[n][e]

[msg specific_143]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_144]
[f 0 5 65278][f 2 1]Increases allies' chance of inflicting[n]Burn/Freeze/Shock by 25%.[n][e]

[msg specific_145]
[f 0 5 65278][f 2 1]Increases allies' chance of inflicting[n]Burn/Freeze/Shock by 50%.[n][e]

[msg specific_146]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_147]
[f 0 5 65278][f 2 1]Decreases allies' chance of being[n]inflicted by ailments by 25%.[n][e]

[msg specific_148]
[f 0 5 65278][f 2 1]Decreases allies' chance of being[n]inflicted by ailments by 50%.[n][e]

[msg specific_149]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_150]
[f 0 5 65278][f 2 1]May decrease SP cost of allies'[n]support skills by half.[n][e]

[msg specific_151]
[f 0 5 65278][f 2 1]May decrease SP cost of allies'[n]support/Almighty skills by half.[n][e]

[msg specific_152]
[f 0 5 65278][f 2 1]Decreases SP cost of allies'[n]support/Almighty skills by half.[n][e]

[msg specific_153]
[f 0 5 65278][f 2 1]Increases chance of ally not[n]being Downed when attacked.[n][e]

[msg specific_154]
[f 0 5 65278][f 2 1]Greatly increases chance of ally not[n]being Downed when attacked.[n][e]

[msg specific_155]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_156]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Fire skills by half.[n][e]

[msg specific_157]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Fire skills by 75%.[n][e]

[msg specific_158]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Ice skills by half.[n][e]

[msg specific_159]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Ice skills by 75%.[n][e]

[msg specific_160]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Elec skills by half.[n][e]

[msg specific_161]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Elec skills by 75%.[n][e]

[msg specific_162]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Wind skills by half.[n][e]

[msg specific_163]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Wind skills by 75%.[n][e]

[msg specific_164]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Psy skills by half.[n][e]

[msg specific_165]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Psy skills by 75%.[n][e]

[msg specific_166]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Nuke skills by half.[n][e]

[msg specific_167]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Nuke skills by 75%.[n][e]

[msg specific_168]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Bless skills by half.[n][e]

[msg specific_169]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Bless skills by 75%.[n][e]

[msg specific_170]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Curse skills by half.[n][e]

[msg specific_171]
[f 0 5 65278][f 2 1]Decreases SP cost of[n]Curse skills by 75%.[n][e]

[msg specific_172]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_173]
[f 0 5 65278][f 2 1]Increases amount of HP[n]restored to self by 50%.[n][e]

[msg specific_174]
[f 0 5 65278][f 2 1]Doubles amount of HP[n]restored to self.[n][e]

[msg specific_175]
[f 0 5 65278][f 2 1]Increases amount of SP[n]restored to self by 50%.[n][e]

[msg specific_176]
[f 0 5 65278][f 2 1]Doubles amount of SP[n]restored to self.[n][e]

[msg specific_177]
[f 0 5 65278][f 2 1]Doubles amount of HP/SP[n]restored to self.[n][e]

[msg specific_178]
[f 0 5 65278][f 2 1]Increases effect period of support [n]skills cast on allies by 1 turn.[n][e]

[msg specific_179]
[f 0 5 65278][f 2 1]Increases effect period of support [n]skills cast on allies by 2 turns.[n][e]

[msg specific_180]
[f 0 5 65278][f 2 1]Increases effect period of support [n]skills cast on self by 1 turn.[n][e]

[msg specific_181]
[f 0 5 65278][f 2 1]Increases effect period of support [n]skills cast on self by 2 turns.[n][e]

[msg specific_182]
[f 0 5 65278][f 2 1]Doubles effect of Drain-type[n]skills and passives.[n][e]

[msg specific_183]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_184]
[f 0 5 65278][f 2 1]Expendable items not used[n]up after a Baton Pass.[n][e]

[msg specific_185]
[f 0 5 65278][f 2 1]Decreases SP cost by half[n]after a Baton Pass.[n][e]

[msg specific_186]
[f 0 5 65278][f 2 1]Decreases damage from attacks[n]that targets weaknesses.[n][e]

[msg specific_187]
[f 0 5 65278][f 2 1]High chance of ally avoiding attacks[n]by foes inflicted by ailments.[n][e]

[msg specific_188]
[f 0 5 65278][f 2 1]Triples effect of Charge/[n]Concentrate.[n][e]

[msg specific_189]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_190]
[f 0 5 65278][f 2 1]Revives with 1 HP when KO'd.[n]Usable 4 times per battle.[n][e]

[msg specific_191]
[f 0 5 65278][f 2 1]Increases Attack by 50%[n]during 1 More.[n][e]

[msg specific_192]
[f 0 5 65278][f 2 1]Increases chance of triggering[n]ally's Persona traits.[n][e]

[msg specific_193]
[f 0 5 65278][f 2 1]Increases chance of triggering[n]ally's Follow-Up attack.[n][e]

[msg specific_194]
[f 0 5 65278][f 2 1]Increases Attack/Defense based[n]on Inmate Registry completion.[n][e]

[msg specific_195]
[f 0 5 65278][f 2 1]Decreases HP/SP cost to 0[n]during 1 More.[n][e]

[msg specific_196]
[f 0 5 65278][f 2 1]Decreases SP cost to 0[n]for insta-kill skills.[n][e]

[msg specific_197]
[f 0 5 65278][f 2 1]Doubles amount of HP/SP[n]restored to self.[n][e]

[msg specific_198]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_199]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_200]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_201]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_202]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_203]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_204]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_205]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_206]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_207]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_208]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_209]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_210]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_211]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_212]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_213]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_214]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_215]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_216]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_217]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_218]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_219]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_220]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_221]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_222]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_223]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_224]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_225]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_226]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_227]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_228]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_229]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_230]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_231]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_232]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_233]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_234]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_235]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_236]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_237]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_238]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_239]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_240]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_241]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_242]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_243]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_244]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_245]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_246]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_247]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_248]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_249]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_250]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_251]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_252]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_253]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_254]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_255]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_256]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_257]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_258]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_259]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_260]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_261]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_262]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_263]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_264]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_265]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_266]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_267]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_268]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_269]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_270]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_271]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_272]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_273]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_274]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_275]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_276]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_277]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_278]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_279]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_280]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_281]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_282]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_283]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_284]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_285]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_286]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_287]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_288]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_289]
[f 0 5 65278][f 2 1]Acquire bonus Traits when[n]fusing with a Treasure Demon.[n][e]

[msg specific_290]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_291]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_292]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_293]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_294]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_295]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_296]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_297]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_298]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

[msg specific_299]
[f 0 5 65278][f 2 1]リザーブのヘルプ[n][e]

