[msg technical_help_000]
[f 0 5 65278][f 2 1]Technical Help Blank[n][e]

[msg technical_help_001]
[f 0 5 65278][f 2 1]Technical Damage+[n][e]

[msg technical_help_002]
[f 0 5 65278][f 2 1]Technical Damage++[n][e]

[msg technical_help_003]
[f 0 5 65278][f 2 1]Technical Damage+++[n]Knockdown rate+[n][e]

[msg technical_help_004]
[f 0 5 65278][f 2 1]Technical Damage++++[n]Will knock down enemy[n][e]

