[msg item_000]
[s]BLANK[n][e]

[msg Item_001]
[s]Unused[n][e]

[msg Item_002]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_003]
[s]Curved, Nepalese knife[n]also used as a tool.[n][e]

[msg Item_004]
[s]A cane once carried by a[n]legendary gentleman thief.[n][e]

[msg Item_005]
[s]A dagger with a pale,[n]blue blade.[n][e]

[msg Item_006]
[s]A dagger used during[n]Wiccan rituals.[n][e]

[msg Item_007]
[s]Reserved[n][e]

[msg Item_008]
[s]A dagger used for[n]skinning prey.[n][e]

[msg Item_009]
[s]RESERVE[n][e]

[msg Item_00A]
[s]A dagger capable of[n]conducting electricity.[n][e]

[msg Item_00B]
[s]A deadly tool used by[n]medical professionals.[n][e]

[msg Item_00C]
[s]RESERVE[n][e]

[msg Item_00D]
[s]A replica dagger that[n]was once used by a king.[n][e]

[msg Item_00E]
[s]A sharper, higher-grade[n]skinning knife.[n][e]

[msg Item_00F]
[s]RESERVE[n][e]

[msg Item_010]
[s]A dagger tempered using[n]advanced techniques.[n][e]

[msg Item_011]
[s]A dagger that a famous[n]gambler once used.[n][e]

[msg Item_012]
[s]RESERVE[n][e]

[msg Item_013]
[s]A heavy knife with a lot[n]of heft to it.[n][e]

[msg Item_014]
[s]Replica of a dagger used[n]in medieval Europe.[n][e]

[msg Item_015]
[s]RESERVE[n][e]

[msg Item_016]
[s]A replica dagger capable[n]of enraging enemies.[n][e]

[msg Item_017]
[s]A dagger best used for[n]parrying and defense.[n][e]

[msg Item_018]
[s]RESERVE[n][e]

[msg Item_019]
[s]A medieval dagger used[n]to deliver a killing strike.[n][e]

[msg Item_01A]
[s]A light dagger that[n]makes evasion easier.[n][e]

[msg Item_01B]
[s]RESERVE[n][e]

[msg Item_01C]
[s]RESERVE[n][e]

[msg Item_01D]
[s]A curved blade used by[n]Ancient Greeks.[n][e]

[msg Item_01E]
[s]A dagger forged in fire[n]that burns with intensity.[n][e]

[msg Item_01F]
[s]RESERVE[n][e]

[msg Item_020]
[s]RESERVE[n][e]

[msg Item_021]
[s]RESERVE[n][e]

[msg Item_022]
[s]RESERVE[n][e]

[msg Item_023]
[s]A dagger used to drive[n]angels from Paradise.[n][e]

[msg Item_024]
[s]RESERVE[n][e]

[msg Item_025]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_026]
[s]A baseball bat with nails[n]hammered into it.[n][e]

[msg Item_027]
[s]A blunt weapon used in[n]judgment of its foes.[n][e]

[msg Item_028]
[s]A reinforced iron pipe.[n][e]

[msg Item_029]
[s]RESERVE[n][e]

[msg Item_02A]
[s]A replica of a metal[n]hammer used in battle.[n][e]

[msg Item_02B]
[s]A blunt weapon with[n]great striking power.[n][e]

[msg Item_02C]
[s]RESERVE[n][e]

[msg Item_02D]
[s]Replica with even more[n]heft to it.[n][e]

[msg Item_02E]
[s]Blunt instrument affixed[n]with caltrops.[n][e]

[msg Item_02F]
[s]RESERVE[n][e]

[msg Item_030]
[s]Replica of a hammer with[n]a notable history.[n][e]

[msg Item_031]
[s]A pipe tainted by[n]demonic energy.[n][e]

[msg Item_032]
[s]RESERVE[n][e]

[msg Item_033]
[s]Replica of a hammer with[n]a notable history.[n][e]

[msg Item_034]
[s]A beautiful blunt[n]instrument.[n][e]

[msg Item_035]
[s]RESERVE[n][e]

[msg Item_036]
[s]A blunt instrument able[n]to put foes to sleep.[n][e]

[msg Item_037]
[s]A blunt instrument able[n]to deal severe damage.[n][e]

[msg Item_038]
[s]RESERVE[n][e]

[msg Item_039]
[s]Replica of a weapon used[n]in Ancient China.[n][e]

[msg Item_03A]
[s]A blunt weapon that[n]pulses with ethereal light.[n][e]

[msg Item_03B]
[s]A blunt weapon capable[n]of breaking a meteorite.[n][e]

[msg Item_03C]
[s]An exceptionally heavy[n]blunt instrument.[n][e]

[msg Item_03D]
[s]RESERVE[n][e]

[msg Item_03E]
[s]RESERVE[n][e]

[msg Item_03F]
[s]RESERVE[n][e]

[msg Item_040]
[s]A blunt weapon that[n]burns the soul within.[n][e]

[msg Item_041]
[s]A staff that can[n]mysteriously elongate.[n][e]

[msg Item_042]
[s]RESERVE[n][e]

[msg Item_043]
[s]A blunt weapon able[n]to put foes to sleep.[n][e]

[msg Item_044]
[s]RESERVE[n][e]

[msg Item_045]
[s]RESERVE[n][e]

[msg Item_046]
[s]A blunt weapon that[n]intimidates its enemies.[n][e]

[msg Item_047]
[s]RESERVE[n][e]

[msg Item_048]
[s]A legendary weapon[n]wielded by a god.[n][e]

[msg Item_049]
[s]A sword made for[n]stealing.[n][e]

[msg Item_04A]
[s]A ladle used by bakeneko[n]for headhunting townsfolk.[n][e]

[msg Item_04B]
[s]A sword from where rain[n]falls sooner than usual.[n][e]

[msg Item_04C]
[s]Sword said to cut faster[n]than the speed of sound.[n][e]

[msg Item_04D]
[s]A curved blade originally[n]used in the Middle East.[n][e]

[msg Item_04E]
[s]A curved blade able to[n]leave foes confused.[n][e]

[msg Item_04F]
[s]RESERVE[n][e]

[msg Item_050]
[s]A sword that renders[n]sleep upon enemies.[n][e]

[msg Item_051]
[s]A curved blade originally[n]used in the Middle East.[n][e]

[msg Item_052]
[s]A sword with a malicious-[n]looking blade.[n][e]

[msg Item_053]
[s]A sword said to work[n]miracles.[n][e]

[msg Item_054]
[s]A sword that looks like a[n]pirate hero would use it.[n][e]

[msg Item_055]
[s]RESERVE[n][e]

[msg Item_056]
[s]A sword with electricity[n]running through it.[n][e]

[msg Item_057]
[s]A sword with patterns[n]etched across the blade.[n][e]

[msg Item_058]
[s]A sword radiating heat.[n][e]

[msg Item_059]
[s]A sword forged with[n]heavy materials.[n][e]

[msg Item_05A]
[s]RESERVE[n][e]

[msg Item_05B]
[s]A sword that confuses[n]enemies with every cut.[n][e]

[msg Item_05C]
[s]RESERVE[n][e]

[msg Item_05D]
[s]A sword that glows with[n]a cold, ethereal light.[n][e]

[msg Item_05E]
[s]Unused.[n][e]

[msg Item_05F]
[s]A sword that obeys the[n]will of its wielder.[n][e]

[msg Item_060]
[s]RESERVE[n][e]

[msg Item_061]
[s]RESERVE[n][e]

[msg Item_062]
[s]A sword with a luminous[n]blade.[n][e]

[msg Item_063]
[s]Unused.[n][e]

[msg Item_064]
[s]RESERVE[n][e]

[msg Item_065]
[s]RESERVE[n][e]

[msg Item_066]
[s]RESERVE[n][e]

[msg Item_067]
[s]RESERVE[n][e]

[msg Item_068]
[s]RESERVE[n][e]

[msg Item_069]
[s]A sword that sings with[n]divine strength.[n][e]

[msg Item_06A]
[s]RESERVE[n][e]

[msg Item_06B]
[s]RESERVE[n][e]

[msg Item_06C]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_06D]
[s]RESERVE[n][e]

[msg Item_06E]
[s]A telescoping, flesh-[n]rending whip.[n][e]

[msg Item_06F]
[s]A fire-red whip.[n][e]

[msg Item_070]
[s]A whip that can rip the[n]skin from enemies.[n][e]

[msg Item_071]
[s]A whip that brings luck.[n][e]

[msg Item_072]
[s]A whip that can burst[n]into flames.[n][e]

[msg Item_073]
[s]A whip that looks like[n]one a hero would use.[n][e]

[msg Item_074]
[s]RESERVE[n][e]

[msg Item_075]
[s]A bladed, telescoping[n]whip.[n][e]

[msg Item_076]
[s]An electrified,[n]telescoping whip.[n][e]

[msg Item_077]
[s]RESERVE[n][e]

[msg Item_078]
[s]A whip able to blow[n]away memories.[n][e]

[msg Item_079]
[s]A whip shaped like a tail.[n][e]

[msg Item_07A]
[s]RESERVE[n][e]

[msg Item_07B]
[s]A telescoping whip with[n]increased power.[n][e]

[msg Item_07C]
[s]A whip made from chains.[n][e]

[msg Item_07D]
[s]RESERVE[n][e]

[msg Item_07E]
[s]A whip with a terrifying[n]strike.[n][e]

[msg Item_07F]
[s]An electrified,[n]telescoping whip.[n][e]

[msg Item_080]
[s]RESERVE[n][e]

[msg Item_081]
[s]A whip capable of[n]inducing sleep.[n][e]

[msg Item_082]
[s]RESERVE[n][e]

[msg Item_083]
[s]RESERVE[n][e]

[msg Item_084]
[s]RESERVE[n][e]

[msg Item_085]
[s]A whip that dissolves sin.[n][e]

[msg Item_086]
[s]A light and sturdy whip.[n][e]

[msg Item_087]
[s]RESERVE[n][e]

[msg Item_088]
[s]RESERVE[n][e]

[msg Item_089]
[s]RESERVE[n][e]

[msg Item_08A]
[s]RESERVE[n][e]

[msg Item_08B]
[s]A whip that controls[n]the night.[n][e]

[msg Item_08C]
[s]RESERVE[n][e]

[msg Item_08D]
[s]A whip that freezes[n]enemies.[n][e]

[msg Item_08E]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_08F]
[s]A sword with no edge.[n][e]

[msg Item_090]
[s]A sword that cannot cut[n]konjak.[n][e]

[msg Item_091]
[s]A sword that seems[n]beautiful.[n][e]

[msg Item_092]
[s]A sword with power[n]to control the cold.[n][e]

[msg Item_093]
[s]A sword with a menacing[n]look to it.[n][e]

[msg Item_094]
[s]A sword that used to be[n]an army standard issue.[n][e]

[msg Item_095]
[s]A sword used in historical[n]dramas.[n][e]

[msg Item_096]
[s]A sword that can work[n]miracles.[n][e]

[msg Item_097]
[s]A sword that shines in[n]the moonlight.[n][e]

[msg Item_098]
[s]RESERVE[n][e]

[msg Item_099]
[s]RESERVE[n][e]

[msg Item_09A]
[s]A sword used in Iaido.[n][e]

[msg Item_09B]
[s]RESERVE[n][e]

[msg Item_09C]
[s]A sword that's dizzying[n]to look upon.[n][e]

[msg Item_09D]
[s]A sword with an[n]extremely long blade.[n][e]

[msg Item_09E]
[s]RESERVE[n][e]

[msg Item_09F]
[s]A sword capable of[n]inducing sleep.[n][e]

[msg Item_0A0]
[s]A sword that can slice[n]through memories.[n][e]

[msg Item_0A1]
[s]RESERVE[n][e]

[msg Item_0A2]
[s]A magic sword that frees[n]blood from the body.[n][e]

[msg Item_0A3]
[s]RESERVE[n][e]

[msg Item_0A4]
[s]A sword that can be used[n]for anything.[n][e]

[msg Item_0A5]
[s]RESERVE[n][e]

[msg Item_0A6]
[s]The renowned sword from[n]the Tale of Genji.[n][e]

[msg Item_0A7]
[s]RESERVE[n][e]

[msg Item_0A8]
[s]RESERVE[n][e]

[msg Item_0A9]
[s]A sword disguised as a[n]long smoking pipe.[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]A sword that separates[n]actors from amateurs.[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_0AE]
[s]Gloves that deliver[n]deep impacts.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]Metal knuckles.[n][e]

[msg Item_0B2]
[s]Gloves that shine with[n]oxidized silver.[n][e]

[msg Item_0B3]
[s]Iron gloves that hold a[n]power within.[n][e]

[msg Item_0B4]
[s]Gloves that deal sound[n]barrier–breaking hits.[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]Gloves that possess[n]power.[n][e]

[msg Item_0B7]
[s]Gloves that leave enemies[n]dizzy.[n][e]

[msg Item_0B8]
[s]RESERVE[n][e]

[msg Item_0B9]
[s]Gloves with increased[n]power.[n][e]

[msg Item_0BA]
[s]Gloves favored by pro[n]fighters.[n][e]

[msg Item_0BB]
[s]Gloves that deliver[n]a promise.[n][e]

[msg Item_0BC]
[s]RESERVE[n][e]

[msg Item_0BD]
[s]RESERVE[n][e]

[msg Item_0BE]
[s]RESERVE[n][e]

[msg Item_0BF]
[s]RESERVE[n][e]

[msg Item_0C0]
[s]Cute gloves that look like[n]bears. Aww.[n][e]

[msg Item_0C1]
[s]Gloves with incredibly[n]destructive power.[n][e]

[msg Item_0C2]
[s]Gloves styled after the[n]nomadic sky father.[n][e]

[msg Item_0C3]
[s]RESERVE[n][e]

[msg Item_0C4]
[s]RESERVE[n][e]

[msg Item_0C5]
[s]Named after Indra's[n]weapon.[n][e]

[msg Item_0C6]
[s]A whip that gives you[n]control of your opponent.[n][e]

[msg Item_0C7]
[s]A crude, yet effective,[n]blunt instrument.[n][e]

[msg Item_0C8]
[s]Unused.[n][e]

[msg Item_0C9]
[s]A small axe for first-time[n]users.[n][e]

[msg Item_0CA]
[s]An axe that leaves a[n]lasting impression.[n][e]

[msg Item_0CB]
[s]RESERVE[n][e]

[msg Item_0CC]
[s]An axe that delivers a[n]heavy impact.[n][e]

[msg Item_0CD]
[s]RESERVE[n][e]

[msg Item_0CE]
[s]A cold-looking axe with[n]a blue hue to it.[n][e]

[msg Item_0CF]
[s]RESERVE[n][e]

[msg Item_0D0]
[s]A primitive axe.[n][e]

[msg Item_0D1]
[s]An axe that might come[n]out in a fairy tale.[n][e]

[msg Item_0D2]
[s]An axe that surges with[n]power.[n][e]

[msg Item_0D3]
[s]RESERVE[n][e]

[msg Item_0D4]
[s]RESERVE[n][e]

[msg Item_0D5]
[s]RESERVE[n][e]

[msg Item_0D6]
[s]A replica that looks like[n]it might come from space.[n][e]

[msg Item_0D7]
[s]Unused.[n][e]

[msg Item_0D8]
[s]RESERVE[n][e]

[msg Item_0D9]
[s]Replica of an axe wielded[n]by a legendary hero.[n][e]

[msg Item_0DA]
[s]RESERVE[n][e]

[msg Item_0DB]
[s]An axe that emits a[n]bedazzling, floral aroma.[n][e]

[msg Item_0DC]
[s]A glove that rattles[n]the bone.[n][e]

[msg Item_0DD]
[s]A glove with triangular[n]blades that strike vitals.[n][e]

[msg Item_0DE]
[s]Gloves made from heavy[n]metals.[n][e]

[msg Item_0DF]
[s]An authentic, imitation[n]energy sword for kids.[n][e]

[msg Item_0E0]
[s]A sword adorned with[n]foreboding flames.[n][e]

[msg Item_0E1]
[s]Imitation energy sword[n]with a blinding blade.[n][e]

[msg Item_0E2]
[s]A sword able to burn[n]everything to the ground.[n][e]

[msg Item_0E3]
[s]A sword with a curved[n]blade.[n][e]

[msg Item_0E4]
[s]A whip that sends heads[n]spinning.[n][e]

[msg Item_0E5]
[s]A chain weighted on one[n]end.[n][e]

[msg Item_0E6]
[s]An axe that can destroy[n]everything with one swipe.[n][e]

[msg Item_0E7]
[s]RESERVE[n][e]

[msg Item_0E8]
[s]RESERVE[n][e]

[msg Item_0E9]
[s]A cruel-looking axe.[n][e]

[msg Item_0EA]
[s]An axe capable of[n]inducing despair.[n][e]

[msg Item_0EB]
[s]A sword that possesses[n]the power to transmutate.[n][e]

[msg Item_0EC]
[s]RESERVE[n][e]

[msg Item_0ED]
[s]RESERVE[n][e]

[msg Item_0EE]
[s]RESERVE[n][e]

[msg Item_0EF]
[s]RESERVE[n][e]

[msg Item_0F0]
[s]A heavy chain designed[n]to bind legs.[n][e]

[msg Item_0F1]
[s]Gloves for instilling[n]discipline.[n][e]

[msg Item_0F2]
[s]RESERVE[n][e]

[msg Item_0F3]
[s]A sword that's hard to hit[n]but easy to topple.[n][e]

[msg Item_0F4]
[s]RESERVE[n][e]

[msg Item_0F5]
[s]A silver sword resplendent[n]in its ornamentation.[n][e]

[msg Item_0F6]
[s]A sword with a zig-zag[n]design.[n][e]

[msg Item_0F7]
[s]RESERVE[n][e]

[msg Item_0F8]
[s]RESERVE[n][e]

[msg Item_0F9]
[s]Used as data, will not show.[n][e]

[msg Item_0FA]
[s]Used as data, will not show.[n][e]

[msg Item_0FB]
[s]A rapier with a very[n]sharp tip.[n][e]

[msg Item_0FC]
[s]RESERVE[n][e]

[msg Item_0FD]
[s]RESERVE[n][e]

[msg Item_0FE]
[s]An angelic rapier.[n][e]

[msg Item_0FF]
[s]A divine, angelic rapier.[n][e]

[msg Item_100]
[s]A cane once carried by a[n]legendary gentleman thief.[n][e]

[msg Item_101]
[s]A noble dagger of a[n]fallen angel.[n][e]

[msg Item_102]
[s]A legendary weapon[n]wielded by a god.[n][e]

[msg Item_103]
[s]A refined staff with an[n]extended reach.[n][e]

[msg Item_104]
[s]A ladle used by bakeneko[n]for headhunting warriors.[n][e]

[msg Item_105]
[s]A noble sword with a[n]luminous blade.[n][e]

[msg Item_106]
[s]A elegant whip that sends[n]heads spinning.[n][e]

[msg Item_107]
[s]A strong whip that[n]controls the night.[n][e]

[msg Item_108]
[s]A whip that frightens and[n]freezes enemies.[n][e]

[msg Item_109]
[s]A refined sword for the[n]experienced actor.[n][e]

[msg Item_10A]
[s]The true renowned sword[n]from the Tale of Genji.[n][e]

[msg Item_10B]
[s]Cute, strong gloves that[n]look like bears. Aww.[n][e]

[msg Item_10C]
[s]Gloves styled after the[n]nomadic sky father.[n][e]

[msg Item_10D]
[s]Named after Indra's[n]weapon, but improved.[n][e]

[msg Item_10E]
[s]A strong axe capable[n]of inducing despair.[n][e]

[msg Item_10F]
[s]A noble axe that emits[n]a bedazzling, floral aroma.[n][e]

[msg Item_110]
[s]A dagger with an[n]electric design.[n][e]

[msg Item_111]
[s]A blunt weapon of great[n]nobility.[n][e]

[msg Item_112]
[s]A sword with a[n]magician's name.[n][e]

[msg Item_113]
[s]A whip that glows in the[n]dark night.[n][e]

[msg Item_114]
[s]A gaudy looking sword.[n][e]

[msg Item_115]
[s]Gloves light as a horse[n]running through the skies.[n][e]

[msg Item_116]
[s]An axe with a cosmic[n]design.[n][e]

[msg Item_117]
[s]A sword with a fearful[n]design.[n][e]

[msg Item_118]
[s]A rapier with an alluring[n]white shine.[n][e]

[msg Item_119]
[s]A dagger of judgment.[n][e]

[msg Item_11A]
[s]A blunt weapon, called by[n]some the ultimate weapon.[n][e]

[msg Item_11B]
[s]A very sharp sword[n]replica.[n][e]

[msg Item_11C]
[s]A whip named after a[n]magical chain.[n][e]

[msg Item_11D]
[s]A sword with a splendid[n]blade.[n][e]

[msg Item_11E]
[s]Gloves that only the[n]victorious ones can use.[n][e]

[msg Item_11F]
[s]A replica once used by[n]a crusader.[n][e]

[msg Item_120]
[s]A sword with a sharp[n]blade.[n][e]

[msg Item_121]
[s]A rapier with a very thin[n]blade.[n][e]

[msg Item_122]
[s]A sword that reflects[n]no light.[n][e]

[msg Item_123]
[s]A sword with the power[n]of a goddess.[n][e]

[msg Item_124]
[s]Gloves that might prove[n]useful when gambling.[n][e]

[msg Item_125]
[s]A beam sword that allows[n]the user to win any battle.[n][e]

[msg Item_126]
[s]A rapier that imbues[n]courage.[n][e]

[msg Item_127]
[s]A sword that remembers[n]the foes it slices through.[n][e]

